psi4/psi4

src/bin/dmrg/dmrgscf.cc

@SebWouters timings are now shown in CheMPS2 module.

Add timings to chemps2 module

---

tests/x2c/input.dat

x2c test added

---

CMakeLists.txt
cmake/ConfigPython.cmake

Fixes #163. Tested on OSX, Ubuntu 15.04, and CentOS 6 with system python(s), homebrew, and anaconda (py2 and py3).

Fix CMake finding proper python

---

CMakeLists.txt

cc https://github.com/psi4/psi4public/pull/164#issuecomment-131152671, thanks @jturney.

Quick fix to PR #164

---

cmake/ConfigPython.cmake

Should fix issue when finding python library during conda-build.
cc https://github.com/psi4/psi4public/pull/164#issuecomment-134687960

Tweaking cmake ConfigPython

---

share/fsapt/pymol/Disp.pymol
share/fsapt/pymol/Elst.pymol
share/fsapt/pymol/Exch.pymol
share/fsapt/pymol/IndAB.pymol
share/fsapt/pymol/IndBA.pymol
share/fsapt/pymol/Total.pymol
share/fsapt/pymol/geom.pymol
share/fsapt/pymol/orient.pymol
share/fsapt/pymol/run.pymol
share/fsapt/pymol/vis.pymol
src/bin/fisapt/fisapt.cc
src/bin/fisapt/fisapt.h
src/bin/psi4/read_options.cc

I have modified the Pymol files in /share/fsapt/pymol/ so that they can be executed from the command line as well as the Pymol GUI.

Modified pymol files for command line execution

---

src/bin/psi4/CMakeLists.txt
src/bin/psi4/psi_start.cc
src/bin/psi4/python.cc

This gets us back to a working ``make psi4so``. Basic docs at https://github.com/psi4/psi4/wiki/8_FAQ_Contents#psi4so

Make psi4.so work again. Based on work by @bennybp

---

src/bin/optking/molecule_fragments.cc

Fixing issue #310 CH3F was not fully optimizing due to missing internal coordinates.  This issue led to the discovery that the code joining separated fragments had significant problems (basically atom reindexing/ordering).
None
Ready to go.  All optimization tests passed.

rewrote buggy code that joined initially separated fragments.

---

share/python/driver.py
share/python/proc.py
src/lib/libmints/molecule.cc

Tentative quick fix of molecule cloning. Hopefully fixes issue #235 

Reorder operations in molecule clone. Fix cloning of PointGroup

---

doc/sphinxman/document_driver.py
doc/sphinxman/source/dftd3.rst
doc/sphinxman/source/fchk.rst
doc/sphinxman/source/proc_py.rst
share/python/driver.py
share/python/qcdb/dbwrap.py
share/python/qcdb/libmintsbasisset.py
share/python/qcdb/libmintsgshell.py
share/python/qcdb/libmintsmolecule.py
share/python/qcdb/libmintspointgrp.py
share/python/qcdb/modelchems.py
share/python/qcdb/mpl.py
share/python/qcdb/orca.py

sphinx cleanup

---

src/bin/dmrg/dmrgscf.cc

Bug fix for nmopi[ h ] != smopi[ h ]

Bug fix for nmopi[ h ] != smopi[ h ]

---

doc/sphinxman/source/introduction.rst

Updating introduction.rst

---

src/lib/libscf_solver/hf.cc

Moved the final SCF printing after the stability analysis is complete, instead of after the first SCF convergence. Ready to go.

Final SCF printing after stability analysis.

---

src/bin/fisapt/fisapt.cc
src/bin/psi4/read_options.cc

This PR corrects the current implementation of exchange-scaled F-SAPT.

Exchange-Scaled F-SAPT

---

samples/example_psi4rc_file

Fixes issues #392
- [ x ] Fix issue #392 
- [ x ]  Ready to go

fixes #392 (I love easy fixes)

---

src/lib/libfock/PK_workers.cc
src/lib/libfock/PKmanagers.cc
src/lib/libfock/PKmanagers.h

Corrected passing NULL when a shared_ptr is expected in the new PK code.
Fixes #398

Fixing issue 398

---

share/python/aliases.py
share/python/dependency_check.py
share/python/inputparser.py
share/python/p4util/exceptions.py
share/python/p4util/numpy_helper.py
src/bin/detci/ciwave.cc
src/bin/detci/ciwave.h
src/bin/detci/diag_h.cc
src/bin/detci/mcscf.cc
src/bin/detci/mitrush_iter.cc
src/bin/detci/params.cc
src/bin/detci/sem.cc
src/bin/detci/structs.h
src/bin/psi4/read_options.cc
src/lib/libscf_solver/hf.cc
tests/numpy-array-interface/input.dat
tests/rasci-ne/input.dat

Several tweaks to prepare for the 1.0 release.

Release tweaks

---

src/bin/dfocc/manager.cc

There was an error in df-mp3 grad. I was comment out the wrong line. Now, it is fixed and DF-MP3 grad works!

Fixing DF-MP3

---

.travis.yml

llvm has returned to us! reenable travis

---

doc/sphinxman/source/conda.rst
tests/sapt6/input.dat

reduce sapt6 test for travis's sake

---

src/bin/fisapt/fisapt.cc

Small correction to the code and additional output for SAPT.

Minor output modification for SAPT

---

psi4/src/psi4/psimrcc/mrcc.h

Removed unused functions in psimrcc.

Remove functions from mrcc.h.

---

doc/sphinxman/source/conda.rst

Corrected curl flag from o to O

Corrected curl flag from o to O

---

doc/sphinxman/source/tutorial.rst

Changed functions to be clickable in tutorial.rst

---

doc/sphinxman/source/tutorial.rst

"...want to do counterpoise (CP) corrected energies." -> "...want to do counterpoise (CP) correction to compute interaction energies"

Resolved sentence structure

---

psi4/driver/__init__.py
psi4/driver/json_wrapper.py
psi4/driver/p4util/exceptions.py
psi4/driver/p4util/numpy_helper.py
psi4/run_psi4.py
psi4/src/core.cc
tests/CMakeLists.txt
tests/json/CMakeLists.txt
tests/json/energy/CMakeLists.txt
tests/json/energy/input.py
tests/json/energy/input.py.dat
tests/json/gradient/CMakeLists.txt
tests/json/gradient/input.py
tests/numpy-array-interface/input.dat

Provides serialized input and output capabilities through a JSON interface. This is an experimental feature and the JSON interface itself will likely evolve significantly over various iterations.
- `psi4 --json data.json` is now a valid Psi input.
- All python based exceptions (not just Psi exceptions) in Psithon should now be printed to the Psi output as well as stdout.
- Dimension objects now have an `__iter__` attribute.

Enables serialized JSON jobs

---

doc/sphinxman/source/glossary_psivariables.rst
psi4/driver/procedures/mcscf/mcscf_solver.py
psi4/driver/procedures/proc.py
psi4/src/psi4/detci/ciwave.cc
psi4/src/psi4/detci/ciwave.h
psi4/src/psi4/detci/diag_h.cc
psi4/src/psi4/detci/opdm.cc
psi4/src/psi4/detci/params.cc
psi4/src/read_options.cc
tests/casscf-sa-sp/input.dat
tests/ci-property/input.dat
tests/dfcasscf-sa-sp/input.dat

As discussed CI moves to a zero-indexed scheme.

CI: Moves to zero-root indexing

---

psi4/src/psi4/detci/diag_h.cc
tests/fci-tdm-2/input.dat
tests/fci-tdm/input.dat

Apparently missed two tests when moving CI to a zero-indexing. A bit confused why there were not picked up by the "ci" tag, but oh well. Fixed now.

CIWave: Patches up zero indexing

---

psi4/driver/inputparser.py
psi4/driver/molutil.py
tests/python/CMakeLists.txt
tests/python/pubchem/CMakeLists.txt
tests/python/pubchem/input.py

Allows Pubchem syntax to be used in Python inputs.

Pubchem in Python

---

psi4/src/psi4/detci/diag_h.cc
psi4/src/read_options.cc
tests/casscf-fzc-sp/input.dat

CIWave: Minor CI patches.

---

psi4/src/psi4/ccdensity/get_moinfo.cc
psi4/src/psi4/cceom/get_moinfo.cc
psi4/src/psi4/cchbar/get_moinfo.cc
psi4/src/psi4/cclambda/get_moinfo.cc
psi4/src/psi4/ccresponse/get_moinfo.cc
psi4/src/psi4/cctriples/get_moinfo.cc
psi4/src/psi4/detci/get_mo_info.cc
psi4/src/psi4/detci/opdm.cc
psi4/src/psi4/libfock/apps.cc
psi4/src/psi4/libfock/hamiltonian.cc
psi4/src/psi4/libfock/solver.cc
psi4/src/psi4/libfock/soscf.cc
psi4/src/psi4/libmints/deriv.cc
psi4/src/psi4/libmints/dimension.cc
psi4/src/psi4/libmints/dimension.h
psi4/src/psi4/libmints/factory.cc
psi4/src/psi4/libmints/factory.h
psi4/src/psi4/libmints/matrix.h
psi4/src/psi4/libmints/oeprop.cc
psi4/src/psi4/libmints/vector.cc
psi4/src/psi4/libmints/vector.h
psi4/src/psi4/libmints/wavefunction.cc
psi4/src/psi4/libmints/wavefunction.h
psi4/src/psi4/libscf_solver/hf.cc
psi4/src/psi4/libscf_solver/rohf.cc

#571 has gone a little awry in its git history. This should be a clean version. Relying on CI for compile testing. Maybe should still be squash merged.

Duplicate of Refactoring of Dimension Class

---

doc/sphinxman/source/cubeprop.rst

Fixed broken link to vmd_cube script

Fixed broken link to vmd_cube script

---

doc/sphinxman/source/opt.rst

Substitute "geometry projection" with "geometry optimization" in `opt.rst`

Fix opt.rst

---

psi4/src/psi4/libmints/writer.cc

This PR simply adds atom and AO labels to the printing of MO's. 
An example of the way it currently looks with this PR: 
```
==> Molecular Orbitals <==
1            2            3            4            5
1    KR1 s       0.9940785    0.4464603    0.0000000    0.0000000    0.0000000
2    KR1 s       0.0144528   -1.0568053    0.0000000    0.0000000    0.0000000
3    KR1 px      0.0000000    0.0000000    0.9928515    0.0000000    0.0000000
4    KR1 py      0.0000000    0.0000000    0.0000000    0.9928515    0.0000000
5    KR1 pz      0.0000000    0.0000000    0.0000000    0.0000000    0.9928515
6    KR1 s      -0.0017038   -0.0826135    0.0000000    0.0000000    0.0000000
7    KR1 px      0.0000000    0.0000000    0.0182476    0.0000000    0.0000000
8    KR1 py      0.0000000    0.0000000 …
```

Added printing of AO and atom labels to printing of MO's

---

doc/sphinxman/source/cubeprop.rst
psi4/share/psi4/scripts/vmd_cube.py

Updates the vmd_cube script.
Adds new color schemes and the ability to control image size.

Updates vmd_cube.

---

psi4/src/psi4/detci/ciwave.h
psi4/src/psi4/detci/h0block.cc
psi4/src/psi4/detci/printing.cc
psi4/src/psi4/optking/mem.cc

This PR 
(a) adds checks that alloc's have been succesful in optking
(b) rewrites detci's print_config routine to use dynamic memory allocation instead of static arrays, which I believe caused issue #606.

Safer memory operations

---

README.md
tests/python/threading/CMakeLists.txt

I forgot the `threading/CMakeLists.txt`. Now included. Error found by @schiebermc

quick fix for MKL build

---

doc/sphinxman/source/detci.rst
doc/sphinxman/source/mcscf.rst
doc/sphinxman/source/methods.rst
psi4/header.py
psi4/src/psi4/detci/civect.cc

Update CI and MCSCF sections of manual

---

.codecov.yml

Updates the CodeCov to provide a very low coverage barrier. This should be fixed later once the coverage has been increased to reasonable level.

Updates CodeCov YAML. 

---

tests/CMakeLists.txt
tests/rohf-orb-rot/CMakeLists.txt
tests/rohf-orb-rot/input.dat
tests/rohf-orb-rot/output.ref

A test case for dgasmith's orbital rotation code using an ROHF reference.

Added test case for dgasmith's orbital rotation code

---

external/upstream/libefp/CMakeLists.txt
tests/pcmsolver/scf/input.dat

Fixes pcmsolver/scf for py3

---

psi4/src/psi4/dfocc/ccsd_triples.cc

The integral overflow problem in the (T) energy code was solved. 

Fixing integral overflow problem in (T) energy code

---

doc/sphinxman/CMakeLists.txt
doc/sphinxman/source/build_faq.rst
doc/sphinxman/source/build_planning.rst
doc/sphinxman/source/conda.rst
doc/sphinxman/source/conf.py.in
doc/sphinxman/source/plugins.rst
doc/sphinxman/source/simint.rst

docs conda and docs build updates

---

doc/sphinxman/source/glossary_psivariables.rst
psi4/src/export_wavefunction.cc
psi4/src/psi4/ccenergy/ccenergy.cc
tests/cc4/input.dat

Adds more CC variables and fixes docstring.

Devdevel bugs

---

psi4/driver/procrouting/dft_funcs/hyb_superfuncs.py

Updated citation and description for PBE0

---

psi4/src/psi4/libfock/DFJK.cc

Fix possible unsigned subtraction wrap around.

---

psi4/src/export_mints.cc
psi4/src/psi4/dfocc/df_corr.cc
psi4/src/psi4/fnocc/ccsd.cc
psi4/src/psi4/fnocc/coupled_pair.cc
psi4/src/psi4/fnocc/df_ccsd.cc
psi4/src/psi4/lib3index/df_helper.cc
psi4/src/psi4/libdisp/dispersion.cc
psi4/src/psi4/libfock/cubature.cc
psi4/src/psi4/libmints/3coverlap.cc
psi4/src/psi4/libmints/basisset.cc
psi4/src/psi4/libmints/basisset.h
psi4/src/psi4/libmints/ecpint.cc
psi4/src/psi4/libmints/eribase.cc
psi4/src/psi4/libmints/matrix.cc
psi4/src/psi4/libmints/vector.cc

Pybind includes are gone from libmints and a couple of other locations, to speed up compilation.

Remove pybind from Libmints

---

doc/sphinxman/source/basissets.rst
psi4/share/psi4/basis/NOTES

Provide documentation for a soon-to-follow PR from Lori that will fix the Ca basis for cc-pCV5Z

Docs for fixing cc-pCV5Z Ca basis

---

tests/CMakeLists.txt

Bypass `props2` test

---

doc/sphinxman/source/cubeprop.rst

The online docs are not rendering properly, this fixes the RST

Fix the RST for command line help

---

psi4/driver/driver.py
psi4/driver/procrouting/interface_cfour.py
psi4/driver/qcdb/cfour.py
psi4/src/read_options.cc

Cfour threading & Optking ending fixes

---

psi4/driver/procrouting/proc.py
tests/dft-grad1/input.dat

Fixes small issue in gradients for custom `dft_functionals` @loriab.

DFT: Fixes custom dft_func for gradients

---

doc/sphinxman/source/dft.rst

Change description of obsolete `set dft_functional` to argument passing

Update DFT docs 

---

psi4/driver/json_wrapper.py
psi4/src/psi4/dfep2/dfep2.cc
tests/json/energy/input.py
tests/json/energy/input.py.dat

Ensures that JSON provenance data is always written and updates its memory setter to the new type. Removes EP2 pragma's that shouldn't exists and has caused problems.

Minor JSON and EP2 tweaks

---

psi4/driver/qcdb/libmintsgshell.py

Issue #846 has been fixed, so a contraction set where all primitives have a coefficient of 0 will remain untouched. While I was poking around the file, I decided to clean up some other things.

Issue 846 Fix; Changed 0 Coefficient Handling

---

tests/psi4numpy/rhf-hessian/input.py

A minor correction to the test file of rhf-hessian. Unfortunately, this wasn't picked 
before the merge of https://github.com/psi4/psi4/pull/757.

removed redundant code in rhf hessian test file 

---

psi4/src/psi4/dcft/CMakeLists.txt

Allows for #925 to work for #923 for those with old cmake and new intel compilers.

allows for old cmake and new intel compilers

---

psi4/driver/procrouting/sapt/sapt_proc.py
psi4/driver/procrouting/sapt/sapt_util.py

A few fixes for the problems outlined in issues #911 and #910.

SAPT(DFT) printing and GGA bug fixes.

---

psi4/src/psi4/libmints/matrix.cc

Added missing existence check for each symmetry sub matrix in the advanced Matrix::gemm. (The first Matrix::gemm in matrix.cc). 

Advanced Matrix::gemm, added existence check for each symmetry submatrix

---

psi4/extras.py
psi4/header.py

Adds hostname printing to output file header, and stop time to output file "footer" before success/failure beer/coffee message.

Adds hostname to header, stop time info to footer

---

external/downstream/v2rdm_casscf/CMakeLists.txt

fix v2rdm typo

---

psi4/extras.py
psi4/header.py
psi4/run_psi4.py

Added execution time to the end of output file.

add total execution time to output.

---

psi4/src/psi4/fnocc/ccsd.h
psi4/src/psi4/fnocc/frozen_natural_orbitals.h
psi4/src/psi4/lib3index/dftensor.h
psi4/src/psi4/libfunctional/superfunctional.h
psi4/src/psi4/libqt/qt.h

Exports symbols for my tutorial plugins, some private plugins, and gpu_dfcc.

Plugins psiapi

---

.travis.yml

Switch to `psi4/label/dev` in `.travis.yml`

Switch to psi4/label/dev

---

doc/sphinxman/source/manage_git.rst

Document a few more troubles ppl can hit.

DOC: a few more gotchas

---

doc/sphinxman/source/scf.rst
psi4/driver/procrouting/proc.py
tests/dfmp2-3/input.dat

Fixes small mem/disk DFJK issue in MP2 gradients and adds some documentation on the new mem/disk DFJK options.

MP2 DFJK logic fix and DFJK docs

---

cmake/autocmake_omp.cmake
external/upstream/libxc/CMakeLists.txt
psi4/driver/qcdb/hessparse.py
psi4/driver/qcdb/libmintsmolecule.py
psi4/driver/qcdb/molparse/to_schema.py
psi4/driver/qcdb/molparse/to_string.py
psi4/share/psi4/scripts/test_threading.py
psi4/src/psi4/libfock/MemDFJK.cc
psi4/src/psi4/libfock/PK_workers.cc
psi4/src/psi4/libfock/PK_workers.h
psi4/src/psi4/libfock/PKmanagers.cc
psi4/src/psi4/libfock/PKmanagers.h
psi4/src/psi4/libmints/molecule.cc

Threadmisc

---

psi4/src/psi4/libsapt_solver/sapt0.h
psi4/src/psi4/libsapt_solver/utils.cc
psi4/src/read_options.cc
tests/json/schema_0_energy/input.py
tests/json/schema_0_ghost/input.py
tests/json/schema_0_gradient/input.py
tests/json/schema_0_orient/input.py
tests/json/schema_0_properties/input.py
tests/json/v11_energy/input.py
tests/json/v11_gradient/input.py

SCF_TYPE and SAPT mem

---

psi4/src/psi4/libmints/local.h

Exports Boys localization for plugins.

export boys localizer for plugins

---

.travis.yml
external/common/lapack/FindTargetOpenMP.cmake
external/common/lapack/TargetLAPACKConfig.cmake.in
psi4/extras.py
psi4/header.py
psi4/share/psi4/scripts/test_threading.py
psi4/src/psi4/dcft/CMakeLists.txt

addl contrib and test_threading fixes

---

doc/sphinxman/source/build_planning.rst
external/upstream/dkh/CMakeLists.txt
external/upstream/erd/CMakeLists.txt
external/upstream/gdma/CMakeLists.txt
external/upstream/simint/CMakeLists.txt
psi4/CMakeLists.txt
psi4/src/psi4/libefp_solver/efp_solver.cc
psi4/src/psi4/libmints/integral.cc
tests/erd/scf5/input.dat
tests/scf5/input.dat
tests/simint/scf5/input.dat

fix up simint and erd
~**Contains debug printing which should be removed before final merge**~

simint and erd

---

psi4/src/psi4/libscf_solver/rhf.cc
psi4/src/psi4/libscf_solver/rohf.cc
psi4/src/psi4/libscf_solver/uhf.cc

Raises exception to address #1045.

Adds XC exception to stability code

---

doc/sphinxman/source/fchk.rst

Update to new location of the FCHKWriter - now in core.

Update location of the FCHKWriter to core

---

codemeta.json
external/common/lapack/CMakeLists.txt
external/common/lapack/FindMathOpenMP.cmake
external/common/lapack/TargetLAPACKConfig.cmake.in
external/downstream/gpu_dfcc/CMakeLists.txt
external/upstream/ambit/CMakeLists.txt
psi4/share/psi4/scripts/test_threading.py

I was browsing some MolSSI-tweeted videos and learned about the `codemeta.json` movement. Didn't sound like a bad idea, so here's a start, reformatted from the 1.1 paper. It potentially needs more authors from psi1-psi3 era.

author info

---

codemeta.json
external/downstream/v2rdm_casscf/CMakeLists.txt
psi4/driver/qcdb/interface_dftd3.py

accumulate post-rc3 changes

---

psi4/src/psi4/libmints/oeprop.cc

Makes print statement more clearly communicate to user which density matrix is being employed. c closes #1055 

Oeprop printing

---

README.md

trivialities

---

doc/sphinxman/source/dftd3.rst
doc/sphinxman/source/gcp.rst

Andysim patch 1

---

psi4/src/psi4/lib3index/dfhelper.cc

Added printout for memory availability in DFHelper

enh: adds mem printout to DFHelper

---

.travis.yml

Add py37 to Travis-CI

---

README.md

doc: fix the img I moved in psi4media

---

tests/CMakeLists.txt
tests/cbs-xtpl-nbody/CMakeLists.txt
tests/cbs-xtpl-nbody/input.dat
tests/cbs-xtpl-nbody/output.ref

Added tests for nbody-cbs compatibility

---

external/upstream/gau2grid/CMakeLists.txt
external/upstream/libint/CMakeLists.txt
external/upstream/libxc/CMakeLists.txt
psi4/CMakeLists.txt

This is part of Psi4 porting to Windows (#933).

Update dependencies for Windows

---

doc/sphinxman/source/prog_code_intro.rst
doc/sphinxman/source/prog_debug_profile.rst

Add a couple of missing stub files from my previous PR, fixes #1146

doc: add missing stub files for programmers' manual

---

tests/runtest.py

Port tests to Windows

---

psi4/src/psi4/fisapt/fisapt.cc
psi4/src/psi4/fisapt/fisapt.h
psi4/src/psi4/fisapt/local2.cc
psi4/src/psi4/fisapt/local2.h

fmt: clang-format FISAPT module

fmt: clang-format FISAPT module

---

psi4/src/psi4/libpsi4util/PsiOutStream.cc
psi4/src/psi4/libpsi4util/class_macros.h
psi4/src/psi4/libpsi4util/combinations.cc
psi4/src/psi4/libpsi4util/exception.cc
psi4/src/psi4/libpsi4util/exception.h
psi4/src/psi4/libpsi4util/libpsi4util.h
psi4/src/psi4/libpsi4util/memory_manager.cc
psi4/src/psi4/libpsi4util/memory_manager.h
psi4/src/psi4/libpsi4util/process.cc
psi4/src/psi4/libpsi4util/process.h
psi4/src/psi4/libpsi4util/stl_string.cc

fmt: clang-format LIBPSI4UTIL module

fmt: clang-format LIBPSI4UTIL module

---

psi4/src/psi4/libtrans/integraltransform.h
psi4/src/psi4/libtrans/integraltransform_functors.h
psi4/src/psi4/libtrans/integraltransform_moinfo.cc
psi4/src/psi4/libtrans/integraltransform_oei.cc
psi4/src/psi4/libtrans/integraltransform_sort_mo_tpdm.cc
psi4/src/psi4/libtrans/integraltransform_sort_so_tpdm.cc
psi4/src/psi4/libtrans/integraltransform_tpdm_restricted.cc
psi4/src/psi4/libtrans/integraltransform_tpdm_unrestricted.cc
psi4/src/psi4/libtrans/mospace.h

fmt: clang-format libtrans

---

psi4/src/psi4/libdiis/diisentry.cc
psi4/src/psi4/libdiis/diisentry.h
psi4/src/psi4/libdiis/diismanager.cc
psi4/src/psi4/libdiis/diismanager.h

fmt: clang-format libDIIS

---

psi4/src/psi4/dfmp2/corr_grad.cc
psi4/src/psi4/dfmp2/corr_grad.h
psi4/src/psi4/dfmp2/mp2.cc
psi4/src/psi4/dfmp2/mp2.h
psi4/src/psi4/dfmp2/wrapper.cc

fmt: clang-format DFMP2 module

---

psi4/src/psi4/libdisp/dispersion.cc
psi4/src/psi4/libdisp/dispersion.h
psi4/src/psi4/libdisp/dispersion_defines.h

fmt: clang-format LIBDISP module

fmt: clang-format LIBDISP module

---

psi4/src/psi4/libpsipcm/psipcm.cc
psi4/src/psi4/libpsipcm/psipcm.h

fmt: clang-format libpsipcm

---

psi4/src/psi4/libiwl/buf_close.cc
psi4/src/psi4/libiwl/buf_fetch.cc
psi4/src/psi4/libiwl/buf_flush.cc
psi4/src/psi4/libiwl/buf_init.cc
psi4/src/psi4/libiwl/buf_put.cc
psi4/src/psi4/libiwl/buf_wrt.cc
psi4/src/psi4/libiwl/buf_wrt_mat.cc
psi4/src/psi4/libiwl/buf_wrt_val.cc
psi4/src/psi4/libiwl/config.h
psi4/src/psi4/libiwl/iwl.h
psi4/src/psi4/libiwl/iwl.hpp
psi4/src/psi4/libiwl/rdone.cc
psi4/src/psi4/libiwl/wrtone.cc

fmt: clang-format LIBIWL module

fmt: clang-format LIBIWL module

---

psi4/src/psi4/libscf_solver/cuhf.cc
psi4/src/psi4/libscf_solver/cuhf.h
psi4/src/psi4/libscf_solver/frac.cc
psi4/src/psi4/libscf_solver/hf.cc
psi4/src/psi4/libscf_solver/hf.h
psi4/src/psi4/libscf_solver/mom.cc
psi4/src/psi4/libscf_solver/rhf.cc
psi4/src/psi4/libscf_solver/rhf.h
psi4/src/psi4/libscf_solver/rohf.cc
psi4/src/psi4/libscf_solver/rohf.h
psi4/src/psi4/libscf_solver/sad.cc
psi4/src/psi4/libscf_solver/sad.h
psi4/src/psi4/libscf_solver/stability.cc
psi4/src/psi4/libscf_solver/uhf.cc
psi4/src/psi4/libscf_solver/uhf.h

fmt: clang-format libscf_solver

---

psi4/src/psi4/gdma_interface/wrapper.cc

fmt: clang-format GDMA interface

---

psi4/src/psi4/cctransort/a_spinad.cc
psi4/src/psi4/cctransort/b_spinad.cc
psi4/src/psi4/cctransort/c_sort.cc
psi4/src/psi4/cctransort/cache.cc
psi4/src/psi4/cctransort/cctransort.cc
psi4/src/psi4/cctransort/d_sort.cc
psi4/src/psi4/cctransort/d_spinad.cc
psi4/src/psi4/cctransort/denom.cc
psi4/src/psi4/cctransort/e_sort.cc
psi4/src/psi4/cctransort/e_spinad.cc
psi4/src/psi4/cctransort/f_sort.cc
psi4/src/psi4/cctransort/fock.cc
psi4/src/psi4/cctransort/memcheck.cc
psi4/src/psi4/cctransort/pitzer2qt.cc
psi4/src/psi4/cctransort/scf_check.cc
psi4/src/psi4/cctransort/sort_tei_rhf.cc
psi4/src/psi4/cctransort/sort_tei_uhf.cc

clang-format the cctransort module

fmt: clang-format the cctransort module

---

appveyor.yml

Reduce the number of tests on Appveyor

---

external/upstream/chemps2/CMakeLists.txt

addon: get CheMPS2 with build improvements

addon: get CheMPS2 with build improvements

---

psi4/src/psi4/cctriples/ET_AAA.cc
psi4/src/psi4/cctriples/ET_AAB.cc
psi4/src/psi4/cctriples/ET_ABB.cc
psi4/src/psi4/cctriples/ET_BBB.cc
psi4/src/psi4/cctriples/ET_RHF.cc
psi4/src/psi4/cctriples/ET_UHF_AAA.cc
psi4/src/psi4/cctriples/ET_UHF_AAB.cc
psi4/src/psi4/cctriples/ET_UHF_ABB.cc
psi4/src/psi4/cctriples/ET_UHF_BBB.cc
psi4/src/psi4/cctriples/EaT_RHF.cc
psi4/src/psi4/cctriples/MOInfo.h
psi4/src/psi4/cctriples/Params.h
psi4/src/psi4/cctriples/T3_UHF_AAA.cc
psi4/src/psi4/cctriples/T3_UHF_AAB.cc
psi4/src/psi4/cctriples/T3_UHF_ABC.cc
psi4/src/psi4/cctriples/T3_grad_RHF.cc
psi4/src/psi4/cctriples/T3_grad_UHF_AAA.cc
psi4/src/psi4/cctriples/T3_grad_UHF_AAB.cc
psi4/src/psi4/cctriples/T3_grad_UHF_BBA.cc
psi4/src/psi4/cctriples/T3_grad_UHF_BBB.cc
psi4/src/psi4/cctriples/cache.cc
psi4/src/psi4/cctriples/count_ijk.cc
psi4/src/psi4/cctriples/get_moinfo.cc
psi4/src/psi4/cctriples/globals.h
psi4/src/psi4/cctriples/test_abc_loops.cc
psi4/src/psi4/cctriples/transpose_integrals.cc
psi4/src/psi4/cctriples/triples.cc

Clang format libdpd, without conflicts. Supersedes #1209

fmt: clang-format cctriples

---

psi4/share/psi4/scripts/test_threading.py
tests/opt13/input.dat

These are a couple items that are preventing the conda-builds from working. Mentioning #1283 so we remember to adjust opt13 back after solution.

patch for conda-builds

---

psi4/src/psi4/libmints/matrix.cc

Fixed OMP for matrix.rms()

---

README.md

Correct (py versions), expand (commit activity), and organize the README badges. Also fix the slack invite issue.

shields.io update

---

psi4/src/psi4/libmints/matrix.cc
psi4/src/psi4/libmints/wavefunction.cc
psi4/src/read_options.cc

Some minor fixes cherry-picked from #1061

Minor fixes

---

psi4/src/psi4/dcft/dcft.h
psi4/src/psi4/dfmp2/mp2.h
psi4/src/psi4/libfock/PK_workers.h
psi4/src/psi4/libfock/PKmanagers.h
psi4/src/psi4/libfock/hamiltonian.h
psi4/src/psi4/libfock/jk.h
psi4/src/psi4/libfock/points.h
psi4/src/psi4/libfock/solver.h
psi4/src/psi4/libfock/soscf.h
psi4/src/psi4/libfock/v.h
psi4/src/psi4/libfunctional/LibXCfunctional.h
psi4/src/psi4/libmints/coordentry.h
psi4/src/psi4/libmints/eri.h
psi4/src/psi4/libmints/potential.h
psi4/src/psi4/libmints/rel_potential.h
psi4/src/psi4/liboptions/liboptions.h
psi4/src/psi4/liboptions/liboptions_python.h
psi4/src/psi4/libpsi4util/exception.h
psi4/src/psi4/libscf_solver/rhf.h
psi4/src/psi4/libscf_solver/uhf.h
psi4/src/psi4/optking/bend.h
psi4/src/psi4/optking/cart.h
psi4/src/psi4/optking/oofp.h
psi4/src/psi4/optking/stre.h
psi4/src/psi4/optking/tors.h
psi4/src/psi4/scfgrad/scf_grad.h

clang-tidy: Finishes off "override" conversion

---

appveyor.yml
tests/pytest/conftest.py

Fix "psi4 --test" on Windows

---

psi4/driver/driver_cbs.py

Removed unused line.

---

tests/dft-custom-gga/input.dat

Fixes #994 and #1038. FT97 does not want to converge, so I gave it a handicap. And with that, all the tests that run in a reasonable amount of time pass on a release build.

Fix Failing dft-custom-gga

---

psi4/share/psi4/basis/2zapa-nr.gbs
psi4/share/psi4/basis/3zapa-nr.gbs
psi4/share/psi4/basis/4zapa-nr.gbs
psi4/share/psi4/basis/5zapa-nr.gbs
psi4/share/psi4/basis/6zapa-nr.gbs
psi4/share/psi4/basis/7zapa-nr.gbs

`cbs-xtpl-energy` test won't pass in conda-build if non-ascii present.

re-asciify

---

psi4/src/psi4/detci/ints.cc
psi4/src/psi4/libfunctional/superfunctional.cc
psi4/src/psi4/scfgrad/jk_grad.cc

As discussed in https://github.com/psi4/psi4/issues/933#issuecomment-423183802, *clang-cl* supports *OpenMP* 4.0, so the adaptation to *OpenMP* 2.0 is not necessary.

Revert "Fix OpenMP for Windows in detci, libfunctional, and scfgrad"

---

psi4/src/psi4/libmints/matrix.cc
psi4/src/psi4/libmints/mintshelper.cc

As discussed in https://github.com/psi4/psi4/issues/933#issuecomment-423183802, *clang-cl* supports *OpenMP* 4.0, so the adaptation to *OpenMP* 2.0 is not necessary.

Revert "Fix OpenMP for Windows in libmints"

---

psi4/src/psi4/lib3index/cholesky.h
psi4/src/psi4/lib3index/denominator.h
psi4/src/psi4/lib3index/dfhelper.cc
psi4/src/psi4/lib3index/dfhelper.h
psi4/src/psi4/lib3index/dftensor.cc
psi4/src/psi4/lib3index/dftensor.h
psi4/src/psi4/lib3index/fittingmetric.cc

Now that #1200 is merged, can proceed with formatted lib3index. Replaces #1169. Relevant to #1144.

fmt: clang-format lib3index (take 2)

---

psi4/src/psi4/libfunctional/LibXCfunctional.cc
psi4/src/psi4/libfunctional/LibXCfunctional.h
psi4/src/psi4/libfunctional/functional.cc
psi4/src/psi4/libfunctional/functional.h
psi4/src/psi4/libfunctional/superfunctional.cc
psi4/src/psi4/libfunctional/superfunctional.h

Applies clang-format to libfunctional. Part of #1144

fmt: clang-format libfunctional

---

doc/sphinxman/source/conda.rst

Add python 3.7 to versions listed in the conda docs

Update pyversions in conda install docs

---

tests/pcmsolver/scf/input.dat

Some PCM related updates/fixes that were enabled after the move of SCF to Python.
~- [ ] Do gradients with PCM semi-numerically [à la ECP](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L2095-L2132), see https://github.com/psi4/psi4/issues/402#issuecomment-386149151~ **Probably for 1.4**

Small PCM updates after scfitertopy

---

azure-pipelines.yml
psi4/CMakeLists.txt
psi4/psi4.bat

Implement `psi4` command on Windows.

psi4 command on Windows

---

psi4/src/psi4/libpsio/volseek.cc

Fix the crash reported by @tonigi (https://github.com/psi4/psi4/issues/933#issuecomment-446601070)

Fix integer overflow in psi::psi_volseek

---

external/common/lapack/FindTargetOpenMP.cmake
psi4/src/psi4/libciomr/libciomr.h
psi4/src/psi4/libciomr/tstart.cc
psi4/src/psi4/libqt/qt.h

at least let v2rdm configure, compile, and load. the openmp find_components was broken for plugins by #1348

remedial v2rdm

---

psi4/src/read_options.cc
tests/nbody-convergence/input.dat

code parsers for docs want things just so.

humor the docs parsing

---

psi4/driver/driver.py

The instructions in the docstring did not result in a correct Molden file. Fixes #1485. No new features added.

Fix documentation for writing natural orbitals to Molden file

---

psi4/driver/p4util/python_helpers.py

missed a dot

---

psi4/src/psi4/libmints/writer.cc

The Molden format allows one to store data in high precision, which is beneficial for post-processing. This PR increases the number of digits and the format of the relevant numbers to double precision.
Fixes #1486. See also #1485 
I've tested with the following example:
```
molecule {
0 1
O          1.01646        0.05097        0.09714
H          1.98435        0.06069        0.05173
H          0.73761        0.24513       -0.81034
}
set basis cc-pVTZ
E, wfn = properties('ccsd', properties=['dipole'], return_wfn=True)
Da_so = wfn.Da()
SCa = core.doublet(wfn.S(), wfn.Ca(), False, False)
Da_mo = core.triplet(SCa, Da_so, SCa, True, False, False)
molden(wfn, 'psi4.molden', density_a=Da_mo)
```
The Molden files before and after the change are attached: …

Molden file format: double precision orbital energies, occupation numbers and molecular orbital coefficients

---

external/common/lapack/FindTargetOpenMP.cmake
psi4/driver/driver.py

reconcile fchk and gdma fixes psi4/psi4#1523

---

psi4/src/psi4/libscf_solver/sad.cc

Fixes #1528: the index offsets were wrong for ghost atoms.

Fix indexing for ghost atoms

---

codemeta.json
psi4/header.py

@raimis, @JonathonMisiewicz, @alenaizan, @susilehtola, @zachglick  
Please suggest any spelling or initials changes. Also, supply info for https://github.com/psi4/psi4/blob/master/codemeta.json. Either post here or PR _to this PR_. You're also at liberty to decline.

v1.3 additional contributions

---

.travis.yml

Lets packages update even though we're caching on Travis CI

Use before_cache to solve caching troubles on Travis

---

tests/scf-dipder/input.dat

Replace 'get_array' with 'variable' to avoid deprecation warning

Update scf-dipder test case

---

doc/sphinxman/source/build_faq.rst
doc/sphinxman/source/build_planning.rst
psi4/driver/json_wrapper.py
tests/json/schema-1-energy/input.py
tests/json/schema-1-properties/input.py

Name is changing slightly. Both versions accepted.

json_wrapper uses qcschema_input

---

doc/sphinxman/source/introduction.rst
external/downstream/snsmp2/CMakeLists.txt
external/upstream/ambit/CMakeLists.txt
external/upstream/libxc/CMakeLists.txt

update  addon build commits

---

CMakeLists.txt
doc/sphinxman/source/manage_release.rst
external/upstream/libxc/CMakeLists.txt

misc.
```
[2019-03-04 21:34:07] [build] Scanning dependencies of target libxc_external
[2019-03-04 21:34:07] [build] [  2%] Creating directories for 'libxc_external'
[2019-03-04 21:34:07] [build] [  4%] Performing download step (git clone) for 'libxc_external'
[2019-03-04 21:34:07] [build] Cloning into 'libxc_external'...
[2019-03-04 21:34:10] [build] fatal: could not read Username for 'https://gitlab.com': No such device or address
[2019-03-04 21:34:10] [build] fatal: The remote end hung up unexpectedly
[2019-03-04 21:34:10] [build] Cloning into 'libxc_external'...
[2019-03-04 21:34:11] [build] fatal: could not read Username for 'https://gitlab.com': No such device or address
[2019-03-04 21:34:12] [build] …
```

min py to 36. use libxc tarball

---

external/upstream/gau2grid/CMakeLists.txt
external/upstream/pybind11/CMakeLists.txt
external/upstream/qcelemental/CMakeLists.txt

shift req'd deps from GH clone to URL for lgtm, who fears becoming a DDOS agent through `git clone`

download externals through url instead of git clone

---

psi4/driver/p4util/optproc.py
psi4/driver/p4util/procutil.py
psi4/driver/p4util/solvers.py
psi4/driver/p4util/util.py
psi4/driver/procrouting/dft/superfunctionals.py
psi4/driver/procrouting/response/scf_products.py
psi4/driver/qcdb/libmintsbasisset.py
psi4/driver/qcdb/libmintsmolecule.py

Makes corrections suggested by lgtm.

---

external/upstream/libint/CMakeLists.txt
psi4/src/psi4/libmints/eri.h

rejoin the rest of the world with libderiv/libderiv.h
fyi, @susilehtola , @mbanck, @yurivict

rejoin the rest of the world with libderiv/libderiv.h

---

psi4/driver/qcdb/vib.py
psi4/src/read_options.cc

missing items

---

psi4/src/psi4/dcft/dcft_compute.cc
psi4/src/psi4/dcft/dcft_density_UHF.cc

Adding some warnings regarding #1579.

Add DF-DCFT warning messages.

---

psi4/src/psi4/libmints/oeprop.h

Added PSI_API to OEProp for use in external pluggins

added PSI_API to OEProp

---

azure-pipelines.yml
doc/sphinxman/source/manage_git.rst
doc/sphinxman/source/manage_release.rst
doc/sphinxman/source/prog_faq.rst
doc/sphinxman/source/prog_style_py.rst
external/upstream/qcengine/CMakeLists.txt

postrelease, codereview, bots docs

---

psi4/driver/json_wrapper.py
tests/json/schema-1-energy/input.py
tests/json/schema-1-energy/output.json.ref

Moves JSON output handle to tempfile to remove odd atexit issues.

JSON: Moves output data to tempfile

---

psi4/src/psi4/libpsio/tocprint.cc

Fix print issue in tocprint.cc

Fix lgtm issues in libpsio

---

psi4/src/psi4/dfmp2/corr_grad.cc
psi4/src/psi4/lib3index/denominator.cc
psi4/src/psi4/libdiis/diismanager.cc
psi4/src/psi4/libfunctional/LibXCfunctional.cc

LGTM: dfmp2, lib3index, libdiis, libfunctional

---

psi4/src/psi4/detci/civect.cc
psi4/src/psi4/detci/h0block.cc
psi4/src/psi4/detci/mitrush_iter.cc
psi4/src/psi4/detci/olsengraph.cc
psi4/src/psi4/detci/printing.cc
psi4/src/psi4/detci/sigma.cc
psi4/src/psi4/detci/slaterd.cc
psi4/src/psi4/detci/slaterd.h
psi4/src/psi4/detci/stringlist.cc

most of LGTM alerts for detci

---

psi4/src/psi4/libmints/matrix.cc
psi4/src/psi4/libmints/matrix.h

LGTM of libmints

---

psi4/src/psi4/scfgrad/jk_grad.cc
psi4/src/psi4/scfgrad/response.cc
psi4/src/psi4/scfgrad/scf_grad.cc

LGTM fixes for scfgrad

---

psi4/src/psi4/cc/ccenergy/BT2.cc
psi4/src/psi4/cc/ccenergy/analyze.cc
psi4/src/psi4/cc/ccenergy/diis_RHF.cc
psi4/src/psi4/cc/ccenergy/diis_ROHF.cc
psi4/src/psi4/cc/ccenergy/diis_UHF.cc
psi4/src/psi4/cc/ccenergy/get_moinfo.cc
psi4/src/psi4/cc/ccenergy/local.cc

Mostly integer type conversion.

Fix lgtm issues in ccenergy

---

psi4/src/psi4/cc/cceom/MOInfo.h
psi4/src/psi4/cc/cceom/WabefDD.cc
psi4/src/psi4/cc/cceom/diag.cc
psi4/src/psi4/cc/cceom/diagSS.cc
psi4/src/psi4/cc/cceom/get_moinfo.cc
psi4/src/psi4/cc/cceom/globals.h
psi4/src/psi4/cc/cceom/local.cc
psi4/src/psi4/cc/cceom/local_guess.cc
psi4/src/psi4/cc/cceom/overlap.cc
psi4/src/psi4/cc/cceom/precondition.cc

Removes lgtm issues with the cceom module.

Fix lgtm issues in cceom

---

psi4/driver/driver.py

Fixes #1638 
Corrects some small errors in the documentation of the molden writer, plus improved formatting.

Fix documentation for writing Molden files for CI NO roots

---

psi4/src/core.cc
psi4/src/psi4/libciomr/sq_rsp.cc

lgtm core and partial libciomr

---

psi4/src/psi4/cc/cchbar/MOInfo.h
psi4/src/psi4/cc/cchbar/Params.h
psi4/src/psi4/cc/cchbar/globals.h

LGTM for cchbar

---

psi4/src/psi4/libqt/blas_intfc.cc
psi4/src/psi4/libqt/timer.cc

Fixed timer.cc and blas_intfc.cc

LGTM fixes for libqt

---

psi4/src/psi4/libdpd/T3_AAA.cc
psi4/src/psi4/libdpd/T3_AAB.cc
psi4/src/psi4/libdpd/T3_RHF.cc
psi4/src/psi4/libdpd/T3_RHF_ic.cc
psi4/src/psi4/libdpd/file2_init.cc
psi4/src/psi4/libdpd/file2_mat_rd.cc
psi4/src/psi4/libdpd/file2_mat_wrt.cc
psi4/src/psi4/libdpd/file4_cache.cc
psi4/src/psi4/libdpd/file4_init.cc
psi4/src/psi4/libdpd/file4_init_nocache.cc
psi4/src/psi4/libdpd/file4_mat_irrep_rd_block.cc
psi4/src/psi4/libdpd/file4_mat_irrep_row_rd.cc
psi4/src/psi4/libdpd/file4_mat_irrep_row_wrt.cc
psi4/src/psi4/libdpd/file4_mat_irrep_wrt_block.cc
psi4/src/psi4/libdpd/pairnum.cc

Remove LGTM errors from libdpd

LGTM for libdpd

---

psi4/src/psi4/cc/cclambda/DL2.cc
psi4/src/psi4/cc/cclambda/L1.cc
psi4/src/psi4/cc/cclambda/L2.cc
psi4/src/psi4/cc/cclambda/L3_AAA.cc
psi4/src/psi4/cc/cclambda/L3_AAB.cc
psi4/src/psi4/cc/cclambda/Lamp_write.cc
psi4/src/psi4/cc/cclambda/Lnorm.cc
psi4/src/psi4/cc/cclambda/Local.h
psi4/src/psi4/cc/cclambda/MOInfo.h
psi4/src/psi4/cc/cclambda/Params.h
psi4/src/psi4/cc/cclambda/WefabL2.cc
psi4/src/psi4/cc/cclambda/cc2_L1.cc
psi4/src/psi4/cc/cclambda/cc2_L2.cc
psi4/src/psi4/cc/cclambda/cclambda.cc
psi4/src/psi4/cc/cclambda/cclambda.h
psi4/src/psi4/cc/cclambda/denom.cc
psi4/src/psi4/cc/cclambda/diis.cc
psi4/src/psi4/cc/cclambda/get_moinfo.cc
psi4/src/psi4/cc/cclambda/globals.h
psi4/src/psi4/cc/cclambda/init_amps.cc
psi4/src/psi4/cc/cclambda/local.cc
psi4/src/psi4/cc/cclambda/overlap_LAMPS.cc
psi4/src/psi4/cc/cclambda/pseudoenergy.cc

LGTM for cclambda

---

psi4/src/psi4/cc/ccresponse/Local.h
psi4/src/psi4/cc/ccresponse/MOInfo.h
psi4/src/psi4/cc/ccresponse/Params.h
psi4/src/psi4/cc/ccresponse/X2.cc
psi4/src/psi4/cc/ccresponse/analyze.cc
psi4/src/psi4/cc/ccresponse/diis.cc
psi4/src/psi4/cc/ccresponse/get_moinfo.cc
psi4/src/psi4/cc/ccresponse/globals.h
psi4/src/psi4/cc/ccresponse/local.cc

LGTM for CCResponse, mostly handling int/size_t complaints.

Lgtm ccresponse

---

psi4/src/psi4/libsapt_solver/disp22sdq.cc
psi4/src/psi4/libsapt_solver/disp22t.cc
psi4/src/psi4/libsapt_solver/disp2ccd.cc
psi4/src/psi4/libsapt_solver/disp30.cc
psi4/src/psi4/libsapt_solver/sapt2.cc
psi4/src/psi4/libsapt_solver/sapt2p.h
psi4/src/psi4/libsapt_solver/sapt2p3.h
psi4/src/psi4/libsapt_solver/usapt0.cc
psi4/src/psi4/optking/combo_coordinates.cc
psi4/src/psi4/optking/frag.cc
psi4/src/psi4/optking/frag_natural.cc
psi4/src/psi4/optking/frag_print.cc
psi4/src/psi4/optking/geom_gradients_io.cc
psi4/src/psi4/optking/molecule.cc
psi4/src/psi4/optking/molecule_backstep.cc
psi4/src/psi4/optking/molecule_fragments.cc
psi4/src/psi4/optking/molecule_irc_step.cc
psi4/src/psi4/optking/molecule_linesearch_step.cc
psi4/src/psi4/optking/molecule_nr_step.cc
psi4/src/psi4/optking/molecule_prfo_step.cc
psi4/src/psi4/optking/molecule_print.cc
psi4/src/psi4/optking/molecule_rfo_step.cc
psi4/src/psi4/optking/molecule_sd_step.cc
psi4/src/psi4/optking/opt_data.cc
psi4/src/psi4/optking/optking.cc

Remaining LGTM errors/warnings for libsapt_solver addressed (mostly size_t related).Print statements in optking also fixed.

LGTM libsapt_solver and optking

---

psi4/src/psi4/detci/odometer.cc
psi4/src/psi4/detci/olsengraph.cc
psi4/src/psi4/detci/params.cc
psi4/src/psi4/detci/printing.cc
psi4/src/psi4/liboptions/liboptions.cc
psi4/src/psi4/liboptions/liboptions.h
psi4/src/psi4/liboptions/print.cc

LGTM liboptions

---

.travis.yml

use old mp2d for CI

---

psi4/driver/procrouting/sapt/fisapt_proc.py
psi4/src/read_options.cc

repeat of https://github.com/loriab/psi4/pull/9

@dsirianni fisapt-d

---

psi4/src/psi4/lib3index/dfhelper.cc

Use in-core algorithm in MemDFJK

---

psi4/driver/qcdb/mpl.py

The self tests (`python mpl.py`) now work with modern py3 & mpl.

Update mpl.py for py3

---

external/upstream/qcelemental/CMakeLists.txt
external/upstream/qcengine/CMakeLists.txt
psi4/driver/__init__.py
psi4/driver/json_wrapper.py
psi4/driver/p4util/util.py
psi4/driver/schema_wrapper.py
psi4/extras.py
psi4/run_psi4.py
psi4/src/psi4/cc/ccenergy/ccenergy.cc
psi4/src/psi4/fnocc/ccsd.cc
psi4/src/psi4/fnocc/df_ccsd.cc
tests/json/schema-1-energy/input.py
tests/pytests/test_qcschema.py
tests/pytests/utils.py

Updates the Psi4 interface to the MolSSI QCSchema using canonical QCElemental objects.

QCSchema Interace

---

.travis.yml

let's not build g2g

---

CMakeLists.txt
azure-pipelines.yml
conda/win/meta.yaml
external/upstream/gau2grid/CMakeLists.txt
external/upstream/qcelemental/CMakeLists.txt
psi4/driver/qcdb/molecule.py

bumps and pydantic 1 fix

---

psi4/src/psi4/libdpd/buf4_symm2.cc

Correcting `libdpd` documentation. @lothian should confirm this one himself.

Correct Libdpd Documentation

---

psi4/driver/qcdb/align.py

typos in future advice

---

psi4/src/psi4/dct/dct_gradient_RHF.cc
psi4/src/psi4/dct/dct_integrals_RHF.cc
psi4/src/psi4/dct/dct_intermediates_RHF.cc
psi4/src/psi4/dct/dct_oo_RHF.cc
psi4/src/psi4/dct/dct_tau_RHF.cc
psi4/src/psi4/libmints/basisset.cc
psi4/src/psi4/libmints/basisset.h
psi4/src/psi4/libmints/bessel.cc

I was testing a trick I had heard of to clean up valgrind output (which alas, didn't work). I got carried away fixing the memory leaks it reported before deciding that continuing was not the best way to use my time. Don't expect this work to be continued in the immediate future. A "Valgrind Day" just like "LGTM Day" or "Documentation Day" would be very useful.

Fix some memory leaks

---

doc/sphinxman/source/bibliography.rst
doc/sphinxman/source/scf.rst

The arXiv manuscript detailing the finite-element calculations for the SAP potenials has been published; this PR updates the documentation with the final reference.

Final reference for SAP potentials.

---

psi4/src/psi4/dmrg/dmrgscf.cc
psi4/src/psi4/libmints/mintshelper.cc
psi4/src/psi4/libmints/mintshelper.h

Bug fix and improvements to the MintsHelper class constructor.

Fix issue with memory deallocation in the DMRG code

---

psi4/src/psi4/detci/ciwave.cc

Does exactly what it says in the title.

Correct copy-paste error message

---

.azure-pipelines/azure-pipelines-linux.yml
doc/sphinxman/source/bibliography.rst
external/downstream/adcc/CMakeLists.txt

Switch to adcc main channel and update the fallback version downloaded from github.

Small adcc amendments (Use main channel, update fallback version)

---

doc/sphinxman/source/bibliography.rst
doc/sphinxman/source/scf.rst

The Cholesky is now based on the Gershgorin theorem, which I describe in a note in the PRA article. The routines' accuracy has been benchmarked in the arXiv paper.

Update Cholesky manual references

---

psi4/src/psi4/libmints/orthog.cc

Tries to make sure calculations work even in very ill-behaved cases. Also adds citation that was added to the docs into the code.

Very bad linear dependencies may lead to NaN or infinite condition no

---

psi4/driver/driver_findif.py
psi4/driver/qcdb/vib.py
tests/pytests/test_vibanalysis.py

vib analysis misc.

---

psi4/driver/p4util/text.py
psi4/extras.py
psi4/run_psi4.py

Extracts the `Exception`-based error message and prints it out in an attention-seeking box.
----
Example:
```
Cleaning optimization helper files.
PsiException: Could not converge geometry optimization in 1 iterations.
Traceback (most recent call last):
File "/Users/kruse/qc/psi4.bin/bin/psi4", line 331, in <module>
exec(content)
File "<string>", line 29, in <module>
File "/Users/kruse/qc/psi4.bin/lib/psi4/driver/driver.py", line 1201, in optimize
raise OptimizationConvergenceError("""geometry optimization""", n - 1, wfn)
psi4.driver.p4util.exceptions.OptimizationConvergenceError: Could not converge geometry optimization in 1 iterations.
Printing out the relevant lines from the Psithon --> Python processed input file:
""","LiF2m")
core.IO.set_default_namespace("LiF2m") …
```

enhances the visibility of psi4's error messages

---

psi4/driver/procrouting/proc.py
tests/dft-custom/input.dat
tests/dft-custom/output.ref

Fixed parsing dft_functional=dict() for banner print.

---

.lgtm.yml
codemeta.json

Updating codemeta while I've got author info handy. Anyone -- you're welcome to update affiliations. The rule of thumb is affiliation is the most recent place from whence you contributed to psi. @maxscheurer, please supply your latitude and longitude.

v1.4 codemeta.json

---

cmake/FindPythonLibsNew.cmake
psi4/src/export_wavefunction.cc

Update Ca_subset/Cb_subset docs.

---

README.md
codemeta.json

as it says on the tin. also, update DOI and add papers in README

try to appease lgtm javascript

---

psi4/driver/driver.py
psi4/driver/p4util/util.py
psi4/driver/procrouting/proc.py
psi4/driver/procrouting/proc_table.py
psi4/driver/procrouting/response/scf_response.py
psi4/src/read_options.cc
tests/tdscf-1/input.dat
tests/tdscf-1/output.ref
tests/tdscf-2/input.dat
tests/tdscf-2/output.ref
tests/tdscf-3/input.dat
tests/tdscf-3/output.ref
tests/tdscf-4/input.dat
tests/tdscf-4/output.ref

Allows TDSCF code to be called from any SCF (HF,DFT) computation. 

TDSCF psithon interface

---

external/downstream/cct3/CMakeLists.txt
psi4/src/psi4/libfock/cubature.cc
psi4/src/psi4/libmints/gshell.cc

closes #1943 
reviewers, any reason for the `RHS.original_coef_` inconsistency formerly?

various fixes incl treutler gcc5

---

psi4/src/psi4/libsapt_solver/usapt0.cc
psi4/src/psi4/libsapt_solver/usapt0.h
tests/CMakeLists.txt
tests/sapt9/CMakeLists.txt
tests/sapt9/input.dat
tests/sapt9/output.ref

This PR (finally) fixes issue #1830 with USAPT0 by introducing a bunch of conditionals. I also uncovered and corrected a bug in the Exch-Disp term in USAPT0 while working on this.
- [x ] Ready for review

Usapt spin fix

---

psi4/src/psi4/fnocc/df_ccsd.cc
tests/fnocc4/input.dat

I would like access to the CCSD pair energies from the FNOCC code in Psi4. I made a small modification to the FNOCC code so the pair energies are calculated (using an existing for loop) and I've added the new variable "CCSD PAIR ENERGIES" to store the quantity. 
This is my first PR with Psi4 so I apologize in advance if I've missed any coding guidelines.

Print pairs

---

psi4/src/psi4/libscf_solver/hf.cc

Add missing sanity check.

---

psi4/driver/procrouting/response/scf_response.py
tests/CMakeLists.txt
tests/scf-response2/CMakeLists.txt
tests/scf-response2/input.dat
tests/scf-response2/output.ref

The size check in the scf response code was wrong.

Fix #1998.

---

.github/PULL_REQUEST_TEMPLATE.md
psi4/share/psi4/scripts/test_threading.py
tests/mbis-3/input.dat

omp diagnostic and mbis fix

---

psi4/driver/schema_wrapper.py

Schema: Fixes #1987

---

psi4/src/psi4/dfmp2/mp2.cc
psi4/src/psi4/lib3index/cholesky.cc
psi4/src/psi4/lib3index/dfhelper.cc
psi4/src/psi4/libfock/DiskDFJK.cc
psi4/src/psi4/libfock/DiskJK.cc
psi4/src/psi4/libfock/apps.cc
psi4/src/psi4/libfock/cubature.cc
psi4/src/psi4/libfock/hamiltonian.cc
psi4/src/psi4/libfock/points.cc
psi4/src/psi4/libfock/solver.cc
psi4/src/psi4/libfock/soscf.cc
psi4/src/psi4/libfunctional/LibXCfunctional.cc

Adds lgtm changes and addresses core dev comments

---

psi4/CMakeLists.txt
psi4/driver/p4util/python_helpers.py
tests/pytests/test_option.py

Remove spaces when reading options, fixes #2004

Remove spaces when reading options, fixes #2004

---

CMakeLists.txt
doc/sphinxman/document_tests.pl
psi4/CMakeLists.txt
tests/dft-dens-cut/input.dat
tests/freq-masses/input.dat
tests/mints15/input.dat
tests/mp2-h/input.dat
tests/sapt-exch-disp-inf/input.dat
tests/scf-auto-cholesky/input.dat
tests/scf-cholesky-basis/input.dat
tests/scf-response2/input.dat
tests/v2rdm_casscf/v2rdm4/input.dat

fix fchk testing, v2rdm4 for L2, and test comments

---

CMakeLists.txt
README.md
psi4/driver/p4util/fchk.py
tests/pytests/test_fchk_writer.py

getting intermittant errors < 3.e-9, so relaxing fchk tolerances a bit.

relax fchk a bit

---

psi4/src/export_wavefunction.cc
psi4/src/psi4/libmints/deriv.cc
psi4/src/psi4/libmints/wavefunction.cc
psi4/src/psi4/libmints/wavefunction.h
psi4/src/psi4/libqt/qt.h

Add set_Lagrangian in Wavefunction. Also expose `C_DGEQP3` function.

Add set_Lagrangian in Wavefunction

---

.azure-pipelines/azure-pipelines-linux.yml

tidy up some build/CI locations.

fix linux azure

---

psi4/src/psi4/libmints/extern.cc

This PR threads the calculation of one-electron potential integrals from external point charges. It replaces a call to `OneBodyAOInt.compute()`, which is not threaded and computes the full N-by-N matrix, with a new threaded `for` loop over pairs of shells so that only the lower triangle of the symmetric matrix is calculated. Here's a quick benchmark of times for a SAPT0/jun-cc-pVDZ calculation of a nucleic acid base pair (144 electrons, 425 basis functions, 1879 auxiliary basis functions) with 7393 external point charges on an Intel Xeon E5-2695v4 with 18 cores in each of 2 sockets:
Cores | Old code, no charges | Old code, with charges | New code, no charges | New code, with charges
----- | ------- | ------- | ------- | -------
1 | 1.00 | 1.00 | 1.00 | 1.00
2 | 1.65 | 1.08 | 1.71 | 1.68
4 …

Threaded external charge potential

---

.azure-pipelines/azure-pipelines-linux.yml
psi4/src/psi4/cc/cceom/Params.h
psi4/src/psi4/cc/cceom/WamefSD.cc
psi4/src/psi4/cc/cceom/WbmfeDS.cc
psi4/src/psi4/cc/cceom/WmbejDD.cc
psi4/src/psi4/cc/cceom/WmnefDD.cc
psi4/src/psi4/cc/cceom/WnmjeDS.cc
psi4/src/psi4/cc/cceom/cc2_sigma.cc
psi4/src/psi4/cc/cceom/cc3_HC1.cc
psi4/src/psi4/cc/cceom/cc3_HC1ET1.cc
psi4/src/psi4/cc/cceom/diag.cc
psi4/src/psi4/cc/cceom/diagSS.cc
psi4/src/psi4/cc/cceom/get_eom_params.cc
psi4/src/psi4/cc/cceom/globals.h
psi4/src/psi4/cc/cceom/hbar_norms.cc
psi4/src/psi4/cc/cceom/restart.cc
psi4/src/psi4/cc/cceom/restart_with_root.cc
psi4/src/psi4/cc/cceom/rzero.cc
psi4/src/psi4/cc/cceom/schmidt_add.cc
psi4/src/psi4/cc/cceom/sigmaCC3.cc
psi4/src/psi4/cc/cceom/sigmaCC3_RHF.cc
psi4/src/read_options.cc

EOM CC3 bugfix / code cleanup

---

psi4/src/export_wavefunction.cc
psi4/src/psi4/libscf_solver/hf.h
psi4/src/psi4/occ/coord_grad.cc

Fixes a couple of minor issues for a research project of mine. See todos.

OCC Densities to Wavefunction

---

external/upstream/mdi/CMakeLists.txt
psi4/CMakeLists.txt
psi4/driver/mdi_engine.py

Update MDI support to version 1.2.

Update MDI support to version 1.2

---

.github/workflows/docs.yml

docs syntax GHA

---

psi4/src/psi4/optking/set_params.cc

Cleans up some of the logic and printing in optking's set_params.

Clean up set_params logic and printing

---

psi4/driver/driver.py
psi4/driver/p4util/python_helpers.py
psi4/driver/procrouting/proc.py
psi4/src/read_options.cc
tests/pytests/standard_suite_runner.py
tests/x2c2/input.dat

A few items I ran across. addresses #2197

misc, incl. x2c grad warning

---

psi4/src/psi4/dfmp2/mp2.cc

While looking over the Cholesky decomposition in `dfmp2` so I can steal it for `dct`, I noticed that the relevant code simplifies in 2021.

More doublet, less code

---

.azure-pipelines/azure-pipelines-linux.yml
doc/sphinxman/source/external.rst
doc/sphinxman/source/sapt.rst
doc/sphinxman/source/scf.rst
external/downstream/adcc/CMakeLists.txt

This PR fixes a bug accidentally introduced in #2190 that prevented docs updates.
1.4 please - a new release had better have docs that actually work.

Restore the Docs

---

psi4/CMakeLists.txt

w/o this, tests run fine in place but fail upon install.

install molden testing files

---

README.md

These are the obvious edits I found. Could be more.

Update README.md for v1.4

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-windows.yml
CMakeLists.txt
doc/sphinxman/source/manage_release.rst

release proc update. drop py36.

---

doc/sphinxman/source/manage_release.rst

might fix docs

---

psi4/src/psi4/libscf_solver/hf.cc

Cleans a function I came across when working on some SCF improvements.

Cleanup `form_FDSmSDF`

---

psi4/src/export_wavefunction.cc

Documents `epsilon_a_subset` and `epsilon_b_subset`

Document `epsilon_a_subset` and `epsilon_b_subset`

---

psi4/src/read_options.cc

Improve docstring of DMRG_LOCAL_INIT

---

psi4/src/psi4/lib3index/dfhelper.cc

This addresses at least one of the problems (see details below) associated with #2279.

Make combined omega DF algorithm consistent with uncombined version.

---

external/upstream/qcelemental/CMakeLists.txt
external/upstream/qcengine/CMakeLists.txt
tests/json/schema-1-response/input.py

time to fix the full test suite again. these will help, though more PRs may be needed.

bump qcel/qcng and fix a test

---

psi4/src/export_wavefunction.cc

Appease the sphinx

---

psi4/src/psi4/libmints/vector.cc
psi4/src/psi4/libmints/vector.h

Exactly what it says in the title. @fevangelista, we need this for my Forte fixes.

Mark `Vector::clone` const

---

psi4/driver/procrouting/response/scf_response.py
psi4/src/psi4/libscf_solver/uhf.cc
tests/CMakeLists.txt
tests/scf-response3/CMakeLists.txt
tests/scf-response3/input.dat

Fixes #2265.
This is a first attempt to make the feature work in `cpscf_linear_response`, but the code is a bit ugly and needs to be cleaned up...
~~I'm also not 100% sure why/where correct pre-factors/signs need to be added 🤯 😄~~

UHF Linear Response

---

.azure-pipelines/azure-pipelines-windows.yml
psi4/src/psi4/libdiis/diismanager.cc
psi4/src/psi4/libqt/blas_intfc.cc
psi4/src/psi4/libqt/qt.h

This PR uses `axpy` and `memcpy` throughout `libdiis`, for the sake of fairer comparisons when I'm doing speed profiling.

Vectorize libdiis

---

doc/sphinxman/source/tdscf.rst

Pull in additional documentation for TDSCF options

Pull in extra TDSCF documentation

---

.azure-pipelines/azure-pipelines-windows.yml
psi4/src/psi4/dlpno/mp2.cc
psi4/src/psi4/dlpno/mp2.h

Simple performance improvement for the DLPNO-MP2 algorithm. For DLPNO-MP2 computations on many-core machines, I see speedups around 20%

DLPNO-MP2 Performance Improvement

---

psi4/driver/procrouting/scf_proc/scf_iterator.py
psi4/src/core.cc
psi4/src/psi4/occ/occwave.cc
psi4/src/read_options.cc

Closes #2401 by removing a keyword that does nothing of any use.
One less thing for me to check in an upcoming PR.

Deprecate inert keyword.

---

doc/sphinxman/source/scf.rst
psi4/src/psi4/libscf_solver/hf.cc

GWH is not a guess, but a way to approximate the Hamiltonian for interacting systems.

Improve documentation on the GWH guess

---

psi4/src/psi4/lib3index/fittingmetric.cc

This PR replaces `new`/`delete` in `lib3index/fittingmetric.cc` with `std::vector` per task in #2412

Cleaned fittingmetric new/delete

---

psi4/src/psi4/libmints/wavefunction.cc
psi4/src/psi4/libmints/wavefunction.h
psi4/src/psi4/libscf_solver/rhf.cc
psi4/src/psi4/libscf_solver/rhf.h
psi4/src/psi4/scfgrad/scf_grad.cc

Misc. cleanup related to SCF densities. Marking function returns const, removing redundant class members, and condensing variable declarations and variable definitions

SCF Density Cleanup

---

psi4/src/psi4/fnocc/opdm.cc
tests/cepa1/CMakeLists.txt
tests/cepa2/CMakeLists.txt
tests/cepa3/CMakeLists.txt

Heals tests and marks the tests that _should have caught this_ as `fnocc` tests.

Revision to previous fnocc cleanup

---

psi4/driver/procrouting/proc.py
tests/pytests/test_raises.py

Closes #2310 - an error message is more helpful than a segfault, in my opinion.

Close #2310

---

psi4/src/psi4/libmints/molecule.cc
psi4/src/psi4/libmints/molecule.h

Some code triplication may be eliminated.
-  [X] Yay for negative LOC

Reduce code triplication in Molecule::atom_at_position

---

tests/adcc/formaldehyde-pe-adc1/input.dat
tests/pcmsolver/tdscf/input.dat
tests/pcmsolver/uhf-tdscf/input.dat

patch excited state psivars in addon tests

---

psi4/src/psi4/libmints/eri.cc
psi4/src/psi4/libmints/eri.h
psi4/src/psi4/libmints/integral.cc
psi4/src/psi4/libmints/integral.h

Per issue #2374, this PR adds an interface to Yukawa ERIs from Libint2.

Interfaced Yukawa Libint2 ERI Kernel

---

psi4/driver/procrouting/diis.py

This PR makes changes so that `Psi` can do DIIS on an `ambit.BlockedTensor`, as required by the `forte` plugin. This PR will not work until [this ambit PR](https://github.com/jturney/ambit/pull/53) is merged, but passes locally. The test suite tells us little about this one, sadly.
@loriab, I leave it up to you whether this warrants an update to the version of ambit that Psi takes.
@fevangelista @lcyyork

Fix Forte [Psi Part]

---

psi4/src/psi4/libmints/CMakeLists.txt
psi4/src/psi4/libmints/multipoles.cc
tests/pytests/test_mcmurchie_davidson.py

Get Psi4 running correctly with Intel (2021.4) again. I'm sorry to uglify the nice structured bindings (thanks for the name, @robertodr). Edit with any better suggestions. I've got full tests running locally.

c++14 multipole for Intel

---

.github/workflows/ecosystem.yml
conda/win/meta.yaml
psi4/__init__.py
psi4/driver/driver_util.py
psi4/driver/p4util/procutil.py
psi4/driver/p4util/python_helpers.py
psi4/driver/qcdb/libmintsbasisset.py
psi4/driver/schema_wrapper.py
tests/pytests/standard_suite_runner.py
tests/pytests/test_misc.py

This is No. 3 of the DDD series, #1351.

ddd formatting

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-windows.yml
.github/workflows/ecosystem.yml
conda/win/meta.yaml
psi4/__init__.py
tests/fsapt-ext-abc-au/test_input.py
tests/fsapt-ext-abc/test_input.py
tests/fsapt-ext-abc2/test_input.py
tests/fsapt-terms/test_input.py
tests/pytests/addons.py

believe it or not, every "fix windows conda package" commit in the past week has actually fixed the problem at hand. for this round, let's try installing databases on windows and anchoring scripts from module.
EDIT:

more installed windows path adjustments

---

psi4/driver/procrouting/proc.py
psi4/src/export_wavefunction.cc
psi4/src/psi4/cc/ccdensity/ccdensity.cc
psi4/src/psi4/cc/ccdensity/wfn_saver.cc
psi4/src/psi4/dmrg/dmrgscf.cc
psi4/src/psi4/libmints/wavefunction.h

DMRG density to wavefunction. Closes #2558.

DMRG density to wavefunction

---

psi4/src/psi4/libqt/lapack_intfc.cc
psi4/src/psi4/libqt/qt.h

Because @huangm29 needs the SVD function plugin-exposed for Forte purposes.

PSI_API SVD

---

psi4/driver/p4util/procutil.py
psi4/driver/schema_wrapper.py
psi4/src/psi4/liboptions/liboptions.cc
psi4/src/psi4/liboptions/liboptions.h

Some changes to make Forte and Psi compatible with each other again. Heavily coordinated with Lori.
Also gets rid of an unused function that was raising a compile-time warning.

Make DDD work with Forte.

---

psi4/driver/procrouting/response/scf_response.py
psi4/src/psi4/libscf_solver/rhf.cc
psi4/src/psi4/libscf_solver/uhf.cc
psi4/src/psi4/libscf_solver/uhf.h

Preparing for future code by improving docstrings and removing unused member variables.

Misc. cleanup

---

psi4/src/psi4/adc/adc.cc
psi4/src/psi4/adc/adc.h
psi4/src/psi4/adc/compute_energy.cc
psi4/src/psi4/cc/ccdensity/get_rho_params.cc
psi4/src/psi4/cc/cclambda/get_params.cc
psi4/src/psi4/dmrg/dmrgscf.cc
psi4/src/psi4/liboptions/liboptions.cc
psi4/src/psi4/liboptions/liboptions.h

Exactly what it says on the tin. Now with fewer memory leaks.

Replace `get_int_array` with `get_int_vector`

---

psi4/src/psi4/lib3index/dfhelper.cc
psi4/src/psi4/lib3index/dfhelper.h

This is the first PR of what will probably be a series to improve the readability of `dfhelper.cc`. Because this code is overwhelming, I'm breaking the PR into pieces. Rapid approval cycle appreciated, since there will likely be a lot of these.

DFHelper Readability 1

---

psi4/src/psi4/libsapt_solver/sapt.cc
psi4/src/psi4/libsapt_solver/sapt.h
psi4/src/psi4/libsapt_solver/sapt0.cc
psi4/src/psi4/libsapt_solver/sapt2.cc

Consolidates some code used to get the metric in SAPT.
I'll resume cleaning up this code after `DFHelper` is documented.

SAPT Metric Cleanup

---

psi4/src/psi4/libmints/twobody.h

Indexing conventions had better be explicit.

Document indexing conventions

---

psi4/src/psi4/libfock/PKmanagers.cc

Remove more uses of `ERISieve`, in preparation for its removal.

`PKMgrYoshimine` Sieve Removal

---

conda/win/meta.yaml
external/upstream/qcengine/CMakeLists.txt

some misc. changes. I also have suspicions about fnocc7 but not confirmed.

qcng v0.24.1 update

---

psi4/src/psi4/detci/get_mo_info.cc
psi4/src/psi4/detci/globaldefs.h
psi4/src/psi4/detci/structs.h

Remove a now-meaningless validation step in `detci`.

Remove legacy check

---

psi4/src/psi4/libmints/vector.h

Restore a `const` lost during the Vector refactor.
Quick merge appreciated - needed to fix Forte.

Remark clone const

---

psi4/src/psi4/cc/ccenergy/Wmbej.cc
psi4/src/psi4/cc/ccenergy/t1_ijab.cc
psi4/src/psi4/cc/ccenergy/t2.cc
psi4/src/psi4/cc/ccenergy/taut.cc

Pull more attributes from the wavefunction rather than the `MOInfo` object. The next PR will be less trivial.

Chip away at MOInfo (3/???)

---

psi4/src/export_mints.cc
psi4/src/psi4/libmints/matrix.cc
psi4/src/psi4/libmints/matrix.h

Mark `Matrix::get_block` const

---

.azure-pipelines/azure-pipelines-linux.yml
psi4/driver/driver.py

update for geometric 1.0

---

.azure-pipelines/azure-pipelines-windows.yml
CMakeLists.txt
external/upstream/qcelemental/CMakeLists.txt
psi4/driver/driver_nbody.py
psi4/driver/inputparser.py
psi4/src/psi4/libfock/cubature.cc

misc updates, incl. py311

---

psi4/src/psi4/libfock/v.cc

Remove new from v.cc

---

psi4/src/psi4/libpsi4util/PsiOutStream.cc

Closes #2799 : prints out the name of the file that failed to open

Show file name in error message

---

CMakeLists.txt
doc/sphinxman/source/build_planning.rst

closes #2789 thanks for the reminder!

qcng deps in docs

---

.github/workflows/docs-pr.yml
.github/workflows/docs.yml
devtools/conda-envs/docs-cf.yaml

Poke master docs build that broke ~12 days ago w/o a clear cause.

fix docs build on master

---

psi4/driver/frac.py
psi4/driver/p4util/python_helpers.py
psi4/driver/procrouting/proc.py
psi4/src/core.cc
psi4/src/export_plugins.cc
psi4/src/export_wavefunction.cc
psi4/src/psi4/libmints/deriv.cc
psi4/src/psi4/libmints/wavefunction.cc
psi4/src/psi4/libmints/wavefunction.h
psi4/src/psi4/libpsi4util/process.cc
psi4/src/psi4/libpsi4util/process.h
psi4/src/psi4/libscf_solver/hf.cc

Quick review appreciated for sake of `deriv.cc`.

Remove deprecated

---

codemeta.json
psi4/header.py
tests/cookbook/manual-fd-hess-energy/input.dat
tests/cookbook/manual-fd-hess-grad/input.dat

fix cookbooks after set_frequencies removed

---

psi4/src/psi4/cc/ccdensity/add_core_ROHF.cc

Fix segfault

---

tests/matrix1/input.dat

When the comment says perform a phase change on _all_ the eigenvectors, that includes eigenvector 0.

Close #2828

---

.github/workflows/docs.yml
psi4/driver/procrouting/solvent/ddx.py
psi4/src/psi4/libmints/mintshelper.cc
psi4/src/psi4/libmints/numinthelper.h
psi4/src/psi4/libmints/potentialint.cc
psi4/src/psi4/libmints/potentialint.h

ints and master docs fixes

---

psi4/src/psi4/libtrans/integraltransform_sort_so_tei.cc

Make example 1 of #2231 at least _run_. I'm not quite sure it's correct just yet, though.

Fix error in libtrans

---

psi4/src/psi4/libfock/dft_integrators.h
psi4/src/psi4/libfock/points.h
psi4/src/psi4/libfock/v.cc
psi4/src/psi4/libfock/v.h
psi4/src/psi4/libfunctional/superfunctional.h

Lots of DFT Commenting

---

psi4/driver/procrouting/proc.py
psi4/driver/procrouting/proc_util.py

Rename 'build_disp_functor' to 'build_functional_and_disp'

---

doc/sphinxman/source/scf.rst
psi4/src/read_options.cc

Make SCF guess docs less confusing for the casual reader, based on feedback in the Evangelista group.

Clarify SCF Guess Documentation

---

psi4/src/psi4/libmints/vector.cc
psi4/src/psi4/libmints/vector.h
psi4/src/psi4/libqt/blas_intfc.cc
psi4/src/psi4/libqt/blas_intfc_mangle.h
psi4/src/psi4/libqt/qt.h

Adds `DAXPBY` to `libqt` so I can add `axpby` to `Vector`. Needed for #2885.

Add DAXPBY to Psi and to the Vector class.

---

psi4/src/export_functional.cc
tests/pytests/test_dft_blocking.py

fix test_dft_blocking 

---

doc/sphinxman/source/manage_git.rst

update the review guidance

---

psi4/src/psi4/libfock/v.cc

Fix UKS gradient parallelization

---

THIRD-PARTY-LICENSES

c-f required something like this for PCMSolver, so I went ahead with it for Psi4 also. None present a problem with overall LGPL-3.0-only as far as I can see. Some of the folks we're still in contact with and could ask to dual-license, if there was a problem.

add third-party-licenses

---

psi4/src/psi4/fisapt/fisapt.cc

As a result of implementing new ISAPT variants, a printout of dipole moments before/after link reassignment was added. This printout does not make any sense for the original `FISAPT_LINK_ASSIGNMENT == C` variant (there was no link reassignment so what do before and after even mean?).
This PR removes this spurious printout for old link reassignment schemes `FISAPT_LINK_ASSIGNMENT == C`  and `FISAPT_LINK_ASSIGNMENT == AB`.

Removed ambiguous (and incorrect) dipole printing in ISAPT/C

---

.azure-pipelines/azure-pipelines-windows.yml
devtools/conda-envs/Windows-buildrun-maxeco.yaml

faster windows CI

---

external/upstream/ddx/CMakeLists.txt
psi4/driver/procrouting/solvent/ddx.py
tests/pytests/test_ddx.py

Fix bug in lpb fock routine and update tests

---

.azure-pipelines/azure-pipelines-windows.yml

Update LLVM version to suit Azure Windows

azure windows clang fix, perhaps

---

cmake/xhost.cmake

Just comments a cryptic line in xhost.cmake

Add comment in xhost.cmake

---

doc/sphinxman/source/manage_release.rst
external/upstream/pcmsolver/CMakeLists.txt
psi4/driver/p4util/python_helpers.py
psi4/share/psi4/plugin/wavefunction/wavefunction.cc.template
tests/pytests/test_cppe.py
tests/scf-ecp/CMakeLists.txt
tests/scf-ecp/test_input.py

fix plugin for doccpi_ and misc

---

psi4/driver/qcdb/vib.py

Sherrill group revisions to thermochemistry analysis printing for additional clarity. The new output for tu4 is below. 
``` 
==> Thermochemistry Energy Analysis <==
Raw electronic energy, E_e
Total E_e, Electronic energy at well bottom                                           -76.02703273 [Eh]
Zero-point vibrational energy, ZPVE = Sum_i omega_i / 2,  E_0 = E_e + ZPVE
Vibrational ZPVE                        14.440 [kcal/mol]       60.419 [kJ/mol]       0.02301219 [Eh]        5050.592 [cm^-1]
Correction ZPVE to E_e                    14.440 [kcal/mol]       60.419 [kJ/mol]       0.02301219 [Eh]        5050.592 [cm^-1]
Total E_0, Enthalpy at 0 [K]                                                          -76.00402054 [Eh]
*** Absolute enthalpy, not an enthalpy of formation ***
Thermal …
```

thermo chem analysis printing

---

psi4/driver/p4util/python_helpers.py
psi4/extras.py

fix pcmsolver on windows

---

psi4/src/psi4/libfock/cubature.cc

#3004 seems to have been a false alarm (closes #3004), but since the code made a couple people suspicious, may as well add some notes.

Chebyshev quadrature notes

---

tests/scf-guess/output.ref

Looks like I didn't push the updated reference output for the MODHUCKEL guess...

Update scf-guess reference output for MODHUCKEL

---

psi4/driver/procrouting/empirical_dispersion.py

NOTE: this commit was applied to v1.8.1 even though not merge to master until after that release.

pytest not really reqd

---

.azure-pipelines/azure-pipelines-windows.yml
conda/win/meta.yaml

- ~Tests added for any new features~
- ~[All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)~

update azure win

---

.azure-pipelines/azure-pipelines-windows.yml
.github/workflows/ecosystem.yml
azure-pipelines.yml

merged changes

---

.github/workflows/ecosystem.yml
psi4/src/psi4/dummy_einsums/CMakeLists.txt

The recent Einsums PR seems to have broken source builds. This fixes it.

Fixes building from source

---

doc/sphinxman/source/manage_release.rst
doc/sphinxman/source/nitpick-exceptions

postrelease documentation

---

codedeps.yaml
external/upstream/libxc/CMakeLists.txt
psi4/CMakeLists.txt
tests/pytests/test_erisieve.py
tests/pytests/test_np_views.py

fix libxc min

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-windows.yml
.github/workflows/docs.yml
codedeps.yaml
devtools/conda-envs/linux-64-buildrun.yaml
devtools/conda-envs/osx-64-buildrun.yaml
devtools/conda-envs/osx-arm64-buildrun.yaml
devtools/conda-envs/win-64-buildrun.yaml
psi4/__init__.py
psi4/driver/inputparser.py
psi4/driver/p4util/numpy_helper.py
psi4/driver/p4util/procutil.py
psi4/driver/p4util/python_helpers.py
psi4/driver/p4util/util.py
psi4/driver/task_planner.py

resolve more paths

---

conda/win/meta.yaml
psi4/driver/p4util/util.py
psi4/driver/qcdb/libmintsgshell.py
psi4/src/psi4/libmints/gshell.h

AM symbol list

---

psi4/src/psi4/lib3index/dfhelper.cc
psi4/src/psi4/lib3index/dfhelper.h
psi4/src/read_options.cc
tests/pytests/test_jkmemory.py
tests/python/3-index-transforms/input.py

Collect SAPT changes in the progress of SAPT consolidation.

Avoid Disk algorithm of MemDF

---

psi4/src/psi4/fisapt/fisapt.cc

remove DCBS from FISAPT

---

psi4/src/psi4/libpsio/error.cc

As the title says. PSIO errors now give suggestions on how to fix the observed PSIO issue.

Adjust printout for PSIO errors

---

.azure-pipelines/azure-pipelines-windows.yml
CMakeLists.txt
cmake/custom_cxxstandard.cmake
doc/sphinxman/source/build_planning.rst
doc/sphinxman/source/introduction.rst
external/upstream/einsums/CMakeLists.txt

require c++20

---

.azure-pipelines/azure-pipelines-linux.yml
.github/workflows/ecosystem.yml
CMakeLists.txt
codedeps.yaml
external/upstream/pybind11/CMakeLists.txt
external/upstream/qcelemental/CMakeLists.txt
external/upstream/qcengine/CMakeLists.txt

Loriab patch 3

---

psi4/src/psi4/libmints/eribase.cc

Fixes the buffer overflow error described in #3214 .

Fix buffer overflow error

---

.azure-pipelines/azure-pipelines-windows.yml
.github/workflows/docs-pr.yml
.github/workflows/docs.yml
.github/workflows/ecosystem.yml

fix ci mamba
