CMakeLists.txt
I cannot get PSI to compile without this. `PsiUtil` gets add to the link list but in the wrong place (after the boost libs), causing it to have undefined references.
=> PsiUtil seems to be missing from the PSILIBS list

lib/python/inputparser.py
The following input file breaks `inputparser.py`
```
$ cat input.dat
molecule h2 {
H
H 1 0.9
}
set basis 6-31G**
energy('scf')
```
The exception is
```
$ psi4 input.dat
Input error: Unmatched (
```
The error is specific to the fact that the comment appears on the first line of the file.
=> Fix inputparser.py bug

tests/psitest.pl
This uses whatever perl it finds in the `$PATH`. If you use a non-default perl, hardcoding the perl path is a pain.
=> Do not hardcode path for Perl

src/bin/psi4/python.cc, src/lib/liboptions/liboptions.cc, src/lib/liboptions/liboptions.h
When reading the options from the input file, all strings are set as
StringDataType even if they are IStringDataType.
I only did it for the 'local' options and not the global ones.
=> Differentiate between StringDataType and IStringDataType

lib/python/inputparser.py
The following type of `set` block breaks inputparser in the `quotify` function:
```
set {
myplugin 'a/c'
myplugin 'a\b'
}
```
with errors like
```
Traceback (most recent call last):
File "<string>", line 14, in <module>
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
and 
```
File "<string>", line 15
psi4.set_global_option("MYPLUGIN", "'a"\"b'")
^
SyntaxError: unexpected character after line continuation character
```
=> Inputparser fix for slashes inside option string

src/bin/psi4/psi_start.cc, src/lib/libpsio/filemanager.cc, src/lib/libpsio/psio.hpp
On some systems, the default temp location should not be `/tmp`
but it is set by either `$TMPDIR`, `$TEMP` or `$TMP` (commenly done on HPC
systems, where the temp location may be somthing special, a ssd for example).
This patch first checks those 3 environment variables
and uses its value when set. It falls back to `/tmp` when
nothing is set.
`std::getenv` needs C++11 to be thread safe.
=> Use $TMPDIR for default of PSI_SCRATCH when set

src/lib/libmints/writer.cc
In the moldenwriter a `!=` operation is directly used on two doubles. Never do this, doubles are no ints.
=> Never directly compare doubles

src/bin/psi4/python.cc
Modifies the exception translator to communicate the file() and line() information to the python exception wrapper class. When debugging a plugin (my use case), this makes it much easier to figure out the source of an exception that's thrown from C++ as `throw PSIEXCEPTION('message')`.
=> Exception Formatting

src/bin/psi4/gitversion.py
With the current code, when `make update_version` is run with py3, the fields variable is something like `["b'f9256f7\\n'"]`, with the extra escaped newline.
=> Modify gitversion.py to work in python3

lib/python/inputparser.py, lib/python/qcdb/libmintsmolecule.py
Fix for #169. I didn't run the whole test suite, but I did run `cc1`, `opt3` with python2.6.
=> Fix python 2.6

conda-recipe/psi4/post-link.sh
When PSI4 updates in miniconda, the testing dialogue,
```
Nuclear Repulsion Energy..........................................PASSED
SAPT0 Eelst.......................................................PASSED
SAPT0 Eexch.......................................................PASSED
SAPT0 Eind........................................................PASSED
SAPT0 Edisp.......................................................PASSED
SAPT0 Etotal......................................................PASSED
```
prints as a single line which is wrapped by the terminal:
```
Nuclear Repulsion Energy..........................................PASSED SAPT0 Eelst....
...................................................PASSED SAPT0 Eexch...................
....................................PASSED SAPT0 …
```
=> Fixed conda linktest printing

doc/sphinxman/CMakeLists.txt
These custom commands where added without the custom target `sphinxpdf` existing.
=> Only define custom commands when the target exists (sphinxpdf)

src/bin/thermo/thermo.cc
I updated thermo.cc so that only 1 warning message is printed when the frequencies are checked for low and imaginary values. I also added a newline after the low frequency mode warning.
Previous output (3 imaginary modes, total of 12 low frequency modes):
```
WARNING: At least one vibrational frequency is imaginary!
WARNING: At least one vibrational frequency is imaginary!
WARNING: At least one vibrational frequency is imaginary!
```
and
```
Warning: used thermodynamic relations are not appropriate for low frequency modes.    Warning: used thermodynamic relations are not appropriate for low frequency modes.    Warning: used thermodynamic relations are not appropriate for low frequency modes.    Warning: used thermodynamic relations are not appropriate for low frequency modes.    Warning: …
```
=> Thermo low/imaginary frequency warnings

doc/sphinxman/document_options_c.pl
Documentation fails to build with perl 5.22 and reports the following error:
Can't use 'defined(%hash)' (Maybe you should just omit the defined()?)
at /build/psi4-0.3/doc/sphinxman/document_options_c.pl line 150.
doc/sphinxman/CMakeFiles/sphinxman.dir/build.make:106: recipe for
target 'doc/sphinxman/source/autodoc_abbr_options_c.rst' failed
=> Replace deprecated defined(%hash) with exists()

.gitmodules, CMakeLists.txt, cmake/ConfigPCMSolver.cmake, cmake/FindPCMSolver.cmake, lib/python/inputparser.py, lib/python/pcm_placeholder.py.in, setup, src/bin/psi4/CMakeLists.txt, src/lib/libpsipcm/CMakeLists.txt
We use the strategy devised by @loriab for external add ons. This commit provides the necessary Find* and Config* CMake script files. Other modifications take into account the new strategy.
=> PCMSolver is no longer a git submodule.

src/bin/optking/frag_disp.cc
Fix for issue #231 .  When I made the linear bend code more robust recently, I tightened up enforcement of nonsense torsions.  In #231, the crash appears to be bad luck mostly, as a dozen iterations into the back-transformation on geometry step 3, we just happen to hit a bogus bend.  Turns out this only happened after the iterative procedure started diverging anyway, so I am adding just a test that gives up faster.
=> bail on backtransformation if dx gets ridiculous

.travis.yml
Travis CI currently takes 2-6 (average 3) hours to complete depending on the current travis load, which is a bit on the long side. To help with this I am proposing that we reduce the number of build types from 15 to the following:
- Latest clang/gcc with both debug and release flags (4 cases)
- Oldest supported clang/gcc with both debug and release flags (4 cases)
It should be noted that travis CI typically runs the first 3-6 test cases immediately upon submission and then runs the rest in a general queue. The real time killer is when the 15th CI case does not start to run for 2-5 hours after initial submission. With the proposed changes we will hopefully be running through travis consistently in about an hour. 
This will deteriorate our CI coverage a bit; however, I think this keeps with …
=> Reduced the number of travis CI cases

.scripts/travis_run.py, .travis.yml, lib/python/p4util/util.py
* runs `ctest -L quick -j2` through python rather than bash
* finds the test output files that are in directories a layer deeper than expected, e.g. the pcmsolver that's failing on the wavefunction_pass PR
* writes `compare_values()` output to output.dat (why haven't we done this before?)
* someone who understands how travis deals with run.log should examine this bit: `tciout = open('run.log', 'a')`
=> ctest for travis in python. compare_values to outfile.

src/lib/libscf_solver/hf.cc, src/lib/libscf_solver/hf.h, src/lib/libscf_solver/ks.cc, src/lib/libscf_solver/ks.h, src/lib/libscf_solver/rhf.cc, src/lib/libscf_solver/rohf.cc, src/lib/libscf_solver/rohf.h, src/lib/libscf_solver/uhf.cc
Added virtual functions to UKS and RKS to override the soscf_update of UHF and RKS. The result is that calling soscf_update on these functions will now fail with an error message instead of a set fault.
Also cleaned up the SOSCF logic a bit.
This PR is ready to be merged if everything passes. Fixes #256.
=> SOSCF: Now correctly throws an error for RKS/UKS SOSOCF updates

doc/sphinxman/source/scf.rst, src/bin/psi4/read_options.cc, src/lib/libscf_solver/hf.cc
DF_SCF_GUESS was not completely suppressed for PK integrals. The code is now cleaned up and the documentation updated.
=> DF_SCF_GUESS with PK integrals

src/lib/libmints/petitelist.h
Reduces the minimum overlap between atoms to fix issue #195. Reductions to this tolerance in the future would likely have to be for ghost atoms only.
A downside to this is linear depends will pop up much more often when two atoms are this close together, especially in highly symmetric molecules.
=> Reduced atom overlap tolerence to 0.1 to fix #195

src/lib/libfock/GTFockJK.cc, src/lib/libscf_solver/hf.cc
PSI4 compiles when HAVE_JK_FACTORY is enabled and GTFock works with symmetry.
=> PSI4 now compiles correctly with HAVE_JK_FACTORY flag enabled.  

share/python/driver.py, share/python/proc.py, src/bin/ccenergy/get_params.cc, src/bin/cctransort/cctransort.cc, src/bin/cctriples/get_moinfo.cc, src/bin/psi4/read_options.cc, src/bin/transqt2/get_params.cc, tests/cc16/input.dat
Allows BCCD with ROHF starting orbitals.
=> BCCD with ROHF starting orbitals now works, fixes #294

share/plugin/aointegrals.cc.template, share/plugin/mointegrals.cc.template, share/plugin/sointegrals.cc.template
fixed up some plugin templates that escaped the wavefunction pass
=> more wavefunction-pass for plugins

src/bin/detci/ints.cc, src/lib/libfock/soscf.cc
With ICC 2015 and `XHOST` turned off the changed loop will fail. You can either turn `XHOST` on, set `#prama novector` for the inner loops, or unroll the loop as shown to fix the problem. I would consider this a compiler bug, but I was curious if anyone had other opinions. A bit scary that we are running into this kind of thing.
A few details:
- `TPDMp` and `actMOp` are both `double**`'s with shapes of `nact*nact` by `nact*nact`.
- All indices are within bounds.
- Very excited for everyone to review the most neglected piece of code in the MCSCF orbital optimization.
=> CIWave: Fixes strange ICC 2015 compiler error with certain vectorization options

setup
Fixes the os.environ KeyError in setup with compilers are not provided to the setup script and CC/CXX/FC environment variables are not set.
=> Fixes os.environ error in setup

src/lib/libmints/integralparameters.cc, src/lib/libmints/orbitalspace.cc
There were two bugs in the code:
- The RIBS orbital space was not orthonormal.
- When manually providing geminal basis functions to the CorrelationFactor object the number of elements were not properly stored and the code assumes zero functions.
These bugs should only have appeared to people coding up explicitly correlated methods. It should not have effected the average user.
=> Resolves bug in OrbitalSpace RIBS and F12 CorrelationFactors.

src/bin/optking/frag_apply_frozen_constraints.cc, src/bin/optking/molecule.cc, src/bin/optking/opt_params.h, src/bin/optking/set_params.cc, src/bin/psi4/read_options.cc
Improved fixed-coordinate optimizations.  Test opt7 still works, as does a full dihedral scan of HOOH in C2 symmetry.  Resolves issue #10 (there are no longer any nonsymmetric displacements).  A new keyword `FIXED_COORD_FORCE_CONSTANT` allows tweaking for softer or firmer constraints, if necessary.
The code does interpret fixed dihedrals <-180 or >180.  However, the code does NOT currently deduce the most direct way through the dihedral discontinuity at 180.  So it's a bad idea to give an input geometry with a dihedral of, say 178, and assign a target value of -178.
Also, I've turned off dynamic trust radius sizing for optimizations with fixed coordinate targets by default.
=> Improved fixed-coordinate optimizations, PES scans.

src/lib/libmints/molecule.cc
This PR adds "ATOM" to the list of point groups that does not need to be replaced in the point group name.
=> Added "ATOM" to list of point groups that does not need "n" replaced. This allows the thermo module to handle atoms.

src/lib/libmints/oeprop.cc
Minor change to the blank lines and units printed by Lowdin charge calculations. The purpose of this update is to make it easier to parse PSI4 output for different types of charges.
Previous:
```
outfile->Printf( "  Mulliken Charges: (a.u.)\n");
outfile->Printf( "\n\n  Lowdin Charges [a.u.]:\n\n");
```
Updated:
```
outfile->Printf( "  Mulliken Charges: (a.u.)\n");
outfile->Printf( "  Lowdin Charges: (a.u.)\n");
```
=> Making Mulliken and Lowdin charge output more consistent

cmake/ConfigPCMSolver.cmake, tests/pcmsolver/pcm-dft/input.dat, tests/pcmsolver/pcm-dft/output.ref, tests/pcmsolver/pcm-scf/input.dat, tests/pcmsolver/pcm-scf/output.ref
=> Update PCMSolver to v1.1.1

share/python/driver.py
This PR addresses psi4/#249 in that it makes the docsctrings consistent with the procedures dict.
=> Update docstrings in driver.py, fix psi4/#249

doc/sphinxman/source/conda.rst, doc/sphinxman/source/external.rst, doc/sphinxman/source/tutorial.rst
Update of the scratch directory documentation.
=> Scratch docs

doc/sphinxman/source/pcmsolver.rst, doc/sphinxman/source/psithoninput.rst, doc/sphinxman/source/psithonmol.rst, share/plugin/Makefile.conda.template, share/plugin/Makefile.template, share/plugin/__init__.py.template, share/plugin/ambit.cc.template, share/plugin/aointegrals.cc.template, share/plugin/doc.rst.template, share/plugin/mointegrals.cc.template, share/plugin/plugin.cc.template, share/plugin/pymodule.py.template, share/plugin/scf.cc.template, share/plugin/scf.pymodule.py.template, share/plugin/scf.scf.cc.template, share/plugin/scf.scf.h.template, share/plugin/sointegrals.cc.template, share/plugin/wavefunction.cc.template, share/python/driver.py, share/python/qcdb/molecule.py, share/python/wrappers.py, src/bin/psi4/export_mints.cc, src/lib/libsapt_solver/ind20.cc, src/lib/libscf_solver/hf.cc
docs and licenses and castup, oh my
=> docs and licenses and castup, oh my

doc/sphinxman/source/plugins.rst
Documentation for plugin creation using binary distribution (on linux only).
=> Document Makefile for plugin from binary

src/lib/libmints/sointegral_twobody.h
Removes `sointegral_twobody.h`'s dependence on `mpi_wrapper.h` and `local.h`.  Also removes some MADNESS stuff that was missed originally.
=> Fixed issue raised by Lori

include/psi4-config.in
psi4-config had PYTHON_INTERPRETER rather than PYTHON_EXECUTABLE.  I need this for my v2rdm plugin to compile with @loriab 's fancy configure script.
=> changes PYTHON_INTERPRETER to PYTHON_EXECUTABLE

src/bin/detci/ciwave.cc, src/bin/detci/diag_h.cc, src/bin/detci/h0block.cc, src/bin/detci/sem.cc
Fixes a memory leak in the CI code where a matrix that scaled like `maxiter^3` was not being freed. This only effected computations where the maximum number of iterations was set to a very large value (100+, default 12).
=> CIWave: Fixes memory leak

.travis.yml
Turns off clang in Travis CI until the hosting issue is resolved. Useful links:
- [LLVM mailing list](http://lists.llvm.org/pipermail/llvm-foundation/2016-May/000020.html)
- [Travis Ticket](https://github.com/travis-ci/travis-ci/issues/6120)
=> Stops clang CI builds until LLVM hosts their compilers again

share/python/procedures/proc.py
SAPT2+(3)dMP2 was doing SAPT0dMP2 because of a typo in proc.py.
=> Fix SAPT2+(3)dMP2 in proc.py

cmake/ConfigAmbit.cmake, cmake/ConfigChemps2.cmake, plugins/skeletonambit/CMakeLists.txt, plugins/skeletonaointegrals/CMakeLists.txt, plugins/skeletonmointegrals/CMakeLists.txt, plugins/skeletonscf/CMakeLists.txt, plugins/skeletonsointegrals/CMakeLists.txt, plugins/skeletonwavefunction/CMakeLists.txt, share/plugin/ambit.cc.template, share/plugin/ambit.input.dat.template, src/bin/psi4/create_new_plugin.cc, src/bin/psi4/gitversion.py
=> externals and plugins prep for 1.0rc2

cmake/ConfigPCMSolver.cmake
The `GIT_TAG` argument to `ExternalProject_Add` was changed to `v1.1.4` to reflect a version bump in [PCMSolver](https://github.com/PCMSolver/pcmsolver/releases/tag/v1.1.4)
I had introduced a bug with v1.1.3 The polarization charges were computed with a degraded accuracy. This was caught neither by the library own unit tests nor by Psi4 tests, as it becomes apparent only when trying to calculate higher-order response properties (available in DALTON, but I failed to run the PCM tests there...)
I apologize for any inconvenience!
=> Update PCMSolver to its v1.1.4

share/python/driver.py, tests/fd-freq-energy-large/input.dat
=> partial freq findif fix

.lgtm, psi4/share/psi4/python/driver_cbs.py
Configures LGTM properly. In the last cbs() pass, I refined the encoding of "an SCF is produced in the course of a CCSD" to "a HF is produced in the course of a CCSD". Unfortunately, I only refined it in a first pass that hit mp2, ccsd, ccsd(t), etc., not the lesser used fno-ccsd(t), mp3, cisd, etc. which can also be extrapolated. The alarming result is that if you used the latter, you'd get that the extrapolation of HF between 0 and –300 is –600.
=> LGTM & CBS wrapper fix

doc/sphinxman/source/molden.rst, psi4/share/psi4/python/driver.py, psi4/share/psi4/python/procedures/proc.py, psi4/src/export_mints.cc, psi4/src/psi4/dcft/dcft_density_UHF.cc, psi4/src/psi4/dfocc/occ_iterations.cc, psi4/src/psi4/dmrg/dmrgscf.cc, psi4/src/psi4/libmints/writer.cc, psi4/src/psi4/libmints/writer.h, psi4/src/read_options.cc
The MOLDEN file written by psi4, which can be used by our external programs, is HUGE when a reasonably-sized molecule is calculated using a large basis set. Since for many post-processing purposes the virtual orbitals are unnecessary, it would be interesting to have an option to drop writing most virtual MOs to the file, dramatically cutting down its size. This PR implements the molden_novirtual option to SCF. If true (it is false by default to preserve the original behavior), only the occupied orbitals are written to the molden file in a closed-shell molecule. In an open-shell system, 2*max(nocca,noccb) orbitals are written.
=> rebased: added option to discard unoccupied MOs in MOLDEN file

psi4/config.py.in
Patch to the plugin code to work with ```PYMOD_INSTALL_LIBDIR``` paths. Tested with and without ```PYMOD_INSTALL_LIBDIR``` set to ```/python2.7/site-packages```.
=> Patch to allow the plugin code to work with PYMOD paths

doc/sphinxman/source/psithoninput.rst
Fix one instance of the energy() function reference not being clickable by changing "~driver.energy()" to be "~psi4.energy()"
Fix energy() function reference to be clickable
=> Unclickable Function Reference

doc/sphinxman/source/sapt.rst
Jerome's name is now correctly spaced in the authors section.
=> Deleting extra space

doc/sphinxman/source/numpy.rst
Resolved typo in code which would have given syntax error if copied verbatim.
Corrected print statement in NumPy Views section that was missing a `)'.
=> Resolved potential syntax error

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, doc/sphinxman/document_cfour.py, doc/sphinxman/document_databases.py, doc/sphinxman/document_driver.py, doc/sphinxman/document_efpfrag.py, doc/sphinxman/document_plugins.py, doc/sphinxman/source/psi4doc/themes/psi4doc/theme.conf, psi4/run_psi4.py, psi4/src/core.cc, samples/numpy-array-interface/input.dat, samples/numpy-array-interface/test.in
=> python 3.5 travis

psi4/src/psi4/dfmp2/mp2.cc
Previously, Psi4 was segfaulting when there were no occupied or virtual orbitals in a DF-MP2 computation. Now, it handles this a bit more gracefully by throwing.
=> Makes Psi4 fail gracefully when there are no active virtuals in DF-MP2

psi4/driver/qcdb/molecule.py
Added `save_xyz()` function to `qcdb.Molecule` with `save_natom` as additional argument.
Will supersede `LibmintsMolecule.save_xyz()`.  
* **User Interest**
=> Added save_xyz() to qcdb.Molecule

psi4/driver/procedures/proc.py, psi4/driver/procedures/proc_util.py, psi4/src/export_mints.cc, tests/x2c1/input.dat
Fixes a few issues with Psi4 brought up on the forum.
=> Minor Psi4 fixes for v1.1

psi4/src/psi4/optking/molecule_read_coords.cc
Fixes bug reported [here](http://forum.psicode.org/t/fixed-dihedral-optimization-error/323).  I was sloppy and apparently no one had tried a 0 degree fixed angle before.
Passed HOOH at 0 degrees.  Still need to run other psi standard tests.
=> bug fix of prevention of zero target optimization values by the evil atof()

psi4/driver/procedures/mcscf/mcscf_solver.py, psi4/driver/procedures/proc.py, psi4/src/psi4/detci/ciwave.cc, psi4/src/psi4/detci/ciwave.h, psi4/src/psi4/detci/ints.cc, psi4/src/psi4/libfock/GTFockJK.cc, psi4/src/psi4/libfock/jk.h, psi4/src/psi4/libfock/soscf.cc, psi4/src/psi4/libfock/soscf.h, psi4/src/read_options.cc, tests/CMakeLists.txt, tests/ao-casscf-sp/CMakeLists.txt, tests/ao-casscf-sp/input.dat, tests/ao-casscf-sp/output.ref, tests/ao-dfcasscf-sp/CMakeLists.txt, tests/ao-dfcasscf-sp/input.dat, tests/ao-dfcasscf-sp/output.ref, tests/casscf-fzc-sp/input.dat, tests/casscf-sa-sp/input.dat, tests/dfcasscf-fzc-sp/input.dat, tests/dfcasscf-sa-sp/input.dat, tests/dfcasscf-sp/input.dat, tests/dfrasscf-sp/input.dat, tests/rasscf-sp/input.dat
I added a new integral transformation for CASSCF.  This PR does the integral transformation as a series of J builds rather than actually carrying out an N^5 integral transformation.  For direct, DF, gtfock, this can provide some significant savings.  
For example, a system with 3248 basis functions, the AO-DF-CASSCF performs the CASSCF procedure in 7054 second while the DF-CASSCF performs the CASSCF procedure in 14800 seconds.  
This is a serial version of the AO-CASSCF procedure.  It is possible to implement this in parallel by using a distributed Fock builder.  I will make another PR once I can get GTFock to compile, but this code works without GTFock and MPI.   
-  [x]   I don't understand …
=> AO-CASSCF:  Faster integral transformation for direct/DF CASSCF

psi4/driver/procedures/proc.py, psi4/src/psi4/libscf_solver/hf.cc
Guess READ takes orbital occupations from the READ in orbitals, which are not the same (size wise anyhow).
Fixes cc14 (you will have to trust me on this).
=> Fixes ROHF occupation guess with READ orbitals

psi4/driver/plugin.py
Prevents the user from using a C++ keyword as a name for a new plugin. It came up on [this](http://forum.psicode.org/t/trouble-in-build-plugin-for-psi4/349) forum post.
=> Prevents the user from using C++ keywords for plugin names.

cmake/psi4OptionsTools.cmake, external/upstream/pybind11/CMakeLists.txt, psi4/CMakeLists.txt, psi4/src/CMakeLists.txt, psi4/src/export_mints.cc
Get Psi4 to a tagged version on pybind11 that's likely to be deployed
- @ryanmrichard and @bennybp, shall we agree upon 2.0.0 as our next set point? Not much code adaptation required. Note `pybind11::pybind11` --> `pybind11::module`. There's a one-word patch I'll forward to the pb11 people, but I don't think it'll interfere with you (leftover `::pybind11` in pybind11Config.cmake).
=> pybind11 2.0.0 update

.travis.yml, CMakeLists.txt, cmake/ConfigTesting.cmake
Turn off plugin testing by default. Turn on for Travis.
=> plugins testing

psi4/src/psi4/libdpd/buf4_init.cc, psi4/src/psi4/libdpd/file2_init.cc
See discussion in #550.
Commonly, new users of libdpd will think that DPD::buf4_init() and DPD::file2_init() are initializing blank (zeroed out) tensors to be manipulated.  The note added to the comments above these functions should help some from making this mistake. 
I also removed comments from the file2_init() that describe arguments that do not exist.
=> Clarification in libdpd

psi4/driver/procedures/proc.py, psi4/src/psi4/dmrg/dmrgscf.cc, psi4/src/psi4/mrcc/mrcc.cc, tests/cbs-xtpl-func/input.dat, tests/mrcc/ccsd_t_/CMakeLists.txt, tests/mrcc/ccsdt/CMakeLists.txt
=> fix short-term CheMPS2 outage

cmake/custom_cxxstandard.cmake
According to [clang source](http://llvm.org/svn/llvm-project/cfe/trunk/lib/Frontend/InitPreprocessor.cpp) (about half way down the page), clang always reports version 4.2.1 when using ```__GNUC__```, ```__GNUC_MINOR__```, ```__GNUC_PATCHLEVEL__```. This PR updates the version tester to use ```__clang_major__```, ```__clang_minor__```, ```__clang_patchlevel__``` when clang is detected.
This issue appeared when using Intel compilers on a Mac.
=> Update base compiler version detection with Intel compiler and clang.

cmake/psi4OptionsTools.cmake, plugins/skeleton/CMakeLists.txt, plugins/skeletonambit/CMakeLists.txt, plugins/skeletonaointegrals/CMakeLists.txt, plugins/skeletondfmp2/CMakeLists.txt, plugins/skeletonmointegrals/CMakeLists.txt, plugins/skeletonscf/CMakeLists.txt, plugins/skeletonsointegrals/CMakeLists.txt, plugins/skeletonwavefunction/CMakeLists.txt
This factors the code in the `CMakeLists.txt` of the various plugin templates into one function to avoid
copy/paste.  Within this function it then ensures that `CMAKE_PREFIX_PATH` is properly passed to each build in turn allowing the user to build plugins and use externally built Psi4 dependencies.
=> Plugin fix

.travis.yml, tests/ao-casscf-sp/input.dat, tests/ao-dfcasscf-sp/input.dat, tests/casscf-fzc-sp/input.dat, tests/casscf-sa-sp/input.dat, tests/dfcasscf-fzc-sp/input.dat, tests/dfcasscf-sa-sp/input.dat, tests/dfcasscf-sp/input.dat, tests/dfrasscf-sp/input.dat, tests/fsapt-diff1/input.dat, tests/fsapt1/input.dat, tests/fsapt2/input.dat, tests/isapt1/input.dat, tests/isapt2/input.dat, tests/mints5/input.dat, tests/mom/input.dat, tests/nbody-he-cluster/CMakeLists.txt, tests/opt-multi-dimer-c1/input.dat, tests/opt-multi-dimer-c2h/input.dat, tests/opt-multi-frozen-dimer-c2h/input.dat, tests/opt10/input.dat, tests/opt5/input.dat, tests/opt6/input.dat, tests/opt7/input.dat, tests/opt8/input.dat, tests/opt9/input.dat, tests/rasscf-sp/input.dat, tests/sapt6/CMakeLists.txt, tests/x2c1/input.dat
shorten quicktests for Travis' sake
- in tests, make sure you say `#TEST`, not `# TEST`
=> drop some quicktests

.travis.yml
Most of the developers have Travis turned on in our psi4 forks (esp. as we each hosted _the_ Psi4 for a different phase over the summer). So every time we push a branch and make a PR back to psi4/psi4, Travis is running twice. According to [this](https://docs.travis-ci.com/user/customizing-the-build#Safelisting-or-blocklisting-branches), we can turn on/off travis for certain branches. So this PR hopefully keeps Travis running on all the psi4/psi4 PRs and any long-term non-PR branches you add, while turning it off for the branches that are covered under psi4/psi4 master testing. At least I think that's how this works.
=> attempt to stop double travis-ci-ing our PR branches

CMakeLists.txt, doc/sphinxman/source/erd.rst, external/upstream/erd/CMakeLists.txt, psi4/driver/driver.py, psi4/driver/p4util/util.py, psi4/driver/procedures/dft_functional.py, psi4/src/psi4/libmints/erd_eri.cc, psi4/src/psi4/libmints/erd_eri.h, psi4/src/psi4/libmints/gshell.cc, psi4/src/psi4/libmints/writer.cc, tests/erd/CMakeLists.txt, tests/erd/mp2-module/CMakeLists.txt, tests/erd/mp2-module/input.dat, tests/erd/mp2-module/output.ref, tests/erd/scf5/input.dat, tests/erd/scf5/output.ref
This is a continuation of @bennybp's #587 that I'd like to wrap up, but the gdma Travis isssue needs fixing. We can work out merge order later.
=> ERD progress

.travis.yml, external/upstream/dkh/CMakeLists.txt, external/upstream/gdma/CMakeLists.txt, external/upstream/pcmsolver/CMakeLists.txt, psi4/src/core.cc
@bennybp pointed out [here](https://github.com/psi4/erd/pull/5) that we need to be paying attention to thread safety in called libraries, even if they don't have OpenMP, because Psi4 does. This is trying to follow the guidance in [the venerable document (search `ifcoremt`)](https://software.intel.com/en-us/articles/threading-fortran-applications-for-parallel-performance-on-multi-core-systems)
```
/*
* Multithreaded C-Fortran mixed language test program
*/
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>
#include <errno.h>
#include "threadpool.h"
#include "forreent.h"
#define NUM_THREADS 12
#define NUM_JOBS 10
/* definitions for …
```
=> add intel RTL Fortran threading initialization/finalization

psi4/driver/procedures/mcscf/diis_helper.py
NumPy linked DSYEV was not robust enough under certain conditions. Switches to Psi4 power inversion to fix this issue.
=> CIWave: Fixes occasional power issue with the MCSCF DIIS object

psi4/src/CMakeLists.txt, psi4/src/core.cc
Fixes an issue where building with Intel but without fortran enabled would lead to undefined symbols `for_rtl_init_()` and `for_rtl_finish_()`
=> Fix for building with Intel without fortran enabled

psi4/src/psi4/dfmp2/mp2.cc, tests/CMakeLists.txt, tests/extern2/CMakeLists.txt, tests/extern2/input.dat, tests/extern2/output.ref
Adds missing CPHF terms, so that DF-MP2 gradients are correct when an external potential is present. Fixes #618.
=> DFMP2 gradients with external potential

cmake/psi4OptionsTools.cmake, plugins/skeleton/CMakeLists.txt, plugins/skeletonambit/CMakeLists.txt, plugins/skeletonaointegrals/CMakeLists.txt, plugins/skeletondfmp2/CMakeLists.txt, plugins/skeletonmointegrals/CMakeLists.txt, plugins/skeletonscf/CMakeLists.txt, plugins/skeletonsointegrals/CMakeLists.txt, plugins/skeletonwavefunction/CMakeLists.txt
Since #582, presumably, all the skeleton plugins that we check out and build from template have actually been using the same, `basic`, template. The adding to ctest bit wasn't working either.
=> Fix Plugin Testing

psi4/src/psi4/libpsio/aio_handler.cc
Add missing include to fix build with gcc 7 (see #631).
=> Add missing include.

psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/dfmp2/mp2.h, psi4/src/psi4/libmints/wavefunction.cc, tests/mp2-module/input.dat
Move components of the mp2 energy into the `variables_` map so that they're accessible from Python (cc #642).
Are the any backwards compatibility or other reasons to leave the `energies_` member variable around?
=> DF-MP2: Put energies in variables_ so that they are available in Python

doc/sphinxman/source/freq.rst, psi4/src/psi4/findif/fd_freq_0.cc, psi4/src/psi4/findif/fd_freq_1.cc, psi4/src/psi4/findif/fd_misc.cc, psi4/src/psi4/findif/findif.h, psi4/src/read_options.cc
This PR adds code to the findif codes that allows to save the current geometry and normal modes to  a Molden file.
Normal mode info is only written if explicitly requested by the user (via the boolean keyword NORMAL_MODES_WRITE). The normal modes are saved in [Molden format](http://www.cmbi.ru.nl/molden/molden_format.html).
=> Add a function to save normal modes and geometry after a vibrational analysis

external/upstream/pcmsolver/CMakeLists.txt, psi4/CMakeLists.txt, psi4/driver/inputparser.py, psi4/driver/p4util/python_helpers.py, tests/pcmsolver/dipole/input.dat, tests/pcmsolver/dipole/output.ref, tests/pcmsolver/scf/input.dat
Fixes a [build](http://forum.psicode.org/t/crc32-undefined-symbol-at-runtime-when-built-with-pcmsolver-gcc-4-9-4/449/10) and an [execution](http://forum.psicode.org/t/pcmsolver-inp-file-not-found-bug/438/7) issue with PCMSolver.
=> Fix various issues with PCM

psi4/src/psi4/libfock/cubature.cc
This cleans up a matrix before diagonalisation by removing extremely small values arising from numerical accuracy during matrix generation. Diagonalisation of matrices that have off-diagonal elements of ca <10-14 with DSYEV appears to lead to unexpected eigenvalues, which ultimately lead to different DFT grid generation on different processor types that show subtly different behaviour with numerical accuracy.
Ultimately, this enables the dftd3-version test to pass on core i7-5930X processors (all Haswell?) where before it failed due to generation of an odd DFT grid compared with other processors.
- I don't think this should affect anything other than within OrientationMgr but the main …
=> Orientationmgr diag

psi4/src/read_options.cc
I found a bunch of typos in the list of options in the manual. I then ran flyspell in emacs to see if there were any more. This PR should eliminate most of them.
=> Fix a number of typos in the list of options.

doc/sphinxman/source/bibliography.rst, doc/sphinxman/source/cc.rst, doc/sphinxman/source/pcmsolver.rst, psi4/src/psi4/cctransort/CMakeLists.txt, psi4/src/psi4/cctransort/cctransort.cc, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/read_options.cc, tests/pcmsolver/CMakeLists.txt, tests/pcmsolver/ccsd-pte/CMakeLists.txt, tests/pcmsolver/ccsd-pte/input.dat, tests/pcmsolver/ccsd-pte/output.ref, tests/pcmsolver/dft/input.dat, tests/pcmsolver/scf/input.dat
This PR enables CCSD calculations with the PCM in the [PTE (Perturbation-To-Energy) approximation](http://dx.doi.org/10.1063/1.3245400). The CCSD amplitude equations are solved using the solvated Fock matrix and MOs, _i.e._ running SCF with PCM and then using the solvated SCF determinant as the reference.
It boils down to adding the PCM polarization energy in the reference energy used in the CC modules.
=> PCM-CCSD in the PTE approximation

psi4/src/psi4/ccresponse/LHX1Y2.cc, psi4/src/psi4/ccresponse/X2.cc, psi4/src/psi4/ccresponse/polar.cc
Fixes a small bug in out of core dpd_dot24 function in X2.cc and LHX1Y2.cc files of ccresponse. The bug resulted in different polarizability values with symmetry on and off. It was traced to a small typo: 
use of '&' vs '&&'. Also, the polarizability tensor is properly symmetrized.
- [ X] Ready to go
=> Fixes a small bug in ccresponse

psi4/src/psi4/libdpd/buf4_scmcopy.cc
I tracked down a seg fault during a largish cc2 calculation to an integer overflow in the value of `size` in DPD::buf4_scmcopy(). I think it was triggered because I allocated a large amount of RAM so a huge chunk of data was to be copied in one go rather than in bits. In my case,
`size = rowtot*coltot = 47252*47252 = -2062215792`
Funnily enough, memcpy wasn't very happy being called with a negative size to copy!
It's a simple case of `int*int` being larger than an int!
Changing `size` to a `long int` and adding some casts matches other sections of the file (although perhaps replacing them all with `size_t` might be better?).
This fix got my calculation past the point where it caused the seg fault (although it's still running: it might take a few days!).
This bug probably only got …
=> Fixes an integer overflow in libdpd

psi4/src/psi4/libscf_solver/hf.cc, tests/pytest/test_addons.py
Fixes a PCM test failure when running `psi4 --test`. The bug was pointed out by @loriab in #697 
Closes #697.
=> Fix PCM test failure in psi4 --test

.travis.yml, CMakeLists.txt, doc/sphinxman/source/build_planning.rst, doc/sphinxman/source/erd.rst, doc/sphinxman/source/libint.rst, doc/sphinxman/source/manage_addon.rst, doc/sphinxman/source/simint.rst, external/upstream/libint/CMakeLists.txt, psi4/CMakeLists.txt, psi4/src/CMakeLists.txt, psi4/src/psi4/libmints/CMakeLists.txt, psi4/src/psi4/libmints/eribase.cc, tests/pywrap-checkrun-rhf/input.dat, tests/pywrap-checkrun-rohf/input.dat, tests/pywrap-checkrun-uhf/input.dat
Updates Libint 1.2.0 @ evaleev/libint <-- libint 1.1.6 @ psi4/libint, evaleev/libint#77
=> Use upstream libint1

psi4/src/CMakeLists.txt, psi4/src/core.cc, psi4/src/export_options.cc
Expose P::e.options in Python and enable pure pybind11 plugins.
=> Expose P::e.options in Python.

psi4/src/psi4/fnocc/ccsd.cc, psi4/src/psi4/fnocc/df_ccsd.cc
T1 and D1 diagnostics computed by ccsd/df-ccsd routed through fnocc are added to psi4 global variables
=> adds t1/d1 diagnostics computed in fnocc to psi4 global variables

psi4/driver/p4util/python_helpers.py, tests/CMakeLists.txt, tests/mints3/input.dat, tests/mints9/purepythonanalog.in, tests/scf-upcast-custom-basis/CMakeLists.txt, tests/scf-upcast-custom-basis/input.dat
Fixes #719 by changing the `name` that's passed to the C++ BasisSet constructor. It used to be like `file /path/to/basis/set.gbs`, but that it very tricky to read the basis set name from a dumped wavefunction and reinstantiate the basis set. For built-in basis sets, it's not too bad -- we can just [parse the string](https://github.com/psi4/psi4/blob/9d1564e67837bbf7f348c1600aa2c353457671ec/psi4/driver/procrouting/proc.py#L1295). For custom basis sets that assign different basis sets to different atoms, that string ends up as a `'+'`-delimited list of gbs files, which isn't information preserving.
@andysim: if you're going to rewrite this stuff anyways, it might not be worth merging this.
=> Fix gh-719, inability to project between custom basis sets

psi4/src/psi4/libmints/dimension.cc
Cleans up a function that was erroneously printing Dimension objects when creating Slices.
=> Get rid of print info.

psi4/src/psi4/ccdensity/Params.h, psi4/src/psi4/ccdensity/ccdensity.cc, psi4/src/psi4/ccdensity/deanti_RHF.cc, psi4/src/psi4/ccdensity/deanti_ROHF.cc, psi4/src/psi4/ccdensity/deanti_UHF.cc, psi4/src/psi4/ccdensity/fold_RHF.cc, psi4/src/psi4/ccdensity/fold_ROHF.cc, psi4/src/psi4/ccdensity/fold_UHF.cc, psi4/src/psi4/ccdensity/get_params.cc, psi4/src/psi4/ccresponse/get_params.cc, psi4/src/psi4/ccresponse/pertbar.cc, psi4/src/psi4/ccresponse/polar.cc, psi4/src/read_options.cc
1. Default gauge has been set to "velocity" for ccresponse calculations. Un-necessary
printing removed from pertbar.cc
2. cc-energies are reproduced from densities only when debug's value is non-zero.
=> Minor changes in ccdensity and ccresponse

psi4/driver/procrouting/findif_response_utils/db_helper.py, psi4/src/psi4/findif/fd_misc.cc
Minor tweaks to finite differences in the atomic_displacements() function that is used only in prototype ROA calculations at present.  
Now supports 3-point and 5-point formulae finite differences in the atomic_displacements() function.
Now returns displacements in canonical most negative to most positive order.
I have used this function in dipole moment derivative/file17 computations.  Further development along these lines is likely.
None at this juncture.
None
Should be ready to go.
=> minor tweak of finite difference atomic_displacements order

psi4/driver/procrouting/mcscf/mcscf_solver.py, psi4/src/psi4/detci/opdm.cc, tests/dfcasscf-fzc-sp/input.dat
Fixes an issue related to the definition of natural orbitals in CASSCF computations (#740).
=> CASSCF: semicanonicalize docc and virt blocks of Favg.

psi4/src/psi4/ccenergy/ccenergy.cc, psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/dfocc/dfocc.cc, psi4/src/psi4/dfocc/manager.cc, psi4/src/psi4/fnocc/ccsd.cc, psi4/src/psi4/fnocc/df_ccsd.cc, psi4/src/psi4/fnocc/fnocc.cc, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/writer.cc, psi4/src/psi4/libscf_solver/rhf.cc, psi4/src/psi4/libscf_solver/rohf.cc, psi4/src/psi4/libscf_solver/uhf.cc, psi4/src/psi4/occ/manager.cc, psi4/src/psi4/occ/occwave.cc
This pull request aims to properly update energy, orbital energies, densities etc of the wave function for (conventional and density-fitted Mp2) and density-fitted CCSD calculations, so as to ensure proper checkpointing using FCHK interface. 
Also, there seems to be a problem in using FCHKWriter for conventional mp2 gradient calculations as I get a segmentation fault. This PR is meant to fix these problems which was pointed out by abdale on the psi4 forum. http://forum.psicode.org/t/problems-with-wavefunction-object-and-fchk-interface/532
=> Proper update of post-scf wave-functions for fchk interface

doc/sphinxman/source/numpy.rst, psi4/driver/p4util/numpy_helper.py, psi4/src/export_mints.cc, psi4/src/psi4/libpsi4util/PsiOutStream.cc, tests/numpy-array-interface/input.dat
Occasionally we had issues cropping up where users were assigning views that were not tied to the Matrix object. Consider the following:
```
mat = Matrix(5, 5)
view = mat.np
del mat
```
Previously, `mat` and `view` lifetimes were not tied together. The NumPy array would point to deleted memory in the above example. With this PR, the object lifetime are tied together and `mat` is not actually deleted in this example (just a handle to it) so that the `view` remains valid. This also allows operations like `view = Matrix(5, 5).np` and `Cocc = wfn.Ca_subset("AO", "OCC").np` to work without issue.
A small downside is that the views cannot be cached as this would lead to circular nurse/patient relationships and prevent the objects from ever being garbage collected. This makes the `.np` accessors …
=> Numpy update

.clang-format, .style.yapf
Adds a .clang-format file to psi4 based on discussion of issues #752. (closes #752)
To format C++ files (with inplace edit) run:
```
clang-format -style=file -i [<file> ...]
```
=> Add clang-format/YAPF style files

psi4/src/psi4/libqt/qt.h, psi4/src/psi4/libqt/timer.cc, psi4/src/psi4/libscf_solver/sad.cc
Implemented a pair of functions,
- `void start_skip_timers()`
- `void stop_skip_timers()`
to skip all nested `timer_on` and `timer_off` calls and avoid complicated timing output.
By the following modification to `/psi4/psi4/src/psi4/libscf_solver/sad.cc`:
```
void SADGuess::compute_guess()
{
timer_on("SAD Guess");
start_skip_timers(); // Added new line.
form_D();
form_C();
stop_skip_timers(); // Added new line.
timer_off("SAD Guess");
}
```
the output `timer.dat` shows:
```
HF: Form H                  :      0.000u      0.017s      0.019w      2 calls
HF: Form S/X                :      0.000u      0.000s      0.000w      2 calls
HF: Guess                   :      0.400u      0.000s      0.247w      2 calls
| SAD Guess                 :      0.400u      0.000s      0.238w      2 calls
HF: …
```
=> Implemented skip_timer functions to help avoid timer clutter.

psi4/driver/procrouting/proc.py, psi4/src/psi4/libdisp/dispersion.cc, tests/dftd3/energy/input.dat
DFT-D plus the use of a guess basis set produced an error because of a typo in setting the dispersion energy: set_variables -> set_variable.
=> Fixes basis_guess with -D combo

psi4/src/export_mints.cc
99% of the docstrings export_mints.cc are now composed, with appropriate py::arg's. There are a few docstrings remaining, which were left either because I couldn't figure them out or they lacked C++ documentation.
Psi4 compiled and psi4 --test finished successfully after these changes.
=> Pybind docstrings exportmints

psi4/include/psi4/pragma.h, psi4/src/psi4/libmints/electrostatic.h, psi4/src/psi4/liboptions/liboptions_python.h
Adds diagnostic pragmas for clang to pragma.h and updates a couple of places to use them.
=> Adds pragma diagnostic macros for clang

doc/sphinxman/source/optking.rst, psi4/src/psi4/optking/set_params.cc, psi4/src/read_options.cc
Adds convergence threshold option for geometry optimization of supermolecular complexes which is slight relaxation of `g_convergence gau_tight` criteria which allows for:
- tight convergence of energy and forces, and
- relaxed convergence of `max_disp` and `rms_disp` displacement criteria. 
These criteria allow for successful optimization on flat potential surfaces, especially those associated with interfragment (supermolecular) geometry optimizations.
Adds `interfrag_gau_tight` value to `g_convergence` OPTKING convergence threshold control keyword.  
- Basic users can use keyword to achieve quality geometry optimizations of supermolecular complexes, without manual manipulation of individual `g_convergence` components.
=> ENH: Adds conv thresh for supermolec complex opt

tests/CMakeLists.txt, tests/props2/input.dat, tests/props3/input.dat, tests/scf-coverage/input.dat
Based off the forums and a few issues there are a few tests that are not quite robust enough to test the code rather than a operational tweaks.
- `props2` - The new orientation code requires that this be moved to the COM at every step.
- `props3` - Overall convergence needs to be tightened to move flutter in 64-pole below test threshold.
- `scf-cov` - Convergence needs to be tightened in addition to not using a C2v molecule during a orientation check.
=> FIX: Tightens up a few tests

external/upstream/pybind11/CMakeLists.txt, psi4/CMakeLists.txt, tests/dft-grad1/CMakeLists.txt, tests/dft-grad1/input.dat, tests/dft-grad2/CMakeLists.txt, tests/dftd3/grad/input.dat, tests/ocepa2/input.dat, tests/omp3-3/input.dat
There were a few more `set dft_functional fctl` in the full test suite. This should polish it off
tests/dftd3/grad/input.dat
```
...
grad = gradient('bp86-d2gr')
compare_matrices(ref, grad, 7, "Outsourced dft gradients called by name")  #TEST
clean()
grad = gradient('scf', dft_functional='bp86-d2gr')
compare_matrices(ref, grad, 7, "Outsourced dft gradients called by options") #TEST
```
```
Outsourced dft gradients called by name...........................PASSED
Traceback (most recent call last):
File "stage/usr/local/psi4/bin/psi4", line 260, in <module>
exec(content)
File "<string>", line 43, in <module>
File "/home/psilocaluser/gits/hrw-matt/objdir/stage/usr/local/psi4/lib/psi4/driver/driver.py", line 606, in gradient
wfn = procedures['gradient'][lowername](lowername, molecule=molecule, …
```
=> Patch failing tests

psi4/src/core.cc
Issue reported by @zhi-wang: passing `NULL` pointer to `for_rtl_init_` function in `core.cc` makes program quit silently. Fix also suggested by @zhi-wang. Closes psi4/psi4#771
=> Fix initialization of Fortran run-time

.gitignore, .scripts/travis_build.sh, .travis.yml, CMakeLists.txt, CTestConfig.cmake, cmake/psi4OptionsTools.cmake, external/upstream/ambit/CMakeLists.txt, external/upstream/chemps2/CMakeLists.txt, external/upstream/dkh/CMakeLists.txt, external/upstream/erd/CMakeLists.txt, external/upstream/gdma/CMakeLists.txt, external/upstream/gtfock/CMakeLists.txt, external/upstream/libefp/CMakeLists.txt, external/upstream/libint/CMakeLists.txt, external/upstream/libxc/CMakeLists.txt, external/upstream/pcmsolver/CMakeLists.txt, external/upstream/pybind11/CMakeLists.txt, external/upstream/simint/CMakeLists.txt
Ninja is supposed to be faster at compiling than make. CMake supports it out-of-the-box, it's enough to pass it as generator:
```
cmake -H. -Bbuild -GNinja
```
I have tried to use Ninja on Travis and the Clang build runs in ~21 minutes. The GCC builds however fail due to a compiler bug.
=> Make Psi4 buildable with Ninja

CMakeLists.txt, cmake/custom_cxxstandard.cmake, psi4/__init__.py, psi4/driver/inputparser.py, psi4/driver/p4util/numpy_helper.py, psi4/driver/plugin.py, psi4/driver/procrouting/interface_cfour.py, psi4/driver/procrouting/proc.py, psi4/driver/procrouting/wrappers_cfour.py, psi4/driver/qcdb/libmintsbasisset.py, psi4/driver/wrapper_database.py, psi4/header.py, psi4/run_psi4.py, psi4/src/core.cc, psi4/src/create_new_plugin.cc, psi4/src/psi4/lib3index/denominator.cc, psi4/src/psi4/libefp_solver/efp_solver.cc, psi4/src/psi4/libpsi4util/process.cc, psi4/src/psi4/libpsi4util/process.h, psi4/src/psi4/libpsio/filemanager.cc, psi4/src/psi4/libpsio/psio.hpp
I hit a system that was raising [putenv and setenv not avail](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libpsi4util/process.cc#L136). Rather than solve it, decided (with support) to clean environment variables out of `P::e`. Only active uses were PSI_SCRATCH and PSIDATADIR.
=> Rid P::e of envvar

psi4/src/export_functional.cc, psi4/src/psi4/libfock/cubature.cc, psi4/src/psi4/libfock/v.cc, tests/dft-b2plyp/input.dat
Fixes an issues where VV10 occasionally seg faults due to improperly sized temporary arrays.
Also, spot the error of why the Naive grid blocker has been seg faulting for years in [#9575ede](https://github.com/dgasmith/psi4/commit/9575ede082c5287be1c176a13299829317b3b719). Highly recommend we stop using raw pointers and C functions.
=> VV10 Grid fix

doc/sphinxman/source/sapt.rst
Added aux_basis building lines to the advanced example.
None.
=> Fix advanced SAPT example

tests/cookbook/rohf-orb-rot/input.dat
This PR fixes a line in cookbook-rohf-orb-rot test that was previously causing a failure
- Not sure if this is applicable?
- No questions at this time
=> Fix cookbook-rohf-orb-rot test

doc/sphinxman/source/libint.rst, psi4/driver/procrouting/proc.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/dfocc/dfocc.h, psi4/src/psi4/dfocc/get_moinfo.cc, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/matrix.h, psi4/src/psi4/libmints/oeprop.cc, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmints/wavefunction.h, psi4/src/psi4/libscf_solver/cuhf.cc, psi4/src/psi4/libscf_solver/cuhf.h, psi4/src/psi4/libscf_solver/rhf.cc, psi4/src/psi4/libscf_solver/rhf.h, psi4/src/psi4/libscf_solver/rohf.cc, psi4/src/psi4/libscf_solver/rohf.h, psi4/src/psi4/libscf_solver/uhf.cc, psi4/src/psi4/libscf_solver/uhf.h
Allow symmetry to be used in SCF, but then convert the symmetrized wavefunction to a desymmetrized (C1) format for use by non-symmetry-aware modules
=> Desymmetrize SCF for non-symmetry-aware modules

doc/sphinxman/CMakeLists.txt, doc/sphinxman/source/contributing.rst, doc/sphinxman/source/manage_addon.rst, doc/sphinxman/source/manage_index.rst, doc/sphinxman/source/prog_blas.rst, doc/sphinxman/source/prog_faq.rst, doc/sphinxman/source/programming.rst, doc/sphinxman/source/psiapi.ipynb, doc/sphinxman/source/style_c.rst, psi4/src/read_options.cc
So all the build docs on the wiki are indeed deprecated as they announce. But all the rest of the docs  are of varying levels of value and states of deprecation. This collects the ones that really shouldn't be lost.
=> Migrate some existing wiki docs into sphinxman

CMakeLists.txt, doc/sphinxman/source/chemps2.rst, doc/sphinxman/source/dkh.rst, doc/sphinxman/source/erd.rst, doc/sphinxman/source/gdma.rst, doc/sphinxman/source/libefp.rst, doc/sphinxman/source/libint.rst, doc/sphinxman/source/pcmsolver.rst, doc/sphinxman/source/simint.rst, external/upstream/ambit/CMakeLists.txt, external/upstream/chemps2/CMakeLists.txt, external/upstream/dkh/CMakeLists.txt, external/upstream/erd/CMakeLists.txt, external/upstream/gdma/CMakeLists.txt, external/upstream/gtfock/CMakeLists.txt, external/upstream/libefp/CMakeLists.txt, external/upstream/libint/CMakeLists.txt, external/upstream/libxc/CMakeLists.txt, external/upstream/pcmsolver/CMakeLists.txt, external/upstream/pybind11/CMakeLists.txt, external/upstream/simint/CMakeLists.txt, psi4/src/psi4/libpsi4util/process.cc
address build issues for FreeBSD packaging @yurivict 
=> address build issues for FreeBSD packaging

doc/sphinxman/source/glossary_psivariables.rst, psi4/src/psi4/ccresponse/optrot.cc, psi4/src/psi4/ccresponse/polar.cc, tests/cc29/input.dat, tests/cc39/input.dat
Originally, only the last rotation or polarizability values computed were actually dumped to the dictionary accessed by `core.get_variables`. This fix pushes each one into the dictionary with its corresponding wavelength (in NM). I've added a few lines to `tests/cc39/input.dat` and `tests/cc29/input.dat` to test the polarization and rotation variables, respectively. I've run the tests separately since the quick tests on Travis may not cover them, the results can be found [here](https://gist.github.com/bgpeyton/6a7842adb77a03a10bf696c8364a9c54) and [here](https://gist.github.com/bgpeyton/a6654acd0f7fcaa89b5023bebd40b025). 
None
=> Fix to dump all rotation and polarizability values calculated to get_variables() dictionary

doc/sphinxman/source/bibliography.rst, doc/sphinxman/source/plugin_snsmp2.rst, psi4/driver/endorsed_plugins.py
This PR adds the [SNS-MP2 plugin](https://github.com/DEShawResearch/sns-mp2) to the list of endorsed Psi4 plugins such that the SNS-MP2 method can be called by energy() without the use of any import statements.
=> SNS-MP2 Plugin Addition

doc/sphinxman/source/cubeprop.rst, psi4/driver/p4util/util.py, psi4/src/psi4/libcubeprop/csg.cc, psi4/src/psi4/libcubeprop/csg.h, psi4/src/psi4/libcubeprop/cubeprop.cc, psi4/src/psi4/libcubeprop/cubeprop.h, psi4/src/read_options.cc, tests/cubeprop-esp/input.dat, tests/cubeprop/input.dat
This is an enhancement to Psi4 cubeprop library. Cube files are usually plotted using isocontour surfaces with a common iso value. This PR implements the computation of adaptive isocontour values that capture a certain fraction of a MO density (orbital squared) using the least amount of points. This is similar to the approach of Lehtola and Jónsson [J. Chem. Theory Comput. 10, 642–649 (2014)], but appears to be different in the fact that the implementation in this PR uses two isocontour values.
The added code just sorts a cube file's grid points and finds a pair of positive and negative isocontour values the satisfy the above definition. The default is to capture 85% of the density, but the user can specify a different value with the new option `CUBEPROP_ISOCONTOUR_THRESHOLD`.  The …
=> CUBEPROP: Compute adaptive isocontour range for cube files

psi4/src/psi4/dmrg/dmrgscf.cc
PR #844 made the dipole field a required argument almost everywhere but missed DMRG. The DMRG code now supplies this argument, so the code can be built again!
=> External Field Cleanup in DMRG, #844 Continued

psi4/src/export_wavefunction.cc, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmints/wavefunction.h
This PR adds implementation of `force_soccpi` and `force_doccpi`, allowing the user to change the singly and doubly occupied orbitals per irrep in the Wavefunction object. The alpha and beta electron counts are also updated accordingly. This functionality should only be used by expert users in special circumstances, since it causes inconsistency in the Wavefunction object for SCF purposes. (Let me know if I should add some sort of "expert" flag in the documentation to reflect this, or if I need to add any other documentation besides what I've put in already!)
=> Adding force_soccpi and force_doccpi functions

psi4/driver/driver.py, psi4/driver/p4util/exceptions.py, tests/opt1/input.dat
Allow access to wfn (incl. geom) after optking errors
```
try:
optimize('hf')
except psi4.ConvergenceError as err:
gotcha = err.wfn
print(gotcha.molecule().nuclear_repulsion_energy())
```
=> Get useful info back after optimizer errors

doc/sphinxman/CMakeLists.txt, doc/sphinxman/source/add_tests.rst, doc/sphinxman/source/prog_faq.rst, doc/sphinxman/source/programming.rst, psi4/src/psi4/optking/molecule_irc_step.cc, psi4/src/psi4/optking/opt_data.cc, tests/CMakeLists.txt, tests/opt-irc-3/CMakeLists.txt, tests/opt-irc-3/input.dat
As documented in #859, an IRC performed on a tightly converged transition state would converge to the initial transition state. The obvious workaround showed non-deterministic optking steps, as documented in #860. Both bugs originate from neglecting the possibility of near-zero gradients and have been fixed. Also as documented in #860, there is still some non-deterministic behavior after the minimum has been found. As optking is going to be moved Python-side soon and this behavior is irrelevant for most users, I'll hold off from investigating that until we see if the Python-version has the problem.
I have added a test case for tightly converged transition states, thanks to the oddly prescient #881. For the sake of other developers, I added a page on how to add test cases.
Notable points …
=> #859, #860 Fix: Tightly Converged IRCs Now Run

external/upstream/pcmsolver/CMakeLists.txt, psi4/CMakeLists.txt, psi4/driver/p4util/python_helpers.py
Parsing the PCM section of the input requires changing directories. As noted in #817 this is not really documented anywhere and affects users.
=> Preserve current working directory when parsing PCM section

psi4/src/psi4/libfock/v.cc, tests/dft-vv10/CMakeLists.txt, tests/dft-vv10/input.dat
Small timer mistype in VV10 NL correlation. I patched this up and added a (faster) test to the quicktests suite so that we also check VV10 in CI.
=> DFT: Fix VV10 timer error and quickens test

doc/sphinxman/source/psithoninput.rst
Default memory had been raised to 500 MiB, update documentation to match it.  Add some extra information about the handling of IEC/SI units. 
=> Update memory docs

psi4/src/export_mints.cc, psi4/src/psi4/findif/fd_1_0.cc, psi4/src/psi4/findif/fd_freq_0.cc, psi4/src/psi4/findif/fd_freq_1.cc, psi4/src/psi4/findif/fd_geoms_1_0.cc, psi4/src/psi4/findif/fd_geoms_freq_0.cc, psi4/src/psi4/findif/fd_geoms_freq_1.cc, psi4/src/psi4/libmints/cdsalclist.cc, psi4/src/psi4/libmints/cdsalclist.h, psi4/src/psi4/libmints/deriv.cc, psi4/src/psi4/libmints/factory.cc, psi4/src/psi4/libmints/factory.h, psi4/src/psi4/libmints/matrix.h, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libmints/pointgrp.cc, psi4/src/psi4/libmints/pointgrp.h, psi4/src/psi4/scfgrad/response.cc
The CdSalcList code is made fully accessible to the Python layer, per #884. This code does that and makes a few other changes to clean up code I found while trying to write the documentation for Pybind.
Pinging @loriab and @dgasmith by request.
=> CdSalcList Pybinding, Cleanup

psi4/src/psi4/libfock/points.cc, psi4/src/psi4/libfock/v.cc, psi4/src/psi4/libfock/v.h, tests/dft1/input.dat
Apparently UKS Meta-GGA's have been wrong since the LibXC patch. I have fixed this error and get quite a nice agreement across our test set. I have changed the `dft1` test to cover these cases and be a bit more specific in what we are testing.
I have also started on UKS VV10; however, I am not quite confident it is correct. The VV10 energy is certainly correct, but the gradient might not be scaled correctly. This is the last chance I have to look at it for several weeks so it will need to wait.
=> UKS Meta-GGA fixes and UKS VV10

external/upstream/pcmsolver/CMakeLists.txt, psi4/CMakeLists.txt, psi4/driver/inputparser.py, psi4/driver/p4util/python_helpers.py, psi4/run_psi4.py, psi4/src/psi4/libpsipcm/psipcm.cc, psi4/src/read_options.cc
This PR brings (hopefully!) to a close the PCM-changes-directory saga noted in issue #817 and partially alleviated in PR #818.  
This change needed an API update PCMSolver-side, hence the minimum required version bump to its 1.1.12 version.
- As (probably not very clearly) noted in the manual, **analytical gradients including PCM are NOT available**. Should there be a stop in the code when such a request is made or should the code be routed to use a numerical gradient?
=> Fix PCM kerfuffle with directories

psi4/src/psi4/libmints/overlap.cc, tests/scf-hess1/input.dat
A typo in the overlap integral second derivatives caused errors in the analytic hessians.  The error seems to be confined to one of the three contributions to matrix elements where the angular momentum in the bra and ket differ, and only when the derivatives both refer to the same perturbation; which is why the code made it through the initial tests.  I'm still trying to wrap my head around exactly why those tests work, so I'd like a day or two before this is ready to merge.  My sincere apologies to all whom this bug inconvenienced.  Fixes #791 and #901.
=> Fix Hessian bug

tests/dft1/input.dat
psi4/psi4#897 guess change in dft1 had a bad reaction for wB97 (1 2) w/SAD and with (-1 2) w/GWH. This fixes it up again.
=> Fixes wB97 & wB97X SAD occupations in dft1 test

psi4/driver/procrouting/proc.py
The IWL integrals are calculated but apparently not needed for DF-DCFT. Added IF/ELSE clause to avoid this.
=> turning off iwl integrals for df-dcft

doc/sphinxman/source/sapt.rst, psi4/driver/procrouting/proc.py, psi4/driver/qcdb/psivardefs.py, psi4/src/psi4/fisapt/fisapt.cc, psi4/src/psi4/libsapt_solver/sapt0.cc, psi4/src/psi4/libsapt_solver/usapt0.cc, psi4/src/read_options.cc
When requesting uncoupled induction in RHF-based SAPT0, the final summary still printed Ind20,r instead of Ind20,u as the line title, and no warning was issued about the uncoupled induction stored in the Psi4 variable for coupled induction, contrary to what is happening for open-shell SAPT0.
Solves #907.
=> Corrected printing for uncoupled induction

psi4/src/psi4/detci/ints.cc, psi4/src/psi4/dfep2/dfep2.cc, psi4/src/psi4/fisapt/fisapt.cc, psi4/src/psi4/lib3index/df_helper.cc, psi4/src/psi4/lib3index/df_helper.h, psi4/src/psi4/libfock/soscf.cc, psi4/src/psi4/libsapt_solver/fdds_disp.cc, psi4/src/psi4/libsapt_solver/usapt0.cc, tests/python/3-index-transforms/input.dat
Furthers the generality of integral transformations and enables a special workflow, `DIRECT_iaQ`, to alleviate disk IO when transforming to `pqQ` forms.  Timings comparing the `DIRECT_iaQ` and `DIRECT` methods are inbound.
Edit: Here are some tests that (almost comically) display the efficacy of `DIRECT_iaQ` over `DIRECT` + `pqQ`.
1. Test1: 
[input.txt](https://github.com/psi4/psi4/files/1740970/input.txt)
[timer.txt](https://github.com/psi4/psi4/files/1740977/timer.txt)
2. Test2:  
[input.txt](https://github.com/psi4/psi4/files/1740966/input.txt)
[timer.txt](https://github.com/psi4/psi4/files/1740974/timer.txt)
Notice the difference between the `DFH: MO to disk` timers.  
Edit2: I added a reduction on `max_val` in `prepare_sparsity` to ensure thread safety.  This was incorrect before. …
=> New DF_Helper Technology

.travis.yml
Switches off a few dependancies until they can be updated on the conda channel. Travis CI is hitting time limits fairly frequently when building these.
=> CI: Turns off v2RDM and PCM in Travis until conda modules are updated.

psi4/driver/driver.py, psi4/run_psi4.py
Adds NumPy file to the `messy` flag and ensures that those files are correctly parsed through the restart renaming.
File names are going haywire a bit with different conventions for either PSIO or "user facing names" like Molden and cube files. Anyone have a good idea how to rectify this? It would also be good to have restart work for gradients, Hessians, and properties as well. Ill add this to the wish ilst.
=> SCF NumPy restart files

psi4/driver/driver_nbody.py, psi4/driver/qcdb/libmintsbasisset.py, psi4/driver/qcdb/libmintsbasissetparser.py, psi4/driver/qcdb/libmintsgshell.py
Minor ECP fixes, so that more ECP's from EMSL Basis set exchange work out of the box. See issue #926 .
=> Some ECP fixes.

psi4/driver/driver.py, psi4/driver/driver_cbs.py, tests/CMakeLists.txt, tests/cbs-parser/CMakeLists.txt, tests/cbs-parser/input.dat, tests/cbs-parser/output.ref, tests/props4/input.dat, tests/props4/output.ref
Standardized handling of "/" in method name between frequency, hessian, gradient, properties and energy.
- Use of `_cbs_gufunc` helper function consistently across `energy`, `hessian`, `gradient`, `frequency` and `properties`
- `_cbs_gufunc` throws an exception for unsupported "true" CBS calls to `frequency` and `properties`, "method/basis" syntax works
- all relevant tests pass, see below
- modified regex in `_parse_cbs_gufunc_string()` to correctly handle `sapt2+(3)/basis` calls or `method/6-311++G` calls; splitting now only happens on variants of `+ D:`.
=> Allow for "/" in the names of methods.

psi4/driver/procrouting/sapt/__init__.py, psi4/driver/procrouting/sapt/sapt_jk_terms.py, psi4/driver/procrouting/sapt/sapt_mp2_terms.py, psi4/driver/procrouting/sapt/sapt_proc.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/libscf_solver/hf.h, tests/CMakeLists.txt, tests/sapt-dft-api/CMakeLists.txt, tests/sapt-dft-api/input.dat, tests/sapt-dft-api/output.ref, tests/sapt-dft-lrc/CMakeLists.txt, tests/sapt-dft-lrc/input.dat, tests/sapt-dft1/input.dat, tests/sapt-dft2/input.dat, tests/sapt-dft2/output.ref
Makes SAPT(DFT) quite a bit more flexible by allowing a potential user to build SCF wavefunctions (any will work, HF or DFT). An example can be found in `tests/sapt-dft-api`.
I have also added LRC references with SAPT(DFT). @ajmisquitta please checkout `tests/sapt-dft-lrc` and verify these are working as expected.
Closes #939 .
=> SAPT(DFT) flexibility changes

doc/sphinxman/source/glossary_psivariables.rst, psi4/driver/driver_nbody.py, tests/CMakeLists.txt, tests/nbody-intermediates/CMakeLists.txt, tests/nbody-intermediates/input.dat, tests/nbody-intermediates/output.ref
Exports intermediate energies computed within N-Body driver to psivars named `N-BODY {cluster-identity} TOTAL ENERGY` for workflow incorporation and sanity-checking.
Convention for `cluster-identity`: `(monomer_tuple)@(basis_tuple)` enumerates the particular monomers involved in the cluster computation in `monomer_tuple`, and enumerates the basis set used within the cluster computation in `basis_tuple`.  In this way, ghost monomers are easily identified as any fragment with basis functions (included in `basis_tuple` not present in `monomer_tuple`.   For example,
```
"N-BODY (1, 2)@(1, 2, 3) TOTAL ENERGY"                  =>    -529.655058639489
```
indicates that the total energy for the fragment (1, 2) in basis set (1, 2, 3) is -529.66 [Eh].  
Notable points that this PR has either …
=> Exporting N-Body intermediates to psivars

CMakeLists.txt, doc/sphinxman/source/build_planning.rst, doc/sphinxman/source/pcmsolver.rst, external/upstream/gau2grid/CMakeLists.txt, psi4/CMakeLists.txt
Bump gau2grid to v1.0 and lose `mpmath`.
- Note that bumping the `find_package(gau2grid 1.0)` is only for appearances sake since 0.1 tag worked just fine. 
=> Bump gau2grid to v1.0

doc/sphinxman/source/conda.rst
Adds NumPy to the psi4-dev environment as it is 1) required to build gau2grid and 2) required to run Psi4.
We also need to install deep-diff here as well which is only available on pip/conda-forge. Should this be: `conda create -n p4dev python=x.x psi4-dev numpy deep-diff -c psi4 -c conda-forge`
=> Adds NumPy to the psi4-dev clone.

.travis.yml, psi4/CMakeLists.txt, psi4/driver/qcdb/libmintsmolecule.py, psi4/src/psi4/libmints/molecule.cc, psi4/versioner.py, tests/pywrap-align-chiral/CMakeLists.txt, tests/pywrap-align/CMakeLists.txt
=> Avoid hungarian

psi4/src/psi4/libfock/v.cc, psi4/src/psi4/libscf_solver/uhf.cc, tests/CMakeLists.txt, tests/dft-bench-ionization/input.dat, tests/dft-grad-meta/CMakeLists.txt, tests/dft-grad-meta/input.dat, tests/dft-grad-meta/output.ref, tests/dft-vv10/input.dat
Patch up VV10 UKS dispersion. This had been a nagging issue for awhile now, but it turns out the only real issue is that I forgot to add the VV10 energy to the total SCF energy. I had originally started blaming the Fock term as the VV10 energy was spot on and subsequently starting playing with those values. Quite the blooper on my part:
```
(p4dev) daniel:~/Gits/psi4ds/tests/dft-bench-ionization (vv10_uks)$ python ../../psi4/run_psi4.py --inplace input.dat
VSXC: Psi4 vs. Q-Chem.............................................PASSED
VV10: Psi4 vs. Q-Chem.............................................PASSED
B97M-V: Psi4 vs. Q-Chem...........................................PASSED
LC-VV10: Psi4 vs. Q-Chem..........................................PASSED
wB97M-V: Psi4 vs. …
```
=> VV10: Fixes UKS non-local dispersion

psi4/src/psi4/findif/fd_geoms_freq_0.cc
=> Fix #941, Incorrect #Displacements Reported

doc/sphinxman/CMakeLists.txt, doc/sphinxman/source/dft.rst, doc/sphinxman/source/dftnl.rst, psi4/driver/procrouting/dft_funcs/dict_builder.py, psi4/driver/procrouting/dft_funcs/dict_dh_funcs.py, psi4/driver/procrouting/dft_funcs/superfuncs.py, psi4/driver/procrouting/empirical_dispersion.py, psi4/driver/procrouting/proc.py, psi4/driver/qcdb/dashparam.py, psi4/src/psi4/libfunctional/superfunctional.h, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/read_options.cc, tests/dft-vv10/input.dat, tests/dft-vv10/output.ref, tests/dft-vv10/ref_outputs/blyp-scnl.ref
DFT-NL (=non-local) adds the VV10 correlation energy to arbitrary DFT functionals using functional specific  vv10_b parameter. Conceptually similar to DFT-D. DOI: 10.1021/ct200644w
Fixes https://github.com/psi4/psi4/issues/870
* **Developer notes**
* ** Notes**
* forcing pure HF with VV10  will seg. fault. (no integration grid). Only `energy('hf')` with `set DFT_VV10_B` is caught, not `energy('scf')` to allow custom access to the scf.
* NL parameters were entered manually, someone please check over them for strange values or typos
* tests are kept short, but we also don't test every dispersion dash parameter out there.
* for double-hybrids with multiple versions, the frozen core and/or D3BJ parent variant was chosen for a sensible consistency.
=> adding DFT-NL scheme

psi4/driver/driver_nbody.py
Addresses #885 by refactoring N-Body driver to three newly independent functions, driven by the existing `nbody_gufunc()`:
- `build_nbody_compute_list()`: Builds list of all N-body computations to be performed
- `compute_nbody_components()`: Performs given N-body computation(s), could be exploited as pleasantly parallel
- `assemble_nbody_components()`: Stitches components back together into _bona fide_ N-body energies (currently standard behavior of N-body driver)
- Opportunity for "pleasantly parallel" N-body computations
- UI to N-Body driver unchanged
- Standard N-body calls, e.g., `energy(..., bsse_type='cp')` retain current functionality via …
=> N-Body driver refactor (fixes #885)

psi4/src/export_mints.cc, psi4/src/psi4/libmints/basisset.cc, psi4/src/psi4/libmints/basisset.h, tests/dfmp2-ecp/input.dat, tests/dfmp2-ecp/output.ref
Freeze additional electron pairs on atoms with ECPs. This stops erratic behaviour in MP2 correlation energies as described in #976 .
=> Handle ECP's in n_frozen_core(), fixes #976

tests/cc46/CMakeLists.txt
Removes cc46 from ctest temporarily to keep full tests passing.  There is no major bug here, rather a bunch of conflicting logic in the `run_cc_property` driver that will be patched before final release.
=> Disable CC46 to keep full tests green on 1.2rc1

doc/sphinxman/source/pcmsolver.rst, psi4/driver/driver.py, tests/pcmsolver/opt-fd/input.dat, tests/pcmsolver/opt-fd/output.ref
The user needs not set `dertype='energy'` explicitly anymore when calling `optimize`. The test case has been extended accordingly.
=> Force use of finite difference gradient with PCM

doc/sphinxman/source/scf.rst, psi4/driver/procrouting/proc.py
closes #973 
#973 Contained the report that RHF stability analysis = follow would silently check for instabilities and then continue on doing nothing about them, and a request to implement FOLLOW for RHF/ROHF. This PR fixes the first part, The feature request has been added under a separate issue (#1005)
=> Stop RHF/ROHF stability_analysis from silently skipping a "FOLLOW"

psi4/driver/p4util/python_helpers.py
As a side effect of #961, all wavefunctions had to have a density-fitted basis set when doing any energy computations, even if not density-fitted. Any scripts calling `psi4.core.Wavefunction.build` would have to manually set the DF basis to zero.
`psi4.core.Wavefunction.build` now automatically sets the DF basis to zero - one less upgrade problem for users to worry about.
=> wavefunction.build auto-zeros DF basis

psi4/src/psi4/libmints/dimension.h
`Slice` class is used in Forte. However, recent modifications blinds `Slice` from plugins.
This PR expose `Slice` class as `PSI_API` to be called in plugins.
=> Expose class Slice as PSI_API.

psi4/src/core.cc, tests/pytest/test_addons.py
So `psi4.clean_options()` is a mainstay of psiapi mode because it allows you to do two calculations after another both starting from a clean slate of options. Likewise, it is important for testing b/c we do one behind the scenes (in pytest) between each test so that your MP2 doesn't get PCM solvation, etc. For plugins, this has been broken since the `clean_options()` command was invented, in that as soon as you tried to set an option unique to the plugin (as opposed to one that another module in read_options.cc defined) _after_ a options cleanse, it would complain about an invalid option. This PR reloads the plugin options after a cleanse.
=> fix local options for plugins

psi4/__init__.py, psi4/psi4Config.cmake.in, psi4/src/psi4/libciomr/block_matrix.cc, psi4/src/psi4/libciomr/int_array.cc
=> fix PSI_API in libciomr

external/upstream/gau2grid/CMakeLists.txt, psi4/CMakeLists.txt
gau2grid now provides spherical basis sets in `gaussian` _or_ `cca` ordering. let's make sure we get the right one!
~**This won't work until a PR comes into g2g and versions/git tags get bumped here.**~
=> gau2grid: ensure we get the right bf ordering

psi4/src/psi4/fisapt/fisapt.cc
Adds hierarchical timers to FISAPT for code profiling purposes.  Timing info for various F-SAPT terms and HF embedding printed to `timer.dat`.
=> ENH: Adds timers to FISAPT

psi4/src/psi4/fnocc/blas.cc
This change allows F_DGEMV to be called (when using plugins, for example) without modifying the source code in fnocc/blas.cc and recompiling Psi4.
=> Adds PSI_API tag before the definition of F_DGEMV in ../fnocc/blas.cc

psi4/src/psi4/libciomr/eigsort.cc
PSI_API for eigsort function in libciomr.
Nothing notable... just fixes missing symbol in one of my plugins.
=> PSI_API for eigsort function in libciomr

CMakeLists.txt, doc/sphinxman/source/freq.rst, doc/sphinxman/source/thermo.rst, external/common/lapack/CMakeLists.txt, external/common/lapack/FindMathOpenMP.cmake, external/common/lapack/FindTargetOpenMP.cmake, external/common/lapack/TargetLAPACKConfig.cmake.in, external/downstream/gpu_dfcc/CMakeLists.txt, external/downstream/v2rdm_casscf/CMakeLists.txt, external/upstream/chemps2/CMakeLists.txt, external/upstream/libefp/CMakeLists.txt, psi4/CMakeLists.txt, psi4/driver/procrouting/proc.py, psi4/share/psi4/scripts/test_threading.py, psi4/src/CMakeLists.txt, psi4/src/psi4/ambit_interface/convert.cc, psi4/src/psi4/ambit_interface/integrals.cc, psi4/src/read_options.cc, tests/cc-module/CMakeLists.txt
Fixes up the OpenMP problems. This still needs some tidying, but you can start to take a look.
=> OpenMP, take 2

psi4/src/psi4/psimrcc/main.cc, psi4/src/psi4/psimrcc/mrccsd_t_compute.cc, psi4/src/psi4/psimrcc/mrccsd_t_compute_restricted.cc, psi4/src/psi4/psimrcc/mrccsd_t_compute_spin_adapted.cc, psi4/src/psi4/psimrcc/mrccsd_t_heff.cc, psi4/src/psi4/psimrcc/mrccsd_t_heff_a.cc, psi4/src/psi4/psimrcc/mrccsd_t_heff_a_restricted.cc, psi4/src/psi4/psimrcc/mrccsd_t_heff_ab.cc, psi4/src/psi4/psimrcc/mrccsd_t_heff_ab_restricted.cc, psi4/src/psi4/psimrcc/mrccsd_t_heff_b.cc, psi4/src/psi4/psimrcc/mrccsd_t_heff_b_restricted.cc, psi4/src/psi4/psimrcc/mrccsd_t_heff_restricted.cc, psi4/src/psi4/psimrcc/mrccsd_t_setup.cc, psi4/src/psi4/psimrcc/special_matrices.cc, psi4/src/psi4/psimrcc/updater_mk.cc
This is part of *Psi4* porting to *Windows* (https://github.com/psi4/psi4/issues/933).
=> Port psimrcc to Windows

psi4/src/psi4/scfgrad/jk_grad.cc, tests/CMakeLists.txt, tests/dft-grad-disk/CMakeLists.txt, tests/dft-grad-disk/input.dat, tests/dft-grad-disk/output.ref
Fixes a bug in the DFJK gradient algorithm when using disk paging. On top of drawing similarities to Python and C++ one should be very aware of their differences as well. Bit me here.
Fixes #1094 and Fixes #1095.
As a note it is not possible to ensure that the provided test continues to check the paging algorithms as circumstance may change. Is there a good way to encode this thought into the test?
Something to back port quickly.
=> JK_Grad: Fix for disk paging after wK rewrite

.travis.yml
I don't want to fix py27 bug in #1098, so this evades testing it.
=> CI: stop testing py27. insufficient conda pkgs to add py37

psi4/src/psi4/libciomr/block_matrix.cc, psi4/src/psi4/libciomr/init_array.cc, psi4/src/psi4/libciomr/init_matrix.cc, psi4/src/psi4/libciomr/int_array.cc, psi4/src/psi4/libciomr/libciomr.h, psi4/src/psi4/libciomr/long_int_array.cc, psi4/src/psi4/libciomr/tstart.cc, psi4/src/psi4/libciomr/zero.cc
This is part of Psi4 porting to Windows (#933).
=> Port libciomr to Windows

psi4/src/psi4/lib3index/dfhelper.cc
=> dfh: fix direct_iaq memory estimate in AO_core module

psi4/src/psi4/lib3index/dfhelper.cc
Now
```
==> Integral Setup <==
DFHelper Memory: AOs need 0.001 [GiB]; got 0.419 [GiB] so using in-core AOs.
==> MemDFJK: Density-Fitted J/K Matrices <==
```
=> DFH: condense memory printing and straighten out casts

psi4/src/psi4/lib3index/dfhelper.cc, psi4/src/psi4/lib3index/dfhelper.h, psi4/src/psi4/libfock/jk.h, psi4/src/psi4/libscf_solver/sad.cc
How many PRs does it take to correctly and conveniently print JK memory? This is the fourth.
=> DFH: suppress DFH memory messages during SAD guess

psi4/src/export_mints.cc, psi4/src/psi4/libcubeprop/csg.cc, psi4/src/psi4/libmints/basisset.cc, psi4/src/psi4/optking/geom_gradients_io.cc, tests/dfmp2-ecp/input.dat
Fix for #1102. We were subtracting ECP's, as (Z + ECP) was > 0 (usually around 10), even when the atom was ghosted (Z == 0).
=> Do not freeze electrons on ghost atoms.

psi4/src/psi4/libmints/coordentry.h, psi4/src/psi4/libmints/molecule.cc, tests/dfmp2-freq1/CMakeLists.txt, tests/dfmp2-freq1/input.dat, tests/dfmp2-freq2/CMakeLists.txt, tests/dfmp2-freq2/input.dat
Fixes issue #1093, where the use of density fitting caused a crash when computing frequencies.
As for why these fixes are necessary:
Previously, the clone function would have separate memory addresses for elements of the two lists, which would be fixed by update_geometry assuming that coordinate reinterpretation was allowed. This is precisely what the driver does not allow when getting a findif hessian. The basis set setting code assumed that the memory addresses were the same. This assumption failing led to the originally reported error with setting basis sets. As this seems a rather sane assumption to me, it is Now enforced.
This uncovered a second error when ZMAT coordinates were used: energies at displacements would be off by ~4 hartrees. When the molecule is cloned in the process of …
=> Make Density Fitting Compatible with Frequencies (#1093 Fix)

psi4/src/export_wavefunction.cc
Exposition of the function Fa_subset and Fb_subset to python
There really are not todos here. Beforehand it was quite cumbersome to get the F matrix in AO form. 
No tests were added.
ctest -L quick runs through
=> Exposing Fa_subset and Fb_subset functions to python

psi4/src/psi4/libfock/PK_workers.h
Eliminates a compilation warning due to the way the copy constructor and = operator were disabled in the PKWorker class.
=> Remove warning due to PKWorker class

psi4/src/psi4/libmints/oeprop.cc
set_Ca treats Cb_so_ incorrectly in the same orbs case.
I did not trigger the bug actively, but it looks like a clear bug to me. The bug won't have triggered in any meaningful code, because every algorithm queries same orbs and therefore only uses Ca_so_ if(same_orbs). However it should be fixed regardless.
Please review carefully.
ctest -L quick ran through without errors.
=> Fix assignment bug in Prop::set_Ca.

psi4/src/psi4/libmints/multipolesymmetry.h
Add PSI_API to libmints/multipolesymmetry.h, so that it can support a version of v2rdm_casscf plugin.
=> add PSI_API to class OperatorSymmetry

psi4/driver/procrouting/proc.py
There was a bug (see conversation between myself and Andy Simmonett in Slack channel earlier today) where if you attempted to use orbital casting on a frequency computation with symmetry, the first symmetry-breaking displacement would succeed at the small basis computation but crash at the large basis computation, saying that it couldn't cast orbitals between symmetries.
The code was previously set so that GUESS would be set to READ. This would cause Psi to attempt to read the last saved orbitals. As [the casting mechanism has nothing to do with reading](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L1336-L1341), the last saved orbitals weren't the orbitals from the small basis computation, but the orbitals from the last geometry, which may well be of the wrong …
=> Fix Casting Incompatibility with Multiple Geometries

psi4/src/export_oeprop.cc, psi4/src/psi4/libmints/oeprop.cc, psi4/src/psi4/libmints/oeprop.h
This pull request adresses https://github.com/psi4/psi4/issues/1116 :
1.) Split Prop into 
- - Prop: All One Electron convenience accessors and setters and getters, but no access to globals at all. Prop is now only a convenience class, which sets up a few nice accessors.
- - TaskListComputer: This class handles all the compute baseclass elements of Prop, adding, removing tasks from a task queue and computing them. It's very low complexity.
This was done to allow Prop to be easily inheritable without having to implement all the Taskqueue things, which honestly did not have a lot do with Prop itself. This commit makes using Prop inside the code a ton easier.
This was done in commit 
528c0d7 : https://github.com/psi4/psi4/commit/528c0d719e8bb49b12652417b00db506241a4bee
2.) Split OEProp in …
=> Split of Prop and OEProp to allow I/O less computation of Properties without globals.

psi4/src/psi4/fisapt/fisapt.cc, psi4/src/psi4/fisapt/fisapt.h
Removes initialization of DFHelper object in fexch and find by having a dfh object as member data.
=> Remove initialization of DFHelper object in fisapt fexch and find.

psi4/src/psi4/libmints/chartab.cc
=> Fix psi::CharacterTable assignment operator to copy bits_

psi4/CMakeLists.txt, psi4/src/CMakeLists.txt
=> Improve build configuration for MSVC

psi4/src/psi4/dfocc/effective_mograd.cc
Noticed #893 marked fixed. It is, but only in unrelated #824. Fixing it separately.
=> fixes #893 (2-electron system crash) outside other PR

appveyor.yml
This is part of Psi4 porting to Windows (#933).
=> Add Appveyor configuration to compile and tests on Windows

psi4/driver/p4util/exceptions.py, psi4/driver/procrouting/scf_proc/scf_iterator.py, tests/scf2/input.dat
SCF: Add SCFConvergence Error such that the error will have the wavefunction as a member.
=> SCF: Add SCFConvergence Error 

psi4/driver/procrouting/proc.py
Since we [say we're returning the dimer wfn](https://github.com/psi4/psi4/blob/master/psi4/driver/driver.py#L505-L507), let's return the dimer wfn for fisapt. currently returning a `psi4.core.FISAPT` object that does not inherit from Wfn. Hence no way to drive OEPROP on a sapt calc.
=> return wfn after FISAPT

appveyor.yml, psi4/src/psi4/detci/civect.cc
=> Fix undefine variable in psi::CIvect::dcalc2

psi4/src/psi4/detci/ints.cc, psi4/src/psi4/libfunctional/superfunctional.cc, psi4/src/psi4/scfgrad/jk_grad.cc
MSVC supports only OpenMP 2.0, but *Psi4* needs higher at some parts.
=> Fix OpenMP for Windows in detci, libfunctional, and scfgrad

psi4/src/psi4/dfocc/ccd_iterations.cc, psi4/src/psi4/dfocc/ccd_iterations_low.cc, psi4/src/psi4/dfocc/ccdl_iterations.cc, psi4/src/psi4/dfocc/ccsd_iterations.cc, psi4/src/psi4/dfocc/ccsd_iterations_low.cc, psi4/src/psi4/dfocc/ccsdl_iterations.cc, psi4/src/psi4/dfocc/lccd_iterations.cc
The formatting of the iteration tables was off when dE > 0.
=> DF-CCSD iterations print aligned

psi4/include/psi4/pragma.h, psi4/include/psi4/psi4-dec.h, psi4/include/psi4/psifiles.h, psi4/include/psi4/pybind11.h, psi4/include/psi4/times.h
Hand- and clang-format psi4/include except for `masses.h` and `physconst.h`. Those two files are handled in #1213.
replaces #1193 
part of #1144
=> fmt: clang-format the code in psi4/include (take 2)

appveyor.yml
Appveyor is falling, because the new version (2019.0) of MKL is not detected.
=> Fix MKL on Windows

.travis.yml
Switches off Py35 Travis until the fail on PyTest exit bug can be tracked down. This bug does not appear to affect areas besides Travis as far as we know.
=> CI Stability

psi4/src/psi4/dfocc/ccsd_triples.cc
Enhances user experience for DF-CCSD(T) gradients.
=> adding triples gradient timings

psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/mintshelper.cc
MSVC supports only OpenMP 2.0, but *Psi4* needs higher at some part
=> Fix OpenMP for Windows in libmints

psi4/src/psi4/dcft/dcft_density_UHF.cc
MSVC supports only OpenMP 2.0, but *Psi4* needs higher at some parts.
=> Fix OpenMP for Windows in dcft

psi4/src/psi4/detci/opdm.cc, psi4/src/psi4/detci/tpdm.cc
=>  Fix memory error in psi::detci::CIWavefunction

psi4/src/psi4/ccenergy/ccenergy.cc, psi4/src/psi4/cclambda/L2.cc, psi4/src/psi4/cclambda/cache.cc, psi4/src/psi4/cclambda/cc2_L2.cc, psi4/src/psi4/cclambda/cclambda.cc, psi4/src/psi4/cclambda/cclambda.h, psi4/src/psi4/cclambda/converged.cc, psi4/src/psi4/cclambda/denom.cc, psi4/src/psi4/cclambda/diis.cc, psi4/src/psi4/cclambda/get_moinfo.cc, psi4/src/psi4/cclambda/get_params.cc, psi4/src/psi4/cclambda/init_amps.cc, psi4/src/psi4/cclambda/local.cc, psi4/src/psi4/cclambda/sort_amps.cc, psi4/src/psi4/cclambda/status.cc, psi4/src/psi4/cclambda/update.cc
Inherit CCLambdaWavefunction from CCEnergyWavefunction and further
build a class around CCLambdaWavefunction.
This PR just contains the inheritance of the CCLambdaWavefunction from the CCEnergyWavefunction, but no other functional changes or features.
The main motivation for this was so that this can be merged before the clang-format of the cclambda module in #1206 that seems to be happening before #1061. It would be nice to have these changes in before the formatting.
=> ENH: CCLambdaWfn inherits from CCEnergyWfn

appveyor.yml
*Appveyor* is switching to Python 3.7 by default, but some package are not yet ready. So stay with Python 3.6 for a while.
=> Use Python 3.6 for Windows builds

psi4/driver/driver.py, tests/opt-full-hess-every/CMakeLists.txt, tests/opt-full-hess-every/input.dat
Fixes and closes #1298. `full_hess_every` now takes hessians at the latest geometry rather than the reference geometry.
Because this bug was not caught by the test suite, I've added a test to catch this bug, and it clocks in at just over 6 seconds on my Mac.
=> Fix #1298, full_hess_every taking hessians at the starting geometry.

psi4/src/core.cc
fixes #1284 by forcing flush in `core.print_out`. Similar to what is done in `PsiOutStream.cc` is already.
Perhaps @PeterKraus can test it, as he was the only one confirming the issue.
=> Fix proposal for issue 1284 (SCF printing)

psi4/run_psi4.py
There is no `rreplace` function which would be handy, so split on the first match from the end, and join on the replacement. does the job. 
fixes #1286
=> Replace only the last match when generating outfile name from infile. 

psi4/src/psi4/dcft/dcft_memory.cc
DCT files were not correctly being cleared upon completion. Among other things, the tau matrix was not properly cleared, which led to energy denominator computations for the MP2 guess incorporating the tau matrix when a DC-12 variant was selected. The MP2 guess was not correct.
Requesting the attention of @andysim on this.
=> Fixes #1309, clears DCT files correctly.

psi4/src/psi4/detci/ciwave.cc, psi4/src/psi4/detci/ciwave.h, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmints/wavefunction.h
Adds a constructor to `Wavefunction` taking a reference wavefunction as argument. The body of the CTOR performs:
```
shallow_copy(reference_wavefunction);
set_reference_wavefunction(reference_wavefunction);
```
which seemed to be otherwise copy-pasted in correlated wavefunction CTORs.
=> Wavefunction constructor from reference

doc/sphinxman/source/cbs.rst, psi4/driver/driver.py, psi4/driver/driver_cbs.py, tests/CMakeLists.txt, tests/cbs-xtpl-dict/CMakeLists.txt, tests/cbs-xtpl-dict/input.dat, tests/cbs-xtpl-dict/output.ref, tests/cbs-xtpl-freq/input.dat, tests/cbs-xtpl-freq/output.ref
The general idea is to allow more flexible definition of CBS functions, and clean up the `cbs()` function a little. The goal is to allow further corrections to the energy into CBS, eg differences of basis sets (eg. `\Delta E_{diff} = E(aug-cc-pvtz) - E(cc-pvtz)`) or frozen core corrections (`\Delta E_{ae} = E(freeze_core True) - E(freeze_core False)` or DKH ...
Added `frequency` to cbs-compatible calls.
=> Rework of CBS to use dictionaries

psi4/src/psi4/dcft/dcft_scf_RHF.cc, psi4/src/psi4/dcft/dcft_scf_UHF.cc, psi4/src/psi4/dcft/dcft_sort_mo_tpdm.cc, psi4/src/psi4/detci/mitrush_iter.cc, psi4/src/psi4/fnocc/frozen_natural_orbitals.cc, psi4/src/psi4/libfock/DiskJK.cc, psi4/src/psi4/libmints/basisset.cc, psi4/src/psi4/libmints/petitelist.cc, psi4/src/psi4/libqt/pople.cc, psi4/src/psi4/libsapt_solver/sapt.cc, psi4/src/psi4/libtrans/integraltransform_functors.h, psi4/src/psi4/libtrans/integraltransform_moinfo.cc, psi4/src/psi4/libtrans/integraltransform_oei.cc, psi4/src/psi4/libtrans/integraltransform_sort_mo_tpdm.cc, psi4/src/psi4/libtrans/integraltransform_tei_2nd_half.cc, psi4/src/psi4/mcscf/scf_read_so_tei.cc, psi4/src/psi4/occ/trans_ints_rhf.cc, psi4/src/psi4/occ/trans_ints_rmp2.cc, psi4/src/psi4/occ/trans_ints_uhf.cc, psi4/src/psi4/occ/trans_ints_ump2.cc, psi4/src/psi4/optking/IRC_data.h, psi4/src/psi4/optking/frag_disp.cc, psi4/src/psi4/optking/interfrag_orient.cc, psi4/src/psi4/optking/lindh_guess.cc, psi4/src/psi4/optking/linear_algebra.cc, psi4/src/psi4/optking/molecule.cc, psi4/src/psi4/optking/molecule_irc_step.cc, psi4/src/psi4/optking/molecule_nr_step.cc, psi4/src/psi4/optking/molecule_prfo_step.cc, psi4/src/psi4/optking/opt_data.cc
Uses `clang-tidy` to find and fix uses of `0`/`1` instead of `false`/`true`. Fixes applied with:
```
cd <build-dir>/psi4-core-prefix/src/psi4-core-build
run-clang-tidy.py -header-filter='.*' -checks='-*,modernize-use-bool-literals' -fix
```
Based on #1312 
=> clang-tidy apply modernize-use-bool-literals fixes

appveyor.yml, external/upstream/qcelemental/CMakeLists.txt, psi4/driver/driver.py, psi4/driver/driver_findif.py, psi4/driver/procrouting/empirical_dispersion.py, psi4/driver/procrouting/proc.py, psi4/driver/qcdb/molecule.py, psi4/driver/qcdb/psiutil.py, psi4/src/export_psio.cc, tests/CMakeLists.txt, tests/cookbook/manual-fd-hess-energy/input.dat, tests/cookbook/manual-fd-hess-grad/input.dat, tests/cookbook/manual-sow-reap/input.dat, tests/cookbook/manual-sow-reap/run-psi4-disps.csh, tests/cubeprop-esp/input.dat, tests/cubeprop-frontier/input.dat, tests/cubeprop/input.dat, tests/fd-freq-energy-large/input.dat, tests/fd-freq-gradient-large/input.dat, tests/json/schema-1-properties/input.py, tests/opt-full-hess-every/CMakeLists.txt, tests/x2c1/input.dat
Change of FINDIF to be metadata based per #1148, task one, and qcdb molecule compatibility per #1148, task two.
=> Findif Metadata

psi4/driver/p4util/python_helpers.py, psi4/driver/qcdb/libmintscoordentry.py, psi4/driver/qcdb/libmintsmolecule.py, psi4/driver/qcdb/psiutil.py
This is a trivial change that replaces `==` operator with `is` operator, following PEP 8 guideline:
> Comparisons to singletons like None should always be done with is or is not, never the equality operators.
https://legacy.python.org/dev/peps/pep-0008/#programming-recommendations
=> Compare to `None` using identity `is` operator

psi4/driver/driver.py, psi4/driver/qcdb/interface_gcp.py
Make tests run reliably and a bit cleaner.
=> extra findif freq file clean

psi4/src/psi4/libmints/matrix.h, psi4/src/psi4/libpsi4util/exception.cc, psi4/src/psi4/libpsi4util/exception.h
Uses `clang-tidy` to find and fix instances where `noexcept` can be used instead of `throw()`. Fixes applied with:
```
cd <build-dir>/psi4-core-prefix/src/psi4-core-build
run-clang-tidy.py -header-filter='.*' -checks='-*,modernize-use-noexcept' -fix
```
Based on #1312 
=> clang-tidy apply modernize-use-noexcept fixes

psi4/include/psi4/pragma.h, psi4/src/psi4/libqt/CMakeLists.txt, psi4/src/psi4/libqt/lapack_intfc.cc, psi4/src/psi4/libqt/lapack_intfc_mangle.h, psi4/src/psi4/libqt/qt.h
Fixes #1290 by wrapping calls to deprecated (and removed in Netlib's LAPACK 3.8.0) with appropriate replacements.
**UPDATE**
I have added a `PSI_DEPRECATED` macro in `pragma.h` to be used to deprecate functions, classes, variables. It will emit a warning at compile-time.
None of these subroutines were used in Psi4, so I only ran smoketests locally.
=> Replace calls to deprecated LAPACK subroutines

psi4/src/psi4/dcft/dcft_gradient_UHF.cc, psi4/src/psi4/dcft/dcft_integrals_UHF.cc, psi4/src/psi4/dcft/dcft_qc.cc
Fixes #1288. The trouble was that Bozkaya's code used libtrans to transform integrals, and those were written to disk in their antisymmetrized, redundancy-free form, as libtrans does. The DCT code gets different integrals from libtrans but then sorts those to get the same blocks as Bozkaya wrote earlier in the redundant form. Because the DCT-sorted integral block had antisymmetry redundancies, it was larger than the libtrans block that did not have those redundancies.
Fixed by changing the code to use a block without those redundancies.
I imagine this is of interest to @amjames and @ssh2.
=> Fix 1288: ODC Compatible with Other OO Code

psi4/driver/procrouting/scf_proc/scf_iterator.py
Raise the error that we can't do stability analysis on DFT "wavefunctions" before we bother to compute the (potentially very expensive) integrals necessary for this. The same error message is getting raised C-side under the same condition. This commit just raises it sooner, because spending the better part of an an hour computing integrals for no reason is annoying.
=> Raise no-stability-check error early

psi4/driver/p4util/python_helpers.py, psi4/driver/p4util/util.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmints/wavefunction.h, tests/CMakeLists.txt, tests/serial-wfn/CMakeLists.txt, tests/serial-wfn/input.dat
This is a first pass at implementing serialization of the Wavefunction object as suggested by @dgasmith in #887 . This functionality allows a wavefunction to be read to or written from a file:
closes #887 
```
e, wfn_old = energy('mp2', return_wfn=True)
Wavefunction.to_file(wfn_old, filename)
wfn_new = Wavefunction.from_file(filename)
```
The wavefunction can also be stored directly in memory as a python dictionary:
```
wfn_dict = Wavefunction.to_file(wfn_old)
wfn_new = Wavefunction.from_file(wfn_dict)
```
In this code snippet, `wfn_new` and `wfn_old` should be identical (by value, not reference). A test case was added that corresponds to this example.
=> Serialize Wavefunction 

psi4/src/export_functional.cc
Add the C++ default to `PointFunctions::compute_points` so I don't have to try/except psi4numpy
=> default compute_points

psi4/src/psi4/libqt/CMakeLists.txt
Wraps new lapack function tests in a Fortran_ENABLED block; and resolves OpenMP linking issues.
Ultimately, we'd want to change the detection from a Fortran function to a C function.
=> Resolves configure issue in libqt wrt lapack

psi4/src/psi4/libdpd/split.cc
Allow psi4 to be compiled with C++17. Default compilation still uses C++11.
=> Make psi4 compatible with C++17

psi4/src/core.cc
Fixes a bug where the following input file crashes:
```
molecule {
O
H 1 1 
H 1 1 2 104.5
}
set basis sto-3g
set scf {
damping_percentage 20
}
energy('scf')
```
`damping_percentage` is defined as a _double_. Before this commit, Psi would naively set the relevant keyword to be the int the user gave it and then complain when it tried to read options later. It now knows to cast to double.
=> Fix bug with setting double options to integers

psi4/src/core.cc, psi4/src/create_new_plugin.cc, psi4/src/export_blas_lapack.cc, psi4/src/export_cubeprop.cc, psi4/src/export_diis.cc, psi4/src/export_fock.cc, psi4/src/export_functional.cc, psi4/src/export_mints.cc, psi4/src/export_options.cc, psi4/src/export_plugins.cc, psi4/src/export_psio.cc, psi4/src/export_wavefunction.cc, psi4/src/read_options.cc
clang-format the code in psi4/src
N.B. Pay particular attention to `read_options.cc`, which I formatted manually to preserve docstring formatting.
=> fmt: clang-format the code in psi4/src

psi4/run_psi4.py
=> Make failing "psi4 --test" to return non-zero status

azure-pipelines.yml
This is intended as a replacement for *Appveyor*, which has 60 min limit. *Azure* allow to run up to 360 min!
=> CI for Windows on Azure

cmake/psi4OptionsTools.cmake
During the CMake cleanup the LAPACK target was removed from the bin/lib modules. This resulted in OpenMP flags not being passed to the compiler.  This PR adds the library target back.
=> Adds back LAPACK target to bin/lib modules

psi4/driver/driver_cbs.py
Fixes an error involving a FNO-(T) delta correction for CBS as in `energy('fno-ccsd/cc-pVDZ+D:fno-ccsd(t)/cc-pVDZ'`
=> fixes incorrect CBS delta correction for fno-ccsd

psi4/driver/procrouting/scf_proc/scf_iterator.py
Fixes a bug that prohibits computing stability analysis for wfns with an X2C Hamiltonian.
Previously the relativistic basis was not set which made mints unhappy.
=> makes relativistic basis visible for SO integrals

psi4/src/psi4/dcft/dcft_density_UHF.cc
As discussed in https://github.com/psi4/psi4/issues/933#issuecomment-423183802, *clang-cl* supports *OpenMP* 4.0, so the adaptation to *OpenMP* 2.0 is not necessary.
=> Revert "Fix OpenMP for Windows in dcft"

psi4/src/psi4/dfocc/ccsd_triples.cc, psi4/src/psi4/dfocc/ccsdl_iterations.cc, psi4/src/psi4/dfocc/get_moinfo.cc, psi4/src/psi4/dmrg/dmrgscf.cc
Part of #1144. DFOCC was already formatted in #797, so there's very few changes. DMRG we want to avoid formatting so can easily diff with the plugin in the CheMPS2 repo.
=> mild clang-format for dfocc and dmrg

psi4/CMakeLists.txt, psi4/src/export_mints.cc, psi4/src/psi4/libmints/matrix.cc, tests/pytest/test_matrix.py
The support for matrices with `symmetry() != 0` is flawed in several places in the matrix class. While *some* operations are only valid if the matrix is totally symmetric, most do not have this requirement. 
These issues have long gone unnoticed because the majority of places where the object is used the quantity will be totally symmetric. I started noticing these flaws while working on TDDFT which will require most of the changes made here in order to work properly.
- Comments/error messages/variables names have been updated to make meaning more precise.
- In general the non-zero block of the matrix found at `matrix_[h]` has shape `{rowspi_[h], colspi_[h^symmetry_]}` **not** `{rowspi_[h], colspi_[h]}`. The two are coincidentally the same when `symmetry_ == 0` (This was the cause of many …
=> Libmints Matrix: Symmetry Cleanup

psi4/src/core.cc
Small bug fix that prevents adding local options to a module. This error shows only for `string` and `int` type options, but I potentially also in `array` and `python` data types. This PR addresses all four cases.
- In the following part of the code one can potentially encounter the same problem. This can be fixed by adding `module` to the list of parameters passed to this function. Any reason why there is no `std::string module` in the parameter list? Adding it would also make this function consistent with other `set_local_x` functions.
https://github.com/psi4/psi4/blob/396b4c51d6902301baeed41386c49ccb9099a30b/psi4/src/core.cc#L705-L707
=> Fix bug that prevents setting a local string/int option from the py-side if module != current_module

psi4/src/psi4/libmints/ecpint.h, psi4/src/psi4/libmints/potentialint.h
I found a few classes that shouldn't be exported.  From ecpint.h, `AngularIntegral` and `RadialIntegral` are only used internally and are implementation dependent.  In potentialint.h, the functors reside fully in the header and thus don't need to be "exported".
=> Remove a few libmints exports

psi4/src/psi4/libmints/integral.cc, tests/opt-full-hess-every/CMakeLists.txt
The default `MAX_AM_ERI` isn't high enough to perform this test.  Add it only when it is configured high enough.
=> Add opt-full-hess-every test only when MAX_AM_ERI is high enough

psi4/src/psi4/libpsio/filemanager.cc
Make *Psi4* to work without setting `PSI_SCRATCH`.
=> Improve the default path on Winodws

psi4/driver/procrouting/dft/libxc_functionals.py
So the reason there haven't been conda packages for a while is `dft1-alt` is non-deterministically broken on py35. Further investigation shows that the `energy('b97-d')` call was sometimes Grimme GGA for XC and sometimes Becke hybrid but always Grimme dispersion (unordered dicts, remember). Probably introduced by #1151 when I stopped listing `b97-d` as an XC of its own and special casing the processing. The proposed sol'n -- conceding "B97" to Grimme and calling the original hyb "B97-0" -- isn't great or historically sound. But I think it's workable.
=> dft: "B97" conceded to Grimme

CMakeLists.txt, doc/sphinxman/source/add_tests.rst, doc/sphinxman/source/build_planning.rst, psi4/driver/p4util/procutil.py, psi4/src/core.cc
add function to reset options state from dictionary
```
all_options = p4util.prepare_options_for_modules(changedOnly=True, commandsInsteadDict=False)
optking_json_dict = optking.run_json_dict(optking_schema)
p4util.reset_pe_options(all_options)
```
=> reset options state from dictionary

psi4/driver/wrapper_database.py, tests/psithon2/input.dat
This is part of Psi4 porting to Windows (#933).
`psithon2` test fails on Windows:
```
2018-12-05T15:52:01.1057243Z 8/9 Test #307: psithon2 .........................***Failed   24.86 sec
2018-12-05T15:52:01.1057730Z 	Built-in energy...................................................PASSED
2018-12-05T15:52:01.1059103Z 	PSIPATH database..................................................PASSED
2018-12-05T15:52:01.1059291Z 	Built-in database.................................................PASSED
2018-12-05T15:52:01.1059763Z 	PSIPATH plugin....................................................PASSED
2018-12-05T15:52:01.1059834Z 
2018-12-05T15:52:01.1060236Z QcdbException BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 1 for key BASIS among:
2018-12-05T15:52:01.1060376Z …
```
=> Fix path handling and psithon2 test on Windows

.scripts/miniconda.sh
As the title says: calls to `conda config` are not saved in the cache.
It works!
=> Travis: conda config settings are not saved in cache

psi4/src/psi4/libplugin/load_plugin.cc
This fixes a bug in the load_plugin function that incorrectly converted `_` to `-` instead of the opposite.
=> Fix a bug in load_plugin

psi4/src/psi4/libmoinfo/moinfo.cc
The problem was already reported in #1255
=> Fix a memory error in psi::MOInfo::read_mo_spaces

psi4/src/psi4/dcft/dcft_oo_RHF.cc, psi4/src/psi4/dcft/dcft_oo_UHF.cc
Does exactly what it says in the title. We need the maximum value of `maxGradient` _across all threads_.
=> Fix race condition in maximum orbital gradient of parallel ODCT.

tests/pytest/test_dft_benchmarks.py
Continuing #1403. Since we want to check Becke fctl here, better call it B97-0 since surrendered B97 to Grimme.
=> "B97" conceded to Grimme: the cleanup

psi4/src/psi4/cc/cctriples/ET_RHF.cc, psi4/src/psi4/cc/cctriples/EaT_RHF.cc
`EaT_RHF.cc` and `ET_RHF.cc` contain incompatible declarations of `psi::cctriples::thread_data`.
During compilation, templates (i.e. `std::vector<psi::cctriples::thread_data>`) are generated once and reused, while memory access  instructions to `psi::cctriples::thread_data` are generate at each translation unit.
That results into an overflow:
```
==29447==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60800007a380 at pc 0x7fa994502627 bp 0x7fffc3cb6560 sp 0x7fffc3cb6558
WRITE of size 4 at 0x60800007a380 thread T0
#0 0x7fa994502626 in psi::cctriples::EaT_RHF() /home/raimis/prj/psi4.git/psi4/src/psi4/cc/cctriples/EaT_RHF.cc:206
#1 0x7fa993ee2cec in psi::cctriples::cctriples(std::shared_ptr<psi::Wavefunction>, psi::Options&) …
```
=> Fix multiple declaration of psi::cctriples::thread_data

psi4/driver/driver.py, psi4/src/export_mints.cc, psi4/src/psi4/libmints/molecule.cc, tests/fd-freq-energy/input.dat
Fixes #1052 at long, long last: when the user explicitly declares a symmetry, findif is now smart enough to put displacements in the proper subgroup.
As part of the fix, control over molecule cloning for finite difference has passed to `_process_displacement`. It seemed easier (and more appropriate) than adding code to make a new clone in each for loop. The clone would be necessary so that each displacement can have its own symmetry.
Since I was touching that part of the code anyways, I have reorganized so that the reference is guaranteed to be the first displacement. This has the advantage that if orbital reading is enabled, the following displacements will be able to read from the reference, as intended.
=> Symmetry-Breaking Findif, and Reference First

psi4/driver/procrouting/dft/dft_builder.py, psi4/driver/procrouting/dft/dh_functionals.py, psi4/driver/procrouting/dft/gga_functionals.py, psi4/driver/procrouting/dft/hyb_functionals.py, psi4/driver/procrouting/dft/mgga_functionals.py
Resolves #1404. This makes `dsd-blyp-d3(bj)` pull data from `dsd-blyp-d3bj`, as opposed to `dsd-blyp` + `dashparam["d3bj"]["dsd-blyp"]`. Currently affected functionals are:
```
created b97-0-d2 from b97-d2
created b97-0-d from b97-d2
created b97-d from b97-d2
created b97-0-d3bj from b97-d3bj
created b97-0-d3(bj) from b97-d3bj
created b97-d3(bj) from b97-d3bj
created b97-0-d3mbj from b97-d3mbj
created b97-0-d3m(bj) from b97-d3mbj
created b97-d3m(bj) from b97-d3mbj
created dsd-blyp-d from dsd-blyp-d2
created dsd-blyp-d3(bj) from dsd-blyp-d3bj
created dsdpbep86-d2 from dsd-pbep86-d2
created dsdpbep86-d from dsd-pbep86-d2
created dsd-pbep86-d from dsd-pbep86-d2
created dsdpbep86-d3bj from dsd-pbep86-d3bj
created dsdpbep86-d3(bj) from dsd-pbep86-d3bj
created dsd-pbep86-d3(bj) from …
```
=> Check for explicitly defined dispersion corrections first.

psi4/include/psi4/pragma.h, psi4/src/core.cc, psi4/src/export_benchmarks.cc, psi4/src/export_blas_lapack.cc, psi4/src/export_cubeprop.cc, psi4/src/export_diis.cc, psi4/src/export_fock.cc, psi4/src/export_functional.cc, psi4/src/export_mints.cc, psi4/src/export_misc.cc, psi4/src/export_oeprop.cc, psi4/src/export_pcm.cc, psi4/src/export_psio.cc, psi4/src/export_trans.cc, psi4/src/export_wavefunction.cc, psi4/src/psi4/libmints/vector.h, psi4/src/read_options.cc
Switches to use `_a` rather than more verbose `py::arg`. Separated from #1443, as requested.
=> Use literals for arguments in pybind11 bindings

psi4/driver/driver_cbs.py
=> Fix a filesystem error in psi.driver.cbs

psi4/src/export_mints.cc
`overload_cast` from #1448 does not play nicely with Intel compilers and pybind11 https://github.com/pybind/pybind11/issues/1649. This reverts just enough of #1448 to build again.
=> avoid overload_cast

psi4/src/psi4/libscf_solver/sad.cc
The SAD fractional density matrix didn't actually use fractional densities. This is fixed in the present PR.
=> Fix formation of SAD fractional density matrix

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/libscf_solver/cuhf.cc, psi4/src/psi4/libscf_solver/cuhf.h, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/psi4/libscf_solver/hf.h, psi4/src/psi4/libscf_solver/rohf.cc, psi4/src/psi4/libscf_solver/rohf.h, psi4/src/psi4/libscf_solver/uhf.cc, psi4/src/psi4/libscf_solver/uhf.h, tests/CMakeLists.txt, tests/gibbs/input.dat, tests/mp2-module/input.dat, tests/scf-guess/CMakeLists.txt, tests/scf-guess/input.dat, tests/scf-guess/output.ref
This PR modifies the SAD guess so that it first runs a plain Fock build and diagonalizes the obtained Fock matrix. This allows the SAD guess to also work for ROHF, as well as allowing one to manually set the orbital occupations in combination with the SAD guess.
Test calculation on the quintet state of Cr(N2)6 in aug-pcseg-1:
```
molecule {
2 5
Cr 0.0000925386 0.0000682032 0.0019012828
N 0.0004102713 2.3625659492 0.0026269619
N 0.0005967051 3.4672101357 0.0029548744
N 2.3620320503 -0.0004101212 0.0009507667
N 3.4666734940 -0.0002636830 0.0034835308
N -0.0003928082 -2.3624420331 0.0002298447
N -0.0001812896 -3.4670841683 0.0023676850
N -2.3618731053 0.0004033492 0.0009468195
N -3.4665147528 0.0006033882 0.0034481887
N 0.0000117173 -0.0007732394 2.1429780137
N -0.0000350947 -0.0013203851 …
```
=> Improved SAD guess

psi4/driver/driver.py, psi4/driver/p4util/python_helpers.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/cc/ccdensity/get_moinfo.cc, psi4/src/psi4/cc/ccenergy/get_moinfo.cc, psi4/src/psi4/cc/cceom/get_moinfo.cc, psi4/src/psi4/cc/cclambda/get_moinfo.cc, psi4/src/psi4/cc/cctriples/get_moinfo.cc, psi4/src/psi4/cctransort/cctransort.cc, psi4/src/psi4/dcft/dcft_memory.cc, psi4/src/psi4/detci/get_mo_info.cc, psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/dfocc/get_moinfo.cc, psi4/src/psi4/fisapt/fisapt.cc, psi4/src/psi4/fnocc/ccsd.cc, psi4/src/psi4/libfock/apps.cc, psi4/src/psi4/libmints/wavefunction.h, psi4/src/psi4/libmints/writer.cc, psi4/src/psi4/libmoinfo/moinfo.cc, psi4/src/psi4/libsapt_solver/sapt.cc, psi4/src/psi4/libsapt_solver/usapt0.cc, psi4/src/psi4/libscf_solver/stability.cc, psi4/src/psi4/mcscf/mcscf.cc, psi4/src/psi4/occ/get_moinfo.cc
Cramming a few more deprecations into v1.2
=> Deprecate c-side frequencies

azure-pipelines.yml, psi4/src/psi4/libmints/oeprop.cc
=> Fix memory error in psi::MultipolePropCalc::compute_mo_extents

external/downstream/snsmp2/CMakeLists.txt
Use upstream snsmp2 again after driver/qcel rearrangement. Particularly bad since I had deleted the branch this points to. Fixes #1425
=> use upstream snsmp2

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/psi4/libmints/matrix.h, psi4/src/psi4/libscf_solver/cuhf.cc, psi4/src/psi4/libscf_solver/frac.cc, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/psi4/libscf_solver/hf.h, psi4/src/psi4/libscf_solver/rhf.cc, psi4/src/psi4/libscf_solver/rohf.cc, psi4/src/psi4/libscf_solver/sad.cc, psi4/src/psi4/libscf_solver/uhf.cc, psi4/src/read_options.cc
Psi4 is currently using the RMS norm to check for wave function convergence. However, it's well known that the RMS norm isn't as robust as the absolute error in some pathological cases: even though the RMS error is small, you may still have significant gradients for a few orbitals.
This PR implements the maximum absolute norm for DIIS in SCF calculations, which can be toggled by setting ```DIIS_RMS_ERROR false```
=> Implement DIIS absolute error criterion

psi4/src/psi4/cc/ccresponse/roa.cc
This is a part of Psi4 porting to Windows (#933).
`tensor_rr` is `double***`, so it needs double dereferencing to have a pointer to data: 
https://github.com/psi4/psi4/blob/c9be896dd4b4c550b6f7ac792cf11a1274a9a038/psi4/src/psi4/cc/ccresponse/roa.cc#L238
I guess, it should be like here:
https://github.com/psi4/psi4/blob/c9be896dd4b4c550b6f7ac792cf11a1274a9a038/psi4/src/psi4/cc/ccresponse/roa.cc#L289
=> Fix memory error in psi::ccresponse::roa

psi4/src/psi4/detci/ints.cc, psi4/src/psi4/libtrans/integraltransform.cc, psi4/src/psi4/libtrans/integraltransform.h, psi4/src/psi4/libtrans/integraltransform_moinfo.cc, psi4/src/psi4/libtrans/integraltransform_sort_so_tei.cc
There is an invalid memory access at line 209, because `Ca_->colspi()[h]` is smaller than `nalphapi_[h]`:
https://github.com/psi4/psi4/blob/ba98fb72ab73350a613ae96b56d1d4c6074c2ae9/psi4/src/psi4/libtrans/integraltransform_sort_so_tei.cc#L201-L217
I have added an asset to prove that.
=> Fix invalid memory access in psi::IntegralTransform::presort_so_tei

psi4/src/psi4/dfmp2/corr_grad.cc, psi4/src/psi4/libfock/DiskDFJK.cc, psi4/src/psi4/scfgrad/jk_grad.cc, psi4/src/psi4/scfgrad/response.cc, psi4/src/read_options.cc
The value for ```DF_FITTING_CONDITION``` used by the code was changed in #1446, which resulted in a change of numerical values. This PR restores the previously used threshold. See discussion in #1350 and on Slack.
=> Restore previous DF_FITTING_CONDITION default

psi4/driver/qcdb/libmintscoordentry.py, psi4/driver/qcdb/libmintsmolecule.py, psi4/src/psi4/libmints/coordentry.h, psi4/src/psi4/libmints/molecule.cc, psi4/src/psi4/libmints/molecule.h
My debugging efforts indicate the problem with #1325 is that when attempting to clone a molecule with an atom with ZMAT and Cartesian coordinates, when that ZMatrixEntry atom is cloned, its `rto_`, `ato_`, `dto_` CoordEntries are Cartesian. This somehow leads to the parent ZMatrixEntry having `computed_` true, but not for `rto_` and friends. So, we somehow have a bug in molecule creation.
To avoid creating new bugs, I want to understand exactly what is going on before trying to implement a fix. Unfortunately, this part of the code is not in great shape. I'll hopefully include a fix for the bug in here, but in the meantime, I'm submitting the code cleanup I'm doing as I try to follow this part of the code. We do not want `libmints` changes to escape a thorough vetting process.
Notable …
=> CoordValue/CoordEntry Cleanup and 1325 Fix

psi4/src/psi4/libmoinfo/moinfo_base.cc
The last element  of `array` is `array[n-1]`, so the access of  `array[n]` is not correct:
https://github.com/psi4/psi4/blob/62bb956ccfb38cad1bef7e6227aac70ddb1172f7/psi4/src/psi4/libmoinfo/moinfo_base.cc#L281-L285
It is better to use pointer arithmetics: `array + n`.
This is not a bug, just it gives a false positive in memory error detection.
=> Fix memory error in MOInfoBase::convert_int_array_to_vector

psi4/src/psi4/dfmp2/mp2.cc
The DFMP2 gradient was not symmetrized to the molecule's (Abelian) point group before, so optimizations could potentially break symmetry, as pointed out [on the forums](http://forum.psicode.org/t/losing-symmetry-on-first-step-of-geometry-optimization/1201).  This PR enforces the Abelian symmetry, preventing problems with symmetry breaking in optimizations.
=> Symmetrize DFMP2 gradient to largest Abelian group of the molecule

psi4/src/psi4/dcft/dcft.cc, psi4/src/psi4/dcft/dcft_compute.cc
Closes #1482; DCT gradients are now compatible with ROHF starting orbitals. The problem was that  UDCT wavefunctions inherited the `same_a_b_orbs_` of the reference wavefunction, which was wrong for ROHF references. This caused the derivative machinery to try to try an RDCT gradient, which failed for obvious reasons.
While I was changing features inherited from the reference wavefunction, I gave DCT "wavefunctions" proper names.
=> DCT Gradients Compatible with ROHF Guess

psi4/src/psi4/libscf_solver/sad.cc, tests/sapt-ecp/input.dat, tests/sapt-ecp/output.ref
The reorganized SAD code was missing a check if the basis set is actually large enough to allow a full valence active space; this is now fixed.
=> Fix fractional SAD for minimal basis sets

psi4/src/psi4/libscf_solver/rohf.cc
The size of `leftp` is smaller than `doccpi_[h]` in `soscf-ref` tests:
https://github.com/psi4/psi4/blob/be5824d8926dd3e2c12a56944ceec50d1935ca83/psi4/src/psi4/libscf_solver/rohf.cc#L589-L591
=> Fix invalid memory access in psi::ROHF::Hx

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/psi4/libscf_solver/cuhf.cc, psi4/src/psi4/libscf_solver/cuhf.h, psi4/src/psi4/libscf_solver/hf.h, psi4/src/psi4/libscf_solver/rhf.h, psi4/src/psi4/libscf_solver/rohf.cc, psi4/src/psi4/libscf_solver/rohf.h
The first iteration energy in SAD is at best non-variational (RHF, UHF), and at worst completely nonsensical (ROHF, CUHF). As neither a DIIS error can be formed in the lack of a proper density matrix, this PR sets the first iteration energy to zero, so that only sensical energies are printed out.
=> Fix SAD guess energy printout

psi4/src/psi4/libtrans/integraltransform_moinfo.cc
The size of `aQT_` is `nmo_`.  In `cookbook-rohf-orb-rot` test, `aPitzerCount` exceeds it:
https://github.com/psi4/psi4/blob/96296f1e3740b348bd207aa2ed0e3568e723a5a1/psi4/src/psi4/libtrans/integraltransform_moinfo.cc#L209-L212
=> Fix memory error in psi::IntegralTransform::process_spaces

psi4/driver/p4util/python_helpers.py, psi4/driver/procrouting/proc.py, psi4/extras.py, tests/cookbook/rohf-orb-rot/input.dat
Use a centralized function to determine the scratch name associated with scratch files, to make sure they're being read and written consistently.  Fixes `cookbook-rohf-orbrot`, which was writing the modified orbitals to a location other than what the SCF code expects, resulting in them being ignored.
The following (unrelated) failures persist, but are fixed in #1494 .
```
The following tests FAILED:
223 - mints8 (Failed)
291 - opt-irc-1 (Failed)
```
=> Standardize the wfn (de)serialization path

psi4/driver/procrouting/proc.py, psi4/run_psi4.py, psi4/src/export_mints.cc, psi4/src/psi4/dfmp2/corr_grad.cc, psi4/src/psi4/libfock/jk.cc, psi4/src/psi4/scfgrad/jk_grad.cc, tests/CMakeLists.txt, tests/basis-ecp/CMakeLists.txt, tests/basis-ecp/input.dat, tests/basis-ecp/output.ref, tests/opt-irc-1/input.dat, tests/sapt-ecp/input.dat
heals up the remaining broken test cases except for cookbook-rohf-rot
=> ecp and df_fitting_condition fixes

external/upstream/libxc/CMakeLists.txt, psi4/CMakeLists.txt, psi4/src/psi4/libfunctional/LibXCfunctional.cc, psi4/src/psi4/libfunctional/factory.cc
=> move to upstream Libxc 4.3.0

psi4/src/psi4/libmints/writer.cc
No new features were added. This is a bugfix for a minor problem described in issue #1485.
The MoldenWriter::write method was appending output to an existing Molden file, if present. This is not the desired behavior since the appended part is not read by post-processing tools, nor is it part of the definition of the file format. This becomes especially confusing when doing a test calculation, where one is trying to get a psi4 input file to work as intended with some trial and error. All results from previous trials are kept in the Molden file and only the first one is read by a post-processing tool, not the last one.
None
- No new tests added
=> Do not append to existing Molden file

psi4/driver/qcdb/intf_dftd3/runner.py
Stops overwriting DFT energy by D3 energy only. I am not sure how to test for this, as the gradients as well as geometries with and without the patch agree to 8 DP's. I only noticed it when using the `vibrational_analysis(wfn)`, as there the current total energy plays a role...
=> Fix for issue #1356.

psi4/src/psi4/dcft/dcft_compute_UHF.cc
Fixes #1353 by raising an error that DF was never implemented with the QC algorithm in `dcft`. Per discussions with @ssh2, I also added a message that the QC algorithm employs the hessian for DC-06, as the others haven't been implemented yet.
=> Add Not Implemented Messages in DCT

.travis.yml
Travis's third test, which uses GCC6, keeps timing out.  The second uses GCC 5.4, so perhaps trying GCC 8 will speed up the problematic test.  This PR attempts that experiment.
=> Update GCC version for third Travis build

psi4/driver/driver.py, psi4/src/psi4/libmints/writer.cc
The formatted checkpoint files currently produced by Psi4 misname the orbital coefficient and the density matrix fields. This PR (re)establishes the expected behavior, as well as fixes other bugs in the code.
=> Fix inconsistencies in formatted checkpoint files

external/common/lapack/FindTargetOpenMP.cmake, psi4/share/psi4/scripts/test_threading.py
OpenMP detection is very finely balanced to compensate for LAPACK demands, `libgomp` self aggrandizement, and psi4's need to sanely and transparently impose the psi4-compile-omp status on any derived plugins. Unfortunately, #1348 disturbed some of that for the particular case of plugins with fewer active languages than their parent psi4.
A plugin (dfmp2) wasn't inheriting openmp from psi4 and thus was giving unknown openmp pragma warnings upon compile. This wasn't getting caught on linux because I was only checking that iomp5/gomp/omp weren't mixing, not that at least one was present. By happenstance, this did trigger an error on Mac in the course of building `psi4-dev`. This seems to patch things up on Linux. Will use this branch to try out Mac again.
=> openmp inheritance for plugins

psi4/src/psi4/libfock/cubature.cc
`BlockOPoints` performs additional pruning but the result is never checked.  We recently hit a case where this pruning resulted in a `BlockOPoints` object with zero points. This would cause a segfault here: https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libfock/v.cc#L262 because `ncols` would be zero.
Adds a check to `OctreeGridBlocker` where the list of `BlockOPoints` is populated, if the number of points is zero then don't add it to the list.
=> DFT: Adds OctreeGridBlocker -> BlockOPoints pruning check.

.travis.yml
The third Travis test is timing out too much.  This can be traced to the painfully slow download time for the GCC compiler.  We have plans to replace this test with some plugin validation, using native GCC compilers to avoid the timeouts.  For now, we'll just nuke it to allow the backlog of PRs through.
=> Remove third Travis test

azure-pipelines.yml
Add options to *Azure* pipeline to run all the tests. This can be used after significant changes and before release.
This can be used only by users, who have permissions to queue jobs manually on https://dev.azure.com/psi4/psi4 or have their own *Azure* pipelines (e.g. https://dev.azure.com/raimisg/psi4).
- `ctest.type` with default `quick` (settable at queuing time)
- `pytest.type` with default `quick` (settable at queuing time)
=> Add options to trigger all ctests on Azure

psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/lib3index/dftensor.cc, psi4/src/psi4/libfock/DiskDFJK.cc, psi4/src/psi4/libsapt_solver/sapt0.cc, psi4/src/psi4/libsapt_solver/sapt2.cc
Fix more instances where RI inverse overlap is formed without the proper value for the fitting condition.
=> Still more places where DF_FITTING_CONDITION wasn't used.

azure-pipelines.yml
Add options to *Azure* pipeline to build a optimized *Psi4* with custom *Python* version.
~~**Depends on #1527**~~
- `cmake.build_type` with default `Debug` (settable at queuing time)
- `python.version` with default `3.6` (settable at queuing time)
=>  Enable optimized builds on Azure

psi4/driver/qcdb/basislistother.py
I realized that when running PBEh-3c, the calculation would take longer than expected. This was due to the use of a large basis during the density fitting procedure. I have just added the information required to make the code use the same auxiliary basis for the def2-mSVP basis as the ones used for def2-SVP. I did not test this modifications using the test cases.
=> Update to include an auxiliary basis for def2-mSVP

azure-pipelines.yml, conda/win/meta.yaml
Enable *conda* package building for *Windows* with *Azure*.
- `conda.build` with default `false` (settable at queuing time)
=> Enable Windows package building with Azure

psi4/driver/driver.py
Previously, the `dertype` specified in a frequency or optimization-with-hessian computaiton wouldn't get passed on to the pre-hessian gradient. This is now fixed. For optimizations, we can do one better and pass in the last gradient, so we don't need to recompute it. While solving this, I uncovered that supplying a dertype that was "too high" for the derivative level would lead to the default case of energy-only computations. That is also fixed.
**Although this is an enhancement, this is also a bug fix.** Without this PR, I have no way to get a frozen core MP2 optimization with a `full_hess_every` hessian. The user is responsible for supplying the `dertype`, and they currently have no way to get the `dertype` argument to the pre-hessian gradient.
=> dertype and gradient passing

psi4/driver/driver.py, psi4/driver/procrouting/empirical_dispersion.py, psi4/src/core.cc, psi4/src/export_mints.cc, psi4/src/export_wavefunction.cc, psi4/src/psi4/cc/cceom/get_eom_params.cc, psi4/src/psi4/libmints/pointgrp.h, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmoinfo/moinfo.cc, psi4/src/psi4/libmoinfo/moinfo_scf.cc, psi4/src/psi4/libpsi4util/process.h, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/read_options.cc, tests/dft-grad-lr2/output.ref
=> the `parent_symmetry`-ectomy

psi4/driver/json_wrapper.py, psi4/driver/p4util/python_helpers.py, psi4/driver/procrouting/proc.py, psi4/src/psi4/cc/ccenergy/ccenergy.cc, psi4/src/psi4/cc/cctriples/triples.cc, psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/scfgrad/wrapper.cc, tests/json/schema-1-energy/input.py, tests/json/schema-1-throws/input.py, tests/scf-hess1/input.dat
- sets all options at once and allows module-level options (`scf__reference` --> `set scf reference`)
- shifts `json['psi4:qcvars']` --> `json['extras']['qcvars']`
- `json['extras']['wfn_qcvars_only']` collects qcvars only from wfn, not from `P::e`
- uses molecule dtype=2, qcschema one-word, and new error format
- `HF TOTAL HESSIAN`
- removes scs-mp2 ss/os psivars in dfmp2 that were getting autovivified. thereby also corrects printing of 0s
- in cc* modules, defines psivars on wfn that I'm confident will endure
=> update run_json and wfn qcvars

psi4/driver/driver_cbs.py, tests/cbs-xtpl-dict/input.dat, tests/cbs-xtpl-dict/output.ref
This fixes a bug in "options" handling - previously, options requested in CBS() stage were not stashed properly, as OptionsStash requires an array of arrays with option names, instead of an array of option names.
I've also added "options_lo" keyword, so that one can do, say, `"cc_type": "conv"` calculation in an otherwise `"cc_type": "df"` recipe, or as shown in the test, a frozen-core stage in an all-electron recipe.
=> CBS() option handling fix

psi4/driver/wrapper_database.py
Fix the ability to use database computations when open-shell molecules, and thus reference changes, are involved. Because the time at which `molecule` exists, the fix I implemented would be incompatible with reap and sow, so those have been removed. I've simplified the code accordingly.
=> Fix Database for Open Shells; Rip out Reap/Sow

psi4/driver/diatomic.py
Addresses issues highlighted in #1600:
- energies and radii are now sorted based on radius of the diatomic
- initial guess for `r_e` is now the point of minimum energy
- check for number of points around minimum: if fewer than three on either side, print out a warning.
=> Incorporated suggested changes from #1600

psi4/src/psi4/mrcc/mrcc.cc
The value of the 'mem' option was conflated with that for the 'dboc' option, leading to a list directed I/O error at runtime when setting memory available to a 6 digit (or more) number
=> Fix printout of fort.56 file for MRCC

psi4/src/psi4/scfgrad/response.cc, psi4/src/psi4/scfgrad/scf_grad.cc, psi4/src/psi4/scfgrad/scf_grad.h, psi4/src/psi4/scfgrad/wrapper.cc
The Hessian code can be cleaned up by using the SCF class's hessian-vector products.  To avoid the need to cast pointers inside the orbital response code, this PR specializes the response class for each reference type, and removes some junk symmetry code.
=> Cleanup response code

psi4/driver/p4util/python_helpers.py
Need to explicitly allow pickles (which we need to since building objects) in NumPy 16.3. See https://github.com/numpy/numpy/issues/12759 . @dgasmith, needed [here](https://github.com/psi4/psi4/blob/fbb2ff444490bf6b43cb6e027637d8fd857adcee/psi4/driver/p4util/numpy_helper.py#L385), too? quicktests passes w/o. This should fix travis.
=> explicitly np.load(..., allow_pickle=True) since we're building objects

psi4/src/psi4/scfgrad/response.cc
#1550 switched the CPHF solver for analytic Hessians from libfock to the wfn one. That switched the CPHF from 1e-6 to 1e-4 and the HOOH_TS-analytic test case in test_vibanalysis took exception. This PR sends the relevant `CPHF` module (aka libfock) options to the Hessian CPHF call. So returns the default to 6. Thanks to @andysim for difference-hunting.
=> Hessian CPHF options

.travis.yml, azure-pipelines.yml, doc/sphinxman/source/psiapi.ipynb, environment.yml, external/upstream/ambit/CMakeLists.txt, external/upstream/qcengine/CMakeLists.txt, tests/pytest/conftest.py
=> ambit v0.3, parallel pytest, binder start

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/psi4/libscf_solver/hf.h
Fixes #1370 and cleans up some code relating to orbital occupations. `scf_iterator.py` is yapf-ified, the occupation printing code is now Py-side, and two variables specifying the same thing (`nirreps` and `nirrep_`) in the HF initialization have been condensed into a single variable.
=> Validate DOCC/SOCC; Cleanup Occupation Code in HF

psi4/src/psi4/libmoinfo/model_space.cc, psi4/src/psi4/libmoinfo/moinfo.cc, psi4/src/psi4/libmoinfo/moinfo_model_space.cc
Fix lgtm warnings in libmoinfo.
=> Fix lgtm warnings in libmoinfo

psi4/src/psi4/dcft/dcft.cc, psi4/src/psi4/dcft/dcft_df_tensor.cc, psi4/src/psi4/dcft/dcft_memory.cc, psi4/src/psi4/dcft/dcft_scf_UHF.cc, psi4/src/psi4/dcft/dcft_tau_RHF.cc, psi4/src/psi4/dcft/dcft_tau_UHF.cc
Part 1 of the dcft segment of #1615. `ctest -R dcft -j4` passes. Most of the LGTM issues in `dcft` are _not_ addressed in this PR, as the fixes belong elsewhere:
* Changing the type of basisset.nbf and wavefunction.nso from ints to size_t
* Changing Dimension from std::vector<int> to std::vector<size_t>
* Changing rowtot and coltot in dpd.h to be arrays of size_t instead of ints. This one may be more controversial.
=> dcft LGTM: Pt. I

psi4/src/psi4/libtrans/integraltransform.h, psi4/src/psi4/libtrans/integraltransform_oei.cc
The libtrans segment of #1615 in what should be its entirety. We are now passing an argument by const reference. Passes quicktests.
=> libtrans LGTM

psi4/src/read_options.cc
0 <= occ <= 1.0, not 0 >= occ >= 1.0
=> Fix frac_val description

psi4/src/psi4/libscf_solver/hf.cc, psi4/src/psi4/libscf_solver/rhf.cc, psi4/src/psi4/libscf_solver/stability.cc, psi4/src/psi4/libscf_solver/stability.h, psi4/src/psi4/libscf_solver/uhf.cc
The libscf_solver segment of #1615 in what should be its entirety. Mostly changing format strings, but also setting a header guard back to guarding the header, rather than a blank line. Passes quicktests.
=> libscf_solver LGTM

psi4/driver/procrouting/dft/hyb_functionals.py, psi4/driver/procrouting/dft/mgga_functionals.py, tests/pytest/test_dft_benchmarks.py
Adds a few functionals (SCAN0, revSCAN0, SCAN, revSCAN, BMK, revM06-L).
~Enables `dft_bench_i*` tests for SCAN, SCAN0, revPBE, SOGGA, SOGGA11, MN12-SX, MGGA_MS2h, MN12-L, BMK, N12, MGGA_MVS, PKZB, MN15-L, PBE50, MGGA_MVSh, SOGGA11-X, M06-L, N12-SX, PBEOP, MPW1LYP and GAM.~
Enables all reference values in `dft_bench_i*` tests, now sorted alphabetically. Functionals not present in Psi4 are automatically ~marked with `xfail`~ skipped - this currently includes B3TLAP, BP86VWN, LRC-BOP, PBEsol, t-HCTH, t-HCTHh, wM05-D and wM06-D3, in addition to wB97X-D3 which was already marked `xfail`.
=> Add SCAN family of functionals

psi4/src/psi4/adc/init_tensors.cc
At the risk of gaining a reputation for single-character PR's,  I think I have a fix for #1596.  The extra character in the error message looked suspicious, so I nuked it and the `adc` tests still pass.   I'll show the output of the OP's calculation below.
=> Fix possible typo in ADC integral setup

psi4/src/CMakeLists.txt
Alternative solution to problem at #1640
=> Fix cmake changes causing plugin link problems on Mac

azure-pipelines.yml, conda/win/meta.yaml
=> Fix Windows building and packaging

psi4/src/psi4/liboptions/liboptions.cc, psi4/src/psi4/liboptions/liboptions.h, psi4/src/psi4/libscf_solver/sad.cc, psi4/src/read_options.cc, tests/CMakeLists.txt, tests/sad-scf-type/CMakeLists.txt, tests/sad-scf-type/input.dat, tests/sad-scf-type/output.ref
This PR implements  ```SAD_SCF_TYPE``` options that aren't currently allowed as ```SAD_SCF_TYPE``` options, as well as adds tests to check that the computed SAD guess is exact for closed-shell atoms.
=> Implement SAD_SCF_TYPE = CD and PK

psi4/src/psi4/libfock/cubature.cc, psi4/src/psi4/libfock/cubature.h, psi4/src/read_options.cc, tests/dft-pruning/input.dat
XC quadrature weights can become very small and thus their contributions are negligible. This PR introduces a cutoff for small weights. The grid points with small weights are not included in the final grid. Such a cutoff is a standard procedure in many programs.
------
water dimer (RKS total energy): `PBE/aug-cc-pVTZ (99,520)` econv=1e-10 dconv=1e-8
| tolerance | error | #points |
| --- | --- | ---|
| off | 0.0 | 350460 |                                                 
| 1e-30 | 1.36e-12 | 349417 |
| 1e-25 | 1.65e-12 | 348670 |
| 1e-20 | 1.65e-12 | 346918 |
| 1e-18 | 1.68e-12 | 345747 |
| 1e-16 | 1.63e-11 | 340646 |
| 1e-15 | 2.74e-11 | 339647|
| 1e-14 | 5.73e-09  |  335089 |
| 1e-13 | 3.65e-08  |  331285 | …
=> quadrature weights cutoff

tests/dft-pruning/input.dat
The mandatory option setting the `DFT_WEIGHT_TOLRANCE` was missing.
=> fixes test: dft-pruning

psi4/src/psi4/optking/molecule_irc_step.cc, tests/opt-irc-2/input.dat
Last summer, I discovered that the energy _increased_ along the IRC for my complex formation coordinate. I eventually tracked this down to a bug where the molecule did not displace the initial geometry correctly, which this PR fixes. Since that time, those of us at UGA have found this fix essential to follow modes <200i. I discuss this in more detail [here](https://github.com/psi-rking/optking/issues/19).
I updated a test to reflect the fact that the IRC can go a bit further when it displaces correctly. I didn't bother updating the reference files, as I expect it'll be invalidated soon anyways. The whole reason I'm submitting this PR now is to eliminate this bug from consideration when I send @psi-rking the _latest_ IRC bug I found.
Notable points (developer or user-interest) that this PR …
=> IRC: Displace from initial geom correctly

tests/dft-pruning/input.dat
I was getting an error of off one grid point count on local box for 1.e-16 tolerance. So relaxed the count.
=> relax grid point checking near machine epsilon

.pre-commit-config.yaml, .travis.yml, doc/sphinxman/source/code_style.rst, doc/sphinxman/source/prog_faq.rst
Breaks off documentation and `.travis.yml` linting off of #809. I have added a `.pre-commit-config.yaml` that will check for:
- Filenames that would conflict on a case-insensitive filesystem
- Files that contain merge conflict strings.
- Python formatting with YAPF.
- C++ formatting with clang-format.
Hooks are **opt-in** and require you to install [`pre-commit`](https://pre-commit.com/) (with pip or conda) and then run `pre-commit install` to integrate the actual hooks.
=> Document code style and pre-commit hooks

psi4/src/psi4/scfgrad/jk_grad.cc
The default gradient and Hessian screening cutoffs should be the same as for the integrals used in SCF (#1540).
=> Default cutoffs should be same

tests/pytests/test_dertype.py, tests/pytests/test_misc.py, tests/pytests/test_qcng_dftd3_mp2d.py, tests/pytests/test_qcvars.py
At least on Mac, these tests were failing with the latest pytest (5). Happily, the fix doesn't look to break pytest 4.
- heads-up @dgasmith that qcel, qcng may also be susceptible
=> fix error string checking for pytest 5

doc/sphinxman/source/introduction.rst, doc/sphinxman/source/scf.rst, psi4/driver/procrouting/proc.py, psi4/src/psi4/libscf_solver/cuhf.cc, psi4/src/psi4/libscf_solver/cuhf.h, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/psi4/libscf_solver/hf.h, psi4/src/psi4/libscf_solver/rohf.cc, psi4/src/psi4/libscf_solver/rohf.h, psi4/src/psi4/libscf_solver/sad.cc, psi4/src/read_options.cc, tests/scf-guess/input.dat, tests/scf-guess/output.ref
This PR implements the last guess I described last fall: the SAD natural orbitals guess.
=> Implement the SAD natural orbitals guess (doi:10.1021/acs.jctc.8b01089).

psi4/share/psi4/plugin/scf/pymodule.py.template
Simple fix for the SCF plugin template, to work with the new `set_variable` syntax.
=> Fix SCF plugin python file

external/upstream/libxc/CMakeLists.txt
Modify the download location away from the (temporarily?) defunct tddft.org, back to gitlab.
=> Fix libxc download location

psi4/driver/qcdb/libmintsbasissetparser.py
Fixes warning message described on slack by iwatobipen:
```
/home/user/anaconda3/envs/chemo37/lib/python3.7/site-packages/psi4/driver/qcdb/libmintsbasisset.py:854: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/user/anaconda3/envs/chemo37/share/psi4/basis/aug-cc-pvdz.gbs' mode='r' encoding='UTF-8'>
names[index] = parser.load_file(fullfilename)
```
as suggested by @loriab 
=> Close input file in basis set parser once it's not needed anymore

psi4/src/psi4/detci/params.cc
At present the program prints a warning if electrons are outside the active space, and then later on crashes. This PR changes behavior so that the program terminates at once.
=> Crash program if electrons outside of RAS spaces.

psi4/src/psi4/libscf_solver/hf.cc
=> Fix segfault with unconventional basis sets.

tests/pytests/test_mp2d.py
below is what was failing at atol=1.e-8. I venture it was tipped over the threshold, so loosened to 2.e-8. should fix travis.
AAAAA 1e-08
```
[[ 0.         0.        -0.0669792]
[ 0.         0.         0.0669792]]
[[ 0.          0.         -0.06697921]
[ 0.          0.          0.06697921]]
cc-pVDZ tot grad..................................................FAILED
```
=> fix travis mp2d grad

psi4/driver/p4util/python_helpers.py
EDIT: Sorry for no providing the re-producible example
I encountered a crash while using Psi4 python API with the following minimal code example
```python
import psi4
geo_str = """
He  0.000 0.000 -1.48169297
--
He  0.000 0.000  1.48169297
"""
dimer = psi4.geometry(geo_str)
rt_options = {
"basis": "jun-cc-pvdz",
"scf_type": "mem_df",
"reference": "uhf",
"basis_guess": "3-21G",
"guess": "sad",
"e_convergence": 1e-12,
"d_convergence": 1e-12,
}
psi4.set_options(rt_options)
dimer.reset_point_group("c1")
subset_A = [2]
subset_B = [1]
monomerA = dimer.extract_subsets(1, subset_A)
monomerA.set_name("Monomer A")
monomerB = dimer.extract_subsets(2, subset_B)
monomerB.set_name("Monomer B")
scf_e_A, wfnA = psi4.energy("SCF", return_wfn=True, molecule=monomerA)
scf_e_B, wfnB = psi4.energy("SCF", …
```
=> allow_pickle=True in np.save

psi4/src/psi4/dfocc/manager.cc, psi4/src/psi4/dfocc/manager_cd.cc, psi4/src/psi4/occ/manager.cc
Bug fix. Exports missing `MP3 TOTAL ENERGY` variable for `mp2.5` calculations. Expected by the `cbs` driver function.
=> adds missing mp3 energy variables to dfocc and occ

psi4/driver/inputparser.py
The input processor now knows to apply basis syntax to `df_basis_sad`. This PR will need to go in before I can post a problematic (read: something is probably broken) SCF case.
=> Add df_basis_sad to input parser

psi4/src/psi4/dcft/dcft_compute.cc, psi4/src/psi4/dcft/dcft_compute_RHF.cc, psi4/src/psi4/dcft/dcft_compute_UHF.cc, psi4/src/psi4/dcft/dcft_gradient_UHF.cc, psi4/src/psi4/dcft/dcft_integrals_RHF.cc, psi4/src/psi4/dcft/dcft_integrals_UHF.cc, psi4/src/psi4/dcft/dcft_intermediates_RHF.cc, psi4/src/psi4/dcft/dcft_intermediates_UHF.cc, psi4/src/psi4/dcft/dcft_lambda_RHF.cc, psi4/src/psi4/dcft/dcft_lambda_UHF.cc, psi4/src/psi4/dcft/dcft_memory.cc, psi4/src/psi4/dcft/dcft_mp2_RHF.cc, psi4/src/psi4/dcft/dcft_mp2_UHF.cc, psi4/src/psi4/dcft/dcft_oo_RHF.cc, psi4/src/psi4/dcft/dcft_oo_UHF.cc, psi4/src/psi4/dcft/dcft_qc.cc, psi4/src/psi4/dcft/dcft_scf_RHF.cc, psi4/src/psi4/dcft/dcft_scf_UHF.cc, tests/CMakeLists.txt, tests/dcft10/CMakeLists.txt, tests/dcft10/input.dat
While working on a _different_ PR for the dcft code, I stumbled across a bug that I had accidentally introduced in #1310. DCFT previously allowed you to use the amplitudes from a previous computation as your guess for the next one by setting `dcft_guess dcft`. Key to this mechanism was the fact that the LibDPD files persisted after the computation... which is precisely what I changed in #1310 to fix #1309, where intermediate files would interfere with the amplitude guess.
The primary purpose of this PR is to both keep the guess feature working and keep issue #1309 fixed. This is accomplished by checking if `dcft_guess` is `dcft` at the time of `compute_energy` and choosing whether or not to nuke previous files. So past intermediate files will interfere only when you want them to.
There …
=> Restore DCFT Guess

psi4/driver/procrouting/empirical_dispersion.py
Addresses #1724 by telling QCEngine to parent the scratch of dftd3 and mp2d into `$PSI_SCRATCH`. Contrary to what I said in that issue, the dftd3 parameters are written to local working dir (that is, scratch), not to $HOME. There's one other qcng call. It's `qcdb.Molecule.run_dftd3`. I really don't want to be calling `core` there, and it only runs in tests, so leaving that for now.
=> get dftd3 and mp2d into PSI_SCRATCH

psi4/driver/driver_nbody.py, psi4/driver/qcdb/libmintsbasisset.py, psi4/src/psi4/libmints/molecule.cc, psi4/src/psi4/libmints/molecule.h
Resolves #1694 by throwing an exception when active molecule has only 1 fragment.
Resolves #1675 by throwing an exception when requested atom is out of bounds.
Resolves #1613 by changing the lookup path for AUX/DECON bases from `libraryPath` to `basisPath`.
=> Issue cleanup: fix various crashes.

psi4/driver/driver.py
Couldn't (I think) go in the header, but this PR prints the correct scratch directory at the beginning of energy() and gradient() calls. This is particularly useful if the user simultaneously specifies scratch directories in different ways.
=> Add simple print statements for scratch directory

psi4/src/psi4/dfocc/dfgrad.cc
The title is pleasantly self-explanatory.
The `set_gradient` call will automatically set the `gradient_` variable. With the old way of setting the gradient, the gradient wouldn't be picked up by serialization, meaning my attempt at an optking3 IRC (of course) was failing.
I'll also take this opportunity to soapbox about why we (read: I) need to centralize our DF gradient code.
=> Set gradient with set_gradient

psi4/src/core.cc
Resolves #1729 : Reopen outfile when `-o stdout` is used.
The important parts is line 217. The changes from 504 and beyond are from clang-format.
=> "Reopen" outfile when "-o stdout" is used.

psi4/src/psi4/libmints/CMakeLists.txt, psi4/src/psi4/libmints/dimension.cc, psi4/src/psi4/libmints/dimension.h, psi4/src/psi4/libmints/orthog.cc, psi4/src/psi4/libmints/orthog.h, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/read_options.cc
This PR removes duplicated code in Psi4 so that orthogonalization of the basis is handled in one place.
=> Move basis set orthogonalization to libmints/orthog.cc

psi4/src/export_mints.cc, psi4/src/psi4/libmints/deriv.cc, psi4/src/psi4/libmints/deriv.h
This PR introduces an option in the call to `Deriv::compute()` so that the user can specify the type of gradient computation. Currently, this class determines which procedure to follow using an internal logic that is not sufficiently flexible to accommodate plugins.
=> Let the user select the type of derivative computation in the Deriv class

README.md, doc/sphinxman/source/dkh.rst, doc/sphinxman/source/introduction.rst, psi4/driver/diatomic.py, tests/libefp/efp-grad/output.ref, tests/libefp/qchem-efp-sp/output.ref, tests/libefp/qchem-qmefp-puream-sp/output.ref, tests/libefp/qchem-qmefp-sp/output.ref, tests/libefp/qmefp-moldomains/output.ref, tests/v2rdm_casscf/v2rdm1/output.ref, tests/v2rdm_casscf/v2rdm2/output.ref, tests/v2rdm_casscf/v2rdm3/output.ref, tests/v2rdm_casscf/v2rdm4/output.ref, tests/v2rdm_casscf/v2rdm5/output.ref, tests/v2rdm_casscf/v2rdm6/output.ref, tests/v2rdm_casscf/v2rdm7/output.ref
The DOI Foundation [started recommending a new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). While their URL change may be a bit ironic, it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org) and the old `dx` subdomain is being redirected. So, there is no urgency here.
However, for consistency, this PRs suggests to update all static DOI links accordingly, plus the code that generates new DOI links.
- [-] Tests added for any new features
- [-] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)
=> Hyperlink DOIs to preferred resolver

doc/sphinxman/source/cc.rst, doc/sphinxman/source/cfour.rst, doc/sphinxman/source/oeprop.rst, doc/sphinxman/source/scf.rst
Fix occurrences of `psi4.property` in the documentation and replace by `psi4.properties`.
- [-] Tests added for any new features
- [-] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)
=> Renamed instances of property function to properties in docs

psi4/src/psi4/libmints/orthog.cc, tests/pytests/test_qcschema.py
This is consistent to [what HF orthog was doing](https://github.com/psi4/psi4/pull/1759/files?utf8=%E2%9C%93&diff=split&w=1#diff-542034e7ed85da9a795544399b295be6L743) pre #1759 . Fixes the cookbook/rohf and scf-guess-read2 tests, both of which involve ROHF. Look sensible, @susilehtola?
=> orthog test fixes

psi4/src/psi4/fnocc/frozen_natural_orbitals.cc, tests/CMakeLists.txt, tests/fnocc5/CMakeLists.txt, tests/fnocc5/input.dat, tests/fnocc5/output.ref
My DFCC code was relying on Process::environment.globals() for the number of auxiliary functions in the case of scf_type = cd, which failed to work correctly when passing wavefunctions into the energy call.  This PR fixes that bug.
=> fixes bug in df-cc when reading wave functions with scf_type cd.

psi4/driver/procrouting/proc.py, psi4/src/psi4/libmints/orthog.cc, psi4/src/psi4/libmints/orthog.h, psi4/src/psi4/libscf_solver/cuhf.cc, psi4/src/psi4/libscf_solver/rohf.cc, tests/CMakeLists.txt, tests/scf-guess-read2/input.dat, tests/scf-guess-read2/output.ref, tests/scf-guess-read3/CMakeLists.txt, tests/scf-guess-read3/input.dat, tests/scf-guess-read3/output.ref
The orthogonalization changes in the Cholesky pull #1760 broke `scf-guess-read2`. The problem is that I started to renormalize the overlap matrix before doing the eigendecomposition. However, it turns out that there's no (simple?) way to renormalize **and** still have a symmetric orthogonalizing matrix **X**.  
Namely, the natural way to get the right normalization out is that you
1. normalize `S`: `Snorm = diag(1.0/sqrt(S)) *  S * diag(1.0/sqrt(S))`
2. form `Xnorm` for `Snorm`
3. form `X = diag(1.0/sqrt(S)) * Xnorm`
Trying to do step 3 in a way that maintains symmetricity of `X` would require much deeper linear algebra, as you need to know how the eigenvalues and eigenvectors change when you balance S to have a unit diagonal. (It may be that some old linear algebra textbooks show how …
=> Fix issues in ROHF and CUHF

psi4/driver/procrouting/proc.py, psi4/src/psi4/occ/CMakeLists.txt, psi4/src/psi4/occ/manager.cc, psi4/src/psi4/occ/occwave.h, psi4/src/psi4/occ/postprocessing.cc, tests/pytests/occ_methods.txt
See #1783. tl;dr: The goal is to improve orbital convergence in `occ`, but I need the module cleaned up to make it easier to think about the code I'm needing to mess with. I'm breaking a monolith PR into several.
The objective of the current PR is to clean up `occ/manager.cc`. All duplicated printing and variable setting code is now located in `postprocessing.cc`.
* Less code duplication and less code!
* The important `occ` variables are now set in `variables_` C-side so they can be set Py-side.
* A new file has been created, `postprocessing.cc`, for all `occ`'s repetitive printng and Psi variable-setting needs
* @loriab, please check that there's nothing obvious missing. In particular, there is no `test_omp.py`, so I just made a .txt file for you.
=> Clean manager.cc Variables: OCC's Open-Heart Surgery II

psi4/src/psi4/libsapt_solver/amplitudes.cc, psi4/src/psi4/libsapt_solver/ind30.cc, psi4/src/psi4/libsapt_solver/sapt2p3.h
Includes the small missing term in SAPT E(30)ind (issue #1677) with one extra DDOT of size o*v. The additional term is passed around using the variable `e_ind30_vsasb_term_` defined in `sapt2p3.h`  - please change if that's not the preferred way. The results on the A24 database agree with the Psi4NumPy code of Jonathan Waldrop.
=> Fixed the error in E(30)ind (1677)

psi4/src/psi4/scfgrad/jk_grad.cc, psi4/src/psi4/scfgrad/response.cc
Some MO transformations were being performed many times instead of just once in the DF SCF analytic Hessians, as a result of some closed braces being in the wrong place.  The results were correct before but the code was *very* slow.  Sorry for the mistake - my bad.  Fixes #1145
=> Fix performance issue in DF SCF Hessians

psi4/src/psi4/libsapt_solver/amplitudes.cc
While building Psi, my compiler complained:
```
/Users/jonathonmisiewicz/psi4/psi4/src/psi4/libsapt_solver/amplitudes.cc:1135:18: warning: result of comparison against a string literal is unspecified (use strncmp instead) [-Wstring-compare]
if (amplabel == "Ind30 uAR Amplitudes") {
^  ~~~~~~~~~~~~~~~~~~~~~~
```
Might as well fix it _before_ it causes some hard-to-debug problem.
=> Resolve compiler warning

psi4/src/psi4/fisapt/fisapt.cc
Memory overhead estimate in fdisp is an underestimate.  Improve this slightly in hopes of addressing a crashing large test case.
=> Minor improvements to overhead memory estimation in fdisp

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml, psi4/__init__.py, tests/mints9/input.dat
=> try fixing Azure Clang OpenMP

doc/sphinxman/source/build_obtaining.rst
Removes the obsolete mention of Psi3 in the build docs.
If someone wants psi3, they can find it by Google...
=> Psi3 doesn't mentioning in the build docs.

psi4/src/psi4/libmints/orthog.cc, psi4/src/psi4/libmints/orthog.h, psi4/src/psi4/libmints/quadrupole.cc, psi4/src/psi4/libmints/quadrupole.h, psi4/src/psi4/libscf_solver/hf.cc
This PR modifies the partial Cholesky approach by determining the initial pivot by an approach motivated by the Gershgorin circle theorem. By ordering the basis functions in terms of increasing values of  `\sum_j |S_{ij}|`, the Cholesky procedure is initialized with functions that are as close as possible to eigenfunctions of S. Although the original scheme works well, this one is conceptually more attractive as it needs no external input. Moreover, this one should be more generally applicable, e.g. in the case of computing strongly repulsive potentials where some tight functions might have large overlap.
The two approaches appear to reproduce similar results, so the change should not break anything.
=> Simplify partial Cholesky with Gershgorin theorem

.azure-pipelines/azure-pipelines-linux.yml, psi4/__init__.py, psi4/share/psi4/basis/NOTES, psi4/src/psi4/libfock/v.cc, psi4/src/psi4/libsapt_solver/sapt.cc
before (stride, memory, collocation_size) `MEM 1       954741720.0000 1678037264`
```
(dev10) psilocaluser@bash:psinet:/home/psilocaluser/gits/hrw-release/objdir: (safeforqcel2018) grep iB dftmem.out 
Memory:     500.0 MiB
Memory set to  14.901 GiB by Python driver.
1 Threads,  15258 MiB Core
DFHelper Memory: AOs need 3.981 GiB; user supplied 3.981 GiB. Using in-core AOs.
Memory [MiB]:              4076
Cached 100.0% of DFT collocation blocks in 12.502 [GiB].
```
after `MEM 2       954741720.0000 1678037264`
```
(dev10) psilocaluser@bash:psinet:/home/psilocaluser/gits/hrw-release/objdir: (safeforqcel2018) grep iB dftmem2.out 
Memory:     500.0 MiB
Memory set to  14.901 GiB by Python driver.
6 Threads,  15258 MiB Core
DFHelper Memory: AOs need 4.062 GiB; user supplied 4.062 GiB. Using …
```
=> switch out omp call

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/psi4/libscf_solver/hf.cc
Suggestion for #1711
Moves the `nmo` table to a place after the orbital guess, so that it actual contains all the information. Adds a reduced `nmo` table for SAD together with a note that no occupations are available.
_Formatting details up to debate_. Perhaps especially the placement of the `Pre-Iterations` line.
Edit: See updated examples in thread below
=> printout of initial orbital occupations

psi4/src/psi4/libdpd/contract222.cc, psi4/src/psi4/occ/README.txt, psi4/src/psi4/occ/kappa_orb_resp_iter.cc, psi4/src/psi4/occ/occ_iterations.cc, psi4/src/psi4/occ/occwave.h, psi4/src/psi4/occ/trans_ints_rhf.cc, psi4/src/psi4/occ/trans_ints_uhf.cc, psi4/src/read_options.cc
Think of the default orbital optimization algorithm in OCC with the following pseudocode:
```
orbital_gradient = compute_orbital_gradient()
try:
orbital_step = compute_NR_step_via_PCG_with_HF_MO_hessian(orbital_gradient)
except ConvergenceError:
orbital_step = compute_step_with_crude_diagonal_MO_hessian(orbital_gradient)
diis_step()
```
I traced a test failure in an upcoming PR (ocepa-grad2) to a failure in the approximate NR step. Five failures, in fact.
1. The HF MO Hessian couples alpha and beta IDPs. You need a single alpha, not a different alpha for each spin.
2. For the same reason, you need a single beta.
3. The Fock term assumed semicanonical orbitals. OCC does not use semicanonical orbitals.
4. The Fock matrix was acting on the wrong vector.
5. One of the tensor contractions …
=> Debug and Quarantine HF MO Hessian: OCC's Open-Heart Surgery V

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml, external/upstream/qcelemental/CMakeLists.txt, psi4/driver/p4util/python_helpers.py, psi4/driver/procrouting/proc.py, psi4/driver/schema_wrapper.py, psi4/src/psi4/cc/ccdensity/ccdensity.cc, psi4/src/psi4/detci/opdm.cc, psi4/src/psi4/libmints/oeprop.cc, psi4/src/psi4/libmints/oeprop.h, tests/cc46/input.dat, tests/cc54/input.dat, tests/cepa2/input.dat, tests/cepa3/input.dat, tests/ci-property/input.dat, tests/cisd-h2o+-1/input.dat, tests/fci-dipole/input.dat, tests/fci-tdm-2/input.dat, tests/fci-tdm/input.dat, tests/json/schema-1-properties/input.py, tests/mp2-property/input.dat, tests/pcmsolver/dipole/input.dat, tests/props2/input.dat, tests/props3/input.dat, tests/pytests/test_dipoles.py, tests/pytests/test_misc.py, tests/pytests/test_psi4.py, tests/python/cc54/input.py, tests/scf-property/input.dat
**EDIT** change of plans from first post. in order not to have to go from unique multipole elements (10 for octupole) to complete array (27) c-side and flat since P::e.globals restricted to Matrix, now only the compressed array is stored in globals/variables_ and that gets turned into (and back) the complete multidimensional ndarray when queried py-side. quadrupole has been turned back c-side to `(6)`, rather than `(3,3)` for consistency with the other poles.
=> dipole and quadrupole arrays and units

.azure-pipelines/azure-pipelines-linux.yml, tests/opt-irc-2/input.dat
This will temporarily disable installation and testing of `adcc`.
Current `psi4` and `adcc` do not seem to like each other (dependency issues with MKL and HDF5).
As discussed with @loriab, `adcc` will be re-enabled for tests upon reconciliation.
=> Temporarily disable adcc in tests

psi4/src/psi4/libsapt_solver/sapt.cc
This partially reverts #1823 and reopens #1820. The attempt to update OpenMP syntax caused  outrageous CPHF iterations for sapt  with more than one thread and for >double-zeta basis sets.
```
Iter     Energy [mEh]          dE [mEh]         Residual      Time [s]
1 -1328115.94527411 1328115.945274106   82108.848515395             1
2 -808873.32594920 -519242.619324907   43451.688666137             2
3 -296640.46386268 -512232.862086516   32804.415609124             3
4  333490.09801172 -630130.561874404   34046.370717066             4
5 1671552.17203003 -1338062.074018315   56004.396085803             4
6 13698345.73019254 -12026793.558162510  344787.457633287             5
7 -3546455.02303636 17244800.753228907   93826.473521208             6
8 -1533796.48314396 -2012658.539892400 …
```
=> fix threading in sapt cphf

psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/dfocc/get_moinfo.cc, tests/CMakeLists.txt, tests/mp2-h/CMakeLists.txt, tests/mp2-h/input.dat, tests/mp2-h/output.ref
MP2 energy for one-electron systems should be equal to HF energy.
=> Sanitise MP2 for one-electron systems

psi4/src/psi4/adc/adc.cc, psi4/src/psi4/dct/dct.cc, psi4/src/psi4/dfocc/dfocc.cc, psi4/src/psi4/occ/occwave.cc
Per discussion on the conference call, this PR gives some error messages for cases where using a serialized wavefunction would give a segfault. 1851 is still an issue, but one that shouldn't hold up 1.4 or eat my time to straighten out `dfocc`. I'm modernizing enough modules in Psi as it is...
=> Bandaid over 1851... Segfault to error message.

psi4/src/psi4/detci/ciwave.cc
A recent forum request needed to use serialized wavefunctions with `detci`. That's a very easy one, and one I can easily see myself needing as I start getting into some FCI benchmarking, so might as well fix it now.
I decided to use `_default_psio_lib_` rather than making a new PSIO object because `_default_psio_lib_` is used elsewhere in `detci`.
=> 1851 for `detci`

psi4/driver/p4util/text.py
fixes #1867 and introduces a minimal box width (30 chars).
```
!------------------------------------------------------------------!
!                                                                  !
! Unprocessable Molecule remanents under [psi4, xyz, xyz+, psi4+]: !
!  symmetry c1                                                     !
!  N                                                               !
!  N 1.500                                                         !
!                                                                  !
!------------------------------------------------------------------!
```
=> update error message box: preserve newlines

psi4/src/psi4/libsapt_solver/sapt.cc
fixes #1820 (another try)
The docs (https://www.openmp.org/spec-html/5.0/openmpse57.html) say that setting `OMP_NESTED=FALSE` means `max-active-levels-var=1`. The function switched from bool argument for `omp_set_nested()` to integer for `omp_set_max_active_levels`.
=> removed omp_set_nested() which is deprecated in OMP 5.0 

psi4/src/psi4/cc/ccenergy/rotate.cc
This PR fixes the segmentation fault of `CCEnergyWavefunction::rotation()` when there are frozen virtual orbitals.
=> Fix BCC if there are frozen virtual orbitals

.azure-pipelines/azure-pipelines-linux.yml, CMakeLists.txt, tests/scf-cholesky-basis/input.dat
MKL 2020.1 often selects a different basis fn set than 2019.4 or 2020.0, so answers often differ by 1.14e-8. This relaxes tolerance to 2.e-8. Alternative is to add `mkl!=2020.1` to `conda create` line, but this would be disruptive to conda packaging.
* **Note** A definitive test of above statement that returns to 1.e-8 but bans 2020.1 is running at https://dev.azure.com/psi4/psi4/_build/results?buildId=1969&view=logs&j=96451287-da82-57a8-2c11-8da7db9ab71a , but I'll get a head start and submit this PR.
=> accommodate mkl 2020.1 and cholesky-basis, take 5

psi4/driver/procrouting/proc.py, psi4/driver/qcdb/modelchems.py
On Python 3.8.2, I was getting the following warnings
```
/usr/lib/psi4/driver/qcdb/modelchems.py:95: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
text += """    %17s: %s\n""" (rol, cit.doi)
/usr/lib/psi4/driver/qcdb/modelchems.py:148: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
text += """    %17s: %s\n""" (rol, cit.doi)
/usr/lib/psi4/driver/qcdb/modelchems.py:170: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
text += """    %17s: %s\n""" (rol, cit.doi)
/usr/lib/psi4/driver/qcdb/modelchems.py:192: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
text += """    %17s: %s\n""" (rol, cit.doi)
/usr/lib/psi4/driver/procrouting/proc.py:1249: SyntaxWarning: "is" with a literal. Did you …
```
=> Fix warnings

external/upstream/ambit/CMakeLists.txt, external/upstream/pybind11/CMakeLists.txt, psi4/header.py, psi4/src/export_mints.cc, psi4/src/psi4/fnocc/coupled_pair.cc, psi4/src/psi4/occ/manager.cc, tests/pytests/standard_suite_runner.py, tests/pytests/test_standard_suite.py
=> LCCD standard suite, misc.

psi4/src/export_mints.cc, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libmints/mintshelper.h, tests/pytests/test_mints.py
Adds capabilities for overlap half-derivative integrals and exports them to Python side for use in calculating VCD
- None
=> Overlap Half-derivative Integrals

psi4/CMakeLists.txt, psi4/src/export_cubeprop.cc, tests/pytests/test_pyside_cubegen.py
This PR exposes the two functions `compute_orbitals` and `compute_density` from `CubeProperties` to the Python layer. This allows for more flexible dumping of cube files.
Example Code:
```Python
import psi4
import numpy as np
def test_cube_files(expected, computed):
expected = np.genfromtxt(expected, skip_header=9, skip_footer=1)
computed = np.genfromtxt(computed, skip_header=9, skip_footer=1)
np.testing.assert_allclose(expected, computed, atol=1e-14)
mol = psi4.geometry("""
O 0 0 0
H 0 0 1.795239827225189
H 1.693194615993441 0 -0.599043184453037
symmetry c1
units au
""")
psi4.core.be_quiet()
psi4.set_options({'basis': "sto-3g",
'scf_type': 'pk',
'cubeprop_tasks': ['density', 'orbitals']})
scf_e, wfn = psi4.energy('SCF', return_wfn=True)
psi4.cubeprop(wfn)
cubegen = …
```
=> Expose flexible cube generation to Python

psi4/src/psi4/libfock/solver.cc, psi4/src/psi4/libfock/solver.h
Fixes #1918 by removing the subspace preconditioner, per @robertodr's recommendation.
This also adds some more comments to the code, crucially, the fact that this solves the problem `Hx=b` as opposed to `Hx+b=0`. Signs are important.
=> CGRSolver Minor Commenting, Bug Fix

psi4/src/psi4/detci/opdm.cc, tests/pytests/test_detci_opdm.py
=> More TDMs from DETCI

psi4/CMakeLists.txt, psi4/src/psi4/dfmp2/README.txt, psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/dfmp2/mp2.h, tests/pytests/test_gradients.py
This PR closes #1916 and corrects a bug causing third-decimal errors in gradients computed by `dfmp2` with the frozen virtual approximation. See the commit marked "Bugfix!" to see exactly what the issue was. There was a sign error, and Rob was looping over frozen core orbitals when he meant to loop over frozen virtual orbitals.
More importantly for me, this code inserts many, many comments into Rob's code, so I know what I'm doing when I modify it throughout the rest of this PR series. This includes uncovering a very devious computational trick, that as far as I know is unpublished, and also some errors in the original papers. Many thanks to Francesco and Shuhe for the DSRG-PT2 paper, which formed part of the Rosetta Stone for figuring out how this code works.
Several explicit types are …
=> DFGrad II: Comment and Correct `dfmp2`

psi4/run_psi4.py
The main script (`run_psi4.py` in the source tree or `psi4` when installed) was importing qcelemental before it had a chance to modify the Python search path.  If you didn't already have a copy of qcelemental in your Python search path would cause an error. Encountered this on our cluster while trying to run the tests.
=> Moves import of qcelemental in main Psi4 script to be later in the file.

psi4/driver/procrouting/proc.py, psi4/driver/psifiles.py, psi4/include/psi4/psifiles.h, psi4/src/read_options.cc, tests/pytests/standard_suite_runner.py, tests/pytests/test_standard_suite.py
now we can have >1 detci test in the whole pytest suite
=> close detci files so independent psiapi calcs possible

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml, CMakeLists.txt, external/upstream/CMakeLists.txt, external/upstream/mdi/CMakeLists.txt, psi4/CMakeLists.txt, psi4/driver/__init__.py, psi4/driver/driver.py, psi4/driver/mdi_engine.py, psi4/run_psi4.py, tests/pytests/test_mdi.py
This PR enables Psi4 to interoperate on-the-fly with other codes via [The MolSSI Driver Interface (MDI)](https://github.com/MolSSI/MDI_Library).  MDI is an effort of [The MolSSI](https://molssi.org/) to improve and standardize the process of interoperating codes within the computational molecular sciences domain.
In particular, MDI supports interoperability within a driver-engine paradigm, in which a driver code controls the high-level operations of one or more engine codes, orchestrating complex calculations like QM/MM or advanced sampling.  This PR provides all functionality required for Psi4 to act as an MDI engine.  This makes it possible for external codes to exercise control over Psi4 in a manner similar to what is possible using Psi4’s existing API (albeit with a much smaller …
=> Enable interoperability via The MolSSI Driver Interface

psi4/src/core.cc, tests/fnocc4/input.dat
Assigning an int to an array variable accepts it as a one-item array, rather than throwing a fit. @robertodr, this should work for https://github.com/psi4/psi4/pull/1814#issuecomment-642655962. Feel free to just incorporate these lines into your TDDFT PR.
=> cast int to list for array variable

psi4/src/psi4/cc/ccdensity/ccdensity.cc, psi4/src/psi4/cc/ccdensity/sortone_RHF.cc, psi4/src/psi4/cc/ccdensity/sortone_UHF.cc
UHF CCSD gradients were crashing but only in subsequent jobs like the below. Culprit was freeing the opdm https://github.com/psi4/psi4/blob/master/psi4/src/psi4/cc/ccdensity/ccdensity.cc#L416. opdm wasn't getting set for UHF, but it wasn't null either for `free_block` to pass by. Is this a sensible solution?
```
molecule hf {
H
F 1 0.917
}
set reference rhf
gradient("ccsd/cc-pvdz", molecule=hf)
clean()
set reference uhf
gradient("ccsd/cc-pvdz", molecule=hf)
```
snapshot of what was getting set for the various references:
```
>>> grep O ccdensity/sortone* | grep -v OEI | grep O | grep opdm
ccdensity/sortone_RHF.cc:** matrix, O (moinfo.opdm), which we also symmetrize by computing Opq
ccdensity/sortone_RHF.cc:    moinfo.opdm = O;
ccdensity/sortone_ROHF.cc:** matrix, O (moinfo.opdm), which we …
```
=> fix UHF after RHF CCSD gradient crash

psi4/src/psi4/libmints/basisset.cc, tests/dfmp2-ecp/input.dat
In some basis sets that contain ECPs, the "valence" f-shell is included in the effective core. This seems true for all post-lanthanide/actinide atoms. 
In current master, those 60 ECP electrons are always frozen, but in a non-ECP basis with frozen core we'd freeze only 54 of those. The simple solution is to always freeze the 4f electrons (for 6th period) if the shell is full.
=> Fixed ECP and f-electron combinations.

psi4/src/core.cc, psi4/src/psi4/libpsi4util/process.cc, psi4/src/psi4/libpsi4util/process.h
The global `_default_psio_manager_` shared_ptr can destruct
before Process::Environment. However, some destructors called
from Process::Environment may require it. So have Process::Environment
keep a copy of the shared_ptr
Some tasks being run by QCArchive/QCEngine would hang indefinitely, even though the calculation finished. GDB showed memory corruption when destructing the Process::Environment.
The cause was related to the destructor for DIISManager calling PSIO::close
https://github.com/psi4/psi4/blob/8d1a8787504a481f61956fb22b282b6f30005ebc/psi4/src/psi4/libpsio/close.cc#L82 
`PSIOManager::shared_object()` returns a copy of the global shared_ptr `_default_psio_manager_`. The main issue is that `_default_psio_manager_` can be destructed before Process::Environment, as order of …
=> Keep _default_psio_manager_ alive for Process::Environment

psi4/driver/p4util/python_helpers.py, psi4/driver/p4util/testing.py, psi4/driver/procrouting/mcscf/mcscf_solver.py, psi4/driver/procrouting/proc.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/adc/adc.cc, psi4/src/psi4/cc/ccenergy/ccenergy.cc, psi4/src/psi4/dct/dct.cc, psi4/src/psi4/detci/ciwave.cc, psi4/src/psi4/dfep2/dfep2.cc, psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/dfocc/dfocc.cc, psi4/src/psi4/dmrg/dmrgscf.cc, psi4/src/psi4/fisapt/fisapt.cc, psi4/src/psi4/fnocc/ccsd.cc, psi4/src/psi4/fnocc/frozen_natural_orbitals.cc, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmints/wavefunction.h, psi4/src/psi4/libsapt_solver/sapt.cc, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/psi4/occ/occwave.cc, psi4/src/psi4/scfgrad/scf_grad.cc, tests/pytests/standard_suite_runner.py
Some info about module-level provenance of a Wfn would be handy.
=> module provenance of Wavefunction

CMakeLists.txt, external/downstream/CMakeLists.txt, external/downstream/cct3/CMakeLists.txt, psi4/driver/endorsed_plugins.py, psi4/driver/procrouting/proc.py, psi4/extras.py, psi4/src/psi4/liboptions/liboptions.cc, psi4/src/psi4/liboptions/liboptions.h, psi4/src/read_options.cc, tests/pytests/test_addons.py
Add cct3 plugin. Patch liboptions.
- this is connected with https://github.com/piecuch-group/psi4_cct3/pull/2
- note that cct3 builds slowly as it has some hefty fortran files
=> add cct3 plugin

psi4/driver/qcdb/molecule.py
Currently `mol.to_string` cuts off coordinate values `< 5**(-(ZERO))` which is actually `0.9999999999999839`. Switching `ZERO` to `prec` (with default value `12`) correctly dampens for printing, without collapsing all atoms within 1 unit of the center.
=> Fix zero damping in to_print

doc/sphinxman/source/dft.rst, psi4/driver/procrouting/dft/superfunctionals.py, psi4/src/export_functional.cc, psi4/src/psi4/libfunctional/LibXCfunctional.cc, psi4/src/psi4/libfunctional/LibXCfunctional.h, psi4/src/psi4/libfunctional/functional.cc, psi4/src/psi4/libfunctional/functional.h, psi4/src/psi4/libfunctional/superfunctional.cc, psi4/src/psi4/libfunctional/superfunctional.h, psi4/src/read_options.cc, tests/CMakeLists.txt, tests/dft-dens-cut/CMakeLists.txt, tests/dft-dens-cut/input.dat, tests/dft-dens-cut/output.ref
Enables screening of small densities using LibXC's built-in functionality. Enables user to set custom values. 
This fixes, e.g., issues with calculating the H-atom with many functionals.
----
Python API notes (as one would use in `superfunctionals.py`)
It is recommend to set the threshold via the SuperFunctional class
e.g. `sup[0].set_density_tolerance(1e-10) `
Alternatively one can set the threshold also via the LibXCFunctional class, and potentially
set individual thresholds for the components. Below sets the same threshold for all XC kernels.
```
dens_cut=core.get_option("SCF","DFT_DENSITY_TOLERANCE")
if sup[0].is_libxc_func():
sup[0].c_functionals()[0].set_density_cutoff(dens_cut)
else:
for x_func in …
```
=> Enables LibXC density screening

psi4/src/psi4/liboptions/liboptions.cc
This PR fixed a problem that prevents setting string options for modules when these are not defined to be global.
=> Fix issue in options class

psi4/src/psi4/cc/ccdensity/ccdensity.cc, psi4/src/psi4/cc/ccenergy/ccenergy.cc
When computing a gradient through the `cc` mega-module, the reference wavefunction's density would be overwritten with the correlated wavefunction's density. This was because the CCEnergyWavefunction's `Da_` and `Db_` were exactly the same objects as the reference wavefunction's. Of course changing the object associated with one variable name would change the object associated with the other variable name. They're the same object.
This PR makes them different objects, to stop this aberrant behavior.
Obligatory @lothian ping to confirm this shouldn't create other problems in the `cc` mega-module.
Obligatory @hokru ping because this should allow eliminating `recompute_scf_density` from #1884. Fixing up the DCT density is next.
Developers, please tag as bugfix and 1.4.
Notable points …
=> CC Density != SCF Density

psi4/src/psi4/dct/dct.h, psi4/src/psi4/dct/dct_compute_RHF.cc, psi4/src/psi4/dct/dct_compute_UHF.cc, psi4/src/psi4/dct/dct_density_RHF.cc, psi4/src/psi4/dct/dct_density_UHF.cc, psi4/src/psi4/dct/dct_gradient_UHF.cc
The DCT density, when available, is now on the wavefunction.
If you are an orbital optimized method, the density matrices can be computed without solving response equations. This is done in the new `construct_density_oo_UHF` method and its RHF sibling. This allowed me to migrate some code out of `compute_oe_properties`, which was only ever implemented for UHF.
If you are not an orbital optimized method, the density matrices must be computed after solving response equations (if implemented in Psi). This is done in the `compute_ewdm_dc` method, which was already responsible for assembling the OPDM in this case.
Obligatory @hokru ping, as this should clean up #1884.
=> DCT Density to Wavefunction

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/libfock/jk.h, psi4/src/psi4/libmints/mintshelper.h, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmints/wavefunction.h, psi4/src/psi4/liboptions/liboptions.h, psi4/src/psi4/scfgrad/scf_grad.cc
In master Psi, both the `Wavefunction` class and the `MintsHelper` class have their own copy of `basissets_`, a map from basis name to the actual `BasisSet`. There are `get_basisset`, `set_basisset`, and `basisset_exists` methods to manipulate `basissets_`, which are identical between the two classes. So `basissets_` and associated methods are functionally identical on the two classes.
The problem is that every `Wavefunction` object is already guaranteed to have a `MintsHelper` object, there is no reason for the `Wavefunction` object to ever have a different `basissets_` from its `MintsHelper` (because `Wavefunction`’s only use for `basissets_` is aforementioned methods), but there is no mechanism to synchronize the `basissets_` variables of a `Wavefunction` and its `MintsHelper`. So we …
=> Delegate `basissets_` Management to `wavefunction.mintshelper()`

psi4/driver/p4util/python_helpers.py, psi4/driver/procrouting/proc.py, psi4/driver/schema_wrapper.py, psi4/src/psi4/dfocc/manager.cc, psi4/src/psi4/dfocc/manager_cd.cc, psi4/src/psi4/fnocc/ccsd.cc, psi4/src/psi4/occ/manager.cc, psi4/src/psi4/occ/postprocessing.cc, psi4/src/psi4/scfgrad/wrapper.cc, setup.cfg, tests/pytests/standard_suite_runner.py, tests/pytests/test_detci_opdm.py, tests/pytests/test_standard_suite.py
=> standard suite mp3 & co

psi4/src/psi4/dfmp2/corr_grad.cc, psi4/src/psi4/dfmp2/corr_grad.h, psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/dfocc/tei_grad.cc, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libmints/mintshelper.h, psi4/src/psi4/scfgrad/jk_grad.cc, psi4/src/psi4/scfgrad/jk_grad.h, psi4/src/psi4/scfgrad/scf_grad.cc
Previously, the `dfocc`, `dfmp2` and `scfgrad` modules all had nearly identical code to compute the **metric term** of density fitted gradients, the contraction against the metric integral derivatives. `dfmp2` even did this _twice_ for a total of 4 times near identical logic appears. (It was 5 before #1953.) This PR consolidates those into a single `MintsHelper` method.
=> DFGrad IV: Consolidate Metric Gradient

psi4/src/psi4/libsapt_solver/usapt0.cc, tests/CMakeLists.txt, tests/sapt10/CMakeLists.txt, tests/sapt10/input.dat, tests/sapt10/output.ref
This PR is a follow up of PR #1948 and resolves issue #1830.
It covers the corner case where zero spin block occurs in USAPT0 mp2_term due to freezing the core.
=> Usapt0 spin fix fcore

.azure-pipelines/azure-pipelines-linux.yml, psi4/src/psi4/libfock/PKmanagers.cc, psi4/src/psi4/libfock/PKmanagers.h
The PK(reordered, disk) algorithm was using twice as much memory as it should.
This is due to not deleting integral and disk-space buffers correctly:
* During the pre-iterations the `batch size` buffer that prepares the disk space ("pre-striping", within `zero_disk`) and used during the SCF for processing the integrals on disk is not released. 
* The `buffer size` buffer that is used to calculate the integrals is not released after the computation is done
Both buffers are actually the same size and effectively lead to a doubling of the memory demand.
=> PK memory fixes

psi4/src/psi4/libmints/extern.cc, tests/CMakeLists.txt, tests/extern3/CMakeLists.txt, tests/extern3/input.dat
Fixes calculation of nuclear-nuclear interaction energy if a QM/MM point charge and a Ghost atom are at the same position as in the example below. Since a Ghost atom has no nuclear charge, it should not contribute. At any other position apart from the nuclear centers, it would not contribute. But since at this position, the distance between the Ghost and the atom is zero such that the current code wrongly produces a NaN energy.
Setups like this are relevant for [alchemical calculations](https://dx.doi.org/10.1103/PhysRevResearch.2.023220) where fractional nuclear charges are required.
```
molecule mol {
@N 0. 0. 1.
N 0. 0. 0.
no_reorient
no_com
symmetry c1
-7 1
}
Chrgfield = QMMM()
Chrgfield.extern.addCharge(7.05, 0., 0., 1.)
psi4.set_global_option_python('EXTERN', Chrgfield.extern)
set …
```
=> Skip Ghost-Nuclear interaction

.azure-pipelines/azure-pipelines-linux.yml, doc/sphinxman/source/occ.rst, external/upstream/qcelemental/CMakeLists.txt, external/upstream/qcengine/CMakeLists.txt, psi4/driver/procrouting/proc.py, psi4/src/psi4/dfocc/dfocc.cc, psi4/src/psi4/occ/cepa_iterations.cc, psi4/src/psi4/occ/occ_iterations.cc, psi4/src/psi4/occ/occwave.cc, psi4/src/read_options.cc, tests/ci-multi/input.dat, tests/mp2p5-grad1/input.dat, tests/mp2p5-grad2/input.dat, tests/mp3-grad1/input.dat, tests/mp3-grad2/input.dat, tests/pytests/standard_suite_runner.py, tests/pytests/test_detci_opdm.py, tests/pytests/test_standard_suite.py, tests/pywrap-alias/input.dat
=> shift mp2.5 and mp3 default from conv to df

doc/sphinxman/source/glossary_psivariables.rst, psi4/driver/procrouting/scf_proc/scf_iterator.py
The number of electrons as integrated on the DFT quadrature is printed as "Post-Iterations" quantity.
Current formatting:
```
Energy and wave function converged.
==> Post-Iterations <==
electrons on quadrature grid:
NTotal =    2.0000000000 ; deviation = -7.638e-14
Orbital Energies [Eh]
---------------------
--
electrons on quadrature grid:
Nalpha   =    5.9997499893 ; deviation = -2.500e-04
Nbeta    =    4.9997504300 ; deviation = -2.496e-04
NTotal   =   10.9995004192 ; deviation = -4.996e-04
@Spin Contamination Metric:   2.559910084E-05
```
=> prints electron count on quadrature grid

psi4/include/psi4/psifiles.h, psi4/src/export_trans.cc, psi4/src/psi4/detci/ints.cc, psi4/src/psi4/libtrans/README.txt, psi4/src/psi4/libtrans/integraltransform.cc, psi4/src/psi4/libtrans/integraltransform.h, psi4/src/psi4/libtrans/integraltransform_functors.h, psi4/src/psi4/libtrans/integraltransform_moinfo.cc, psi4/src/psi4/libtrans/integraltransform_oei.cc, psi4/src/psi4/libtrans/integraltransform_sort_so_tei.cc, psi4/src/psi4/occ/trans_ints_rhf.cc, psi4/src/psi4/occ/trans_ints_uhf.cc, tests/dft-ghost/input.dat
This PR does some miscellaneous cleanup of the OEI part of `libtrans` and will probably lead to another series of smaller PRs involving `libtrans`. The focus of this PR is to take away from `libtrans` responsibility for creating unused or barely used one-electron objects.
=> OEI libtrans Cleanup

psi4/driver/driver_cbs.py, psi4/src/psi4/dfocc/ccsd_triples.cc, psi4/src/psi4/dfocc/dfocc.cc, psi4/src/psi4/fnocc/df_ccsd.cc, psi4/src/psi4/fnocc/frozen_natural_orbitals.cc
=> minor patches for fnocc and dfocc

psi4/src/psi4/libfunctional/superfunctional.cc
All credit to @hokru . This fixes runtime errors seen on Mac with clang 10
=> fix vv10 for clang10

psi4/CMakeLists.txt, psi4/driver/procrouting/proc.py, psi4/driver/schema_wrapper.py, psi4/src/psi4/cc/ccresponse/ccresponse.cc, psi4/src/psi4/cc/ccresponse/optrot.cc, psi4/src/psi4/cc/ccresponse/polar.cc, psi4/src/psi4/cc/ccresponse/roa.cc, tests/cc46/input.dat, tests/cc46/output.ref, tests/pytests/test_ccresponse.py
Adds the tensors generated from the CC response code to the reference wave function, eventually to be included in the JSON output for a [QCEng](https://github.com/molssi/qcengine) run. Also patched CC-level dipoles and (static) quadrupoles in `proc.py` to be consistent with other naming conventions, allowing them to pass through `schema_wrapper.py`. This means that all (ground state, static) CC one-electron properties should follow the naming convention used on wfn. Old excited state (EOM) and dynamic property variables remain unchanged. 
Updates to the schema wrapper to allow the other tensors though are coming in a separate PR.
=> CC response vars to wfn: polar, optrot, quadrupole

.azure-pipelines/azure-pipelines-linux.yml, CMakeLists.txt, external/upstream/pybind11/CMakeLists.txt, psi4/driver/driver_cbs.py, psi4/driver/procrouting/proc.py, psi4/share/psi4/plugin/ambit/CMakeLists.txt.template, psi4/share/psi4/plugin/aointegrals/CMakeLists.txt.template, psi4/share/psi4/plugin/basic/CMakeLists.txt.template, psi4/share/psi4/plugin/dfmp2/CMakeLists.txt.template, psi4/share/psi4/plugin/mointegrals/CMakeLists.txt.template, psi4/share/psi4/plugin/scf/CMakeLists.txt.template, psi4/share/psi4/plugin/sointegrals/CMakeLists.txt.template, psi4/share/psi4/plugin/wavefunction/CMakeLists.txt.template
=> pybind11 v2.6, cbs dedup, enable_xhost

psi4/src/psi4/libciomr/libciomr.h, psi4/src/psi4/libciomr/long_int_array.cc, psi4/src/psi4/libtrans/integraltransform_sort_mo_tpdm.cc
Fix memory bug in libtrans for large cases.
=> solved memory bug in libtrans when bucketSize exceeds an int

psi4/src/psi4/dfmp2/mp2.cc
Fixes a bug reported by @hokru, where PSIO errors would result for large DFMP2 gradient computations. I forgot to rename a PSIO entry during #1923. 
This bug wasn't any more serious because it would only trigger when a block-based algorithm requested multiple blocks. For DFMP2, this would be a large computation indeed.
=> Fix bug in large dfmp2

psi4/src/psi4/libpsio/error.cc
Redirects the PSIO errors from `stderr` to exception message (stderr and normal output).
Essentially addressing #2019 and #1965.
Example print:
```
!----------------------------------------------------------------------------------!
!                                                                                  !
! Fatal Error: PSIO_ERROR: 5 (open call failed)                                    !
!  Check the location of your scratch directory which can be                       !
!  specified via the $PSI_SCRATCH environment variable or in                       !
!  the $HOME/.psi4rc file.                                                         !
!  Please note that the scratch directory must exist and be                        !
!  writable by Psi4 …
```
=> Better visible PSIO errors

doc/sphinxman/source/oeprop.rst, psi4/driver/p4util/python_helpers.py
This PR updates the MBIS documentation to match the state of the code. Missing logic to reshape the mbis multipoles was also added, which previous tests don't check for, but is necessary when running psi4's mbis through qcengine.
=> Fix MBIS docs and multipole shapes

psi4/driver/schema_wrapper.py, tests/pytests/test_qcschema.py
SCF orbital occupations are a required field for the wavefunction qcschema. This PR makes sure Psi4 populates the field. Addresses #1987
=> add orbital occupations to qcschema wavefunction

doc/sphinxman/source/fchk.rst, psi4/CMakeLists.txt, psi4/driver/__init__.py, psi4/driver/driver.py, psi4/driver/p4util/CMakeLists.txt, psi4/driver/p4util/fchk.py, psi4/src/export_mints.cc, psi4/src/psi4/dfocc/get_moinfo.cc, psi4/src/psi4/libmints/writer.cc, psi4/src/psi4/libmints/writer.h, tests/pytests/conftest.py, tests/pytests/test_fchk_writer.py, tests/pytests/utils.py
Tries to set the correct density label and solves some bugs with writing the incorrect densities.
Relates issue: #1272 
=> improvements to the FCHK writer

psi4/src/psi4/dfocc/dfgrad.cc, psi4/src/psi4/dfocc/dfocc.h, psi4/src/psi4/dfocc/oei_grad.cc, psi4/src/psi4/dfocc/tei_grad.cc
Part of the DF Gradient refactor. It's become clear that Rob's implementation of the DF-MP2 gradients can't be generalized without incurring a performance hit, so the scope of the project now is to generalize what `dfocc` does out of `dfocc` so other modules (like `dct`) can use it. The current step of that is to make the procedure independent of `dfocc` globals.
While I was at it, I got rid of unneeded headers and did some other minor code cleanup.
=> Eliminate gradient globals from `dfocc`

psi4/src/psi4/libfock/cubature.cc
Fixes a bug where a Becke grid is used instead of Treutler in case a Treutler grid was requested.
=> Build Treutler grid if asked to do so.

psi4/driver/p4util/python_helpers.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/libmints/deriv.cc, psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmints/wavefunction.h
This PR follows the change of PR #2064.
To avoid compilation errors for any downstream packages, `Lagrangian()` and `X()` in the `Wavefunction` class have been marked deprecated instead of removing them.
Future code should use lowercase `lagrangian()` and `set_lagrangian()` to obtain and set the orbital Lagrangian matrix (both C++ and Python), respectively.
=> Mark Lagrangian and X as deprecated

psi4/src/psi4/libmints/extern.cc
During the L2 upgrade, I missed the function that handles diffuse external multipoles.  In constructing a test case to avoid a repeat, I found some normalization problems (and a lack of gradients) which will be addressed in a followup PR.  H/T to @g-andres and his group for pointing the problem out.
=> Fix diffuse external potential after L2 upgrade

psi4/driver/p4util/python_helpers.py, psi4/driver/p4util/testing.py
can't have internal `.X()`s or the string deprcation warning triggers and mints8 fails.
=> lagrangian saga continues. fixes mints8

psi4/src/psi4/dfocc/back_trans.cc, psi4/src/psi4/dfocc/dfgrad.cc, psi4/src/psi4/dfocc/dfocc.h, psi4/src/psi4/dfocc/tpdm_tilde.cc
This PR eliminates 600+ duplicate lines of code from `dfocc`, as well as two functions. This cleans up a near-future PR of mine.
Obligatory @loriab ping.
=> Remove more `dfocc` code duplication

psi4/src/psi4/cc/ccresponse/roa.cc
Corrects a minor bug in the coupled cluster ROA code.
=> Fixing minor bug in ccresponse/roa.cc.

psi4/src/psi4/dct/dct.h, psi4/src/psi4/dct/dct_compute_RHF.cc, psi4/src/psi4/dct/dct_compute_UHF.cc, psi4/src/psi4/dct/dct_df_tensor.cc
This PR removes ~300 lines worth of duplicate code in `dct`'s density-fitting, as well as some class variables that had no business being class variables.
This is in preparation for an upcoming PR to fix a longstanding bug in the density-fitted code.
=> Remove code duplication in B matrix construction in DF-DCT.

psi4/CMakeLists.txt, psi4/src/psi4/libmints/matrix.cc, tests/pytests/test_triplet.py
linalg::triplet currently does matrix multiplication in the same order (AB)C. Sometimes, A(BC) may be more efficient, per observation of @zachglick
=> Optimize linalg::triplet matrix multiply

psi4/CMakeLists.txt, psi4/src/psi4/libfock/CDJK.cc, psi4/src/psi4/libfock/DiskDFJK.cc, psi4/src/psi4/libfock/DiskJK.cc, psi4/src/psi4/libfock/GTFockJK.cc, psi4/src/psi4/libfock/MemDFJK.cc, psi4/src/psi4/libfock/PKJK.cc, psi4/src/psi4/libfock/PK_workers.cc, psi4/src/psi4/libfock/PKmanagers.cc, psi4/src/psi4/libfock/apps.cc, psi4/src/psi4/libfock/cubature.cc, psi4/src/psi4/libfock/hamiltonian.cc, psi4/src/psi4/libfock/jk.cc, psi4/src/psi4/libfock/points.cc, psi4/src/psi4/libfock/solver.cc, psi4/src/psi4/libfock/soscf.cc, psi4/src/psi4/libfock/wrapper.cc, tests/pytests/test_raises.py
It looks like errors like #2080 happen when `throw` called from within threaded code in C++. From non-threaded code, Pybind11 catches them and turns them into nicely behaved `RuntimeError`s but from threaded, it just segfaults. This PR averts a few, but there could be far more throughout codebase
closes #2080
=> precheck atoms for grids

psi4/run_psi4.py
Fixes special case of traceback printing where only lineno available is from `exec(content)`, which is useless. This fixes #1920 . We don't get Jonathon's nice `-->` offending line printing, but at least we don't get a new error. I've tried it on `print("asdf")` and some more common mistakes.
```
Traceback (most recent call last):
File "/psi/gits/hrw-py39/objdir39/stage/bin/psi4", line 337, in <module>
exec(content)
File "<string>", line 26
print "asdf"
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("asdf")?
Printing out the relevant lines from the Psithon --> Python processed input file:
!----------------------------------------------------------------------!
!                                                                      !
!  Missing parentheses in call …
```
=> cleaner print for module level errors

.azure-pipelines/azure-pipelines-linux.yml, psi4/src/export_mints.cc, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libmints/mintshelper.h
Exactly what it says in the title. New `libmints` functions mean a @jturney ping, and new functions messing with integrals mean an @andysim ping.
Also, a positive LoC PR. Sad.
=> Create and Python-expose functions for the DF deriv integrals

tests/pytests/conftest.py, tests/pytests/test_triplet.py
once more, try for a clean conda build
=> remove time test  for multithread

doc/sphinxman/source/numpy.rst, psi4/driver/p4util/numpy_helper.py
Address issue #2087. Specifically:
On `numpy.rst`:
1) Updated Numpy quickstart guide link
2) Updated Psi4Numpy Repo link
3) Updated psi4.{Matrix, Vector, Dimension} -> psi4.core.{Matrix, Vector, Dimension}
4) Added link to Psi4's Symmetry quick guide
On `numpy_helper.py`:
1) Updated docstring example to `psi4.core.Matrix`. 
https://github.com/psi4/psi4/blob/master/psi4/driver/p4util/numpy_helper.py#L99 with:
```
>>> data = np.random.rand(20,1)
>>> vector = psi4.core.Matrix.from_array(data)
```
My concern is that the example would not be calling the function directly. What would be the best way to proceed?
=> Update to "Interface to Numpy"

psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/libmints/eri.h, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/matrix.h, psi4/src/psi4/libmints/siminteri.h
While working on some more DF technology, I discovered a bug when trying to load using `Matrix::SaveType::Full`. The code assumed the matrix was square. One of the things this PR does is have the code work when that assumption fails.
But the bigger problem is that `Matrix::SaveType::Full` is Psi3 era tech that shouldn't exist anymore. That SaveType reads/writes a matrix _where all elements of the wrong symmetry are replaced with zeros_. The better solution is to use `Matrix::SaveType::SubBlocks`, where those zero's are neither written nor read. Accordingly, I'm deprecating the Full save in favor of SubBlocks save.
=> Deprecate `Matrix::SaveType::Full`

psi4/src/psi4/cc/amps.cc, psi4/src/psi4/cc/ccenergy/get_params.cc, psi4/src/psi4/libmints/integral.h, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libmints/mintshelper.h, psi4/src/psi4/libmints/onebody.cc, psi4/src/psi4/libmints/transform.cc
This PR introduces a fix to the `get_amplitudes` method used to export T1 and T2 amplitudes to python, which allows the method to work properly when frozen-core coupled-cluster calculations are requested.
=> Fixes get_amplitudes method when requesting frozen-core CC calculations

psi4/src/psi4/occ/coord_grad.cc, psi4/src/psi4/occ/occwave.h
While cleaning out old branches, I noticed a small `occ` cleanup: the H integrals written to disk are no longer used. Accordingly, we can just remove the code responsible for it.
=> Remove Useless `occ` Code

psi4/src/core.cc
I was investigating the "memory not being released" problem that @fevangelista brought up at the developer meeting. For the case of a simple HF energy, the wavefunction object indeed persisted after the energy call. Investigation showed its lifetime was controlled by the fact that we had the legacy wavefunction stored, and garbage collection didn't occur until the legacy wavefunction changed.
Seeing as we don't actually use the legacy wavefunction machinery for anything in Psi, except part of a plugin interface where we tell people to prefer explicit wavefunction passing, this PR deprecates the commands for removal in 1.5, so we can collect garbage faster.
This PR doesn't explain Francesco's reports of _increasing_ memory consumption for FINDIF, but it at least is a start.
=> Deprecate `legacy_wavefunction` getter and setter

CMakeLists.txt, external/upstream/libxc/CMakeLists.txt, psi4/driver/procrouting/scf_proc/CMakeLists.txt, psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/driver/procrouting/solvent/CMakeLists.txt, psi4/driver/procrouting/solvent/efp.py
This PR refactors EFP routines such that they use the mints functions I implemented for PE a while ago.
Less code and a significant speed-up for the electric field integral evaluations.
=> Simplify EFP routines

psi4/src/psi4/libmints/basisset.cc
Fixes a typo in the basis set output.
=> Basis functions should be in plural

psi4/driver/schema_wrapper.py, tests/pytests/test_qcschema.py
Fixes a bug that occurs when one runs `psi4 --qcschema` and requests that the wavefunction is returned. 
Before the orbitals / fock matrix / etc. are returned, all AO-indexed tensors are sorted according to CCA ordering: `Ca` and `Cb` are dimension [AO x MO], so their rows are sorted. `Fa`, `Fb`, `Da`, and `Db` are all dimension [AO x AO], so they are sorted by both row and column. `epsilon_a` and `epsilon_b` are not AO-indexed, so they shouldn't be sorted at all.
As an example, the following HF calculation has fewer MOs than AOs because of linear dependencies, and Psi4 will throw an error when `epsilon_a` is treated as if it were of length AO:
```
import psi4
ret = psi4.schema_wrapper.run_qcschema({
"molecule": {
"geometry": [
0.0, 0.0, -0.1294769411935893,
0.0, -1.494187339479985, …
```
=> qcschema export bug fix

doc/sphinxman/source/tdscf.rst, psi4/src/psi4/libfock/jk.cc, psi4/src/psi4/libmints/matrix.h, tests/pytests/test_tdscf_products.py
This PR fixes a bug causing TD-DFT and stability analysis to give incorrect results (or diverge) when used with density-fitting and symmetry : more generally, the bug occurs any time JK objects used back-transformed C matrices that weren't totally symmetric.
This is ultimately an issue of orbital indexing. When the left index of the generalized C matrix is back-transformed from SO to AO, the blocks need to be flattened together. The code previously combined the blocks from smallest h to lowest h. So columns of irrep `h ^ symmetry_` appear _in order of h ascending_, with the left C assumed totally symmetric. The matrices have different orbital indexing if your right C `symmetry_` is not totally symmetric! This produced inconsistencies when contracting quantities against each other that …
=> Fix DF+Symmetry TD-SCF/Stability by Fixing JK

psi4/src/psi4/libmints/eri.cc, tests/v2rdm_casscf/v2rdm4/input.dat
Disables libint2's primitive screening via the `engine_precision` parameter. This integral screening provided a minor speedup, but in rare cases led to disastrously wrong SCF behavior as noted in #2114 and [here](https://github.com/edeprince3/hilbert/issues/8). This pull request closes those issues.
Note that this primitive screening is independent of the shell-pair level Schwarz and CSAM screening performed in Psi4. The previous workaround to this problem, which was to set the `ints_tolerance` keyword to 0.0, is no longer necessary.
=> Disable libint2 Primitive Screening

psi4/driver/driver_cbs.py, tests/CMakeLists.txt, tests/fnocc6/CMakeLists.txt, tests/fnocc6/input.dat, tests/tdscf-5/CMakeLists.txt, tests/tdscf-5/input.dat
This PR fixes a bug when the `method/basis` specification is used in conjunction with DiskDF (i.e. when the reference wfn is passed on to, e.g. TDSCF or FNOCC).
Fixes #1604.
New test cases added that would trigger the original problem.
=> Fix method/basis bug with DiskDF

psi4/driver/driver_cbs.py, psi4/src/psi4/cc/cctriples/ET_RHF.cc, tests/cbs-delta-energy/input.dat
collection of small changes (see below)
You can calculate the contribution of any delta correction using the db function:
```
dcbs=[{"wfn": "hf", "basis": "cc-pvdz"}, {"wfn": "mp2", "basis": "cc-pVDZ"}, {"wfn": "ccsd(t)","wfn_lo":"ccsd", "basis": "minix"}]
db(cbs,'hbc6',cp='on',cbs_metadata=dcbs,subset='small',tabulate=['CBS DELTA1 TOTAL ENERGY'])
```
=> miscellaneous updates

psi4/src/psi4/cc/ccenergy/ccenergy.cc
This PR fixes a bug where a coupled cluster computation that diverges triggers a further bug in the timer system. A fatal error is now triggered instead.
Closes #1864.
=> Close #1864

.github/workflows/docs.yml
Fix problem @JonathonMisiewicz hit where the GHA docs runs on master branch of forks. Someday there ought to be a more concise way to filter https://github.com/actions/runner/issues/662.
=> only run GHA at psi4 org, not forks

psi4/CMakeLists.txt, psi4/src/CMakeLists.txt
Debug symbols where being mistakenly striped from the core python module.
=> Restores debug symbols in Debug/RelWithDebInfo

psi4/src/export_mints.cc, psi4/src/psi4/dct/dct.h, psi4/src/psi4/dct/dct_integrals_RHF.cc, psi4/src/psi4/dct/dct_integrals_UHF.cc, psi4/src/psi4/dct/dct_intermediates_RHF.cc, psi4/src/psi4/dct/dct_intermediates_UHF.cc, psi4/src/psi4/dct/dct_memory.cc, psi4/src/psi4/dct/dct_oo_RHF.cc, psi4/src/psi4/dct/dct_oo_UHF.cc, psi4/src/psi4/dct/dct_qc.cc, psi4/src/psi4/dct/dct_scf_UHF.cc, psi4/src/psi4/dct/dct_tau_RHF.cc, psi4/src/psi4/dct/dct_tau_UHF.cc, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/matrix.h
This is the first of what will likely be quite a few cleanup PRs in `dct`, in preparation for some features I'd like for 1.5.
This PR creates variants of existing constructors in `libmints`. We're no longer forced to use `SharedMatrix` in `set_block`, and we can now pass a single `Slice` object to `get_block` or `set_block` to use it for both rows and columns.
This PR can be moved to 1.5 if needed. I can also opt for fewer but longer PRs if needed.
=> Misc. DCT Cleanup, `libmints` Function Variants

psi4/src/psi4/dct/dct_oo_UHF.cc, tests/dct-grad1/input.dat, tests/dct6/input.dat, tests/dct7/input.dat
Lori brought to my attention that my previous PR accidentally introduced a bug causing tests to fail. (It was an obvious indexing bug.) That is now fixed.
In the interests of making test-running less onerous, I've also changed the test cases so that I can run all `dct` tests faster. We're checking things less tightly and using smaller basis sets.
=> Bugfix and Test Shortening

devtools/conda-envs/docs-cf.yaml, psi4/src/psi4/libfunctional/LibXCfunctional.cc, psi4/src/psi4/libfunctional/functional.cc, psi4/src/psi4/libfunctional/functional.h, psi4/src/psi4/libfunctional/superfunctional.cc, psi4/src/psi4/libfunctional/superfunctional.h
See Libxc version and citation. looks like below. I'd have to add `xc.h` to another file to put the printing in a nicer place. @susilehtola 
```
==> Algorithm <==
SCF Algorithm Type is DF.
DIIS enabled.
MOM disabled.
Fractional occupation disabled.
Guess Type is SAD.
Energy threshold   = 1.00e-06
Density threshold  = 1.00e-06
Integral threshold = 1.00e-12
==> Primary Basis <==
Basis Set: CC-PVDZ
Blend: CC-PVDZ
Number of shells: 12
Number of basis functions: 24
Number of Cartesian functions: 25
Spherical Harmonics?: true
Max angular momentum: 2
==> LibXC v5.1.2, S. Lehtola, C. Steigemann, M. J. Oliveira, and M. A. Marques, SoftwareX 7, 1 (2018) (10.1016/j.softx.2017.11.002) <==
==> DFT Potential <==
=> Composite Functional: B3LYP <= 
B3LYP Hyb-GGA Exchange-Correlation Functional
P. J. …
```
=> add Libxc printing

doc/sphinxman/source/bibliography.rst, doc/sphinxman/source/glossary_psivariables.rst, doc/sphinxman/source/manage_git.rst, doc/sphinxman/source/scf.rst, psi4/src/core.cc, psi4/src/psi4/libfock/cubature.cc, psi4/src/psi4/libmints/oeprop.cc
Even though Intel+defaults conda gcc7.3, azure gcc-s, and c-f conda gcc9 are perfectly fine with it, defaults conda gcc7.3 as primary compiler segfaults if the `py_psi_get_atomic_point_charges` fn is removed. I don't understand it, but I will appease it. All other changes are fixing stray non-ascii chars, since that's one of my routine steps when things don't make sense. Checking full tests locally.
EDIT: full tests clean
=> odd gcc and atomic_point_charges segfault

tests/mcscf2/input.dat
I've just watched this test take 84--120 iterations to converge over consecutive runs. Lately for py38 conda package it has needed 121, failing the whole thing. So I'm adding extra cushioning. The output.ref is 88, so nothing new. Also the MKL_CBWR=AVX seems on average to increase the iterations needed.
=> mcscf2 stability

psi4/driver/procrouting/dft/dft_builder.py
Part of #2142 that will let CI on https://github.com/MolSSI/QCEngine/pull/291 happen correctly. That is, `import psi4` in the presence of `dftd4-python` python pkg.
=> allow doi as dispersion citation

.github/workflows/docs.yml, doc/sphinxman/source/conf.py.in
=> fix docs again

psi4/src/psi4/dct/dct_compute_RHF.cc, psi4/src/psi4/dct/dct_oo_RHF.cc, psi4/src/psi4/dct/dct_scf_RHF.cc
The next bite-sized DCT cleanup PR. To construct an intermediate `Fa_` and `Fb_`, previously, we'd divide the term in three parts, compute the three contributions separately, and then add them together. Making things more complicated, we add the pieces in different functions. In the RHF case, this PR combines two of those terms from the outset, so there are only two contributions to add.
As a result, we now construct fewer `double*`, use fewer class variables, and have less cause to worry about whether the intermediates `Fa_` and `Fb_` are completely or incompletely constructed. While I haven't run timings, this code should also be faster due to reduced random-access of arrays.
The UHF code is more complicated, so that's best saved for another PR. At that point, I hope to eliminate a few …
=> Simplify RDCT Fock Matrix Construction

psi4/src/export_mints.cc
This PR changes the docstring for `mo_eri` to describe how it behaves with symmetry among your orbitals.
=> Be more detailed in documentation for `mo_eri`

psi4/src/psi4/dct/dct_compute_UHF.cc, psi4/src/read_options.cc
Another tiny one, in case anybody objects to my lack of deprecation.
The old keyword `relax_tau` in `dct` is eliminated. This was marked expert, was rarely a good idea to use, and wasn't consistently applied throughout the code. This keyword was implemented as a way to explore alternate convergence strategies that would have been done in P4N, nowadays.  Because this is fairly obscure code to boot, I'm eliminating it now with no formal deprecation strategy.
=> Remove relax_tau

.azure-pipelines/azure-pipelines-linux.yml, psi4/src/psi4/dct/dct.h, psi4/src/psi4/dct/dct_compute_UHF.cc, psi4/src/psi4/dct/dct_integrals_UHF.cc, psi4/src/psi4/dct/dct_memory.cc, psi4/src/psi4/dct/dct_oo_UHF.cc, psi4/src/psi4/dct/dct_qc.cc, psi4/src/psi4/dct/dct_scf_UHF.cc
The UHF version of #2171. The open-shell DCT code now adds two terms before contracting them against the two-electron integrals, rather than after. Unfortunately, this change was tightly coupled to surrounding code, making it unnecessarily complicated. This PR also removes that complexity. Again, I'd expect this code to be faster due to reduced random access in `process_so_integrals`, but I haven't run timings.
=> Simplify UDCT Fock Matrix Construction

doc/sphinxman/source/external.rst, doc/sphinxman/source/glossary_psivariables.rst, psi4/include/psi4/psifiles.h, psi4/src/psi4/cc/ccdensity/get_moinfo.cc, psi4/src/psi4/cc/ccenergy/ccenergy.cc, psi4/src/psi4/cc/ccenergy/get_moinfo.cc, psi4/src/psi4/cc/cceom/get_moinfo.cc, psi4/src/psi4/cc/cchbar/get_moinfo.cc, psi4/src/psi4/cc/ccresponse/get_moinfo.cc, psi4/src/psi4/cc/cctriples/get_moinfo.cc, psi4/src/psi4/libpsio/init.cc
This PR removes the files `PSIF_CHKPT` and `PSIF_OLD_CHKPT`, as well as references to them elsewhere in the docs and the code. These were unused and caused some confusion in a [recent forum topic](http://forum.psicode.org/t/cannot-retain-scratch-file/2181/4).
=> Remove evidence of defunct CHKPT

psi4/src/psi4/optking/optking.cc
A minor bugfix in optking: internal coordinate files are now kept after a successful optimization.
I'm well-aware that the days of C-Optking are numbered, but I came across this when investigating a tangentially related bug report in forums, so I might as well fix it.
=> keep_intcos works for successful optimization

psi4/src/psi4/libmints/mintshelper.cc
Closes #2192 : a correctness error in threaded correlated DF gradients accidentally introduced during my refactoring. I recommend making a new release candidate sooner rather than later. Sorry, Lori.
=> Major bugfix! Parallelization error in DF gradients

psi4/include/psi4/psifiles.h
Exactly what it says in the title.
There will need to be another docs cleanup to elaborate on the workings of `set_specific_retention` and orbital passing, but I think @hokru has a PR in the works that will be changing that.
=> Remove more unused psifiles

psi4/driver/procrouting/proc.py, psi4/driver/procrouting/response/scf_response.py, psi4/src/read_options.cc
This adds further output to TDSCF and TDDFT calculations, including electric TDM vectors and the excitations and deexcitations that contribute to each excited state. Currently, excitations / deexcitations are only printed for C1 symmetry.
A new option TDSCF_COEFF_CUTOFF (default = 0.1) has been added that sets the cutoff for printing excitation / deexcitation coefficients.
=> Print extra output from TDSCF / TDDFT calculations

psi4/src/core.cc, psi4/src/create_new_plugin.cc, psi4/src/export_mints.cc, psi4/src/psi4/libfunctional/superfunctional.cc, psi4/src/psi4/libmints/basisset.cc, psi4/src/psi4/liboptions/liboptions.cc, psi4/src/psi4/libplugin/load_plugin.cc, psi4/src/psi4/libpsio/filescfg.cc
This is a simple aesthetic cleanup to make the printout more systematic.
If I define the xc functional inline as e.g.
```
my_dft = {
"name": "my lda",
"x_functionals": {"lda_x": {}},
"c_functionals": {"lda_c_pw": {}}
}
energy('scf', dft_functional=my_dft)
```
the capitalization is inconsistent in the output
```
=> Exchange Functionals <=
1.0000         XC_lda_x
=> Correlation Functionals <=
1.0000      XC_lda_c_pw
```
=> Capitalize names of XC functionals

psi4/src/psi4/libmints/basisset.cc, tests/dfmp2-ecp/input.dat, tests/dfmp2-ecp/output.ref
This PR fixes a part of #2012, where requesting to freeze n-th fixed previous shell (using `set freeze_core -n` syntax) would happily carry on, even if an ECP present on a certain atom would substitute more electrons than in the n-th shell. This means the example in #2012 using `freeze_core -2` now throws an exception.
The issue of "smart freezing" of electrons of alkali metals and a further revamp of the interface (per-atom or per-element spec.) is for a different PR.
=> Previous shell core freezing and ECPs

doc/sphinxman/source/bibliography.rst, doc/sphinxman/source/dftd3.rst, doc/sphinxman/source/oeprop.rst, doc/sphinxman/source/sapt.rst, psi4/driver/driver.py
Updates the docs with any undocumented new features in 1.4
I still have #1721 (Libint2 and shell screening), #1723 (QCSchema Interface), and #1728 (QCSchema Wavefunction Quantities) as being undocumented or incompletely documented. Let me know if I'm wrong here, and any suggestions (or volunteers) on how to complete them are welcome.
=> Add some documentation for 1.4 release

psi4/driver/procrouting/dft/dft_builder.py, psi4/src/psi4/libfunctional/superfunctional.cc
Now that I have set up a conda environment, I was able to check whether #2218 fixed the issue of the capitalization of the xc functional keywords. It did not. This merge solves the issue:
```
=> Exchange Functionals <=
1.0000         XC_LDA_X
=> Correlation Functionals <=
1.0000      XC_LDA_C_PW
=> LibXC Density Thresholds  <==
XC_LDA_C_PW:  1.00E-15 
XC_LDA_X:  1.00E-15 
```
=> Really ensure xc functional names are capitalized in output

doc/sphinxman/source/scf.rst
Looks like there was a mistake in the added note on damping in #2225 that wasn't caught by the CI; this PR rectifies the referenced keyword.
=> damping_convergence not damping_threshold

psi4/src/psi4/dct/dct.h, psi4/src/psi4/dct/dct_scf_UHF.cc
This PR fixes Example 1 of #2231, some GEMM errors in the DCT module in the presence of linear dependencies. There's more debugging to do, but this is a perfectly good standalone bugfix.
I also refactored the offending function. Less code duplication, less gratuitous pointers, and eliminated an offset.
This PR is anodyne, so getting this in for 1.4 would be appreciated.
=> Fix GEMM errors in presence of linear dependencies

psi4/src/psi4/dct/dct_df_tensor.cc, psi4/src/psi4/dct/dct_oo_RHF.cc, psi4/src/psi4/dct/dct_oo_UHF.cc, tests/CMakeLists.txt, tests/dct10/output.ref, tests/dct11/CMakeLists.txt, tests/dct11/input.dat, tests/dct11/output.ref
This fixes Example 2 of #2231. DF-DCT no longer segfaults in the presence of linear dependencies.
Even with this merged in, #2231 should stay open until I've had a chance to do some more thorough testing of the module. This is, once again, a stand-alone bugfix.
=> DF-DCT with Linear Dependencies

doc/sphinxman/source/nbody.rst, psi4/driver/driver_nbody.py, tests/dftd3/nbody-cp-gradient/input.dat, tests/dftd3/nbody-cp-gradient/output.ref, tests/nbody-cp-gradient/input.dat, tests/nbody-cp-gradient/output.ref
This PR reverts the behaviour of standard `bsse_type='cp'` calculations to calculate all fragments (monomers) in the full (dimer) basis only. The PR also fixes printing interaction energies disguised as total energies in those tables.
When a calculation is requested with `bsse_type='cp', return_total_data=True`, an `bsse_type=['cp', 'nocp']` is automatically performed and the total energies are calculated & returned. With `bsse_type=['cp','nocp']` (and `return_total_data` unspecified or `False`), the total energies are calculated, but the interaction energies are returned.
The PR fixes #1691 .
=> Revert behaviour of bsse_type='cp'

psi4/src/psi4/detci/olsengraph.cc
Fixes an error in `detci` printing. This one is so obscure that it can easily come in for 1.5.
=> Fix type conversion error

psi4/src/export_mints.cc, psi4/src/psi4/libmints/basisset.cc, psi4/src/psi4/libmints/basisset.h, tests/CMakeLists.txt, tests/phi-ao/CMakeLists.txt, tests/phi-ao/input.dat, tests/phi-ao/output.ref
Currently, the phi_ao function returns the value of the basis functions at a point. However, this ONLY works for cartesian and not spherical basis sets. I updated the code to make this change. This is important to the development of seminumerical methods, like chain-of-spheres exchange.
=> [Small, Important Change] Changed phi_ao code to support puream basis sets

psi4/src/psi4/occ/occwave.cc
Fix [a bug reported on the forums](http://forum.psicode.org/t/cubeprop-mp2-wfn/2228). That traces back to the orbitals getting wiped off OCC wavefunctions due to overzealous memory resets. Thanks to smart pointers, this is completely unnecessary. Offensive code removed.
This is a no-brainer bugfix, so 1.4 target appreciated.
=> OCC: Don't reset orbitals

external/upstream/ambit/CMakeLists.txt, external/upstream/pybind11/CMakeLists.txt, external/upstream/qcelemental/CMakeLists.txt, psi4/driver/qcdb/libmintsbasisset.py, psi4/share/psi4/basis/primitives/diff_gbs.py, tests/scf-coverage/input.dat
=> fix scf-coverage ref after phi_ao sph correction

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/psi4/libscf_solver/mom.cc
This PR moves the printing of the SCF pre-iteration header from `scf_iterate` (where we had to check the number of iterations to know if we needed to print) to the SCF initializer (where no checks are needed).
This can and should wait until 1.5. This is part of a larger project to remove overloading of the `iterations_` variable in HF, needed to get MOM properly working.
=> Move Iteration Header Printing

psi4/src/psi4/dmrg/dmrgscf.cc
As a preliminary PR to giving DMRG a wavefunction, this PR changes many function signatures in DMRG to either not take a wavefunction, use a const reference to a wavefunction when the wavefunction doesn't change, and use a const reference to a Matrix when the Matrix doesn't change.
This PR is 100% cleanup and should probably be saved until 1.5.
=> Watch for Const Wfn Members in DMRG

doc/sphinxman/source/sapt.rst, psi4/driver/procrouting/proc.py, psi4/src/export_mints.cc, tests/CMakeLists.txt, tests/sapt11/CMakeLists.txt, tests/sapt11/input.dat, tests/sapt11/output.ref
In very rare cases, the number of frozen core orbitals in computing the dMP2 correction in SAPT was inconsistent between the dimer and monomer calculations. I only encountered this when one monomer was a charged alkali metal. For example, when computing the dMP2 correction for Na-H20, `freeze_core true` results in one frozen orbital each for Na and H2O in the separate monomer computations, but six frozen orbitals in the dimer computation. Separately, these values make sense, but in this context they result in a meaningless dMP2 value.
=> Fix in handling of frozen core orbitals in SAPT

psi4/src/psi4/libscf_solver/frac.cc, psi4/src/psi4/libscf_solver/hf.h, tests/CMakeLists.txt, tests/frac-sym/CMakeLists.txt, tests/frac-sym/input.dat
Closes #1673. This PR fixes an indexing error causing the wrong orbitals to be scaled during fractional occupation, when there are multiple irreps.
Now that the SCF module has its correctness errors fixed, I can get to some convergence improvements.
=> Fix fractional occupation with symmetry

psi4/src/psi4/libscf_solver/frac.cc, psi4/src/psi4/libscf_solver/hf.h, tests/frac-traverse/CMakeLists.txt
This PR reverts part of #2280 and restores the ability of `frac` to handle zero occupation number. At the cost of storing extra C matrices, this fixes a pre-#2280 bug in the handling of zero occupation number. Closes #2284.
The `frac` code is designed to allow SCF with fractional occupation numbers. Physically, this is an ensemble of Slater determinants, where the probabilities of a given orbital being occupied are uncorrelated. This is implemented by changing the C matrix from meaning "thing that contains orbitals" to "thing that produces the density", and incorporating the occupation numbers into the definition of the C matrix by multiplying by the occupation numbers. These are divided out after SCF to restore the original meaning of C.
Now, in the case of zero occupation number, …
=> Fix 0 Frac Occupancy

.azure-pipelines/azure-pipelines-windows.yml, CMakeLists.txt
the Windows conda package isn't working for some computers. A report (http://forum.psicode.org/t/how-to-run-psi4-on-windows-10/2174/16) is that compiling with AVX _does_ work. The current situation should be building with AVX2 (https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L145) and @kcpearce reports that the conda pkg still fails on his computer with AVX2 instructions, but this is worth a shot.
=> try no xHost to broaden Windows build

psi4/src/psi4/libmints/oeprop.cc, psi4/src/psi4/libmints/oeprop.h, tests/mbis-1/input.dat, tests/mbis-1/output.ref, tests/mbis-2/input.dat, tests/mbis-2/output.ref, tests/mbis-3/input.dat, tests/mbis-3/output.ref, tests/mbis-4/input.dat, tests/mbis-4/output.ref, tests/mbis-5/input.dat, tests/mbis-5/output.ref, tests/mbis-6/input.dat
This is a start to addressing #2272
=> split mbis oeprop

doc/sphinxman/source/dlpnomp2.rst, psi4/driver/p4util/procutil.py, psi4/src/read_options.cc
Fixes the DLPNO docs (PR #2093). I can now build the docs locally, ~~although I still get the following warnings:~~
```
/theoryfs2/ds/glick/gits/psi4/objdir/doc/sphinxman/source/dlpnomp2.rst:90: WARNING: Undefined substitution referenced: "dlpno__pno_convergence".
/theoryfs2/ds/glick/gits/psi4/objdir/doc/sphinxman/source/dlpnomp2.rst:207: WARNING: Undefined substitution referenced: "dlpno__pno_convergence".
```
Update: Warnings are fixed thanks to a suggestion from Lori
=> DLPNO Doc Fix

psi4/src/psi4/libcubeprop/csg.cc, psi4/src/psi4/libcubeprop/csg.h
This PR removes several `new`, `delete`, `block_matrix`, and `free_block` calls in `cubeprop`. I was hoping to eliminate all such calls in order to use `cubeprop` as a test case to study memory management in Psi, but I can't finish the job without refactoring `BlockOPoints`, which is far outside the scope of the PR.
=> Less `cubeprop` manual memory management

psi4/src/psi4/libdiis/diisentry.cc, psi4/src/psi4/libdiis/diisentry.h, psi4/src/psi4/libdiis/diismanager.cc, psi4/src/psi4/libdiis/diismanager.h
This PR gets rid of all `new` and `delete` calls within `libdiis`, replacing them with `std::unique_ptr` and `std::vector`.  
Per [recommendations](https://herbsutter.com/2013/06/05/gotw-91-solution-smart-pointer-parameters/), I use a `std::unique_ptr` to signify the caller (of the `DIISEntry` constructor) loses ownership of the object.
=> Modernize `libdiis` Pointers

psi4/driver/qcdb/libmintsbasisset.py
This PR fixes a memory leak that was occurring in the Python-side `qcdb` code. The code meant to modify a _class variable_ but was actually creating and modifying an _instance variable_. Initialization happened many more times than needed, and some memory was not being cleared upon object deletion.
The only explanation I have for how this produced a memory leak is that having a class variable and an instance variable with the same name confused the Python garbage collector. I was able to confirm object creation and deletion was occurring roughly as expected.
=> Fix `qcdb` memory leak

psi4/src/psi4/libfock/points.cc
Exactly what it says in the title.
=> Fix memory leak of all DFT integration coordinates

psi4/src/psi4/dlpno/mp2.cc, psi4/src/psi4/libdiis/diisentry.cc, psi4/src/psi4/libdiis/diisentry.h, psi4/src/psi4/libdiis/diismanager.cc
This PR fixes a memory leak which I inadvertently introduced myself when refactoring `libdiis`.
What I was _trying_ to do was take heap memory and move it into the stack. You can't actually do that. So when I released my `std::vector` from the smart pointer and saved it to a class variable, the memory was _not_ cleared on object delete because it was still heap memory and not stack memory. _Mea culpa_.
=> Fix DIIS memory leak

psi4/src/psi4/libmints/vector.cc, psi4/src/psi4/libscf_solver/hf.cc
First, this PR cleans up some manual memory management in `libscf_solver`, including a memory leak of an `nao`-by-`nso` matrix created once per call to the SCF code.
During the course of fixing that, I uncovered a correctness error in `libmints`: the `dgemv` function was using rows rather than cols for an argument. The original choice was correct in Fortran-style indexing but not C-style indexing and disagreed with every other `C_DGEMV` call in Psi. It didn't cause any issues because `Vector::dgemv` is almost never used in Psi. The one other time I found it used was for a Hermitian matrix, which of course won't have problems.
=> Fix SCF memory leak and `Vector::gemv`

psi4/src/psi4/libqt/qt.h
Expose the function C_DGELS (found in `qt.h`)
=> Expose C_DGELS via PSI_API

external/upstream/qcelemental/CMakeLists.txt, psi4/driver/schema_wrapper.py
In accordance with https://github.com/MolSSI/QCElemental/pull/275, return certain files in qcschema to be pruned down by user protocols. Bump qcel to 0.24.0 (and qcng to 0.23.0 once it's minted). Note that this can't handle the wfn file b/c binary. And it can't handle `timer.dat` b/c there's no fixed place it lands (I can get it to save calling schema_wrapper directly but not for QCEngine calling psi4).
=> native_files field for qcschema

doc/sphinxman/source/dft.rst, psi4/src/psi4/lib3index/dfhelper.h, psi4/src/psi4/libfock/jk.cc, psi4/src/read_options.cc
Reports indicate that the in-core `MemDF+wcombine` algorithm is not working correctly.
This PR disables the options. MemDF does not longer turn the option on automatically and users setting the option directly will get an exception error. A note is added to the DFT manual.
Issues: #2351 #2279 
Related: #2283
=> disables wcombine option

psi4/driver/p4util/prop_util.py, psi4/driver/p4util/python_helpers.py, psi4/driver/p4util/util.py, psi4/driver/procrouting/proc.py, tests/mbis-6/input.dat, tests/mbis-6/output.ref
This PR has tho objectives:
1.  Make MBIS volume ratios callable from both `oeprop(...,'MBIS_VOLUME_RATIOS')` and `set scf_properties ['MBIS_VOLUME_RATIOS']`. So, solve #2299.   
2. A recent comment suggested that the `free_atom_volume()` function was still being called even though they only requested computation of MBIS charges. This PR also ensures that this doesn't happen anymore.
=> Fixes to MBIS volume ratios

psi4/src/export_mints.cc, tests/pytests/test_vector.py
This PR exposes `Vector.clone()` to the Python layer, a generally useful function and one I specifically need for PyDIIS. Sadly, positive LoC this time.
The cast to `shared_ptr` is necessary for the clone to be available Py-side because when we pybound `Vector`, we specified `std::shared_ptr<Vector>` as its holder type. I imagine this is an example of "[holder types must be applied consistently](https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#std-shared-ptr.)." Let's not talk about how long it took for me to implicate holder types in my test originally failing.
=> Pybind `Vector.clone()`

CMakeLists.txt
This PR solves an issue with the use of the native optimization flags, which are different in various compilers and often get misinterpreted. It looks like the best solution is to first check the brand of the compiler, and then try whether the brand-specific flag(s) work.
Related issues https://gitlab.com/libxc/libxc/-/issues/361 and #2023
=> Make ENABLE_XHOST flag checks dependent on compiler brand.

psi4/src/psi4/dct/dct.h, psi4/src/psi4/dct/dct_compute_RHF.cc, psi4/src/psi4/dct/dct_compute_UHF.cc, psi4/src/psi4/dct/dct_oo_RHF.cc, psi4/src/psi4/dct/dct_oo_UHF.cc, psi4/src/psi4/dct/dct_qc.cc
This PR removes some convergence checks in the `dct` module that are redundant (when formulated correctly) and currently not implemented correctly.
In the current `dct` code, my threaded computations with near linear dependencies were taking a variable number of iterations to converge, due to the condition `update_scf_density_RHF() < orbitals_threshold_` being false. That check is _intended_ to enforce convergence of the orbitals, which change iteration-to-iteration. `update_SCF_density_RHF` returns a measure of how much the reference density changed but does not treat it with an orthogonalizer, so in the near linearly-dependent case, numerical noise leads to the computation proceeding even after all other convergence metrics are flat.
Given the choice between fixing the check or removing …
=> Remove Unnecessary, Buggy `dct` Convergence Metric

psi4/src/psi4/lib3index/dftensor.cc
Adds a basic memory check for the construction of the `Qso` DF Tensor.
This is e.g. needed for large (~1k bfs) (FNO)-DF-CC calculations where the tensor construction may become the main memory bottleneck.
Closes #1372
=> adds DFTensor (Qso) memory check

psi4/src/psi4/dmrg/dmrgscf.cc
This PR does cleanup in `dmrgscf` to mark variables const, remove non-RAII dynamic memory, and switch from pointers to references where possible. This PR is in preparation for updating the deprecated molden call.
=> DMRG Memory/`const` Cleanup

psi4/src/psi4/cc/CMakeLists.txt, psi4/src/psi4/dct/CMakeLists.txt, psi4/src/psi4/dfocc/CMakeLists.txt, psi4/src/psi4/dlpno/CMakeLists.txt, psi4/src/psi4/fisapt/CMakeLists.txt, psi4/src/psi4/libdiis/CMakeLists.txt, psi4/src/psi4/libscf_solver/CMakeLists.txt, psi4/src/psi4/occ/CMakeLists.txt, psi4/src/psi4/scfgrad/CMakeLists.txt
When trying to build from source, I had problems with Pybind11 headers not being found.  This is most likely due to #2369 introducing new dependencies on PB11 being introduced that the build system is unaware of.  This PR fixes the problem on my Linux/ICPC setup, but I'm open to suggestions if there's a more up to date way of telling CMake about these new dependencies.
=> Add pb11 dependency to modules that use DIIS

psi4/driver/p4util/testing.py, psi4/driver/qcdb/testing.py, tests/pytests/test_testing.py
This PR fixes a bug found by Lori, and gives `compare_matrices` the ability to compare names. Although Lori and I were in talks about some other improvements to comparison functions, those would touch `qcelemental` so can't be included here.
This blocks some development on another branch, so I'd appreciate a fast review.
=> Misc. testing changes

psi4/driver/driver.py
This works with both test_fchk_writer and #2400 (needed for independent run of fchk()). Thank goodness the fchk tester had a dfocc (comparatively old-style storage) case.
=> fix fchk again

tests/frac-sym/input.dat, tests/fsapt-ext-abc/input.dat, tests/fsapt-ext-abc2/input.dat, tests/mom-h2o-3/input.dat, tests/mom-h2o-4/input.dat, tests/scf-level-shift-cuhf/input.dat, tests/scf-level-shift-rks/input.dat, tests/scf-level-shift-rohf/input.dat, tests/scf-level-shift-uhf/input.dat, tests/scf-response3/input.dat
This is an _attempt_ to get the docs working again by resolving "Undocumented input" warnings from Sphinx. Worst case scenario, Sphinx outputs are a little shorter. Best case scenario, there was some change in Sphinx that causes crashes when this warning occurs, and we can get docs working again.
=> Silence sphinx warnings

psi4/src/psi4/libmints/deriv.h
Deprecates ways of calling derivatives that are, as best as I can tell, artifacts of legacy code that were never removed.
If anybody downstream of us needs these, we're giving them a chance to prevent us. Otherwise, less code, less problems.
=> Deprecate unused Deriv types

doc/sphinxman/source/basissets.rst, doc/sphinxman/source/build_planning.rst, doc/sphinxman/source/conda.rst, doc/sphinxman/source/libint.rst, doc/sphinxman/source/manage_release.rst, doc/sphinxman/source/psiapi.ipynb
I think whoever brought up the new "warnings" in the sphinx log was on the right track. We do have the treat-warnings-as-errors flag on. It's the treat-broken-links-as-errors flag that we can't enable yet. Between that and the 9800 PR in the newest sphinx changelog released 17 Jan https://www.sphinx-doc.org/en/master/changes.html#release-4-4-0-released-jan-17-2022, I bet that's what's causing our docsbuild fail. Hopefully I haven't added any new syntax errors.
=> fix docs warnings

psi4/src/psi4/libmints/wavefunction.h
Deprecating more legacy code. This boolean is always false in Psi, is only ever used in the Derivative code (but is still always false) where there are other ways to specify this information, and it's a holdover from pre-`scfgrad` days. To oblivion with it.
=> Deprecate `Wavefunction.density_fitted`

psi4/src/psi4/fnocc/opdm.cc
Easy cleanup found when surveying use of density matrix across modules.
@edeprince3
=> `fnocc` mini-cleanup

doc/sphinxman/source/adc.rst, psi4/driver/procrouting/proc.py, psi4/src/read_options.cc, tests/adc1/input.dat, tests/adc2/input.dat
This PR deprecates Psi's built-in ADC module, per discussion on the January developer conference call, issue #1033, and my own investigation.
=> Deprecate Built-In ADC

psi4/src/psi4/lib3index/dfhelper.cc, psi4/src/psi4/lib3index/dfhelper.h, tests/CMakeLists.txt, tests/tdscf-6/CMakeLists.txt, tests/tdscf-6/input.dat, tests/tdscf-6/output.ref
This PR fixes a bug introduced in #1749, where `MemDFJK` handling of range-separated functional was incorrect in the asymmetric case. This incorrect handling lead to incorrect TD-DFT excitation spectra for range-separated functionals when `MemDFJK` was used. This PR hence closes #2431. In the symmetric case, either swapping the contraction order had no effect, or it was corrected by a hermitivitize call later on, so no error was observed.
I strongly recommend backporting this PR (or at least the two characters needed to fix the bug). The rest of the PR other than those two characters is tests and commenting. Credit to @hokru for tag-team debugging.
=> Fix bug in MemDFJK afflicting TDDFT

psi4/driver/procrouting/proc.py, psi4/src/psi4/cc/ccdensity/CMakeLists.txt, psi4/src/psi4/cc/ccdensity/MOInfo.h, psi4/src/psi4/cc/ccdensity/Params.h, psi4/src/psi4/cc/ccdensity/ccdensity.cc, psi4/src/psi4/cc/ccdensity/get_moinfo.cc, psi4/src/psi4/cc/ccdensity/get_params.cc, psi4/src/psi4/cc/ccdensity/to_matrix.cc, psi4/src/psi4/libqt/dx_write.cc, psi4/src/read_options.cc, tests/pytests/test_dipoles.py
Closes #2432.
This is PR 1 in an ongoing series to make `ccdensity` compatible with the standard `Matrix` and `Wavefunction` machinery used elsewhere in Psi. (That means I'll have a lot of PRs for you two to review. Let me know if there's another person from VA Tech you want to take the responsibility of reviewing my PRs.)
=> Change `ccdensity` Keywords Around OPDM Relaxation

psi4/src/psi4/libdiis/diismanager.cc, psi4/src/psi4/libdiis/diismanager.h
Per @fevangelista request, this PR allows Forte to compile with master Psi, almost. That also requires a Forte PR.
=> Expose reset_subspace to C++ for plugins

psi4/src/psi4/cc/ccdensity/MOInfo.h, psi4/src/psi4/cc/ccdensity/build_A_ROHF.cc, psi4/src/psi4/cc/ccdensity/ccdensity.cc, psi4/src/psi4/cc/ccdensity/dump_RHF.cc, psi4/src/psi4/cc/ccdensity/dump_ROHF.cc, psi4/src/psi4/cc/ccdensity/dump_UHF.cc, psi4/src/psi4/cc/ccdensity/ex_sort_td_rohf.cc, psi4/src/psi4/cc/ccdensity/ex_sort_td_uhf.cc, psi4/src/psi4/cc/ccdensity/fold_RHF.cc, psi4/src/psi4/cc/ccdensity/fold_ROHF.cc, psi4/src/psi4/cc/ccdensity/fold_UHF.cc, psi4/src/psi4/cc/ccdensity/get_moinfo.cc, psi4/src/psi4/cc/ccdensity/norm.cc, psi4/src/psi4/cc/ccdensity/sortI_RHF.cc, psi4/src/psi4/cc/ccdensity/sortI_ROHF.cc, psi4/src/psi4/cc/ccdensity/sortI_UHF.cc, psi4/src/psi4/cc/ccdensity/sort_ltd_rohf.cc, psi4/src/psi4/cc/ccdensity/sort_ltd_uhf.cc, psi4/src/psi4/cc/ccdensity/sort_rtd_rohf.cc, psi4/src/psi4/cc/ccdensity/sort_rtd_uhf.cc, psi4/src/psi4/cc/ccdensity/sortone_RHF.cc, psi4/src/psi4/cc/ccdensity/sortone_ROHF.cc, psi4/src/psi4/cc/ccdensity/sortone_UHF.cc, psi4/src/psi4/cc/ccdensity/to_matrix.cc
This PR replaces several `int *` types in `ccdensity` with `Dimension` or `std::vector<int>` objects as appropriate. In addition to eliminating manual memory management and making the code more readable, easy access to `Dimension` objects will allow for a subsequent PR to construct `Matrix` objects directly, replacing the current `block_matrix` representation of objects.
This is PR 2 in an ongoing series to make `ccdensity` compatible with the standard `Matrix` and `Wavefunction` machinery used elsewhere in Psi. Obligatory @lothian notification.
=> Lose `*` in `ccdensity`

psi4/driver/procrouting/diis.py
During review of the ADIIS PR, it was suggested that Psi raise an error if the BFGS doesn't meet the target convergence criteria. This PR changes that, so the error will be raised _if BFGS is very far from meeting the convergence criteria_. 1e-6 would be nice, but 1e-3 is good enough for our purposes.
@loriab, these are the last of the Psi tests on my list to heal.
=> Loosen `adiis` BFGS Solution

psi4/src/psi4/cc/cclambda/cclambda.cc, tests/cc19/CMakeLists.txt, tests/cc19/input.dat, tests/cc19/output.ref, tests/cc28/CMakeLists.txt, tests/cc28/input.dat, tests/cc28/output.ref, tests/cc29/input.dat, tests/cc29/output.ref
This PR fixes a docs fail caused by the previous PR in the series and also adapts a few more tests. Test `cc29` needs another adaptation, but as that will require a new psivar, I'm saving that for the next PR.
This is PR 5 in an ongoing series to make `ccdensity` compatible with the standard `Matrix` and `Wavefunction` machinery used elsewhere in Psi. Obligatory @lothian ping for `cc` and obligatory @loriab ping for fixing the docs.
=> Port `cc19`, `cc28`, modify `cc29`

psi4/src/psi4/cc/cclambda/cclambda.cc
Docs still failed even after the last PR. My current suspicion is that the problem is [this line](https://github.com/psi4/psi4/runs/5253940040?check_suite_focus=true#step:9:248), which results when [an over-active Perl scraper thinks "LEFT-RIGHT" is a psivar](https://github.com/psi4/psi4/blob/master/doc/sphinxman/document_psivariables.pl#L213-L224). I don't particularly feel like learning enough Perl to implement the regex properly, so we're just going to avoid it.
=> Docs Fix Take 2

doc/sphinxman/source/glossary_psivariables.rst, psi4/src/psi4/cc/ccresponse/optrot.cc, tests/cc29/input.dat, tests/cc29/output.ref
This PR adds a new psivar for the length gauge origin-dependence of the specific rotation, to aid in migration of the CC tests. `cc29` now tests this psivar. Once the psivar is accepted, I can resume porting tests over.
This is PR 6 in an ongoing series to make `ccdensity` compatible with the standard `Matrix` and `Wavefunction` machinery used elsewhere in Psi. Obligatory @lothian and @loriab ping for new `cc` psivars. For TDC's benefit, you can go to the "Files changed" tab, "Review changes", and then mark to approve if things look good to you.
=> Add Spec. Rot. Origin Dependence Psivar

psi4/driver/procrouting/response/scf_response.py
This fixes #2452. I export the correct value TD-LEFT EIGENVECTOR BETA and do not overwrite TD-LEFT EIGENVECTOR ALPHA anymore.
I did not rerun the tests, as the fix is trivial. I did not find pre-existing unittests referencing TD-LEFT EIGENVECTOR ALPHA or TD-LEFT EIGENVECTOR BETA
=> Fixed export of left eigenvector beta in scf_response.py

psi4/src/psi4/libpsio/psio.h
Fixes an incorrect header for a PSIO debug function.
=> Restore `psio_tocprint`

tests/cc18/CMakeLists.txt, tests/cc29/CMakeLists.txt, tests/cc38/CMakeLists.txt, tests/cc38/input.dat, tests/cc38/output.ref, tests/cc39/CMakeLists.txt, tests/cc39/input.dat, tests/cc39/output.ref
As of this PR, cctests 1-33, 35-39 are ported. The next batch of tests will involve EOM oscillator strengths.
=> Migrate `cc38`, `cc39`

doc/sphinxman/source/glossary_psivariables.rst, doc/sphinxman/source/notes_c.rst, psi4/driver/procrouting/response/scf_response.py, tests/CMakeLists.txt, tests/pytests/test_cppe.py, tests/tdscf-1/input.dat, tests/tdscf-1/output.ref, tests/tdscf-2/input.dat, tests/tdscf-2/output.ref, tests/tdscf-3/input.dat, tests/tdscf-3/output.ref, tests/tdscf-4/input.dat, tests/tdscf-4/output.ref, tests/tdscf-5/output.ref, tests/tdscf-6/input.dat, tests/tdscf-6/output.ref, tests/tdscf-7/CMakeLists.txt, tests/tdscf-7/input.dat, tests/tdscf-7/output.ref
TDSCF/ADC and EOM can't agree on how to name variables for excitation energies. Per discussion between Lori and I, this moves the TDSCF variable names to the new standard, as I see it. This PR is not complete and is submitted for feedback from the excited-state gurus, who are likely to have strong opinions: @loriab @robertodr @lothian @maxscheurer 
To demonstrate the changes, consider the example file I added. Old code would write the second transition as "TD-HF ROOT 0 -> ROOT 2 EXCITATION ENERGY - B2 SYMMETRY". The new code replaces that with three new psivars:
- TD-HF ROOT 0 (B1) -> ROOT 0 (B2) EXCITATION ENERGY
- TD-HF ROOT 0 -> ROOT 2 EXCITATION ENERGY
- TD-HF ROOT 0 -> ROOT 2 EXCITATION ENERGY - A2 SYMMETRY
We have one access call that requires the symmetries of initial and target …
=> Change TDSCF Variable Names

psi4/src/psi4/cc/cceom/Local.h, psi4/src/psi4/cc/cceom/get_params.cc, psi4/src/psi4/libqt/cc_excited.cc, psi4/src/read_options.cc
`LEOM_CCSD` is included in the list of EOM methods, but I can find no evidence that this method exists in Psi, other than as an option. This PR removes the option entirely.
This brings the EOM methods to create variables for down to EOMCCSD, EOMCC2, and EOMCC3.
Per Lori observation, the `LOCAL_GHOST` option is removed as unused.
=> Remove Reference to Unimplemented Method

external/upstream/libint2/CMakeLists.txt
one-size-fits-most L2 tarball for when building L2 from source (less work than building L2 from generator source, more work than using pre-built L2). equivalent in AM (edit: ~size~) to the current conda builds
=> fix L2 tarball for current post-l2-osi master

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml
The L2 after Friday's merge of l2-oei wasn't working consistently for Mac or Win. Replacements have been built that are stable, so resetting where they appear in repo itself. No change in Linux, as it was working fine. 
```
- h2fe1556_13    [linux]
-    - h879752b_4     [osx]
-    - h2e52968_3     [win]
+    - h879752b_6     [osx]
+    - h2e52968_5     [win]
```
=> pin L2 for l2-oei

doc/sphinxman/source/cfour.rst, doc/sphinxman/source/glossary_psivariables.rst, doc/sphinxman/source/oeprop.rst, psi4/driver/p4util/python_helpers.py, psi4/driver/procrouting/proc.py, psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/driver/procrouting/wrappers_cfour.py, psi4/driver/qcdb/cfour.py, psi4/driver/qcdb/orca.py, psi4/src/psi4/cc/ccdensity/ccdensity.cc, psi4/src/psi4/detci/opdm.cc, psi4/src/psi4/libmints/oeprop.cc, tests/cc54/input.dat, tests/ci-property/input.dat, tests/fci-dipole/input.dat, tests/fci-tdm-2/input.dat, tests/fci-tdm/input.dat, tests/mp2-property/input.dat, tests/props1/input.dat, tests/props2/input.dat, tests/props3/input.dat, tests/pytests/test_misc.py, tests/python/cc54/input.py, tests/scf-property/input.dat, tests/scf-response1/CMakeLists.txt, tests/scf-response2/CMakeLists.txt, tests/scf-response3/CMakeLists.txt
Removes deprecated n-pole component psivars. Puts a warning in some QCDB files that they are not being properly maintained, per #2478.
=> Retire n-pole components

psi4/src/psi4/libmints/3coverlap.cc, psi4/src/psi4/libmints/3coverlap.h, psi4/src/psi4/libmints/CMakeLists.txt, psi4/src/psi4/libmints/integral.cc, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libsapt_solver/fdds_disp.cc
This PR refactors `ThreeCenterOverlapInt` using Libint2. Even though one cannot compute these integrals directly, it's possible to obtain them through the delta function: `<phi(r_1) phi(r_1)| delta(r_1 - r_2) | phi(r_2) 1>`.
=> Three-center overlap integrals using Libint2

psi4/src/export_mints.cc, psi4/src/psi4/libmints/molecule.cc, psi4/src/psi4/libmints/molecule.h
`Molecule::atom_at_position` is supposed to return the index of the atom found in a specified radius of a specified point in 3D space, or -1 if no atom is found in the radius. The current implementation assumes there is never more than one atom within the given radius, and returns the index of the first atom found to be within the tolerance.
This can hypothetically happen in two ways: the atoms are either extremely close, or the tolerance is set to a large value.
The new implementation behaves more like one would expect it to behave: under the aforementioned extreme circumstances it throws an exception and informs the user with an error message.
Not sure what to do about this, at first glance it would be neater if both `qcdb.Molecule.atom_at_position` and …
=> Fix corner case in the C++ implementation of Molecule::atom_at_position

psi4/src/psi4/libscf_solver/hf.cc
Minor cleanups to `find_occupation` as well as the introduction of sanity checks for #2476 to prevent sudden changes of the spin state during the calculation.
=> Cleanup to find_occupation and more sanity checks

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml, CMakeLists.txt, external/upstream/libint2/CMakeLists.txt, external/upstream/pybind11/CMakeLists.txt, psi4/CMakeLists.txt, psi4/src/CMakeLists.txt, psi4/src/psi4/libfock/CMakeLists.txt, psi4/src/psi4/libmints/integral.h, psi4/src/psi4/libqt/CMakeLists.txt, tests/pytests/test_dft_blocking.py
This corresponds to L2 at https://github.com/evaleev/libint/pull/233 .
```
< namespace libint2 {
< inline int INT_NCART(int am) { return ((am + 2) * (am + 1)) >> 1; }
< }
< LIBINT_DEPRECATED("please use libint2::INT_NCART instead")
< inline int INT_NCART(int am) { return libint2::INT_NCART(am); }
---
> #define INT_NCART(am) ((((am)+2)*((am)+1))>>1)
```
With that situation (define in psi and inlined in L2), I get lots of
```
In file included from /psi/gits/hrw-pybind/psi4/src/psi4/libmints/integral.cc:28:
/psi/gits/libint2-efv/install-p01/include/libint2/cgshell_ordering.h:104:12: error: expected unqualified-id before 'int'
104 | inline int INT_CARTINDEX(unsigned int am, int i, int j) {
|            ^~~~~~~~~~~~~
```
I can fix the problem by renaming in psi to `INT_NCART_PSI` and …
=> Update CMake fork of Libint2, c. 2019 -> c. 2022

devtools/conda-envs/docs-cf.yaml
cloud sphinx theme is importing `Markup` from `jinja2`, which is moved in the newly packaged jinja2 3.0 https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-0-0 . so let's try to use jinja2 2
=> try to fix docs build

psi4/src/export_oeprop.cc, psi4/src/psi4/libmints/oeprop.h
Exactly what it says in the title. This is a preliminary PR before I make some other `OEProp` changes.
=> Clean up OEProp pybind

psi4/src/psi4/dfmp2/README.txt
Adds a missing doi in a source tree README file, also standardizes the use of doi syntax (it is doi:foo not DOI foo)
=> Add missing doi, fix doi syntax

psi4/driver/procrouting/response/scf_response.py, tests/tdscf-3/input.dat, tests/tdscf-7/input.dat
Ticks off an item on #2486 and #2477 by allowing "TD-DFT" to be a way to access TD-DFT psivars. As far as I'm aware, TD-DFT psivars are now as we want them.
=> Add TD-DFT psivar access pattern

doc/sphinxman/source/glossary_psivariables.rst, psi4/driver/procrouting/response/scf_response.py, psi4/src/psi4/cc/ccdensity/Params.h, psi4/src/psi4/cc/ccdensity/ex_oscillator_strength.cc, psi4/src/psi4/cc/ccdensity/get_td_params.cc, psi4/src/psi4/cc/ccdensity/globals.h, psi4/src/psi4/cc/ccdensity/oscillator_strength.cc, psi4/src/psi4/cc/cclambda/cclambda.cc, tests/cc47/input.dat, tests/cc47/output.ref, tests/cc52/input.dat, tests/cc52/output.ref
This PR exposes EOMCC oscillator strengths to psivars and makes other miscellaneous changes:
- Adds a comment to the TD-DFT code to disambiguate between eigenvectors of two different matrices.
- Renames a variable created earlier in the `cc` cleanup series.
- Makes the `oscillator_strength.cc` and `ex_oscillator_strength.cc` files more similar
- Begins changing `cc47` to newstyle.
- Adds refactor TODOs
**That said**, the EOMCC code currently only supports irrep-separated indexing. The irrep-combined indexing isn't easily obtainable due to the awkward way `cceom` passes information to `ccdensity`. While I could fix this, I'll save that until after `ccdensity` has a wavefunction, so the task becomes easier. I'm happy to make an issue so we don't forget.
=> EOMCC Oscillator Strengths

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/export_fock.cc, psi4/src/psi4/libfock/DirectJK.cc, psi4/src/psi4/libfock/DiskDFJK.cc, psi4/src/psi4/libfock/DiskJK.cc, psi4/src/psi4/libfock/GTFockJK.cc, psi4/src/psi4/libfock/MemDFJK.cc, psi4/src/psi4/libfock/PKJK.cc, psi4/src/psi4/libfock/jk.cc, psi4/src/psi4/libfock/jk.h
This PR makes two small improvements to the `JK` class and SCF code. These improvements simplify the addition of new JK algorithms to Psi4, particularly an upcoming semi-numerical exchange.
The first change is transferring the responsibility of zeroing out the `J`, `K`, and `wK` matrices from the parent `JK` class to each derived `JK` class. This makes it easier to implement JK algorithms which build the fock matrix incrementally. (i.e. use the difference in density between SCF iterations to compute differences in J/K). With this change, much of the incremental fock code in the `DirectJK` class can be simplified.
The second change is the addition of an `early_screening_` member variable to the `JK`. The idea is that some future JK algorithms will increase performance by using looser …
=> Miscellaneous JK Improvements

doc/sphinxman/source/build_faq.rst, doc/sphinxman/source/build_planning.rst, doc/sphinxman/source/external.rst, psi4/__init__.py, psi4/driver/p4util/procutil.py, psi4/driver/schema_wrapper.py, psi4/extras.py, psi4/run_psi4.py, psi4/src/psi4/libpsio/filemanager.cc, tests/pytests/addons.py, tests/pywrap-cbs1/input.dat
This is No. 5 of the DDD series, #1351.
=> various pieces from ddd

psi4/driver/procrouting/proc.py, psi4/src/export_oeprop.cc, psi4/src/psi4/libmints/oeprop.cc, psi4/src/psi4/libmints/oeprop.h, tests/cc46/input.dat, tests/cc46/output.ref
This PR changes how `OEProp` saves variables and fixes a bug where "CC ROOT 0" variables were not being set.
Previously, OEProp overloaded `title_` to refer to both the name used for the density matrix (for print purposes) and for the name used for properties (as a prefix for variable saving purposes). Only one such name can be used.
Now, OEProp uses the density matrix's name as the density matrix's name (for print purposes) and for the names used for properties (for variable saving purposes, and with the generality of format strings). Multiples names can be used.
With this, I can now save the CC dipoles as both "CC DIPOLE" and "CC2 DIPOLE", so "CC DIPOLE" can be found. The Psi code that tried to access this was never entered previously because it checked for a 'dipole' variable rather …
=> Make OEProp names flexible, to fix CC prop name bug.

psi4/src/core.cc, psi4/src/psi4/cc/ccdensity/ccdensity.cc, psi4/src/psi4/cc/ccdensity/ccdensity.h, psi4/src/psi4/cc/ccdensity/ex_oscillator_strength.cc, psi4/src/psi4/cc/ccdensity/ex_rotational_strength.cc, psi4/src/psi4/cc/ccdensity/oscillator_strength.cc, psi4/src/psi4/cc/ccdensity/rotational_strength.cc, psi4/src/psi4/cc/ccdensity/wfn_saver.cc, psi4/src/psi4/cc/cceom/cceom.cc, psi4/src/psi4/cc/cceom/diag.cc, psi4/src/psi4/cc/ccwave.h, tests/cc56/input.dat, tests/cc56/output.ref
This PR adds support for the remaining access patterns for EOM oscillator strengths and einstein coefficients.
The pieces are now in place to adapt densities and multipoles as well. I'm hopeful that will be the next PR, which should be enough to get 3 of the 4 remaining cc tests ported over.
=> More variable names for EOM properties. Required infrastructure changes

doc/sphinxman/document_tests.pl
Fixes the documentation build because I forgot to remove the deleted `adcc` cmake test dir from `doc/sphinxman/document_tests.pl`
=> fix docs build

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml, external/upstream/ambit/CMakeLists.txt, psi4/CMakeLists.txt
- leaving dftd3 and gcp since they're fast, easy, and important
- now addons tested with less compiler variety on Linux, but I don't think that's too big a problem
=> bump ambit, clear addons from azure

.azure-pipelines/azure-pipelines-windows.yml, psi4/driver/driver_cbs_helper.py, psi4/driver/p4util/procutil.py, psi4/driver/p4util/python_helpers.py, psi4/driver/p4util/text.py, psi4/driver/procrouting/proc.py, psi4/driver/procrouting/proc_table.py, psi4/driver/qcdb/align.py, psi4/driver/qcdb/libmintsbasisset.py, psi4/driver/qmmm.py, psi4/driver/schema_wrapper.py, psi4/src/core.cc, psi4/src/export_plugins.cc, psi4/src/psi4/libfock/cubature.cc, psi4/src/psi4/libfunctional/LibXCfunctional.cc, psi4/src/psi4/libmints/cdsalclist.cc, psi4/src/psi4/libmints/matrix.h, psi4/src/psi4/libmints/vector.h, psi4/src/psi4/libmints/wavefunction.h, psi4/src/psi4/libmints/writer.cc, psi4/src/psi4/libmints/writer.h, tests/cbs-xtpl-func/input.dat, tests/cbs-xtpl-nbody/input.dat, tests/dfmp2-1/input.dat
This is No. 10 of the DDD series, #1351.
- mostly a few little differences with ddd that will reduce the changed line overhead
=> update deprecation warnings text

psi4/driver/driver.py, psi4/driver/driver_findif.py, tests/psimrcc-fd-freq1/input.dat, tests/pytests/test_vibanalysis.py, tests/scf-uhf-grad-nobeta/input.dat
The first eight DDD extracts PRs reduced the delta from
99 changed files, and 5,314 additions and 2,946 deletions. c. dgasmith:recursive to
59 changed files, and 3,408 additions and 1,885 deletions. c. loriab:recursive62
so here's No. 9 of the DDD series, #1351.
* using pieces from Mol, rather than mol, to reduce dependence on psi objects
* use more numpy, less Matrix
* consolidate printing so can go to logging
* start to pass finite difference options (points, steps, projection) as kwargs rather than having findif consult global options
- closes #1683
```
Based on options and gradient (rms=3.60E-02), recommend projecting translations and not projecting rotations.
hessian() will perform frequency computation by finite difference of analytic energies. …
```
=> ddd modifications to findif

psi4/src/psi4/fnocc/ccsd.h, psi4/src/psi4/fnocc/df_ccsd.cc, psi4/src/psi4/fnocc/df_scs.cc, psi4/src/psi4/fnocc/frozen_natural_orbitals.cc, psi4/src/psi4/fnocc/frozen_natural_orbitals.h
Some miscellaneous code cleanup from my first attempt at fixing #2560. There will be a follow-up PR that renames many variables in this code before I can resume the attempt.
Note that although I create Same-Spin and Opposite-Spin matrices, those are currently unused, but will be needed for the #2560 fix.
Quick review appreciated, so I can continue the `fnocc` push.
Obligatory @edeprince3 ping.
=> Initial `fnocc` cleanup

doc/sphinxman/source/glossary_psivariables.rst, psi4/src/psi4/fnocc/ccsd.h, psi4/src/psi4/fnocc/df_ccsd.cc, psi4/src/psi4/fnocc/df_scs.cc, psi4/src/psi4/fnocc/frozen_natural_orbitals.cc, tests/fnocc4/input.dat, tests/fnocc4/output.ref
This PR moves `fnocc`'s pair energies to the same standard used by `cc`: report MP2 and CC, separate by spin, and construct spin-adapted pair energies as well.
The diff is mostly changes in the reference file, so the LoC count is inflated.
=> FNOCC df Pair Energies

psi4/driver/procrouting/response/scf_response.py, psi4/src/read_options.cc, tests/tdscf-1/output.ref, tests/tdscf-2/output.ref, tests/tdscf-3/output.ref, tests/tdscf-4/output.ref, tests/tdscf-5/output.ref, tests/tdscf-6/output.ref, tests/tdscf-7/output.ref
Adds contributing excitations to tdscf output for non-C1 symmetry.
=> Tdscf excitations symmetry

.azure-pipelines/azure-pipelines-windows.yml, CMakeLists.txt, conda/win/meta.yaml
* There's upcoming changes to those packages such that all of psi4 should be pinned and then advanced with the changes. This does that for the Windows recipe.
* fixes #2614 where Windows conda package had _no_ qcel pinning, so depending on channel order, sometimes took a really old qcel and pydantic. after this, channel order shouldn't matter.
=> Fix Numpy Python detection in Windows for new NumPy

psi4/src/psi4/libfock/DirectJK.cc
With Intel compiler, current master throws:
```
/psi/gits/hrw-pybind/psi4/src/psi4/libfock/DirectJK.cc(1015): internal error: null pointer
}
^
compilation aborted for /psi/gits/hrw-pybind/psi4/src/psi4/libfock/DirectJK.cc (code 4)
```
~The `size_t` is in the header, so I don't know why it should need it again, but it seems to want it. All the below fail, too. I'm glad to try any more rational variations.~
```
```
FYI @andyj10224 who has also hit this and @davpoolechem since it came about in #2547.
~EDIT: nevermind, this only lets it build but kills off the threading and doesn't count ints. Ignore PR for now.~
EDIT: ok, this works, though I don't see why Intel should have complained about the original. Throw seen on 2021.4 and 2021.6, btw.
- Tests added for any new features
=> Intel compiler vs DirectJK

psi4/src/psi4/libfock/dft_integrators.h, psi4/src/psi4/libfock/v.cc, psi4/src/psi4/libfunctional/LibXCfunctional.cc
If a DFT functional gives `NaN` when we attempt to numerically integrate it, throw the functional under the bus immediately instead of leaving my ADIIS code to take the blame, i.e., give a better error message.
Closes #2609.
=> Crash on NaN

.azure-pipelines/azure-pipelines-windows.yml, devtools/scripts/ci_run_test.py, psi4/CMakeLists.txt, tests/pytests/standard_suite_ref_local.py, tests/pytests/standard_suite_runner.py, tests/pytests/test_standard_suite.py
- before: 
- W: 1h30m
- L: 41-57m
- after:
- W: 1h5m
- L: 34-38m
- In working on dfocc, I found some stdsuite updates that hadn't been ported from qcng to psi4 and some general improvements.
=> testing dedup, stdsuite upgrades

.github/workflows/ecosystem.yml
GXX 7.5 from conda is throwing bizarre assembly-level errors during libmints compile like `open CFI”` and `Error: .size expression for  does not evaluate to a constant`. This compiler is working fine locally and the conda env hasn't changed since it was working fine on GHA. Searching suggests things like running of of memory for compile or binutils patches. conda has moved from 7.5 to 11.2 pinning, so that's probably a good next step.
=> smother CI linux ecosys assembly error

psi4/src/psi4/libfunctional/LibXCfunctional.cc, psi4/src/psi4/libfunctional/LibXCfunctional.h, psi4/src/psi4/libfunctional/factory.cc, psi4/src/psi4/libfunctional/functional.cc, psi4/src/psi4/libfunctional/functional.h, psi4/src/psi4/libfunctional/superfunctional.cc, psi4/src/psi4/libfunctional/superfunctional.h
This PR removes the hardcoded list of functionals that contain omega and allows setting omega for any Libxc functional that contains it.
Solves an issue described in #2641.
=> Use Libxc setters for omega

psi4/src/psi4/dfmp2/corr_grad.cc, psi4/src/psi4/dfmp2/corr_grad.h, psi4/src/psi4/dfmp2/mp2.cc, psi4/src/psi4/lib3index/dfhelper.h, psi4/src/psi4/scfgrad/jk_grad.h
Remove mention of `ERISieve` from some modules that no longer use it. `libfock` still uses it, but that's a problem for another day.
Also, `dfmp2` cleanup. No more `new`!
=> Remove false uses of ERISieve, also dfmp2 cleanup

psi4/src/psi4/libfock/PKmanagers.cc, psi4/src/psi4/libfock/PKmanagers.h
Slowly replacing `ERISieve` entirely...
=> Remove another use of ERISieve

psi4/src/export_fock.cc
The `LaplaceDenominator` class is exported to the Python layer, but not `TLaplaceDenominator`. I have a Psi4Numpy version of a new (T) method I invented that won't work without this.
=> Export Triples Laplace Denominator to Python Layer

psi4/src/psi4/libscf_solver/rohf.cc
Fixes a memory leak in the ROHF stability check.
This is a tiny shard of the #2642 mega-PR that can be merged independently.
=> Fix memory leak in ROHF stability

psi4/src/psi4/lib3index/dfhelper.cc, psi4/src/psi4/lib3index/dfhelper.h
The next batch of readability fixes to `dfhelper.cc`. The potentially contentious issue here is that I remove the `AO_files_` variable, which was just an identity mapping.
Plenty more cleanup to go!
=> DFHelper Readability 2

psi4/src/psi4/fnocc/df_ccsd.cc, psi4/src/psi4/lib3index/dftensor.cc
- change in printing for identical calc below:
```
<   The DF Tensor (Qso) construction requires 31.261 GiB of memory. 
---
>   DFTensor Memory: Qso construction needs 31.261 GiB; user supplied 35.390 GiB. 
```
```
<         Total memory available:           38146.97 mb
<         CCSD memory requirements:         35113.77 mb
<             3-index integrals:            10081.38 mb
<             CCSD intermediates:           25032.39 mb
<         (T) algorithm:                     9055.34 mb (low-memory)
---
>         Total memory available:             37.253 [GiB]
>         CCSD memory requirements:           34.291 [GiB]
>             3-index integrals:               9.845 [GiB]
>             CCSD intermediates:             24.446 [GiB]
>         (T) algorithm: …
```
=> dftensor memory estimation overrun

psi4/src/psi4/occ/arrays.cc, psi4/src/psi4/occ/arrays.h, psi4/src/psi4/occ/dpd.cc, psi4/src/psi4/occ/dpd.h
These functions are never called anywhere C++-side, and not `PSI_API`.
This is another shard of the https://github.com/psi4/psi4/pull/2642 mega-PR that can be merged independently.
=> Remove unused diagonalizers and linear solvers from occwave::Array2d and occwave::SymBlockMatrix

psi4/src/psi4/libmints/basisset.cc, psi4/src/read_options.cc, tests/dfmp2-ecp/input.dat
This patch adds an option to FREEZE_CORE called "policy", which enables frozen core settings to be looked up from a list specified in the global variable FREEZE_CORE_POLICY. This is more flexible than NUM_FROZEN_DOCC for situations like SAPT where multiple molecules are run in the same command and may require different individual numbers of frozen cores, with settings more customizable than TRUE/FALSE/1/0/-1/-2
This patch addresses some (but not all) issues raised in #2631 by allowing for more flexible policies to be set appropriate to multi-part calculations.
=> Add customizable FREEZE_CORE policy option

doc/sphinxman/source/scf.rst, psi4/src/read_options.cc
Changes a setting in the COSX JK algorithm to a more conservative default.
Previously, the incremental fock option (`cosx_incfock`) was enabled by default. This gave a minor speedup, but it came at the risk of possible SCF convergence issues when using diffuse basis sets. This PR disables this option, so the COSX algorithm will be slightly slower, but more robust by default.
=> Change COSX default

psi4/src/psi4/libmints/wavefunction.cc, psi4/src/psi4/libmints/wavefunction.h, psi4/src/psi4/libscf_solver/cuhf.cc, psi4/src/psi4/libscf_solver/rhf.cc, psi4/src/psi4/libscf_solver/rohf.cc, psi4/src/psi4/libscf_solver/uhf.cc
`c1_deep_copy` sent `nsopi_` to `Wavefunction::epsilon_subset_helper` in place of the number of occupied orbitals. When `nsopi_[h] > nmopi_[h]` for some `h`, this led to accessing out-of-bounds memory. No more.
=> Fix `c1_deep_copy`

psi4/src/psi4/cc/ccenergy/Fmi.cc
Replace an old-style call to `moinfo_` in `cc` with something more modern: using Matrix technology to bypass the loop over the number of irreps.
=> Chip away at MOInfo (1/???)

psi4/src/psi4/mcscf/scf_energy.cc
mcscf::SCF::energy(...) has a block of commented out code for TCSCF references.
Removing it also allows the removal of unused `#include`s and an `extern FILE* outfile` declaration.
This is another shard of the https://github.com/psi4/psi4/pull/2642 mega-PR that can be merged independently.
=> Remove commented out code from mcscf

psi4/src/psi4/dlpno/mp2.cc
Fix a minor logic error in DLPNO-MP2 code, where Mulliken charges are used for determining local density fitting domains, also cleans up variable names (removes underscores from variables that are not instance variables).
=> DLPNO Mulliken Bug Fix

psi4/src/psi4/cc/ccenergy/get_moinfo.cc, psi4/src/psi4/cc/ccenergy/t1.cc, psi4/src/psi4/cc/ccwave.h
Replace an old-style call to `moinfo_` in `cc` with something more modern: get your number of irreps and orbital space information from the wavefunction. Once this is in, I can batch MOInfo elimination from several more files.
=> Chip away at MOInfo (2/???)

psi4/src/psi4/cc/ccenergy/rotate.cc, psi4/src/psi4/cc/ccwave.h, tests/cc15/output.ref, tests/cc16/output.ref
Cleanup `ccenergy/rotate.cc`. There's more cleanup to do, but this is a sufficiently large algorithm change that I'm breaking up the PR here.
=> Clean `ccenergy/rotate` (1/2)

.github/PULL_REQUEST_TEMPLATE.md, tests/dlpnomp2-2/input.dat
=> PR template and dlpno test fix

psi4/src/core.cc, psi4/src/psi4/scfgrad/scf_grad.cc, psi4/src/psi4/scfgrad/scf_grad.h, psi4/src/psi4/scfgrad/wrapper.cc, tests/pytests/test_gradients.py
Closes #2712. Please do not use C-style casting for complicated types.
=> Close #2712

psi4/src/psi4/libpsio/error.cc, psi4/src/psi4/libpsio/psio.h
Errors in PSIO should probably be handled by calling `psio_error(...)`, instead of printing the error messages from the function where the error happens.
This PR renovates this function to something more C++-style, and adds a new string argument that defaults to the empty string. This allows the callers of the function to prepend their own error messages to the text that eventually ends up in the error box, such as OS supplied error messages when a read/write/lseek system call fails.
This should make it easier to clean up `wt_toclen` etc. (see #2700)
=> Renovate the psio_error(...) function

psi4/src/psi4/cc/ccenergy/MOInfo.h, psi4/src/psi4/cc/ccenergy/get_moinfo.cc
When the `cc` mega-module was first created, the `Matrix` class did not exist, and manual reordering arrays were used to keep track of orbital indexing between the symmetry-blocked and non-symmetry-blocked convention. Thanks to #2719, the last of these in `ccenergy` has been replaced with `Matrix` technology, so there is no need to keep this reordering around. This PR thus removes them.
My next CC cleanup PR will Matrix-ify the remaining QT-using parts of `ccresponse`.
=> Remove QT ordering from ccenergy

.github/workflows/docs.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

psi4/src/export_mints.cc, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/matrix.h, tests/CMakeLists.txt, tests/matrix2/CMakeLists.txt, tests/matrix2/input.dat, tests/matrix2/test_input.py
Allow non-symmetric matrix <-> dpdfile2.
The hard part of this PR was figuring out how to initialize a dpd object successfully.
=> Allow non-symmetric matrix <-> dpdfile2

psi4/src/psi4/libmints/matrix.cc, tests/pytests/test_matrix.py
=> `set_block` with `symmetry_`

psi4/src/psi4/libpsio/close.cc, psi4/src/psi4/libpsio/filemanager.cc, psi4/src/psi4/libpsio/open.cc, psi4/src/psi4/libpsio/psio.h, psi4/src/psi4/libpsio/rw.cc, psi4/src/psi4/libpsio/toclen.cc, psi4/src/psi4/libpsio/volseek.cc
Definitions of various IO system call macros are currently replicated and/or scattered across files. These macros were added to paper over differences between Windows and Linux/Mac.
This PR coalesces all of them into `psio.h`.
None
=> Coalesce PSIO system call macros

psi4/src/psi4/libmints/matrix.cc, tests/pytests/test_matrix.py
=> Transpose with symmetry_

psi4/src/psi4/libmints/matrix.cc, tests/pytests/test_matrix.py
Make `back_transform` consistent across the various signatures and better behaved for more "exotic" cases.
=> Standardize `Matrix::back_transform`

psi4/src/psi4/cc/ccdensity/MOInfo.h, psi4/src/psi4/cc/ccdensity/ccdensity.cc, psi4/src/psi4/cc/ccdensity/ex_oscillator_strength.cc, psi4/src/psi4/cc/ccdensity/ex_rotational_strength.cc, psi4/src/psi4/cc/ccdensity/ex_sort_td_rohf.cc, psi4/src/psi4/cc/ccdensity/ex_sort_td_uhf.cc, psi4/src/psi4/cc/ccdensity/get_moinfo.cc, psi4/src/psi4/cc/ccdensity/oscillator_strength.cc, psi4/src/psi4/cc/ccdensity/rotational_strength.cc, psi4/src/psi4/cc/ccdensity/sort_ltd_rohf.cc, psi4/src/psi4/cc/ccdensity/sort_ltd_uhf.cc, psi4/src/psi4/cc/ccdensity/sort_rtd_rohf.cc, psi4/src/psi4/cc/ccdensity/sort_rtd_uhf.cc, psi4/src/psi4/cc/ccdensity/td_cleanup.cc, psi4/src/psi4/cc/ccdensity/transL.cc, psi4/src/psi4/cc/ccdensity/transdip.cc, psi4/src/psi4/cc/ccdensity/transp.cc
All pieces of `ccdensity` related to transition densities have been migrated to use `Matrix` and `Slice` tech, for a net cut of nearly 1100 lines of code!
Don't let the large delta LoC fool you. It's the same tricks over and over and over...
=> Move LTD/RTD and Integrals to `Matrix`

psi4/src/psi4/libmints/matrix.cc, tests/pytests/test_matrix.py
See below. Sister PR to #2734. Needed before I can cleanup `ccresponse`.
=> `get_block` with `symmetry_`

psi4/src/psi4/cc/ccresponse/MOInfo.h, psi4/src/psi4/cc/ccresponse/get_moinfo.cc, psi4/src/psi4/cc/ccresponse/preppert.cc, psi4/src/psi4/cc/ccresponse/sort_pert.cc
Eliminate index management from `ccresponse`.
=> Remove qt/pitzer from ccresponse

psi4/driver/procrouting/empirical_dispersion.py
As of qcengine 0.24, the keyword `local_options` is deprecated in favor of `task_config`. This PR updates the keywords in any remaining qcng calls (looks like main call in `task_base.py` was caught in a previous PR).
=> Update qcengine keywords

psi4/driver/driver_cbs.py, psi4/driver/driver_findif.py
I recently discovered a bug where CBS finite-difference Hessians will crash on systems with zero dipole moment. This is due to `CompositeComputer` not loading a dipole with entries all exactly zero into qcvars. This fix checks that CBS results are not None rather than have any non-zero entries before loading into qcvars. I have verified that this fixes the crash and that e.g. non-existing Hessians are stiil not loaded into result qcvars.
=> Fix crash on CBS finite-difference with zero dipole moment

psi4/src/psi4/libscf_solver/stability.cc, psi4/src/psi4/libscf_solver/stability.h
The old instability following procedure Trotterized a matrix exponential. Now we compute it (more or less) exactly.
Obligatory @susilehtola ping.
=> Modify Instability Following Step

conda/win/meta.yaml, psi4/src/psi4/libfock/PKmanagers.cc
This PR fixes the bug in the PK code brought up in https://github.com/psi4/psi4/issues/2760. It was observed that, for sufficiently small systems and small basis sets run in parallel, the calculation would converge to random energies. After some investigation, it was found that the buffer size assigned per thread in the PK algorithm could potentially be set to zero:
```    
size_t buffer_size = pk_size() / nthreads(); // DP: can be set to 0 in edge cases
size_t lastbuf = pk_size() % nthreads();
for (size_t i = 0; i < nthreads(); ++i) {
// DEBUG        outfile->Printf("start is %lu\n",start);
SharedPKWrkr buf = std::make_shared<PKWrkrInCore>(primary(), sieve(), buffer_size, lastbuf, J_ints_.get(),
K_ints_.get(), wK_ints_.get(), nthreads());
fill_buffer(buf);
set_ntasks(nthreads());
}
``` …
=> PK Bugfix 

psi4/src/psi4/libmints/potentialint.cc, psi4/src/psi4/libmints/potentialint.h
Fixes a segfault discovered by @mfherbst while developing #2767.
It was caused by adding `#include "psi4/libmints/potentialint.h"` in `mintshelper.cc`, because `potentialint.h` included L2's `engine.h`.
=> Restructure PCM functors

psi4/src/psi4/libpsio/CMakeLists.txt, psi4/src/psi4/libpsio/compose_err_msg.cc, psi4/src/psi4/libpsio/psio.h, psi4/src/psi4/libpsio/rw.cc, psi4/src/psi4/libpsio/toclen.cc, psi4/src/psi4/libpsio/volseek.cc
This PR builds upon the functions added in #2711 and #2700 to provide more informative error messages if a `SYSTEM_READ`, `SYSTEM_WRITE` or `SYSTEM_LSEEK` fails, including the OS-provided error message, which may have clues for the cause of the error (disk is full, no permission, etc).
=> Improve PSIO error messages for READ, WRITE and LSEEK

samples/scf5/input.dat, samples/scf5/test.in, tests/scf5/input.dat, tests/scf5/output.ref
The goal of this PR is to expand test coverage of the DFJCOSK and DFJLinK JK subclasses within Psi4 by including their testing within the scf5 test. The scf5 test in Psi4 tests a variety of combinations of SCF_TYPE and SCF reference for singlet and triplet O2. As it were, the COSX and LinK SCF_TYPES were missing from the list of methods analyzed within this test. This PR simply adds COSX and LinK to the list of methods tested in scf5, expanding testing of these two methods beyond what was previously present.
NOTE TO REVIEWERS: This PR is a general JK maintenance/cleanup/improvement PR and is independent of the developments occurring regarding CompositeJK and its direct implementation into Psi4.
=> Expand Testing of COSX and LINK SCF Types

psi4/src/psi4/libpsio/error.cc
While testing PR https://github.com/psi4/psi4/pull/2756, I have discovered a regression introduced by an earlier PR (#2700) of mine.
Before `throw`ing, `psio_error()` tries to write some data to the scratch files. But if `psio_error()` is called due to a write error, and the scratch disk is completely full, then this write will also fail, leading to `psio_error()` getting called again, and an infinite recursion ensues. The source of the regression is that `psio_tocwrite()` ends up calling `wt_toclen()`, which has been enhanced in #2700 to use `psio_error()` if it fails.
This PR resolves the issue by not trying to write anything to scratch if `psio_error()` is called due to a write failure.
=> Fix possible infinite recursion in psio_error when the scratch disk is completely full

psi4/src/psi4/cctransort/cctransort.cc, psi4/src/psi4/cctransort/memcheck.cc, psi4/src/psi4/detci/olsengraph.cc, psi4/src/psi4/dlpno/mp2.cc, psi4/src/psi4/fnocc/lowmemory_triples.cc, psi4/src/psi4/libfock/DirectJK.cc, psi4/src/psi4/libfock/solver.cc, psi4/src/psi4/libmints/cdsalclist.cc, psi4/src/psi4/libmints/extern.cc, psi4/src/psi4/libmints/extern.h
Printf format specifiers are required to match the type of the variable being printed. Using an incorrect format specifier may be UB. This PR resolves instances where the format specifier was incorrect. At least some of these have been triggering GCC warnings, so Psi4 now compiles with a couple fewer warnings.
=> Fix some incorrect printf format specifiers

psi4/driver/driver.py, psi4/driver/mdi_engine.py, psi4/driver/procrouting/proc.py
Sometime between https://github.com/psi4/psi4/commit/5b54376e4f358ec1318539d3ac0a2e42ea0483f8 and https://github.com/psi4/psi4/commit/7e4ecf968ec7920ab404cb357de827cf3785a254, the original(?) code for generating broken-symmetry guesses for UHF/UKS was disabled, and parts of it may have been removed since.
These days, the way to get a BS guess seems to be setting `guess_mix true`, which does not use the old BS code fragments in `scf_helper`.
So, as far as I can tell it is dead code. This PR removes it.
=> Remove remnants of some old, defunct code for doing BS-USCF

psi4/src/psi4/dlpno/mp2.cc, psi4/src/psi4/libfock/cubature.cc, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/matrix.h, psi4/src/psi4/libmints/molecule.cc, psi4/src/psi4/occ/ekt_ea.cc, psi4/src/psi4/occ/ekt_ip.cc, psi4/src/psi4/occ/semi_canonic.cc
Some overloads of `Matrix::diagonalize` in `libmints` are never called anywhere within Psi4, and some more are currently taking pointer arguments. They should be removed, but as discussed in #2693 the entire `Matrix` class is `PSI_API` and Forte is for sure using these diagonalization functions.
To keep the promise of not randomly breaking API without fair warning, this PR deprecates said functions but keeps them usable. Call sites within Psi4 are however converted to use non-deprecated overloads, so after 1.7 is out, completing the removal should just be a simple deletion of the deprecated overloads.
=> Deprecate some overloads of Matrix::diagonalize

doc/sphinxman/source/occ.rst, psi4/src/psi4/occ/arrays.cc, psi4/src/psi4/occ/arrays.h, psi4/src/psi4/occ/kappa_orb_resp.cc, psi4/src/psi4/occ/occwave.cc, psi4/src/psi4/occ/occwave.h, psi4/src/psi4/occ/z_vector.cc, psi4/src/read_options.cc
=> Use LAPACK for Linear Algebra in `occ`

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/psi4/cc/ccdensity/kinetic.cc, tests/cc1/input.dat
=> Modernize `cc` Virial Theorem

psi4/src/psi4/occ/arrays.h, psi4/src/psi4/occ/kappa_orb_resp.cc
=> Remove `Array2d` from `kappa_orb_resp.cc`

external/downstream/adcc/CMakeLists.txt
The version of ADCC that the Psi4 CMake system currently requires (and tries to build if not found) is incompatible with C++17, and thus always fails to build. See https://github.com/adc-connect/adcc/issues/131 for the error message. This error was also mentioned in issue #2572.
This has been resolved by the ADCC/libtensor devs since, so bumping the required/built ADCC version to the latest release should fix _this particular_ issue with the ADCC build process.
=> Bump required/built ADCC version to latest release

.azure-pipelines/azure-pipelines-linux.yml, cmake/autocmake_safeguards.cmake
The `-H<path>` option for CMake is technically not part of the CMake public interface, it is not documented and was never meant for public use. Since CMake 3.13 there is a proper alternative, `-S<path>`, so Psi4 should use that and stop suggesting users to use `-H<path>`.
=> Do not use or suggest the undocumented -H option for CMake

psi4/src/psi4/libciomr/libciomr.h
These functions are relics from Psi3 (or before?) and they have many issues, unfortunately one of them is their function signature. Stemming from the awful interface, users of `rsp(...)` and `sq_rsp(...)` never check if the diagonalization failed, because they _cannot_.
To keep the promise of not randomly breaking API without fair warning, this PR deprecates said functions but keeps them usable. After #2776, `rsp(...)` has no internal callers left. As for `sq_rsp(...)`:
- many former callers of `sq_rsp(...)` have turned out to be unused functions and have been removed
- If #2686 is merged the vast majority of remaining callers are migrated to a new wrapper around DSYEV
- The remaining call sites of `sq_rsp(...)` will all be in `dfocc`, which is not touched for the time being to avoid …
=> Deprecate PSI_API diagonalizers rsp(...) and sq_rsp(...)

psi4/src/psi4/cc/ccdensity/Params.h, psi4/src/psi4/cc/ccdensity/get_rho_params.cc
There are some char arrays in `ccdensity::RHO_Params` that are set in `get_rho_params` but are otherwise never used. This PR removes them. This rectifies a few warnings with GCC 12, caused by the `sprintf `calls used to set them.
=> Remove set-but-unused labels (char arrays) from ccdensity::RHO_Params

psi4/src/psi4/libfock/DFJLinK.cc, psi4/src/psi4/libfock/jk.h, tests/linK-1/input.dat, tests/linK-2/input.dat, tests/linK-3/input.dat
This PR is a rather important update to the DFJLinK JK subclass, counting both as the continuation of the CompositeJK development started in https://github.com/psi4/psi4/pull/2762 and the first PR in the new incremental Fock build standardization seen in https://github.com/psi4/psi4/pull/2682.
To describe the problem, as of now, different integral-direct JK algorithms use different implementations of the incremental Fock build formalism. DirectJK and DFJLinK use the same incremental Fock build formalism, while DFJCOSK uses its own methodology. This introduces two problems:
1. The next step of CompositeJK development is to combine DFJLinK and DFJCOSK into the pilot CompositeJK subclass. To ease this process, DFJLinK and DFJCOSK need to use the same incremental Fock process.
2. The …
=> CompositeJK Part 1.5: DFJLinK/DFJCOSK IncFock Standardization

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml, .github/workflows/ecosystem.yml, conda/win/meta.yaml, external/upstream/libxc/CMakeLists.txt, external/upstream/qcengine/CMakeLists.txt
=> bump libxc and revert qcng

.azure-pipelines/azure-pipelines-windows.yml, psi4/src/psi4/libfock/DirectJK.cc, psi4/src/psi4/libfock/jk.h, samples/scf5/input.dat
This PR is a continuation of the IncFock standardization effort initially started in https://github.com/psi4/psi4/pull/2682, and restarted in https://github.com/psi4/psi4/pull/2792. It is the second PR listed in the PR submission scheme discussed in the comments in https://github.com/psi4/psi4/pull/2682.
For all intents and purposes, the PR has basically the same changes as https://github.com/psi4/psi4/pull/2792, except applied to DirectJK instead of DFJLinK. The same benefits to DFJLinK seen in https://github.com/psi4/psi4/pull/2792 are applied to DirectJK here, and many of the same points of the benefits of that PR apply here, as well.
A couple of notes to be had for reviewers, some of which arise from discussions in https://github.com/psi4/psi4/pull/2792:
1. Unlike …
=> IncFock Standardization Part 2: DirectJK

psi4/src/psi4/cc/ccenergy/d1diag.cc, psi4/src/psi4/cc/ccenergy/d2diag.cc, psi4/src/psi4/cc/ccenergy/new_d1diag.cc, psi4/src/psi4/libqt/david.cc, psi4/src/psi4/mcscf/matrix_base.cc
PR #2686 has accidentally added some superfluous includes of `libpsi4util/PsiOutStream.h`, and I also missed removing a superfluous printf line. No real harm done, but they can be removed.
=> Remove superfluous PsiOutStream includes

psi4/src/psi4/libpsio/rw.cc, psi4/src/psi4/libpsio/toclen.cc, psi4/src/psi4/libpsio/volseek.cc
Apparently `errno` is not defined on FreeBSD by default, so we have to explicitly include `<cerrno>` in files that use it. This PR adds that include.
Fixes and closes #2810
=> Include <cerrno> where required for the sake of FreeBSD

psi4/src/psi4/libqt/blas_intfc.cc, psi4/src/psi4/libqt/qt.h
After the removal of `sem_test` in #2776, the only remaining internal user of `libqt/schmidt_add.cc` is `libqt/david.cc`. That too is destined for removal, if its only user in `dfocc` is removed by #2684. So it looks like `schmidt_add` could be removed in the future, when all of its callers are gone.
To keep the promise of not randomly breaking API without fair warning, this PR deprecates the function, setting up its eventual removal. Note that this `schmidt_add` is not the same function as the `schmidt_add` in `cceom` or `detci`, even though the name is the same.
=> Add deprecation message to schmidt_add in libqt

psi4/src/psi4/detci/set_ciblks.cc
=> Close #2779

doc/sphinxman/source/scf.rst, psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/export_fock.cc, psi4/src/psi4/libfock/DFJCOSK.cc, psi4/src/psi4/libfock/jk.h, psi4/src/read_options.cc, tests/pytests/test_dfjcosk.py
... and another one!
This PR is a continuation of the IncFock standardization effort initially started in https://github.com/psi4/psi4/pull/2682, and continued in https://github.com/psi4/psi4/pull/2792 and https://github.com/psi4/psi4/pull/2808.
This PR continues to standardize the Incremental Fock process across the current integral-direct JK algorithms present in Psi4. However, this PR stands somewhat in contrast to https://github.com/psi4/psi4/pull/2682 and https://github.com/psi4/psi4/pull/2792. In those PRs, their IncFock schemes were adapted to use that of DFJCOSK, without removing the bells and whistles of their IncFock implementations (e.g., recomputing the full Fock matrix every so often, disabling IncFock after a given convergence threshold). In contrast, DFJCOSK is the template …
=> IncFock Standardization Part 3: DFJCOSK

psi4/src/psi4/libfock/dft_integrators.h, psi4/src/psi4/libfock/points.h, psi4/src/psi4/libfock/v.cc, psi4/src/psi4/libfock/v.h, psi4/src/psi4/libfunctional/superfunctional.h
=> Comment `compute_V`; Parallelize UKS `compute_V`

psi4/src/psi4/libfock/v.cc
=> `UV::compute_Vx` Bugfix

.github/workflows/ecosystem.yml
now tests the "next" half of #2821 on GHA. Linux is testing "next" and Mac is testing master.
=> ecosys gha on qcarchive next

psi4/driver/driver_findif.py, tests/CMakeLists.txt, tests/opt16/CMakeLists.txt, tests/opt16/input.dat, tests/opt16/log.ref, tests/opt16/output.ref, tests/opt16/test_input.py
Fixes a bug encountered when running optimizations in BAKERJCC96. All calculations in a finite difference
calculation were writing orbitals to disk and overwriting the old orbitals. Only reference calculation should
be saved. In cases were the symmetry was lowered in one of the last displacements, subsequent gradient calculations
were failing to read orbitals.
```  
File "/home/zander/github/psi4/objdir/stage/lib/psi4/driver/procrouting/proc.py", line 1761, in scf_helper
raise ValidationError("Cannot compute projection of different symmetries.")
```
=> Fixes orbital read for finite difference hessian

psi4/src/psi4/libfock/points.cc, tests/CMakeLists.txt, tests/dlpnomp2-3/CMakeLists.txt, tests/dlpnomp2-3/input.dat, tests/dlpnomp2-3/output.ref, tests/dlpnomp2-3/test_input.py
I have discovered that running DLPNO-MP2 (#2093, #2378) on Cartesian basis sets like (6-31G, 6-31G*, 6-31+G, 6-31+G*, etc) leads to a segfault. Turns out, this was a bug in the `PointsFunction` class, where `set_deriv(0)` is not called 
if the basis set is NOT spherical. I fixed the bug and added a new test case to reflect this.
Requesting reviews from @zachglick @loriab @JonathonMisiewicz 
None :)
None
=> Fix DLPNO-MP2 Segfault with Cartesian Basis Sets

.github/workflows/docs-pr.yml, devtools/conda-envs/docs-cf.yaml, psi4/driver/qcdb/bfs.py
```
Tests failed for psi4-1.8a1.dev6+758d3af-py38_0.tar.bz2 - moving package to C:\tools\miniconda3\conda-bld\broken
WARNING:conda_build.build:Tests failed for psi4-1.8a1.dev6+758d3af-py38_0.tar.bz2 - moving package to C:\tools\miniconda3\conda-bld\broken
E         File "%PREFIX%\lib\site-packages\psi4\driver\qcdb\bfs.py", line 80, in BFS
E           radii = _get_covalent_radii(elem)
E         File "%PREFIX%\lib\site-packages\psi4\driver\qcdb\bfs.py", line 155, in _get_covalent_radii
E           covrad = np.fromiter((covalent_radii_lookup[caps[at]] for at in range(nat)), dtype=np.float, count=nat)
E         File "%PREFIX%\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
E           raise AttributeError("module {!r} has no attribute "
E       
E       AttributeError: module …
```
=> np.float update

psi4/src/export_mints.cc, psi4/src/psi4/fisapt/fisapt.cc, psi4/src/psi4/libcubeprop/csg.cc, psi4/src/psi4/libfock/DFJCOSK.cc, psi4/src/psi4/libmints/extern.cc, psi4/src/psi4/libmints/integral.cc, psi4/src/psi4/libmints/integral.h, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libmints/oeprop.cc, psi4/src/psi4/libmints/orbitalspace.cc, psi4/src/psi4/libmints/x2cint.cc, psi4/src/psi4/libpsipcm/psipcm.cc, psi4/src/psi4/libsapt_solver/sapt.cc, psi4/src/psi4/libscf_solver/sad.cc, psi4/src/psi4/scfgrad/response.cc, psi4/src/psi4/scfgrad/scf_grad.cc
Fixes #2493 
For memory safety, the integrals in libmints should be returned as unique_ptrs rather than raw pointers
=> change raw pointer return in `libmints` to `std::unique_ptr`

psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/matrix.h
This PR removes the `Matrix::diagonalize` overloads deprecated in PR #2738 and closes #2693 as done/superseded.
=> Remove deprecated overloads of Matrix::diagonalize

psi4/src/psi4/dct/dct_compute_RHF.cc, tests/CMakeLists.txt, tests/dct12/CMakeLists.txt, tests/dct12/input.dat, tests/dct12/output.ref, tests/dct12/test_input.py
=> Restore DCT-06 with spin restriction.

psi4/driver/driver.py
The purpose of this PR is the following:
- Fix #2871 
The bug observed when optimizing a molecule containing `Cl` atom using `geometric` via Psi4.
=> Capitalize atom symbols for geometric

psi4/src/psi4/libmints/molecule.cc
`Molecule::clear()` is currently almost a no-op, because it is calling `std::vector::empty()`, which is a getter function that does not modify the object. This PR corrects that.
Is the comment misleading as I suspect it is, or do callers of `Molecule::clear()` really expect it to preserve the size of `Molecule::atoms_`  and `Molecule::full_atoms_`?
=> Actually clear vectors in Molecule

psi4/driver/procrouting/dft/dft_builder.py, psi4/src/export_functional.cc, psi4/src/psi4/libfunctional/LibXCfunctional.cc, psi4/src/psi4/libfunctional/LibXCfunctional.h
=> Libxc citation

psi4/src/psi4/libfunctional/LibXCfunctional.cc, psi4/src/psi4/libfunctional/LibXCfunctional.h, psi4/src/psi4/libfunctional/functional.h, psi4/src/psi4/libfunctional/superfunctional.cc, psi4/src/psi4/libfunctional/superfunctional.h
Adds a function to create a polarized (UKS) version of an unpolarized (RKS) functional. Needed for #2885. We can build the triplet derivatives only by taking combinations of the UKS derivatives. We can't just take single-spin-channel derivatives, as RKS can.
=> Add build_polarized function.

psi4/src/psi4/libscf_solver/cuhf.cc, psi4/src/psi4/libscf_solver/cuhf.h, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/psi4/libscf_solver/hf.h, psi4/src/psi4/libscf_solver/rhf.cc, psi4/src/psi4/libscf_solver/rhf.h, psi4/src/psi4/libscf_solver/rohf.cc, psi4/src/psi4/libscf_solver/rohf.h, psi4/src/psi4/libscf_solver/uhf.cc, psi4/src/psi4/libscf_solver/uhf.h
The `potential_` of SCF subclasses has been moved.
=> potential_ moved to subclasses.

doc/sphinxman/source/tdscf.rst, psi4/driver/procrouting/response/scf_products.py, psi4/driver/procrouting/response/scf_response.py, psi4/src/export_wavefunction.cc, psi4/src/psi4/libfock/v.cc, psi4/src/psi4/libfock/v.h, psi4/src/psi4/libfunctional/superfunctional.cc, psi4/src/psi4/libfunctional/superfunctional.h, psi4/src/psi4/libscf_solver/hf.h, psi4/src/psi4/libscf_solver/rhf.cc, psi4/src/psi4/libscf_solver/rhf.h, tests/pytests/test_tdscf_excitations.py
This PR has TDDFT triplets for LDA and GGA functionals. (Psi does not currently support any TDDFT for meta functionals.) This requires lots of moving parts, so this PR serves as a reference for how they all fit together. For ease of reviewing, I'll have smaller PRs that pull off independent pieces for analysis.
While I'm waiting for reviews, I'll update comments to show exactly how I know these spin-integration formulae are correct, for the benefit of future debuggers.
Closes #2841.
There are four parts that I can split into separate PRs for reviewer convenience. Then I can bring in this PR.
Why were DFT triplets harder than HF triplets? To understand this, we need to understand both the origin of the triplet matrix and the spin properties of the relevant matrix elements.
1. Starting from …
=> Triplet TDDFT

psi4/src/psi4/libqt/probabil.cc, psi4/src/psi4/libqt/qt.h
This PR reworks and simplifies `libqt/probabil.cc`. Excessive conditionals are removed, sanity checks now throw instead of returning zero, and the `double` kludge is supplanted by `uint64_t`
=> Rework factorial and n-choose-k functions in libqt

psi4/src/psi4/dfocc/arrays.cc, psi4/src/psi4/dfocc/arrays.h, psi4/src/psi4/dfocc/tensors.cc, psi4/src/psi4/dfocc/tensors.h
Much like `occ` (PR #2679), `dfocc` also has these functions that are never called anywhere C++-side, and not `PSI_API`.
This is another shard of the https://github.com/psi4/psi4/pull/2642 mega-PR that can be merged independently.
=> Remove unused diagonalizers and linear solvers from dfoccwave::Tensor2d and dfoccwave::Array2d

psi4/src/psi4/libfock/DFJCOSK.cc
This PR provides a more useful error message when the issue described in https://github.com/psi4/psi4/issues/2890 is encountered. In short, the COSX K build method breaks with certain grid configurations - specifically, grid configurations which result in negative grid weights. How to best handle that issue - removing such grid configurations from Psi4 entirely, handling negative grid weights differently within COSX itself - is still under discussion, and this PR is _not_ meant to be a final fix to the aforementioned issue.
Rather, this PR is meant to provide a more informative error message in the case that an end user _does_ encounter this error. Currently, when this error is encountered, it shows up as either a DGESV error (if the initial COSX grid has negative weights) or an ADIIS …
=> Better Error Message for Issue #2890

CMakeLists.txt, psi4/header.py, psi4/src/export_mints.cc, psi4/src/psi4/libqt/CMakeLists.txt, psi4/src/psi4/libqt/blas_intfc.cc, psi4/src/psi4/libqt/lapack_intfc.cc, psi4/src/psi4/libqt/qt.h
- Note that the CI error was due to ongoing changes in QCArchive `next` branch. I've pinned the dep back a release so that psi4's interface to it can be fixed later.
```
import psi4
import numpy as np
vecX = np.array([1., 1., 1.])
pvecX = psi4.core.Vector.from_array(vecX)
print(pvecX.np)  # 1
vecY = np.array([5., 5., 5.])
pvecY = psi4.core.Vector.from_array(vecY)
print(pvecY.np)  # 5
pvecX2 = pvecX.clone()
pvecX2.axpy(2.0, pvecY)
print(pvecX2.np)  # 11
pvecX2 = pvecX.clone()
pvecX2.axpby(2.0, 1.0, pvecY)
print(pvecX2.np)  # 11
pvecX2 = pvecX.clone()
pvecX2.axpby(2.0, 3.0, pvecY)
print(pvecX2.np)  # 13
```
=> daxpby workaround

psi4/src/psi4/libpsi4util/libpsi4util.h, psi4/src/psi4/libpsi4util/process.h, psi4/src/psi4/libpsi4util/stl_string.cc, psi4/src/psi4/libsapt_solver/disp2ccd.cc, psi4/src/psi4/libsapt_solver/sapt2p.h
After seeing some GCC warnings related to sprintf usage I decided to modernize SAPTDIIS label generation with the use of `std::string` and a new utility function to retain the output format of `%2d`.
=> Modernize SAPTDIIS label generation

psi4/__init__.py, psi4/extras.py, psi4/run_psi4.py, psi4/src/core.cc
=> set_output_file enhancements

doc/sphinxman/source/scf.rst, psi4/src/psi4/libfock/CDJK.cc, psi4/src/psi4/libfock/DiskDFJK.cc, psi4/src/psi4/libfock/jk.cc, psi4/src/psi4/libfock/jk.h, psi4/src/read_options.cc, samples/linK-2/input.dat
This PR is part two of a mini-project regarding the two DFJK algorithms present in Psi4. The first PR (https://github.com/psi4/psi4/pull/2848) applied to MemDFJK, and the second PR (this one) applies to DiskDFJK. The goal of this PR project is to add an expert keyword to allow user control over which subalgorithm is used by either MemDFJK or DiskDFJK. See, MemDFJK and DiskDFJK, despite their name, each have separate "subalgorithms" optimized to be run either in-core or out-of-core. While MemDFJK and DiskDFJK can be independently selected with `SCF_TYPE`, their subalgorithms cannot be; subalgorithm selection was previously controlled exclusively through memory allocated to Psi4. The mini-project this PR is part of, is meant to rectify that issue.
In the previous PR of this project, the …
=> DFJK Expert I/O Control Part 2: DiskDFJK

psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/core.cc, psi4/src/psi4/libfock/PKmanagers.cc, psi4/src/read_options.cc
This PR is a companion PR to https://github.com/psi4/psi4/pull/2848 and https://github.com/psi4/psi4/pull/2924. Those two PRs introduced the `SCF_SUBTYPE` keyword to Psi4, allowing for specifications of subalgorithms in SCF methods where appropriate, and applied the `SCF_SUBTYPE` keyword to MemDFJK and DiskDFJK, respectively.
As it turns out, the DFJK algorithms aren't the only JK algorithms where this new keyword may be useful.
The PKJK algorithm contains a number of subalgorithms, as well - an in-core algorithm (labeled InCore in the code) and two out-of-core algorithms (labeled Reorder and Yoshimine in the code). PKJK has some amount of control over which subalgorithm is utilized already - the `PK_ALGO` keyword specifies whether the Reorder or Yoshimine out-of-core algorithm is to be …
=> DFJK Expert I/O Control Bonus: PKJK

psi4/driver/mdi_engine.py, psi4/driver/molutil.py, psi4/driver/procrouting/proc.py, tests/cc31/CMakeLists.txt, tests/cc31/test_input.py, tests/fsapt-ext-abc-au/input.dat, tests/fsapt-ext/input.dat, tests/pytests/test_mdi.py
@carolinesargent identified a bug where running FSAPT with an external potential w/o having frozen the orientation with no_com + no_reorient would run but give the wrong answer. :-(
External potentials has long been one of those cases where we required the user to freeze the orientation at molecule creation time so that the potential could be set in the same frame. This couldn't be fixed driver-side because as soon as the `core.Mol` builds w/o freeze directives, it loses the original Cartesian coordinates. (The clone, set_nocom, set_noreorient calls in the driver allow _regular_ sapt to forego user setting by preventing the dimer, monoA, monoB from having different frames.)
Happily, in the intervening period, @maxscheurer ran into exactly this problem for polarizable embedding potentials …
=> Fix fsapt + external potential - nocom/noreorient

psi4/driver/p4util/python_helpers.py, psi4/src/psi4/libmints/sieve.h
This PR is a companion to https://github.com/psi4/psi4/pull/2933. The goal of https://github.com/psi4/psi4/pull/2933 is to completely eliminate the `ERISieve` class, for reasons explained there. However, it turns out that eliminating `ERISieve` requires fiddling with the v2rdm_casscf plugin, as well, since it also uses `ERISieve`.
This PR is meant to be a deprecation of the `ERISieve` class that will show up in v1.8 in the meantime, in case `ERISieve` isn't fully removed by then.
=> Deprecate ERISieve

cmake/FindPythonModule.cmake, external/upstream/CMakeLists.txt, psi4/__init__.py, psi4/psi4.bat, psi4/run_psi4.py, psi4/share/psi4/scripts/ixyz2database.py, psi4/versioner.py
~Note: this isn't going to pass until after #2946~
=> modernize paths and bugfixes

.github/workflows/ecosystem.yml, external/upstream/pcmsolver/CMakeLists.txt, psi4/src/psi4/libpsipcm/psipcm.cc, tests/pcmsolver/dft/input.dat, tests/pcmsolver/dipole/input.dat, tests/pcmsolver/ghost/input.dat, tests/pcmsolver/scf/input.dat, tests/pytests/test_addons.py, tests/pytests/test_addons_qcschema.py
For reasons described at https://github.com/PCMSolver/pcmsolver/issues/201, Psi4 has been fixed at PCMSolver v1.2.1 . This updates to v1.2.x with very small (e.g., 1e-8) tweaks to ref values. I do finally understand why v1.3.x was failing, but those are much larger changes to ref values (e.g., 1e-2; probably washes out in relative energies), so I'd like @robertodr  to weigh in.
UPDATE: The plan is to go with v1.2 for now and wait on v1.3. The conda package is RTG at 1.2 but isn't merged yet. A later rebuild of the 1.8 conda package could include pcmsolver support.
=> update PCMSolver interface to v1.2.3

tests/linK-1/output.ref, tests/linK-2/output.ref, tests/linK-3/output.ref, tests/scf5/output.ref
A small, simple companion to https://github.com/psi4/psi4/pull/2833. This updates to the reference output files for the tests that use CompositeJK methods (linK-1, linK-2, linK-3, and scf5), especially notable since the current reference files use `DIRECTDFJ` for composite `SCF_TYPE` methods instead of the current `DFDIRJ`.
N/A
N/A
=> CompositeJK Part 2.5: Update Reference Outputs

.github/workflows/ecosystem.yml, external/upstream/ddx/CMakeLists.txt, psi4/driver/procrouting/solvent/ddx.py, tests/pytests/test_ddx.py
Fixes #2940. Closes #2921
@mnottoli  Could you quickly give this a second pair of eyes to check what I'm doing [here when I'm lowering the tolerance](https://github.com/psi4/psi4/blob/6173fba2dc820bba05918f3dfa599550704de4f5/tests/pytests/test_ddx.py#L112) is reasonable --- I'm thinking this is the escaped charge problem for this small system. Maybe we should just remove the test alltogether?
=> Fix tests to reflect pyddx 0.4

doc/sphinxman/source/ddx.rst, psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/driver/procrouting/solvent/ddx.py, tests/pytests/test_ddx.py
Extends DDX interface to support SCF response and TDSCF.
=> Enable dd-solvated TDSCF

psi4/src/psi4/libmints/twobody.cc, psi4/src/read_options.cc, tests/pytests/test_erisieve.py
Add ScreeningType::None as a user option and sets ScreeningType::Schwarz as the default. This should allow use of mixed basis set types to be used in integrals as well.
N/A
=> Adds user option for ScreeningType::None

psi4/src/psi4/lib3index/dfhelper.cc, tests/pytests/test_misc.py
```
import psi4
mymol = psi4.Molecule.from_arrays(geom=[0, 0, 0, 2, 0, 0], elem=["h", "h"], name="h2/mol")
#psi4.set_options({"scf_type": "pk", "df_basis_guess": "false"})
ene = psi4.energy("b3lyp/cc-pvtz", molecule=mymol)
print(ene)
```
=> sanitize molecule names for dfhelper

psi4/src/psi4/libmints/mintshelper.cc, tests/pytests/test_mints.py
Quick fix to symmetry in one-electron integral calls in MintsHelper. Closes #2985
=> Fix #2985: Symmetry OEINTS

doc/sphinxman/source/scf.rst, psi4/driver/procrouting/scf_proc/scf_iterator.py, psi4/src/psi4/libfock/CompositeJK.cc, psi4/src/read_options.cc
Currently, COSX in Psi4 uses a two-grid scheme to complete the SCF - the SCF is first converged on a smaller grid, and then a single iteration is performed on a larger grid, a scheme proposed by Neese. This scheme works quite well for energies; but since the SCF isn't converged on the larger grid, it may not be as ideal if wavefunction properties (e.g., gradients) are desired.
This PR fixes that by adding a new keyword, `COSX_MAXITER_FINAL`, an integer that determines the maximum number of SCF iterations to run on the final COSX grid. By default, this keyword is set to 1, mimicking the current behavior of the code. A more detailed description of behavior can be broken down as follows:
- If `COSX_MAXITER_FINAL` < 0; the SCF will attempt to fully converge on the final COSX grid (within the …
=> More SCF Convergence Control for COSX Final Grid

psi4/src/export_mints.cc, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libmints/mintshelper.h
A small addition needed for an F12 code to work Python-side. Adds the ability to call
```
ao_f12g12(exp_coeff, Basis1, Basis2, Basis3, Basis4)
ao_double_commutator(exp_coeff, Basis1, Basis2, Basis3, Basis4)
```
with an arbitrary combination of 4 bases (some combinations require `SCREENING == 'NONE'` - see #2973). The other kinds of F12 integrals, e.g. `ao_f12()`, already have this functionality and just the two above types were missing.
This minor PR should be completely orthogonal to the recent PRs from @EricaCMitchell. All of these PRs will be needed for the upcoming F12 codes.
=> Add ao_f12g12() and ao_double_commutator() for a quadruplet of bases

psi4/src/psi4/scfgrad/response.cc, psi4/src/psi4/scfgrad/scf_grad.h
The `JK_deriv2` function exists to compute the overlap-derivative-times-TEI part of the right side of the CPHF equation. It's a J-term and a K-like term. with overlap derivative integrals instead of a density.[1] The previous algorithm to do this first computed the alpha spin part in one function call, and then the beta spin part in another function call. This approach was redundant. The first function call had all the intermediates _necessary_ to compute the beta part, but didn't use them. As a result, the function re-computed JK.
This PR refactors `JK_deriv2` so it computes both spin cases in a single function call.
[1] = There's also a Vx term, but its implementation was both unused and buggy. Now it's just unused. Trying to use it in the _old_ way would be even more redundant.
=> Refactor `JK_deriv2`

psi4/src/psi4/scfgrad/response.cc, psi4/src/psi4/scfgrad/scf_grad.h
Refactor `assemble_Q` [like `JK_deriv2`](https://github.com/psi4/psi4/pull/2994). The code had the same problem, so I use the same solution.
=> Refactor assemble_Q

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml, .github/workflows/ecosystem.yml, devtools/conda-envs/docs-cf.yaml
Current qcel not compatible with the new pydantic v2. I minted a new qcel build with the constraint, but the solver sometimes optimizes for pydantic anyways. So let's try explicit constraint.
=> restrain pydantic to v1

psi4/src/psi4/libpsio/error.cc
For some poorly understood confluence of reasons, for some users error messages can _sometimes_ get completely lost when Psi4 exits with a `PSIEXCEPTION`, especially when a PSIO error happens.
This can be observed in recent bug reports, see:
- https://github.com/psi4/psi4/issues/2970
- https://forum.psicode.org/t/sapt0-calculation-crashes-pointer-error/2839
In both of these cases the users were only seeing the error message that has been written to `cerr`, but not the string that `PSIEXCEPTION` should have printed.
IIRC when I tried to research this quite a while ago, I have found this may be a bug in some versions of libstdc++. This PR adds a simple workaround: the exception message is also printed to `cerr` in `psio_error`.
The only side effect, is that some users, who are currently not …
=> Print full PSIO error message to cerr as well

external/downstream/v2rdm_casscf/CMakeLists.txt, psi4/driver/p4util/python_helpers.py, psi4/src/psi4/libfock/PK_workers.cc, psi4/src/psi4/libfock/PK_workers.h, psi4/src/psi4/libfock/PKmanagers.cc, psi4/src/psi4/libfock/PKmanagers.h, psi4/src/psi4/libfock/jk.h, psi4/src/psi4/libmints/sieve.cc, psi4/src/psi4/libmints/twobody.h
This PR is a reimplementation of https://github.com/psi4/psi4/pull/2933; but instead of entirely deleting the `ERISieve` class, it makes `ERISieve` inaccessible for use through the following:
- Using `core.ERISieve.build` now throws an `UpgradeHelper` exception when called, as compared to the previous behavior of giving a warning.
- Calling the `ERISieve` constructor C++-side now throws an exception, with the same message as the UpgradeHelper would give.
Aside from that, this PR does the same things as https://github.com/psi4/psi4/pull/2933. `ERISieve` is replaced with `TwoBodyAOInt` in all use cases, with adjustments as necessary. Additionally, the new version of v2rdm_casscf is used, which also uses `TwoBodyAOInt` instead of `ERISieve`.
- N/A
=> Begone, ERISieve (Kind of)!

doc/sphinxman/source/bibliography.rst, doc/sphinxman/source/scf.rst, psi4/driver/procrouting/proc.py, psi4/src/psi4/libscf_solver/hf.cc, psi4/src/psi4/libscf_solver/hf.h, psi4/src/psi4/libscf_solver/sad.cc, psi4/src/psi4/libscf_solver/sad.h, psi4/src/read_options.cc, tests/pytests/test_scf_options.py, tests/scf-guess/input.dat
This PR implements another variant of the Hückel guess.
The only modification is that the `k` parameter in the GWH rule is replaced by the updated rule from [doi:10.1021/ja00480a005](https://doi.org/10.1021/ja00480a005)
=> Implement another variant of the Hückel guess.

psi4/share/psi4/scripts/test_threading.py, psi4/src/psi4/libfock/DiskDFJK.cc
=> threading test patch

.azure-pipelines/azure-pipelines-linux.yml, CMakeLists.txt, devtools/conda-envs/docs-cf.yaml, doc/sphinxman/source/build_obtaining.rst, doc/sphinxman/source/build_planning.rst, doc/sphinxman/source/fisapt.rst, external/upstream/ambit/CMakeLists.txt, external/upstream/dkh/CMakeLists.txt, external/upstream/pcmsolver/CMakeLists.txt, external/upstream/qcelemental/CMakeLists.txt, external/upstream/qcengine/CMakeLists.txt, psi4/driver/driver_cbs.py, psi4/driver/driver_findif.py, psi4/driver/driver_nbody.py, psi4/driver/task_base.py
=> adapt for pydantic v1 and v2

psi4/src/psi4/libmints/potential.cc, psi4/src/psi4/libmints/sobasis.cc, psi4/src/psi4/libmints/sobasis.h, psi4/src/psi4/libmints/sointegral.cc, psi4/src/psi4/libmints/wavefunction.cc
A quick cleanup removing `new` and `delete` in favor of `std::vector` in SOBasis.
=> Remove new's in SOBasis

psi4/src/psi4/libmints/cdsalclist.cc, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/molecule.cc, psi4/src/psi4/libmints/petitelist.cc, psi4/src/psi4/libmints/petitelist.h, psi4/src/psi4/libmints/sobasis.cc
Cleanup to libmints/petitelist to remove manual memory management in favor of `std::vector`.
Some of the code was not really clear (use of both `len` and `length` in some of the SO objects).
=> Get rid of manual memory management in petitelist

conda/win/meta.yaml, devtools/conda-envs/docs-cf.yaml
For now, a shot in the dark to fix the psicode docs and the nightly windows package. As far as I can tell, there's nothing wrong with the master docs build --  https://psi4manual.netlify.app/ has all its links working just fine. But there's something a little different about how the internal links are expressed, and that makes the redirects misfire when accessed from psicode.org https://github.com/psi4/psicode-hugo-website/blob/master/netlify.toml#L12 .
=> docs and win build

psi4/src/export_mints.cc
~Nominally a~ clarification of some deceptive commands. ~Really to test whether qcf snowflake testing is as broken as I see on another branch.~
=> fix_orientation docstring

psi4/src/psi4/libfock/CompositeJK.cc
This PR is a follow-up to https://github.com/psi4/psi4/pull/2906, and what can be considered an official solution to the issue discussed in https://github.com/psi4/psi4/issues/2890. The current issue is that COSX does not work with certain grid configurations - specifically, it does not work with grids that have negative grid weights, due to the use of an intermediate matrix in COSX that uses the square root of negative grid weights. https://github.com/psi4/psi4/pull/2906 "fixed" this issue by having COSX throw an exception when grids with negative weights were encountered. This PR provides a COSX reformulation that allows COSX to work with negative grid weights.
The reformulation does two primary things:
- The $X$ matrix (Eq. 4 in [Neese …
=> COSX Reformulation for Negative Grid Weights

psi4/src/psi4/libciomr/tstart.cc, psi4/src/psi4/libqt/timer.cc
Improvements discussed in a comment to #3043. The 64-character limit may not be valid on all architectures; this PR should avoid having to revisit the patch.
=> Amend #3043 by allowing a longer hostname and simplifying the code.

doc/sphinxman/source/conf.py.in
=> fix docs build after QCArchive documentation shuffle

doc/sphinxman/source/bibliography.rst, doc/sphinxman/source/sapt.rst
Update the manual to clarify that exchange-scaling of S^2-approximated terms
is no longer done by default, and explain why (cite 2013 Jansen paper)
This is just a quick text edit of the manual, nothing else has changed.
=> Cd sherrill patch 3

tests/pytests/test_comprehensive_jk_screening.py
This PR is designed to enable testing of a wide variety of combinations of `SCF_TYPE`, `SCF_SUBTYPE`, and `SCREENING` keywords available in Psi4. Of the currently-available JK tests, scf5 covers a wide variety of build methods, but only at a single screening type per method (density or csam, depending on the method). Meanwhile, `test_erisieve.py`, after the updates introduced in https://github.com/psi4/psi4/pull/2973, tests a wide variety of screening types, but with limited testing in conjunction with different JK builds (the only tests that don't use the Python interface of `TwoBodyAOInt` directly, use `SCF_TYPE=DIRECT` or `DF` as the JK method for screening comparisons). This leaves a lot of untested JK build+screening combos, which may be potentially broken and uncaught by the CI as a …
=> Add Comprehensive JK Build+Screening Testing

psi4/src/psi4/libfock/SplitJK.h
Thanks to @JonathonMisiewicz for catching this one!
This PR fixes a typo in `SplitJK::set_lr_symmetric`, wherein the `lr_symmetric_` variable is assigned to itself rather than the intended behavior of being assigned to the function input.
This also opens up the question of why this wasn't caught in testing, which I plan on exploring further and addressing in a second PR. Currently, composite methods where `LinK` is used, throw exceptions for cases where `lr_symmetric_` is set to false; but composite methods using `COSX` does not.
N/A
N/A
=> Fix typo in SplitJK::set_lr_symmetric

.github/workflows/docs.yml
I've changed the structure of psi4/psi4docs so that it can store snapshots as well as master. See table https://github.com/psi4/psi4docs#readme . This is a great boon to the psicode.org website processing b/c hugo doesn't like the tens of thousands of static files we have of docs snapshots. Hopefully these lines send the build docs to the new location in the psi4docs repo.
=> reroute docs build

psi4/src/psi4/libpsi4util/exception.h
In C++, the destructor for a templated class should not include the template parameter in the destructor's name. This is not a problem for C++17 and earlier standards, but with C++20 compilers it raises an error. This PR fixes one instance of this problem in psi4.
=> Fix compilation error for C++20

psi4/run_psi4.py
=> make `psi4 --version` faster

external/upstream/libint2/CMakeLists.txt
Small fix to Libint build generator
=> Libint2 Generator

psi4/src/psi4/scfgrad/scf_grad.cc
Issue from forums: https://forum.psicode.org/t/dispersion-gradients/2979
=> Fix printing of dispersion gradients

psi4/src/export_mints.cc, psi4/src/psi4/libmints/dimension.cc, psi4/src/psi4/libmints/dimension.h
This PR aims to improve the Dimension object in various ways, by adding machine-readable (for eg. VSCode) docstrings, adding const to arguments, replacing `int` with `size_t` to match `std::vector::operator[](std::size_t)` and cautiously deprecating member functions that deal with pointers.
Not only are pointers more error-prone, they are currently involved in some strange interaction between `Dimension` and `Matrix` objects, resulting in awkward roundabout initialization/construction that I hope to untangle before Psi4 1.11? (1.11, or maybe 1.12?).
Please let me know if you feel the three deprecations in this PR would be too disruptive or otherwise undesirable, this PR is very much a "request for comments".
−`Dimension::Dimension(int, const std::string&)` is now …
=> Renovate Dimension object

psi4/driver/procrouting/sapt/sapt_proc.py, psi4/driver/procrouting/sapt/sapt_util.py
The purpose of this PR is to turn off FDDS dispersion when SAPT_DFT_FUNCTIONAL = HF in SAPT(DFT). 
SAPT0 uses a HF description of monomers, whereas SAPT(DFT) replaces this description with KS-DFT.  When SAPT(DFT)’s functional is set to HF, the results should be equivalent to those of SAPT0. Currently, SAPT(DFT) / SAPT_DFT_FUNCTIONAL HF computes coupled dispersion with FDDS. This step is costly and unnecessary.
=> Turning off FDDS disp when SAPT_DFT_FUNCTIONAL = HF

psi4/driver/p4util/util.py
=> Fix `oeprop` argument case behavior

psi4/src/psi4/libfock/jk.cc, tests/pytests/test_comprehensive_jk_screening.py
This is an intermediary PR to https://github.com/psi4/psi4/pull/3060. Reviews on that PR have made me reconsider some design decisions as implemented in that PR. At the same time, I want to ensure that no end user runs into any hard failures due to broken `SCF_TYPE` + `SCF_SUBTYPE` + `SCREENING` combinations in v1.9. So this PR goes and simply throws exceptions for every hard failure case as logged in `test_comprehensive_jk_screening.py`. Tests are updated to match, and there's some small refactoring of how JK type + screening exceptions are handled in `jk.cc.`
=> Throw exceptions for broken JK+SCREENING combos

doc/sphinxman/source/scf.rst
This PR updates the documentation to reflect two aspects of the JK code:
1. It mentions the `SCF_TYPE` naming option added as per https://github.com/psi4/psi4/pull/3001. 
2. It provides a warning regarding the current defaults for the COSX grids. From my testing, these grids are very crude in practical use, and cannot be expected to be accurate if high (e.g., chemical) accuracy is desired. The documentation is updated to reflect this.
=> Documentation Updates for CompositeJK

psi4/share/psi4/scripts/vmd_cube.py
Running `vmd_cube.py` would produce an error due to the use of deprecated `.iteritems` instead of `.items`
- Replace `iteritems` with `items`
=> Fix Python3 compatibility in vmd_cube.py

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-windows.yml, .github/workflows/ecosystem.yml, codedeps.yaml, conda/psi4-path-advisor.py, external/upstream/libint2/CMakeLists.txt, psi4/CMakeLists.txt, psi4/driver/p4util/util.py, psi4/src/export_mints.cc, tests/pytests/test_task_planner.py
=> choose libint v2.8.1

psi4/driver/inputparser.py, tests/pywrap-db1/input.dat
=> Drop the default definition of a H2 molecule.

psi4/src/psi4/libciomr/block_matrix.cc, psi4/src/psi4/libciomr/libciomr.h
`block_matrix` should not let its callers discard the arrays it allocates. This PR adds the `[[nodiscard]]` attribute.
Also, if an allocation fails, `block_matrix` now throws instead of calling `exit(1)` and tells the user how many bytes it has tried and failed to allocate.
=> Touch up block_matrix in libciomr

psi4/src/psi4/libdpd/block_matrix.cc, psi4/src/psi4/libdpd/buf4_mat_irrep_rd.cc, psi4/src/psi4/libdpd/buf4_mat_irrep_rd_block.cc, psi4/src/psi4/libdpd/buf4_mat_irrep_row_rd.cc, psi4/src/psi4/libdpd/buf4_mat_irrep_row_wrt.cc, psi4/src/psi4/libdpd/buf4_mat_irrep_shift13.cc, psi4/src/psi4/libdpd/buf4_mat_irrep_shift31.cc, psi4/src/psi4/libdpd/buf4_mat_irrep_wrt.cc, psi4/src/psi4/libdpd/buf4_mat_irrep_wrt_block.cc, psi4/src/psi4/libdpd/cc3_sigma_RHF.cc, psi4/src/psi4/libdpd/cc3_sigma_RHF_ic.cc, psi4/src/psi4/libdpd/contract222.cc, psi4/src/psi4/libdpd/contract244.cc, psi4/src/psi4/libdpd/contract424.cc, psi4/src/psi4/libdpd/contract442.cc, psi4/src/psi4/libdpd/error.cc, psi4/src/psi4/libdpd/init.cc, psi4/src/psi4/libdpd/trans4_mat_irrep_shift13.cc, psi4/src/psi4/libdpd/trans4_mat_irrep_shift31.cc
A lot of error exits in `libdpd` are implemented with `exit(1)` or equivalent. This makes debugging harder, and results in less informative error messages when a test fails in the CI environment.
This PR modernizes all `exit(1)` error exits in `libdpd` into `throw PSIEXCEPTION`.
=> Throw PSIEXCEPTION instead of exit(1) in DPD

psi4/driver/procrouting/sapt/sapt_mp2_terms.py, psi4/driver/procrouting/sapt/sapt_proc.py
When SAPT(DFT) is used with `SAPT_DFT_FUNCTIONAL == 'HF'` to run SAPT0, two pathways for dispersion and exchange-dispersion calculations are possible, through the SAPT0-SAPT2+3 code (requested by `set SAPT_DFT_MP2_DISP_ALG SAPT`) or through the FISAPT code (`set SAPT_DFT_MP2_DISP_ALG FISAPT`). However, in the latter case, the calculation forgot to freeze the core as requested. This PR should preserve frozen-core in this specific situation.
This fixes https://github.com/psi4/psi4/issues/3141. It's quite likely that the FISAPT pathway can be faster (thanks to @carolinesargent for extensive testing), that's why we want to fix it.
=> Pass frozen-core information from SAPT(DFT) to FISAPT dispersion

psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/matrix.h
This is something I have been working on as part of the upcoming Psi4-GauXC interface; but it seems to be of interest for other use cases, so I will be adding it here as a separate PR.
What this change does, is it adds two new member functions to the `Psi4::Matrix`  class, `eigen_map()`  and `eigen_maps()` . Both of these functions serve the same purpose - take the Psi4 matrix in question and return a representation of said matrix through Eigen's `Map` objects. The `Eigen::Map` class acts the same way as a normal `Eigen::Matrix` object, but uses an external array as its data buffer rather than an internal data buffer. The `eigen_map()` and `eigen_maps()` functions, then, return Eigen matrix-like objects that directly link with the Psi4 matrix data buffer of the Psi4 matrix for which the …
=> Add creation of Eigen::Map representations of Psi4 matrices

codedeps.yaml, external/upstream/einsums/CMakeLists.txt, psi4/CMakeLists.txt
```
writing output... [100%] tutorial
/home/runner/work/psi4/psi4/code/objdir/doc/sphinxman/docstring of psi4.core.PyCapsule.nuclear_repulsion_energy:1: WARNING: py:class reference target not found: Annotated[list[float], FixedSize(3)]
/home/runner/work/psi4/psi4/code/objdir/doc/sphinxman/docstring of psi4.core.PyCapsule.nuclear_repulsion_energy_deriv1:1: WARNING: py:class reference target not found: Annotated[list[float], FixedSize(3)]
/home/runner/work/psi4/psi4/code/objdir/doc/sphinxman/docstring of psi4.core.PyCapsule.matrix:1: WARNING: py:class reference target not found: Annotated[list[Annotated[list[float], FixedSize(3)]], FixedSize(3)]
/home/runner/work/psi4/psi4/code/objdir/doc/sphinxman/docstring of psi4.core.PyCapsule.get_dipole_field_strength:1: WARNING: py:class reference …
```
=> test docs build

psi4/src/psi4/libmoinfo/model_space.cc, psi4/src/psi4/libmoinfo/model_space.h, psi4/src/psi4/libmoinfo/model_space_build.cc, psi4/src/psi4/libmoinfo/moinfo.cc, psi4/src/psi4/libmoinfo/moinfo.h, psi4/src/psi4/libmoinfo/moinfo_base.cc, psi4/src/psi4/libmoinfo/moinfo_base.h, psi4/src/psi4/libmoinfo/moinfo_model_space.cc, psi4/src/psi4/libmoinfo/moinfo_scf.cc, psi4/src/psi4/libmoinfo/moinfo_scf.h, psi4/src/psi4/mcscf/scf.cc, psi4/src/psi4/mcscf/scf_pairs.cc, psi4/src/psi4/mcscf/scf_print_eigenvectors_and_MO.cc, psi4/src/psi4/psimrcc/blas_algorithms.cc, psi4/src/psi4/psimrcc/index.cc, psi4/src/psi4/psimrcc/matrix.cc, psi4/src/psi4/psimrcc/mrcc_compute.cc, psi4/src/psi4/psimrcc/updater_bw.cc, psi4/src/psi4/psimrcc/updater_mk.cc
This PR aims to make a lot of tiny improvements to libmoinfo.
While trying to modernize a bit of libmoinfo code to eliminate some (ab)use of the Dimension functions deprecated by PR #2953 I had to try to get at least some grip on what-does-what, but libmoinfo has accumulated some clutter which made that harder than necessary.
One thing led to another, and now this PR is here to hopefully make it easier for the next person.
Docstring addition and more are the subject of a future PR.
=> Clean up #includes, macros, unnecessary array init, error exits, and other miscellaneous things in libmoinfo

external/upstream/libint2/CMakeLists.txt, psi4/CMakeLists.txt, psi4/src/psi4/libmints/rel_potential.cc, psi4/src/psi4/libmints/rel_potential.h
Paying off an old IOU. I'll get to what Francesco and Daniel Nascimento need after this PR is in.
=> Modernize relativistic potential

psi4/src/psi4/dct/dct_density_UHF.cc, psi4/src/psi4/dct/dct_df_operations.cc, psi4/src/psi4/dct/dct_gradient_RHF.cc, psi4/src/psi4/dct/dct_gradient_UHF.cc, psi4/src/psi4/dct/dct_intermediates_RHF.cc, psi4/src/psi4/dct/dct_intermediates_UHF.cc, psi4/src/psi4/dct/dct_memory.cc, psi4/src/psi4/dct/dct_oo_RHF.cc, psi4/src/psi4/dct/dct_oo_UHF.cc, psi4/src/psi4/dct/dct_qc.cc, psi4/src/psi4/dct/dct_relaxed_density_UHF.cc, psi4/src/psi4/dct/dct_scf_RHF.cc, psi4/src/psi4/dct/dct_scf_UHF.cc, psi4/src/psi4/dct/dct_tau_RHF.cc, psi4/src/psi4/libmints/factory.cc
Fixes many compiler warnings by no longer passing redundant arguments to Matrix constructors.
=> Fix many compiler warnings

psi4/src/psi4/libpsi4util/exception.cc
This PR makes small changes to the `PsiException` class, specifically regarding the printout of the function call stack upon throwing. Now, the number of functions included in the printed call stack during exception printout is tied to a singular variable, instead of being scattered about in multiple places. The goal is to allow easier control of the function call stack size during printout for debugging purposes, if desired. 
There are a couple small cleanups here and there as well.
=> Small Refactor of Exception Call Stack Size

psi4/src/psi4/libmints/rel_potential.cc
`RelPotentialInt` and associated integral classes now expose all four W integral types instead of just the W0 integrals.
This PR seems way too easy. @brianz98, please let me know if there are issues. Obligatory @fevangelista and @dnascimento13 pings.
=> Support all W integrals

psi4/src/psi4/detci/import_vector.cc, psi4/src/psi4/detci/params.cc
Detci still has a few places where error termination is effected through printf+abort(). This PR replaces the calls to abort() in with `throw PSIEXCEPTION(msg)`.
The rest of the codebase has more of this pattern, those are subject to future PRs to keep this one small.
=> Throw PSIEXCEPTION instead of calling abort() in detci

psi4/src/export_mints.cc, psi4/src/psi4/libmints/CMakeLists.txt, psi4/src/psi4/libmints/electricfield.cc, psi4/src/psi4/libmints/integral.cc, psi4/src/psi4/libmints/integral.h, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/mintshelper.cc, psi4/src/psi4/libmints/mintshelper.h, psi4/src/psi4/libmints/potential.cc, psi4/src/psi4/libmints/potential_erf.cc, psi4/src/psi4/libmints/potential_erf.h, psi4/src/psi4/libmints/rel_potential.cc, psi4/src/psi4/libmints/tracelessquadrupole.cc, tests/pytests/test_potential_erf.py
This PR refactors the existing `PseudospectralInts` (untested, unused, but maybe needed at some point, see #2414)
with some refactoring: The "old" `PseudospectralInts` did compute `<p| 1/R |q>` *or* `<p| erf(omega*R)/R |q>` with `R = |r -r_c|` for some given point/origin `r_c`. 
- The class `PseudospectralInts` is removed. To compute the "normal" Coulomb potential at a given origin, one can use either `MultipolePotentialInt` (with `max_k=0`) *OR* `ElectrostaticInt`.
- To compute the erf-attenuated Coulomb potential, I created a new class named `PotentialErfInt` to better reflect the actual "property integral" being computed. For testing purposes, I also added the erfc-attenuated Coulomb potential (`PotentialErfComplementInt`), maybe they're also useful at some point. Both use L2 under the …
=> Refactor `PseudospectralInts` using Libint2

doc/sphinxman/source/bibliography.rst, psi4/src/export_mints.cc, psi4/src/psi4/libmints/CMakeLists.txt, psi4/src/psi4/libmints/thc_eri.cc, psi4/src/psi4/libmints/thc_eri.h, psi4/src/read_options.cc, tests/pytests/test_thc_eri.py
In this PR, we implement a pilot version of least squares tensor hypercontraction (LS-THC)... factoring 4-index ERIs (O(N^4)) into two-index quantities (i.e. $(mn|rs) = x_{m}^{P}x_{n}^{P}Z^{PQ}x_{r}^{Q}x_{s}^{Q}$). In the LS-THC formulation, $P$ and $Q$ are derived from grid points, and
$x_{m}^{P} = w_{P}^{\frac{1}{4}} \phi_{m}(x_{P}, y_{P}, z_{P})$,
$E^{PQ} = x_{m}^{P}x_{n}^{P}(mn|rs)x_{r}^{Q}x_{s}^{Q}$
$S^{PP'} = (x_{m}^{P}x_{m}^{P'})^{2}$
$Z^{PQ} = (S^{PP'})^{-1} E^{P'Q'} (S^{QQ'})^{-1}$
This is based off of the work of [Parrish et al. (2012)](https://pubs.aip.org/aip/jcp/article/137/22/224106/194901/Tensor-hypercontraction-II-Least-squares)
These quantities can be constructed integral-direct and non-iteratively. No four or even three-index quantities are stored, thereby allowing for …
=> Least Squares Tensor Hypercontraction (LS-THC) for ERIs (Part 1)

psi4/src/psi4/libfock/jk.h, tests/pytests/test_compositejk.py
Here's another JK mini-PR. This one seems to be of interest in multiple future JK-related developments (such as https://github.com/psi4/psi4/pull/3158), so I figured it would be good to add it on its own.
This PR changes the behavior of `CompositeJK::name()` so that, instead of returning the value "CompositeJK", it returns the names of the underlying `SplitJK` algorithms used. Additionally, using this feature, a new test has been added to `test_compositejk.py`, testing to make sure that proper composite algorithm pairs are called, given an input `SCF_TYPE=J_ALGO + K_ALGO`.
=> Change CompositeJK::name() Behavior

psi4/src/psi4/libmoinfo/moinfo.cc, psi4/src/psi4/libmoinfo/moinfo.h, psi4/src/psi4/libmoinfo/moinfo_base.cc, psi4/src/psi4/libmoinfo/moinfo_base.h
This is the third PR in the `libmoinfo` series, following #3101 and #3155.
Currently, `libmoinfo` is calling the `intvec convert_int_array_to_vector(int n, const int* array)` to initialize some of its `std::vector<int>` members by copying the innards of `Dimension` objects. Unfortunately this is happening through the rather inelegant mechanism of implicitly calling `Dimension::operator const int*() const`, which is set to be removed eventually.
This PR replaces all calls of `convert_int_array_to_vector` in `libmoinfo` with simple assignment-initialization. Now, this could in theory lead to a change in behavior, as the former only copies the first `n` elements of the array inside the Dimension object instead of the entire thing, but in practice that does not seem to be happening. As far as …
=> Eliminate casting of Dimension objects to pointers within libmoinfo

doc/sphinxman/source/bibliography.rst, psi4/src/psi4/libmints/matrix.cc, psi4/src/psi4/libmints/matrix.h, psi4/src/psi4/libmints/thc_eri.cc, psi4/src/psi4/libmints/thc_eri.h
This PR implements the grid pruning scheme of Matthews (https://pubs.acs.org/doi/10.1021/acs.jctc.9b01205), applying a pivoted Cholesky decomposition to the S matrix to remove linear dependencies and drastically reduce the number of grid points. Per @PhillCli's comments on #3157, taking the pseudoinverse of the S matrix can be costly, and this PR fixes that problem! The final rank appears to be _mostly_ invariant to grid size, but only to the molecule/basis set (results in tables below)
| System | Radial, Spherical Points | Initial Rank | Final Rank |
| ------------- | ------------- | ------------- | ------------- |
| Water/cc-pVDZ  | (25, 50) | 2605 | 280 |
| Water/cc-pVDZ  | (50, 86) | 8739 | 280 |
| Water/cc-pVTZ  | (25, 50) | 2630 | 1184 |
| Water/cc-pVTZ  | (50, 86) | 8774 | 1328 |
| …
=> Least Squares Tensor Hypercontraction (LS-THC) for ERIs (Part 2): Grid Pruning

.azure-pipelines/azure-pipelines-windows.yml, psi4/src/psi4/libfock/CompositeJK.cc, psi4/src/psi4/libfock/SplitJK.h, psi4/src/psi4/libfock/jk.h
This PR was motivated by a comment by @andyj10224 in PR https://github.com/psi4/psi4/pull/3150, pointing out that implementing method-specific setters/getters in `SplitJK` could more elegantly and sensibly be performed via downcasting. While the comment in that PR addressed knobs specific to `snLinK`, it is also applicable to other methods within the CompositeJK framework. This PR fixes that, replacing all instances of method-specific setters/getters in the base `SplitJK` class with downcasting to call the needed function at the derived-class level.
=> Replace SplitJK method-specific functions with typecasts

psi4/driver/procrouting/dft/gga_functionals.py, psi4/driver/procrouting/dft/mgga_functionals.py
The `MGGA_MVSh` functional [is aliased to `MVSh`](https://github.com/psi4/psi4/blob/bf9d20fc579995b0bc2c38b749a31c0d6f85c82e/psi4/driver/procrouting/dft/hyb_functionals.py#L326). This is inconsistent with `MGGA_MS0`, `MGGA_MS1`, `MGGA_MS2`, and `MGGA_MVS`. This change adds an alias for `MS0`, `MS1`, `MS2`, and `MVS`, respectively.
**EDIT:** Similarly, there are two more functionals with inconsistent naming: PW91 and mPWPW. LibXC refers to these as PW91 and mPW91, respectively, while the mPWPW paper refers to them as PWPW and mPWPW, respectively. Hence, I added an alias of `PWPW` for `PW91`; and an alias of `mPW91` for `mPWPW`.
=> Make aliases for MGGA_ DFTs and PW91 consistent

doc/sphinxman/source/nbody.rst
The example in https://psicode.org/psi4manual/master/nbody.html is not copy-pasteable as-is, it's missing a basis set.  I picked something small and not horrible so it finishes in a reasonable amount of time.
=> Add missing basis set to nbody example in docs

doc/sphinxman/source/bibliography.rst, doc/sphinxman/source/optking.rst, psi4/src/read_options.cc
Adds new optking options to `read_options.cc`. Adds soon to be added `OPT_COORDINATES CUSTOM` option.
=> Opt options

.github/workflows/ecosystem.yml, codedeps.yaml, external/upstream/einsums/CMakeLists.txt, external/upstream/qcelemental/CMakeLists.txt, external/upstream/qcengine/CMakeLists.txt, psi4/CMakeLists.txt, tests/cbs-xtpl-wrapper/test_input.py, tests/nbody-multi-level/test_input.py
=> Fix CI, update QCEl 0.29, QCEn 0.31, and Einsums 0.6.1

psi4/src/psi4/libdpd/dpd.h, psi4/src/psi4/libdpd/file4_cache.cc, psi4/src/psi4/libpsio/close.cc
=> Close issue #3274

psi4/driver/driver.py, psi4/driver/frac.py, psi4/driver/qcdb/molecule.py
Running ip_tunning clogs stdout by emitting non-silenced printouts, and red-herring warnings.
`ip_tune` does set charge/multiplicity via `set_molecular_charge` and `set_multiplicity`:
* https://github.com/psi4/psi4/blob/master/psi4/driver/frac.py#L609
* https://github.com/psi4/psi4/blob/master/psi4/driver/frac.py#L610C5-L610C37
so it should be safe to keep them out.
An example:
```log
...
c: [1.0, 0]
fc: [0.0]
m: [2]
fm: [3]
Following warning is harmless if you've altered chgmult through `set_molecular_change` or `set_multiplicity`. Such alterations are an expert feature. Specifying in the original molecule string is preferred. Nonphysical masses may also trigger the warning.
c: [1.0, 0]
fc: [0.0]
m: [2]
fm: [3]
Following warning is harmless if you've altered chgmult through …
```
=> fix: slience annoying print outs in ip fitting jobs

psi4/src/psi4/cc/ccdensity/Iab.cc, psi4/src/psi4/cc/ccdensity/MOInfo.h, psi4/src/psi4/cc/ccdensity/get_moinfo.cc, psi4/src/psi4/cc/ccenergy/MOInfo.h, psi4/src/psi4/cc/ccenergy/get_moinfo.cc, psi4/src/psi4/cc/cceom/MOInfo.h, psi4/src/psi4/cc/cceom/get_moinfo.cc, psi4/src/psi4/cc/cchbar/MOInfo.h, psi4/src/psi4/cc/cchbar/get_moinfo.cc, psi4/src/psi4/cc/cclambda/MOInfo.h, psi4/src/psi4/cc/cclambda/get_moinfo.cc, psi4/src/psi4/cc/ccresponse/MOInfo.h, psi4/src/psi4/cc/ccresponse/get_moinfo.cc, psi4/src/psi4/cc/ccresponse/sort_pert.cc, psi4/src/psi4/cc/cctriples/MOInfo.h, psi4/src/psi4/cc/cctriples/get_moinfo.cc, psi4/src/psi4/cctransort/cctransort.cc, psi4/src/psi4/libdpd/dpd.h, psi4/src/psi4/libdpd/init.cc
This is a PR that goes into all the `cc` modules and changes the type of their orbital spaces from `int *` to `Dimension`. Data is now pulled from the wavefunction rather than  what `cctransort` wrote to disk. The unused `cctransort` write operations are removed. I also remove an unused `DPD::init` and converted some `Dimension` that didn't represent a dimension to `std::vector<int>`.
There is nothing remotely exciting about this PR, but the much more important DePointerDPD PR will have `DPD::DPD` demand `Dimension` objects (or rather `DPDMOSpace` objects which require a `Dimension`), so I might as well split this part out.
=> DePointerDPD Warmup: `Dimension` for `cc`

.azure-pipelines/azure-pipelines-linux.yml, .github/workflows/ecosystem.yml, CMakeLists.txt, azure-pipelines.yml, codedeps.yaml, conda/psi4-path-advisor.py, devtools/conda-envs/linux-64-buildrun-addons.yaml, devtools/conda-envs/linux-64-docs.yaml, devtools/conda-envs/osx-64-buildrun-addons.yaml, devtools/conda-envs/osx-64-buildrun.yaml, devtools/conda-envs/osx-arm64-buildrun-addons.yaml, devtools/conda-envs/osx-arm64-buildrun.yaml, devtools/conda-envs/win-64-buildrun-addons.yaml, devtools/conda-envs/win-64-buildrun.yaml, external/upstream/gauxc/CMakeLists.txt, psi4/driver/procrouting/sapt/sapt_mp2_terms.py
~There's been a strange error message the past few weeks on Windows at runtime that's fixed by `libgcc<14.3`. Let's test the rebuild of g2g 2.0.8 and see if this might have fixed this issue, as g2g was the oldest dep on c-f.~
Later
=> convey libgcc windows
